backend/src/main.ts

backend 포트 번호를 3000번에서 5000번으로 옮겨 충돌을 막습니다.
Closes #15 
---

fix: backend and frontend dev server port conflict (fix #15)

---

.gitpod.yml

GitPod 개발환경을 구성합니다.
Closes #6
---

chore(dev): add gitpod configuration

---

frontend/package.json
frontend/tsconfig.json
frontend/vite.config.ts
pnpm-lock.yaml

다양한 icon system을 쉽게 적용하기 위해 Iconify를 세팅합니다.
더불어 Vite plugin인 unplugin-icons를 이용해 bundle 시 사용된 아이콘의 svg만 포함시킵니다.
unplugin-icons 문서: https://github.com/antfu/unplugin-icons#readme
icon 목록: https://icones.js.org/
Closes #20 
---

feat(fe): use iconify

---

.github/workflows/ci.yml
.github/workflows/codeql.yml

GitHub Action으로 CI(Continuous Integration)을 자동으로 수행합니다.
Deploy 관련 자동화는 서버 구조 및 세팅이 결정되면 작성할 예정입니다.
Closes #31 
---

chore(ci): use github action

---

.prettierrc
.prettierrc.js
package.json
pnpm-lock.yaml

Tailwind CSS 팀에서 공식 지원하는 formatter인 `prettier-plugin-tailwindcss`를 적용합니다.
Closes #36 
---

chore: add prettier plugin for tailwind css

---

.devcontainer/devcontainer.json
.github/workflows/ci.yml
.gitignore
.npmrc
.vscode/extensions.json
backend/prisma/schema.prisma
backend/tsconfig.json
docker-compose.yml
pnpm-lock.yaml
scripts/setup.sh

Resolves #5 
- DB container를 docker compose를 이용하여 관리합니다. GitPod 개발환경과 충돌되지 않도록 하였습니다.
- pnpm v7을 사용합니다. v7 관련 breaking change를 반영하였습니다.
---

feat(dev): configure devcontainer

---

.github/ISSUE_TEMPLATE/frontend-component-dev.yml

Frontend에서 component를 개발할 때 사용할 issue template을 작성합니다.
[Example](https://github.com/SOLBI1028/Issue-template/issues/3)
closes #60

chore(fe): Add issue template for components

---

.devcontainer/devcontainer.json
backend/package.json
backend/src/app.module.ts
backend/src/common/config/cacheConfig.service.ts
docker-compose.yml
pnpm-lock.yaml
scripts/setup.sh

Refresh Token 및 Password Reset Token 저장을 위한 Caching module을 설정합니다.
Closes #67 
- Cache storage로는 Redis를 사용하였습니다. 그 이유는
1. caching에 주로 사용되는 데이터베이스입니다. in-memory data store 방식이기 때문에 mongoDB 등의 다른 NoSQL보다 빠릅니다. 
2. in-memory방식이지만 디스크에 데이터를 기록할 수 있기 때문에 복구가 가능합니다. Refresh Token 저장에 적합합니다.
3. 다양한 데이터 타입의 저장을 지원합니다. 추후 여러 서비스에서 사용될 것을 고려하였습니다.
- ConfigService를 통한 배포 환경 등의 설정을 위해 [Async configuration](https://docs.nestjs.com/techniques/caching#async-configuration)을 사용하였습니다. 추후 배포 환경에 따라 .env 파일에 설정을 추가합니다. 
- Global module로 등록하였기 때문에 inject시 별도의 module import 설정은 필요하지 않습니다.
- [사용법](https://docs.nestjs.com/techniques/caching#interacting-with-the-cache-store)
---

feat(be): setup caching moudle

---

backend/package.json
backend/src/auth/common/hash.ts
pnpm-lock.yaml

`Argon2`모듈로 중요한 정보들을 해쉬화하여 저장하도록 합니다. 따로 `auth/common`경로에 `Hash`클래스를 구현하였습니다. `Argon2`와의 의존성을 최소화하기 위함입니다.
`validatePassword()`함수에서 인자의 순서가 강제됩니다. "해쉬화된 비번", "플레인 비번" 순서입니다. 개인적으로 이게 불편하긴한데 방법이 떠오르질 않네요.
Closes #86 
---

feat(be): use argon2

---

frontend/src/common/components/Atom/InputItem.vue
frontend/tailwind.config.js

InputItem 구현
closes #74
- 상위 컴포넌트에서 placeholder, shadow, required 지정 필요
- shadow true일때
- shadow false일때

feat(fe): add input item component

---

frontend/src/common/components/Atom/Button.vue

Reusable Button Components for skkuding website platform. close #68 
got three props of (text, buttoncolor, isrounded) to give css for the style of Buttons.
use computed to convert concatenation of strings.
Any of the props is not required.
Example
```
<Button text="Button" buttoncolor="gray" :isrounded="true"></Button>
```
---

feat(fe): add button component

---

frontend/src/common/components/Molecule/Badge.story.vue
frontend/src/common/components/Molecule/Badge.vue

Badge 구현
closes #120
- 상위 컴포넌트에서 props로 endtime(string)과 ended(boolean) 지정 필요
- ended가 true일때 endtime을 표시해주고 false일때 “Ended”문구를 표시해준다.
- `ended: true`
- `ended: false`
---

feat(fe): add badge component

---

frontend/src/common/components/Atom/BoxTitle.story.vue
frontend/src/common/components/Atom/BoxTitle.vue

- BoxTitle 구현 close #157 
- slot name
- title
- subtitle
- 컴포넌트 이름을 제 마음대로 Box Title이라고 했는데 어떤가요?
---

feat(fe): add box-title component

---

backend/src/contest/contest.service.spec.ts
backend/src/contest/contest.service.ts
backend/src/group/group.service.ts
backend/src/group/guard/group-manager.guard.ts
backend/src/group/guard/group-member.guard.ts
backend/src/user/guard/roles.guard.ts
backend/src/user/user.service.ts

> Resolves #160 
`rejectOnNotFound` 프라퍼티를 사용하여 예외 코드를 최적화합니다.
N/A
---

refactor(be): use rejectOnNotFound property

---

frontend/histoire.config.ts
frontend/package.json
pnpm-lock.yaml

histoire plugin을 추가합니다.
closes #174 
---

chore: add histoire plugin

---

frontend/package.json
frontend/src/common/styles/style.css
frontend/src/main.ts
pnpm-lock.yaml

Closes #167 
페이지 상단에 progress bar를 표시합니다.
---

feat(fe): add progress bar on the top of page

---

.github/ISSUE_TEMPLATE/frontend-page-dev.yml

- issue template 제작 (close #222 )
- [예시](https://github.com/goo314/temp/issues/3)
페이지 구현에 관한 이슈는 아래의 정보가 포함되어야 합니다.
- Page의 URL
- Page 사진 (필수)
- Page description (필수)
- Required APIs
- Required Components
현재 페이지 구현 중인 부분도 있어서 최대한 빨리 구현해봤습니다.
필요 없는 부분이나 추가해야될 부분이 있다면 코멘트 남겨주세요 ~~! 😄
---

feat(fe): add issue template for page development

---

pnpm-lock.yaml

pnpm lockfile로 인한 CI fail을 해결합니다.
---

fix: fix broken lockfile

---

README.md

Repository main 화면에 보여질 README.md 파일을 추가합니다.
미리보기: https://github.com/skkuding/next/tree/10-readme
추가되면 좋을 내용들 자유롭게 남겨주세요~!
Closes #10 
---

feat(docs): create readme

---

frontend/src/common/layouts/default.vue

fix(fe): add margin above footer

---

backend/src/common/exception/business.exception.ts

Fixes #293 
`ActionNotAllowedException`을 추가했습니다.
---

feat(be): add action-not-allowed-exception

---

.github/workflows/ci.yml
backend/prisma/migrations/20221222120916_prevent_deleting_reference/migration.sql
backend/prisma/schema.prisma

Closes #290
Migration file 확인하는 test도 CI에 추가해뒀습니다!
---

fix(be): add missing migration file

---

.vscode/launch.json

Closes #213 
1. `pnpm dev` 명령어로 dev server 실행
2. VSCode 'Run and Debug' 탭에서 'Frontend (Vite.js)' 선택 후 실행
> **Warning**
> GitPod에서는 frontend debugging 기능을 사용할 수 없습니다.
1. VSCode 'Run and Debug' 탭에서 'Backend (Nest.js)' 선택 후 실행
---

feat(ci): configure debugging in vscode

---

lefthook.yml

Git branch 전환 시 자동으로 `setup.sh`를 실행해줍니다.
Branch마다 package와 migration이 달라 전환할 때마다 다시 세팅하는 번거로움을 해결합니다.
---

feat: run setup script when branch switched

---

frontend/src/common/components/Atom/ListItem.story.vue
frontend/src/common/components/Atom/ListItem.vue
frontend/src/common/components/Molecule/Dropdown.story.vue
frontend/src/common/components/Molecule/Dropdown.vue
frontend/src/user/problem/components/Navigator.vue

Close #312
dropdown itemlist 테마 추가했습니다.
각 component에 props주는 것으로 적용할 수 있어요.
---

feat(fe): add dropdown & listitem theme

---

.github/workflows/documentation.yml
.github/workflows/storybook.yml

Close #330 
GitHub Action으로 CD pipeline을 구축하여 build 및 AWS S3 업로드 과정을 자동화합니다.
문서는 [docs.skkuding.dev](https://docs.skkuding.dev), story는 [story.skkuding.dev](https://story.skkuding.dev)에서 확인할 수 있습니다.
---

build: deploy documentation automatically

---

frontend/src/user/contest/pages/index.vue

contest list api를 통해 ongoing, incoming, finished contest data를 받아옵니다.
register now Contest를 지웠는데, 필요여부에 대한 논의가 필요합니다.
close #314

feat(fe): connect contest list api

---

lefthook.yml
scripts/post-checkout.sh
scripts/setup.sh

Lefthook의 post-checkout hook이 실행될 때 멈춰버리는 경우(계속 로딩)가 발생합니다.
Prisma migration에서 충돌이 발생할 경우, 즉 기존 branch와 새로운 branch의 migration history가 diverge될 경우 Prisma가 data를 reset해도 괜찮은지 prompt합니다. 이 때 lefthook은 사용자 input을 받지 않아 영원히 사용자 input을 기다리는 상태로 멈춥니다.
```
> pnpm prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "skkuding", schema "public" at "dev-db:5432"
- Drift detected: Your database schema is not in sync with your migration history.
The following is a summary of the differences between the expected database schema given your migrations files, and the actual schema of the database.
It should be understood as the set of changes to get from the expected schema to the actual schema.
[*] Changed the …
```

fix: prevent lefthook being stucked on checkout

---

backend/prisma/migrations/20230126123416_add_group_config/migration.sql
backend/prisma/schema.prisma
backend/prisma/seed.ts

feat(be): add group json config

---

frontend/package.json
frontend/vite.config.ts
pnpm-lock.yaml

feat(fe): lint and check types on dev server

---

thunder-tests/thunderCollection.json
thunder-tests/thunderclient.json

problem get api 에 대한 문서를 작성했습니다! 😆😆
close #395 
여러 problem을 가져오는 경우, problem이 없는 경우도 있을 수 있기 때문에 따로 response field type을 test 하지 않았습니다.
---

docs(be): add problem get api documentation

---

backend/apps/client/src/group/group.service.ts
backend/apps/client/src/group/interface/group-data.interface.ts

client 앱의 group service에서 eslint 설정이 해제되어 있던 오류를 해결합니다.
---

fix(be): enable eslint for group service

---

scripts/setup.sh

fix: enable git autocompletion lazily

---

.vscode/settings.json

feat: enable nestjs icon pack

---

frontend/src/common/components/Organism/CodeEditor.vue
frontend/vite.config.ts

fix(fe): async call in setup blocks code mirror

---

frontend/package.json
frontend/src/admin/pages/[groupId]/member/index.vue
pnpm-lock.yaml

feat(fe): add group admin member page

---

backend/apps/client/src/app.module.ts
thunder-tests/thunderCollection.json
thunder-tests/thunderclient.json

Clarification 모듈이 클라이언트 앱 모듈 import 목록에서 빠져있어 이를 추가합니다.
---

fix(be): import clarification module in client app

---

frontend/src/user/contest/components/Notice.vue
frontend/src/user/contest/components/Problem.vue
frontend/src/user/contest/components/Top.vue
frontend/src/user/contest/pages/[id].vue

- Top, Notice, Problem 탭 API 연결 완료
- Contest startTime, endTime 기준으로 진행 중이면 초록색, 아니면 빨간색으로 뱃지 수정
- Rank 탭 주석 처리
#525 
---

fix(fe): connect API in a contest detail page

---

backend/apps/client/src/email/mailerConfig.service.ts
scripts/setup.sh

Close #570 
구현해보니까 AWS SDK 없이도 돼서 변경은 최소화했습니다!
테스트용 세팅은 팀즈 참고해주세요!
---

feat: setup nodemailer for ses

---

scripts/setup.sh

PR #582 에서 반영하지 못한 setup script를 수정합니다.
---

fix(be): change tc copy target in setup script

---

thunder-tests/environments/base.json

PR #583, #584 내용 수정입니다. (3트...)
---

fix(be): change env schema

---

.vscode/launch.json
backend/.swcrc
backend/package.json

feat(be): configure debugger for admin and test

---

.eslintrc.js

feat: add no-inferrable-type rule

---

.github/workflows/ci.yml
backend/package.json

Prisma DB seed가 동작하지 않는 문제를 해결합니다.
PR #594 에서 사라진 swc-node를 ts-node로 대체합니다. (내부적으로는 똑같이 SWC로 transpile합니다!)
---

fix(be): cannot seed db

---

backend/apps/client/src/problem/dto/problems.response.dto.ts
backend/apps/client/src/problem/mock/problem.mock.ts
backend/apps/client/src/problem/problem.repository.ts
backend/apps/client/src/problem/problem.service.spec.ts
backend/apps/client/src/problem/problem.service.ts
backend/prisma/migrations/20230706094306_add_result_field_to_submission_table/migration.sql
backend/prisma/schema.prisma
backend/prisma/seed.ts
thunder-tests/collections/tc_col_codedang-client-api.json

> Closes #602 
Problem GET list에서 `submissionCount`, `acceptedRate`, `tags`를 추가로 가져옵니다.
---

feat(be): get related fields in problem get list

---

frontend/src/admin/pages/[groupId]/contest/[id]/CreatePorblemModal.vue
frontend/src/admin/pages/[groupId]/contest/[id]/index.vue
frontend/src/common/components/Organism/TextEditor.vue

- modal 추가
- Text editor height 고칠 수 있게 컴포넌트 수정
close #543 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/617"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(fe): create contest problem modal

---

frontend/src/admin/pages/[groupId]/submission/index.vue

- submission page
close #534 
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/621"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(fe): group admin submission page

---

frontend/src/common/composables/api.ts
frontend/src/user/contest/components/Problem.vue
frontend/src/user/home/pages/index.vue
frontend/src/user/notice/composables/notice.ts
frontend/src/user/notice/pages/[id].vue
frontend/src/user/notice/pages/index.vue
frontend/src/user/problem/pages/index.vue

Close #607 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/631"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(fe): add list api handler

---

.env.development
backend/apps/admin/src/admin.module.ts
backend/apps/admin/src/storage/content.type.ts
backend/apps/admin/src/storage/s3.provider.ts
backend/apps/admin/src/storage/storage.module.ts
backend/apps/admin/src/storage/storage.service.spec.ts
backend/apps/admin/src/storage/storage.service.ts
backend/init-testcase.ts
backend/libs/auth/src/roles/roles.service.spec.ts
backend/package.json
docker-compose.yml
pnpm-lock.yaml
scripts/setup.sh

Close #635 
`S3Client`를 이용하여 버킷에 string을 업로드하는 기능을 구현합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/637"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(be): add storage module to admin app

---

frontend/src/user/group/components/Problem.vue

- 변수가 없어서 뜬 단순 오류 해결 (#633)
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/648"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(fe): add dropped variable

---

backend/prisma/seed.ts
frontend/src/common/composables/api.ts

Close #688
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/689"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(fe): update single time when changing page

---

infra/deploy/.terraform.lock.hcl
infra/local/.terraform.lock.hcl

Deploy 과정에서 깨진 terraform lockfile을 수정합니다.
https://github.com/skkuding/codedang/actions/runs/5699306120/job/15448111020
---

fix: fix broken terraform lockfile

---

frontend/src/common/composables/api.ts

fix(fe): second try of #689

---

backend/apps/admin/src/main.ts
backend/apps/client/src/main.ts
frontend/vite.config.ts

Close #694
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/698"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(fe): add dev server as backend

---

backend/apps/admin/src/group/group.resolver.ts

Closes #691 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/693"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(be): add backend logging in admin

---

backend/apps/admin/src/main.ts
backend/apps/client/src/main.ts

프론트엔드 개발 시 authorization header에 접근할 수 없는 문제를 해결합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/699"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(be): allow auth header access for cors

---

backend/apps/admin/src/main.ts
backend/apps/client/src/main.ts

allowed header에 authorization만 넣으니까 content-type은 금지가 되네요...
wildcard로 전부 허용했습니다! ~~(보안은 모르쇠)~~
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/700"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: allow all headers for cors

---

infra/modules/codedang-infra/ecs-iris.tf
infra/modules/codedang-infra/rabbitmq.tf

Close #717 
random password를 사용합니다. 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/719"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: use random password for rabbitmq

---

.github/workflows/deploy.yml
.github/workflows/devserver.yml
infra/builder/api/Dockerfile.admin
infra/builder/api/Dockerfile.client
infra/modules/codedang-infra/ecs-admin.tf
infra/modules/codedang-infra/ecs-client.tf
infra/modules/codedang-infra/ecs-iris.tf

Close #712 
ECS Fargate에 ARM64를 사용하여 요금을 절약합니다.
Docker image도 ARM64로 build합니다. (x64도 하면 오래걸릴까봐 뺐어요...)
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/716"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(infra): use arm64 in ecs fargate

---

.github/workflows/deploy.yml

Close #721 
github action에 arm 64 기반 iris image build하는 코드를 추가했습니다. 
일단 위에 적혀있는 코드 참고해서 build-iris 부분만 추가했는데, 
그냥 build-backend 부분에 합쳐서 적는 게 나을까요???
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/722"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: add code to build iris image for arm64

---

.github/workflows/deploy.yml

`721-bug-ecs-iris-arm-build` branch 에서 build-iris의 ` Login to Amazon ECR` step의 순서가 잘못되어 발생한 오류 수정
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/723"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: reorder jobs for deploy action

---

.github/workflows/devserver.yml

PR #725에서 완전히 지워지지 않은 step을 제거합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/733"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(cd): remove invalid step

---

.github/workflows/devserver.yml
docker-compose.yml

개발 서버 CD pipeline에서 mount가 지워지지 않아 fail되는 문제가 있습니다.
mount를 지우지 않도록 하는 옵션도 생각해봤는데, 굳이 mount를 사용할 필요성이 큰 거 같지 않아 지웠습니다!
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/734"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(infra): do not mount testcase storage

---

infra/modules/codedang-infra/backend/admin-task-definition.tftpl
infra/modules/codedang-infra/ecs-admin.tf
infra/modules/codedang-infra/ecs-iris.tf
infra/modules/codedang-infra/iris/task-definition.tftpl
infra/modules/codedang-infra/testcase.tf
iris/main.go

Close #701 
Testcase 파일들을 저장할 S3 bucket 세팅
`codednag-testcase` S3 Bucket을 생성해서 저장하도록 설정했습니다. 
`init-testcase.ts` 파일처럼 버킷에 data 전송해보니깐 s3 버킷에 `1.json`파일 생성되는 것까지는 확인했습니다. 
(물론 추가적인 확인이 필요해보입니다 하핳)
iris cluster에는 권한은 추가해 놓았고, 아직 테스트는 못해봤습니다.
그리고 `TESTCASE_SERVER_URL_PLACEHOLDER` 환경변수에 기본적으로 `:id` 문자가 들어가는 것 같은데
어떤 방식으로 수정해야하는지 감이 잡히질 않아서 도움이 필요합니다...ㅎ
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/728"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(infra): add testcase s3 bucket

---

frontend/package.json
frontend/src/App.vue
frontend/src/common/components/Organism/Footer.vue
frontend/src/common/layouts/default.vue
pnpm-lock.yaml

- 바뀐 메인 페이지의 디자인과 통일감을 주기 위해 푸터 디자인 수정
- Email 버튼 클릭시 email 주소가 copy 되는 건 유지
- 푸터가 끝에 붙지 않아서 레이아웃에 justify-between 추가
- main과 footer의 간격이 너무 넓어서 main의 margin-bottom 삭제
close #737 
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/739"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(fe): change footer style

---

frontend/src/admin/pages/[groupId]/problem/index.vue

- Admin 문제 파일 업로드 API 연결
- 배포된 개발 서버에 요청하면 500 반환
- 백엔드 로컬 서버에 요청하면 200 반환
close #660
---

feat(fe): connect admin problem file upload API

---

.github/workflows/devserver.yml
docker-compose.dev.yml

Close #761 
Action 이 트리거되고 나서 Caddyfile이 반영이 바로 되지 않아서, 
`devserver.yml` 에 Caddy conatiner를 reload하는 코드 추가하였습니다. 
(caddyfile이 반영되기 위해서는 reload 또는 restart 가 필요해 보입니다.)
`docker-compose.dev.yml` 에 dependency를 추가해서 
caddy container가 마지막에 생성되도록 설정하였습니다
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/762"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: caddy container in dev server

---

frontend/package.json
frontend/src/App.vue
frontend/src/admin/pages/[groupId]/submission/SubmissionDetailModal.vue
frontend/src/common/components/Atom/Button.vue
frontend/src/common/components/Organism/CodeEditor.story.vue
frontend/src/common/components/Organism/CodeEditor.vue
frontend/src/user/problem/components/Header.vue
frontend/src/user/problem/components/Navigator.vue
frontend/src/user/problem/pages/[id].vue
frontend/src/user/problem/pages/[id]/index.vue
frontend/src/user/problem/store/problem.ts
frontend/src/user/problem/types.ts
frontend/vite.config.ts
pnpm-lock.yaml

Close #743
- CodeMirror의 지원 언어를 backend와 맞췄습니다. (Go 추가)
- Problem header에 auth store를 연결하였습니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/765"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(fe): add submission functionality

---

infra/modules/codedang-infra/backend/task-definition.tftpl
infra/modules/codedang-infra/iris/task-definition.tftpl

task-definition.tftpl 파일을 JSON 포맷에 맞도록 수정합니다.
---

fix: validate task definition

---

frontend/src/user/problem/components/Navigator.vue

문제 제출 창에서 언어가 제대로 선택되지 않습니다.
props에 computed를 적용하여 데이터가 올바르게 업데이트 되도록 수정합니다.
---

fix(fe): update editor language list on-time

---

infra/modules/codedang-infra/ecs-client.tf

ECS 환경 변수에 있던 typo를 제거합니다.
---

fix: remove typo in ecs env

---

backend/apps/admin/src/problem/problem.service.ts

testcase가 upload 될 때 id 형식이 맞지 않는 오류를 수정합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/773"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(be): modify testcase upload format to bucket

---

backend/apps/client/src/group/group.service.ts

Closes #748 
Group에 가입할 때 admin 또는 super admin인 경우 자동으로 group leader로 설정되도록 했습니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/763"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(be): modify createUserGroup function

---

backend/apps/admin/src/problem/problem.service.ts

Closes #775 
기존에는 단순 index를 포함한 Id로 bucket에 올려서 submissionResult 생성 중 testcaseId 부분에서 에러가 발생했습니다.
이에 따라 `problemId:testcaseId` 형식에 맞춰 다시 수정했습니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/777"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(be): modify testcase upload id to bucket

---

Caddyfile

Close #736 
Dev Server에 localhost로 접속이 가능하도록 설정했습니다. 
댓글에서 언급했던 것 처럼 프록시로 먼저 시도해보려고 했는데 도저히 감이 안잡혀서 ㅎㅎ 
일단 급한대로 CORS로 접근해서 설정해놓기는 했습니다만, 보안 상 허술해 보여서...
프록시 관련 설정은 조금 더 찾아보겠습니다!
+ dev server랑 통신하는 동안 frontend 부분에 임시로 설정이 필요한데 그 부분은 팀즈에 올렸어요! 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/779"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: set cors header for dev server

---

frontend/src/admin/pages/problem.vue

Admin problem 페이지에 있는 naive-ui pagination을 pagination 컴포넌트로 변경
close #758
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/789"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

refactor(fe): replace naive-ui pagination to our pagination component

---

frontend/src/user/problem/components/Navigator.vue
frontend/src/user/problem/pages/[id]/index.vue
frontend/src/user/problem/store/problem.ts

- 기존에 상태관리가 잘못 돼서 문제간 이동하거나 탭 이동해도 language가 바뀌지 않거나 이상한 값이 표시되었는데 해결!
close #780 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/790"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(fe): update item in problem language dropdown

---

.github/workflows/deploy.yml
infra/modules/codedang-infra/redis.tf

Close #795 
Elasticache의 log를 Cloudwatch에서 볼 수 있도록 설정합니다. 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/796"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(infra): add log configuration for Elasticache

---

.github/workflows/deploy.yml
backend/apps/client/src/email/email.service.ts
backend/apps/client/src/email/mailerConfig.service.ts
backend/apps/client/src/user/user.controller.ts
backend/libs/exception/src/business.exception.ts

회원가입 이메일이 보내지지 않는 문제를 해결합니다.
SES에서 `aws` 옵션이 설정되지 않아 AWS command가 전달되지 않았는데, import를 추가하여 전달합니다.
배포 시 느린 ARM Docker image build를 개선하기 위해 self-hosted builder를 구성하였습니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/799"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(be): cannot send email with ses 

---

infra/modules/codedang-infra/ecs-client.tf
infra/modules/codedang-infra/ecs-iris.tf
infra/modules/codedang-infra/ecs.tf

#800 에서 고쳐지지 않은 문제를 해결합니다.
ECS에 task execution role 대신, **task role**에 SES 권한을 추가해 container에서 접근할 수 있도록 합니다.
(이번엔 제발...)
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/801"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(infra): add ecs task role for ses

---

infra/modules/codedang-infra/redis.tf

Redis의 Cluster mode를 해제합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/802"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(infra): disable redis cluster mode

---

backend/apps/client/src/submission/dto/judger-response.dto.ts
backend/apps/client/src/submission/submission.service.spec.ts

Judge result에서 accept된 경우(result code 0) validation이 되지 않는 문제를 해결합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/817"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(be): validate accepted judge result

---

frontend/src/admin/components/CreateProblemModal.vue

라벨 옆에 빨간색 별표로 required를 표현
close #828 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/829"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(fe): required expression in create problem modal

---

backend/apps/client/src/submission/dto/judger-response.dto.ts
backend/apps/client/src/submission/submission.service.spec.ts
backend/apps/client/src/submission/submission.service.ts

잘못된 result code(![0, 7])가 반환되었을 때 error를 뱉는 test를 통과하도록 조건을 추가합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/830"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(be): set max value of judger response result code

---

backend/apps/client/src/submission/submission.service.spec.ts
backend/apps/client/src/submission/submission.service.ts

자동으로 serialize되지 않는 BigInt 값을 string으로 변경하여 반환합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/831"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(be): return bigint number as stringified

---

infra/modules/codedang-infra/ecs-api-admin.tf
infra/modules/codedang-infra/ecs-api-client.tf

Task definition 파일에 redis host 오타 수정
clinet task definition 파일명 수정하면서 templatefile명 갱신하지 않은 부분 수정
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/835"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: fix redis host address and task definitions

---

infra/modules/codedang-infra/ecs-iris-asg.tf

사용하던 이미지 ami를 서울region에서 사용할 수 있는 ami로 변경합니다. 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/836"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(infra): use seoul image ami

---

infra/modules/codedang-infra/ecs-api-asg.tf
infra/modules/codedang-infra/ecs-iris-asg.tf
infra/modules/codedang-infra/ecs.tf

launch template에 사용되는 `cloud_init` data source를 수정합니다. 
`template_cloud_init` -> `cloud_init`
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/837"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: fix target group cloudinit_config data source

---

infra/modules/codedang-infra/ecs-api-admin.tf
infra/modules/codedang-infra/ecs-api-client.tf

Close #838 
ALB가 Public Subnet에 위치해있어야 외부에서 접근이 가능합니다.
일단, 콘솔에서 직접 수정해놓은 상태라서 지금은 접근이 되기는 할겁니다!
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/839"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: set alb in public subnet

---

infra/modules/codedang-infra/ecs-api-asg.tf
infra/modules/codedang-infra/ecs-iris-asg.tf
infra/modules/codedang-infra/ecs.tf
infra/modules/codedang-infra/user-data.sh

Clode #840 
`data "cloudinit_config"` 대신에 `templatefile`을 통해서 직접 값을 전달합니다.
`cloudinit_config` 사용했을 때
`templatefile` 테스트 결과
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/841"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: using templatefile for launch template user data

---

infra/modules/codedang-infra/ecs-api-client.tf

`task-definition`에서 `rabbitmq_host`의 오타를 수정합니다. 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/843"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: remove bracket typo from mq host

---

infra/modules/codedang-infra/ecs-api-client.tf
infra/modules/codedang-infra/ecs.tf

EC2로 instance 변경하는 과정에서 삭제된 email 전송 task role 추가합니다. 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/844"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(infra): use task role to send email

---

infra/modules/codedang-infra/backend/admin-task-definition.tftpl
infra/modules/codedang-infra/backend/client-task-definition.tftpl
infra/modules/codedang-infra/iris/task-definition.tftpl
infra/modules/codedang-infra/user-data.sh

Close #849 
Task의 reserved vCPU 를 줄여서 자동 업데이트가 가능하도록 합니다. 
+ user_data의 설정파일에 `ECS_ENABLE_TASK_IAM_ROLE`를 추가했습니다
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/850"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(inf): enable task auto-update

---

infra/modules/codedang-infra/ecs-iris.tf
infra/modules/codedang-infra/iris/task-definition.tftpl

Iris에 필요한 `TESTCASE_BUCKET_NAME`을 추가합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/852"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(infra): add missing ecs iris env

---

infra/modules/codedang-infra/testcase.tf

Deploy 과정에서 발생한 오류를 수정합니다 .
testcase policy의 resource 부분의 코드 수정
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/858"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(inf): change testcase policy resource

---

infra/modules/codedang-infra/testcase.tf

Deploy action에서 발생한 S3 bucket policy 에러를 수정합니다. 
(resource를 testcase가 아니라 frontend로 설정해서 오류 발생함.)
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/861"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(infra): fix testcase bucket policy resource

---

backend/apps/client/src/notice/notice.service.spec.ts
backend/apps/client/src/notice/notice.service.ts

Closes #825 
get Notice 할때 createdBy 가 없어서 추가해주었습니다. `username` 필드를 불러옵니다.
🍀
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/864"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(be): add createdBy to get notice response

---

.github/workflows/deploy.yml

코드 수정 중 runs-on을 지우는 바람에 발생한 오류 수정
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/868"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(infra): add runs-on to deploy action

---

infra/modules/codedang-infra/iris/task-definition.tftpl
iris/src/handler/judge-handler.go

#869 해결을 위해 에러 내용을 로그로 남깁니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/870"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore(iris): add sandbox error logging

---

.github/workflows/deploy.yml
.github/workflows/devserver.yml
infra/builder/iris/Dockerfile
iris/Dockerfile
iris/src/connector/rabbitmq/producer.go
iris/src/handler/judge-handler.go
iris/src/service/sandbox/runner.go
iris/src/service/sandbox/sandbox.go

Close #869 
드디어 원인을 찾았습니다! 야호!
Judger(sandbox)에서 응답으로 보내는 JSON과 Iris에서 읽어오는 JSON의 형태가 맞지 않았습니다.
Judger는 필드명을 snake_case, iris는 camelCase로 사용해 snake_case로 통일하였습니다.
- Judger: https://github.com/QingdaoU/Judger/blob/fd92d0365fa38bdc2b22e563c31ec73d49a98584/src/main.c#L172-L180
https://github.com/skkuding/codedang/blob/96d4751e5710d65d127a6801f31f78feeb19fa82/iris/src/service/sandbox/sandbox.go#L62-L70
- Dockerfile 옮겼습니다 (infra/builder/iris => iris)
- iris 컨테이너는 이제 Ubuntu로 동작합니다.
- iris 응답에 에러 메시지를 포함시켰습니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/879"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(iris): fix mismatched sandbox result

---

iris/main.go
iris/src/service/sandbox/compiler.go
iris/src/service/sandbox/runner.go

컴파일에서 iris가 죽는 원인을 알아보기 위해 로깅을 추가합니다...
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/883"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(iris): add compile failure log

---

iris/src/service/sandbox/compiler.go

컴파일 실패 시 로그를 조금 더 상세하게 남깁니다.
기존에는 compile out 파일이 없으면 에러를 throw하고 결과를 출력하지 않았는데,
out 파일을 나중에 읽고 시스템 에러를 먼저 handling하도록 수정하였습니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/884"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(iris): log compile failure

---

backend/apps/client/src/submission/submission.service.spec.ts
backend/apps/client/src/submission/submission.service.ts
frontend/src/common/components/Molecule/Dropdown.vue
frontend/src/user/problem/components/Navigator.vue
frontend/src/user/problem/components/SubmissionList.vue

채점 시 compile error가 안되는 경우 backend에서 처리하는 코드를 추가합니다.
(컴파일 에러 메시지는 나중에...)
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/886"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(be): handle compile error

---

frontend/src/admin/components/CreateProblemModal.vue

transform으로 timelimit의 type 을 바꿈
close #888 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/889"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(fe): transform type

---

frontend/src/common/components/Atom/InputItem.vue
frontend/src/common/components/Organism/Signup.vue
frontend/src/common/store/auth.ts
frontend/src/common/styles/style.css
frontend/src/main.ts

Close #891 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/894"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(fe): use vee-validate in sign up form

---

.github/workflows/compress-image.yml

Close #814
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/908"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(ci): configure image-actions

---

backend/apps/client/src/submission/submission.controller.ts

Close #768 
```
$ time pnpm build
> backend@ build /workspace/backend
> nest build
webpack 5.88.1 compiled successfully in 32197 ms
real    0m34.239s
user    0m40.869s
sys     0m4.429s
```
```
$ time pnpm build
> backend@ build /workspace/backend
> nest build
webpack 5.88.2 compiled successfully in 4876 ms
real    0m6.918s
user    0m9.285s
sys     0m1.100s
```
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/909"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(be): remove invalid import

---

frontend/src/common/components/Atom/Spinner.story.vue
frontend/src/common/components/Atom/Spinner.vue
frontend/src/common/composables/api.ts
frontend/src/user/problem/components/Navigator.vue
frontend/src/user/problem/pages/index.vue

feat(fe): add loading in problem page

---

frontend/src/common/composables/graphql.ts

take와 pagesPerSlot의 값을 기본값으로 사용하고 싶을 때 칸을 비울 수 있다. 
close #292 
---

fix(fe): let useListGraphQL option optional

---

frontend/index.html

네이버 SEO 작업을 위한 네이버 웹마스터 도구를 사용하려면 사이트 소유 인증이 필요해서 index.html 파일에 meta 태그 추가함.
인증을 위해서는 배포도 필요함!
close #940 
---

feat(fe): add meta tag for naver seo

---

frontend/src/admin/pages/[groupId]/problem/index.vue
frontend/src/common/components/Organism/Sidebar.vue

Temporarily removed sidebar items except main.
Will be changed to icons per groups with siderbar items.
Fixed typo(someting -> something)
---

fix(fe): removed sidebar items, fixed typo

---

scripts/post-checkout.sh

로컬 개발환경에서는 checkout hook으로 데이터베이스 migration을 실행하지 않는다.
---

fix: migrate on checkout only in devcontainer

---

scripts/post-checkout.sh

#966 의 post-checkout script에서 잘못된 문법을 수정합니다.
---

fix: invalid post-checkout script

---

backend/Dockerfile

Docker multi-stage build에서 `ARG` 옵션 사용 시 stage마다 `ARG`를 명시해야 합니다.
---

fix(be): arg does not work in docker multi stage

---

backend/Dockerfile
backend/entrypoint.sh

`pnpm deploy out` 후 폴더 `out`에 `node_modules`가 포함되어있으므로,
`out` 전체를 Docker에 포함시키고, 실행되는 main.js 경로를 수정합니다.
---

fix(infra): include deploy out result in docker

---

frontend/src/common/components/Organism/AuthModal.vue
frontend/src/common/components/Organism/Login.vue

Close #1010 
로그인 모달 높이 수정, 문구 삭제, 마진 수정
---

feat(fe): login modal content, height change

---

frontend-client/package.json

next js 개발용 서버 port 5525로 설정
---

fix(fe): nextjs dev server port

---

frontend-client/app/contest/page.tsx
frontend-client/app/group/page.tsx
frontend-client/app/layout.tsx
frontend-client/app/notice/page.tsx
frontend-client/app/page.tsx
frontend-client/app/problem/page.tsx
frontend-client/tailwind.config.ts

- tailwind config 잘못 수정된 부분 hotfix
- root layout에 main section 미리 만들어서 추후 page 별로 통일성 있게 개발할 수 있도록 함
close #1027 
---

feat(fe): add main section in root layout

---

frontend-client/lib/vars.ts

fetch 할 때 'https://dev.codedang.com/api..." 이렇게 url을 적으면 배포 후에 base url을 바꿀 수 없다. 따라서 아래의 방식으로 fetch 사용할 것!
1. 프로젝트 루트 폴더에 .env 파일 생성
2. .env 파일에 `NEXT_PUBLIC_BASEURL=https://dev.codedang.com/api`쓰기
3. fetch 할 때 아래 사진 처럼 baseUrl 변수 import 해서 사용
---

feat(fe): baseUrl variable for fetch

---

.github/workflows/ci.yml
backend/prisma/schema.prisma

CI 액션 중 Prisma migration을 확인하는 에러에서 잘못된 migration이 감지되어도 job이 fail되지 않습니다.
https://github.com/skkuding/codedang/actions/runs/7327484158/job/19959990575
---

fix(ci): error is not thrown when invalid prisma migration detected

---

backend/apps/client/src/announcement/announcement.controller.ts
backend/apps/client/src/announcement/announcement.module.ts
backend/apps/client/src/announcement/announcement.service.ts
backend/prisma/schema.prisma

`@generated` 폴더 내 타입 import로 인해 클라이언트 앱 빌드 속도가 크게 느려져 import를 지웁니다.
---

fix(be): remove import from generated in client app code

---

backend/apps/client/src/main.ts

#1083에서 수정되지 않아 NestJS 코드를 일부 수정합니다
---

fix(be): let frontend access email-auth header with cors

---

backend/apps/client/src/user/dto/username.dto.ts
backend/apps/client/src/user/user.controller.ts
backend/apps/client/src/user/user.service.spec.ts
backend/apps/client/src/user/user.service.ts
collection/client/User/Check Duplicated Username/409: Duplicated Username.bru
collection/client/User/Check Duplicated Username/Succeed.bru

Close #1097 
중복된 username이 존재하는지 확인하는 api를 구현합니다.
---

feat(be): implement check-duplicated-username api

---

frontend-client/app/_components/Footer.tsx
frontend-client/app/_components/SignUp.tsx
frontend-client/app/layout.tsx
frontend-client/components/ui/sonner.tsx
frontend-client/package.json
pnpm-lock.yaml

Toast를 Sonner로 수정
- Sign Up, Footer에 있는 Toast를 Sonner로 수정했습니다.
- Top-center 적용
- richColors, success, error 사용
close #1110
---
- [x ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

feat(fe): change toaster to sonner

---

frontend-client/app/notice/_components/NoticeTable.tsx
frontend-client/app/notice/page.tsx
pnpm-lock.yaml

- 고정된 게시물 표시
- 일단 최대 10개의 고정된 게시물 가져오기
close #1107 
---

feat(fe): fixed notice

---

.github/workflows/cd-prod.yml

CD - Production workflow 실행 시 AWS credential 연결이 안됩니다...
---

fix(cd): create iam role for ecr push

---

infra/modules/codedang-infra/.terraform.lock.hcl

CD - Production workflow에서 terraform lockfile로 인해 job 실행이 안됩니다.
https://github.com/skkuding/codedang/actions/runs/7384157092
---

fix(infra): resolve invalid terraform lockfile

---

backend/apps/admin/src/contest/contest.service.ts
backend/apps/admin/src/group/group.service.ts
backend/apps/admin/src/problem/problem.service.ts
backend/apps/admin/src/user/user.service.ts
backend/apps/client/src/contest/contest.service.ts
backend/apps/client/src/group/group.service.ts
backend/apps/client/src/notice/notice.service.ts
backend/apps/client/src/workbook/workbook.service.ts

뒤로 페이지네이션할 때(take < 0) cursor가 skip되지 않도록 설정해서, 다음 슬롯이 존재하는지를 확인할 수 있도록 합니다.
---

fix(be): do not skip during backward pagination

---

infra/deploy/.terraform.lock.hcl
infra/local/.terraform.lock.hcl

#1126에서 해결이 제대로 안돼서 다시 올립니다...
---

fix(infra): resolve broken lockfile (2nd try)

---

infra/modules/codedang-infra/ecs-iris-service-asg.tf

fix(infra): fix typo in ecs-iris-service-asg file

---

.eslintrc.js
backend/apps/admin/src/contest/contest.service.spec.ts
backend/apps/admin/src/contest/contest.service.ts
backend/apps/admin/src/problem/problem.service.spec.ts
backend/apps/admin/src/problem/problem.service.ts
backend/apps/admin/src/user/user.service.ts
backend/apps/client/src/announcement/announcement.service.spec.ts
backend/apps/client/src/contest/contest.service.spec.ts
backend/apps/client/src/contest/contest.service.ts
backend/apps/client/src/group/group.service.ts
backend/apps/client/src/notice/notice.service.spec.ts
backend/apps/client/src/problem/problem.repository.ts
backend/apps/client/src/submission/submission.service.ts
backend/apps/client/src/user/user.service.ts
backend/libs/auth/src/roles/roles.service.ts
frontend-client/app/(main)/_components/SignUpEmailVerify.tsx
frontend/src/user/workbook/composables/workbook.ts

feat(ci): apply object-shorthand eslint rule

---

backend/apps/client/src/problem/contest-problem.controller.ts
backend/apps/client/src/problem/workbook-problem.controller.ts

try-catch의 에러 변수 이름을 `error`로 통일합니다
---

refactor(be): use consistant error variable name

---

backend/prisma/seed.ts
collection/client/Contest/Get contest by ID/Succeed.bru
collection/client/Contest/Get finished contests/Succeed.bru
collection/client/Contest/Get group contest by ID/Succeed.bru
collection/client/Contest/Get group finished contests/Succeed.bru
collection/client/Contest/Get group ongoing & upcoming contests/Succeed.bru

close #1180
기존에 private group의 contest였던 것을 Open Space Contest로 변경하고, Private group contest를 3개 생성합니다.
---

feat(be): add more contest seed data

---

frontend-client/app/layout.tsx
frontend-client/lib/utils.ts
frontend-client/next.config.js
frontend-client/package.json
pnpm-lock.yaml

VECEL_URL은 https://로 시작 안하기 때문에 수정
---

fix(fe): change metabase url

---

frontend-client/app/(main)/_components/Footer.tsx

- footer 디자인 변경
- size를 더 크게 조절했습니다
- margin bottom을 없앴습니다.
close #1190
---
- [x ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

feat(fe): change footer design 

---

frontend-client/app/(main)/page.tsx

#1178 에서 적용된 query-based API를 적용합니다.
---

fix(fe): apply updated api style to home page

---

.github/workflows/cd-prod.yml
backend/apps/client/src/auth/auth.controller.ts
backend/apps/client/src/auth/auth.module.ts
backend/apps/client/src/auth/auth.service.ts
backend/apps/client/src/auth/interface/social-user.interface.ts
backend/apps/client/src/user/dto/social-signup.dto.ts
backend/libs/auth/src/kakao/kakao.strategy.ts
backend/libs/constants/src/oauth.constants.ts
backend/package.json
backend/prisma/migrations/20240118071939_change_user_oauth_id_to_string/migration.sql
backend/prisma/schema.prisma
infra/deploy/main.tf
infra/deploy/variable.tf
infra/local/main.tf
infra/local/variable.tf
infra/modules/codedang-infra/backend/client-task-definition.tftpl
infra/modules/codedang-infra/ecs-api-client.tf
infra/modules/codedang-infra/variables.tf
pnpm-lock.yaml

Closes #910
Kakao 로그인 / 회원가입 기능을 추가합니다.
- `UserOAuth` 모델의 `id` 필드의 type이 기존 `Int`였는데, Kakao id가 범위를 넘어가는 문제가 있어 `String`으로 변경하였습니다.
- 기존 Github 로그인 / 회원가입 기능과 로직이 거의 동일하므로 해당 PR 참고 부탁드립니다.
- https://github.com/skkuding/codedang/pull/897
---

feat(be): add kakao login

---

backend/apps/client/src/problem/dto/problem.response.dto.ts
backend/apps/client/src/problem/problem.service.spec.ts
backend/apps/client/src/problem/problem.service.ts
collection/client/Problem/Get problem by ID/Succeed.bru

getProblemById에다가 tag 리스트를 추가하였습니다.
실제 Response
```
{
"id": 1,
"title": "정수 더하기",
"description": "<p>\n  두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오. 첫째 줄에\n  A와 B가 주어진다. (0 < A, B < 10) 첫째 줄에 A+B를 출력한다.\n</p>\n",
"inputDescription": "<p>첫째 줄에 A와 B가 주어진다. (0 < A, B < 10)</p>\n",
"outputDescription": "<p>첫째 줄에 A+B를 출력한다.</p>\n",
"hint": "",
"languages": [
"C",
"Cpp",
"Java",
"Python3"
],
"timeLimit": 2000,
"memoryLimit": 512,
"difficulty": "Level1",
"source": "",
"submissionCount": 0,
"acceptedCount": 0,
"acceptedRate": 0,
"inputExamples": [],
"outputExamples": [],
"tags": [
{
"id": 1,
"name": "If Statement"
}
]
}
```
---

feat(be): add tags to getProblemById

---

backend/apps/client/src/submission/dto/judger-response.dto.ts
backend/apps/client/src/submission/mock/submissionResult.mock.ts
backend/apps/client/src/submission/submission.service.spec.ts
backend/apps/client/src/submission/submission.service.ts
collection/client/Submission/Create Submission/Succeed.bru

docs(be): add submission creation api

---

frontend-client/app/(main)/_components/SignUpRegister.tsx

* userId와 password의 조건을 백엔드 기준에 맞춰 수정
userId: 3-10자 영문 소문자 및 숫자 허용
password: 8자 이상 영문 소문자, 대문자, 숫자 중 2가지 이상 사용
* userId와 password 조건 text 수정
Close #1250 
---

fix(fe): edit username password conditions

---

backend/prisma/seed.ts

feat(be): seeding input output examples

---

frontend-client/middleware.ts

user이거나  일시에만 admin 접근 못하게 설정
---

fix(fe): change protection condition for a admin page

---

frontend-client/app/(main)/_components/Header.tsx

group을 tab에서 빼면서 너무 오른쪽으로 치우쳐져서 왼쪽으로 좀 당겼음
---

fix(fe): change a header position

---

frontend-client/app/(main)/_components/ContestCard.tsx
frontend-client/app/(main)/_components/ProblemCard.tsx
frontend-client/app/admin/_components/GroupSelect.tsx
frontend-client/app/admin/layout.tsx

safari 에서는 text-wrap이 지원 안해서 white-space로 바꿈
---

fix(fe): change text wrap to whitespace

---

frontend-client/app/(main)/_components/SignIn.tsx

- <img width="381" alt="스크린샷 2024-02-07 오후 4 33 20" src="https://github.com/skkuding/codedang/assets/59248080/5971c587-7979-415c-a9c3-66ba47d0fb9f">
- Successfully signed in -> Successfully logged in 으로 변경
---

fix(fe): change login toast message

---

frontend-client/components/SortButton.tsx

feat(fe): add cancel feature in problem table sort button

---

backend/apps/client/src/problem/problem.repository.ts

fix(be): problem sorting

---

.github/workflows/reset-seed.yml
.github/workflows/update-seed.yml

closes #1337 
백엔드팀에서 seed.ts를 수정할 때마다, Infra팀에게 On-premise에 구동중인 db container에 수정된 seed를 반영해달라고 부탁해야 합니다.
이러한 번거로움을 막기 위해, 백엔드팀이 필요할 때마다 수동으로 github action을 실행시켜서 seed가 바로 업데이트 될 수 있도록 합니다.
---

feat(cd): applying updated seed on stage-server by manual trigger

---

frontend-client/app/admin/problem/_components/Columns.tsx
frontend-client/app/admin/problem/page.tsx
frontend-client/components/DataTableAdmin.tsx
frontend-client/components/DataTableColumnHeader.tsx
frontend-client/components/DataTablePagination.tsx
frontend-client/components/OptionSelect.tsx

- Admin problem list page datatable 우선작업
- DataTableAdmin 컴포넌트화
- columns, fetch된data 인자로 전달
- 현재 Date, Hidden 관련 api 없어서 요청한 상태
- Date 내용들은 현재 표시되지 않는 상태
- Hidden Switch는 ui만 만들어놓음 (기능x)
- 우선 codedang client에서 fetch한 상태
- fetch과정에서 tags가져오지 못하는 문제
- 각 column 오름차순, 내림차순, 열 숨기기 기능 구현
---

feat(fe): problem list datatable

---

frontend-client/app/(main)/_components/HeaderAuthPanel.tsx
frontend-client/app/(main)/_components/SignIn.tsx
frontend-client/app/(main)/_components/SignUp.tsx
frontend-client/app/(main)/_components/UserDropdown.tsx

1. Log in -> Log In
2. Sign Out -> Log Out
3. 연타하더라도 log in 토스트 여러개 못 뜨도록 수정 했습니다
Close #1362 
---

fix(fe): edit login and logout

---

frontend-client/app/(main)/_components/ProblemCards.tsx
frontend-client/app/(main)/contest/[id]/@tabs/problem/page.tsx
frontend-client/app/(main)/problem/_components/ProblemTable.tsx
frontend-client/app/admin/problem/page.tsx

홈화면에서 problem API 변경사항 때문에 렌더링 에러가 발생합니다.
---

fix(fe): fix broken main page api

---

frontend-client/app/problem/[id]/layout.tsx
frontend-client/public/codedang-editor.svg

feat(fe): change logo in editor page

---

backend/apps/admin/src/contest/contest.service.spec.ts
backend/apps/admin/src/problem/mock/mock.ts
backend/apps/client/src/problem/dto/problem.response.dto.ts
backend/apps/client/src/problem/dto/problems.response.dto.ts
backend/apps/client/src/problem/mock/problem.mock.ts
backend/apps/client/src/problem/problem.repository.ts
backend/apps/client/src/submission/mock/problem.mock.ts
backend/prisma/__fixtures__/problem/1-description-eng.html
backend/prisma/__fixtures__/problem/1-input-eng.html
backend/prisma/__fixtures__/problem/1-output-eng.html
backend/prisma/migrations/20240215062711_add_english_information_to_problem_model/migration.sql
backend/prisma/schema.prisma
backend/prisma/seed.ts

Closes #1372
영문 버전의 문제 설명을 표시할 수 있도록 하기 위해, Problem 모델에 `engTitle`, `engDescription`, `engInputDescription`, `engOutputDescription`, `engHint`를 추가합니다.
모든 영문 버전의 정보는 optional입니다.
`seed.ts`에서 삽입되는 첫 번째 problem에 영문 설명을 추가했습니다.
---

chore(be): modify problem model to get english informations

---

.github/workflows/cd-prod.yml
infra/modules/codedang-infra/db.tf

- RDS postgresql 버전 업그레이드 (14.7 > 14.10)
- `TFVARS` 환경변수 parsing error
---

fix(cd): resolve cd pipeline errors

---

backend/apps/admin/src/problem/problem.service.ts

`query getProblem`에 `sample` field의 값이 제대로 담기지 않아서 고쳤어요
---

fix(be): include sample data in admin problem query

---

frontend-client/components/DataTableColumnHeader.tsx

- 특정 column hide하는 기능 삭제
- 다시 복구할 방법이 없음!
---

feat(fe): delete hide

---

backend/apps/client/src/problem/problem.repository.ts

`selectOptions`에 타이핑이 되어있지 않아서 생기는 문제를 해결합니다.
---

fix(be): replace input/output-examples with samples

---

frontend-client/app/problem/[problemId]/submission/[submissionId]/page.tsx
frontend-client/app/problem/[problemId]/submission/page.tsx
frontend-client/components/Codeeditor.tsx

- submission 확인할 때 code editor readonly option 추가, editable option 삭제
- 최신순으로 정렬
- 실행시간, 메모리 단위 추가 
close #1421
---

feat(fe): edit submission page

---

backend/apps/client/src/notice/notice.service.ts
frontend-client/app/(main)/notice/_components/NoticeTable.tsx

> Closes #1413 
- 순서를 `id`의 역순으로 정렬합니다.
- 성능 개선을 위해 `createTime` 대신 인덱싱되어 있는 `id`를 정렬 기준으로 사용했습니다.
- 검색 시 case insensitive 모드를 사용합니다.
- 검색어가 입력되었을 때는 고정된 게시물이 노출되지 않도록 합니다.
---

fix: fix minor bugs in notice page

---

frontend-client/app/admin/problem/[id]/page.tsx
frontend-client/app/admin/problem/page.tsx

백엔드 코드에서 testcase 전송 관련 코드가 수정되어 프론트엔드 코드를 이에 맞춥니다!
---

fix(fe): change gql query and response type

---

Caddyfile
backend/apps/admin/src/main.ts
backend/apps/client/src/main.ts

Dev 서버에서 GraphQL에 CORS가 제대로 동작하지 않는 문제를 해결합니다.
---

fix(infra): graphql api cors not working

---

frontend-client/app/problem/[problemId]/submission/[submissionId]/page.tsx
frontend-client/app/problem/[problemId]/submission/page.tsx

- 기존에는 정답을 제출하지 않았을 때 submission 목록에서 다른 사람이 제출한 문제를 누르면 redirect로 이전 페이지로 연결되었음
- 타인의 submission page로 가되, 내용을 보여주지 않는 방향으로 수정함
- 수정하는 김에 data.toReverted()로 되어있는 부분 백엔드 api 변경에 따라 data로 수정  
---

feat(fe): hide submission page for uncorrected state

---

frontend-client/app/(main)/_components/ProblemCard.tsx
frontend-client/app/(main)/problem/_components/Columns.tsx
frontend-client/app/admin/problem/_components/Columns.tsx

- problem page의 solved를 백분율로 고쳤습니다. 
- 메인페이지 카드의 solved rate도 수정했습니다.
- admin에서도 수정했습니다. 
close #1488
---

fix(fe): fix solved percentage

---

frontend-client/app/(main)/problem/_components/ProblemTable.tsx

(main)/problems에서 2xx이 아닌 응답이 전달되었을 때 에러를 핸들링하는 코드를 추가합니다.
---

test(fe): show error message

---

frontend-client/app/(main)/problem/_components/ProblemTable.tsx

#1457 PR 코드에 오타가 있어 수정합니다... 🍎 
---

fix(fe): fix typo in api endpoint

---

backend/apps/client/src/user/user.controller.ts
backend/apps/client/src/user/user.service.ts
collection/client/User/Get Username by Email/Succeed.bru
collection/client/User/Get Username by Email/[404] Not Found.bru

Closes #1453 
Email을 기준으로 사용자 이름을 반환하는 API를 구현했습니다.
---

feat(be): find username by emailaddress

---

frontend-client/app/problem/[problemId]/submission/page.tsx
frontend-client/components/EditorResizablePanel.tsx
frontend-client/components/Paginator.tsx
frontend-client/components/ui/pagination.tsx
frontend-client/lib/usePagination.ts
frontend-client/tailwind.config.ts

> Closes #1247
- Submission 페이지에 페이지네이션을 적용합니다.
- Standings 페이지에는 동일한 페이지네이션을 적용할 예정이나, 백엔드 구현상의 문제로 아직 API를 연결하지 않았습니다.
---

feat(fe): add pagination to submission list

---

frontend-client/.gitignore
frontend-client/app/(main)/error.tsx
frontend-client/app/api/sentry-example-api/route.ts
frontend-client/app/global-error.tsx
frontend-client/app/sentry-example-page/page.tsx
frontend-client/components/EditorLayout.tsx
frontend-client/next.config.js
frontend-client/package.json
frontend-client/sentry.client.config.ts
frontend-client/sentry.edge.config.ts
frontend-client/sentry.server.config.ts
pnpm-lock.yaml

프론트엔드 Next.js에 Sentry 모니터를 구성합니다.
---

feat(fe): configure sentry monitor

---

backend/libs/exception/src/graphql-error-code.ts

closes #1469 
400 에러에 대해 GQL 에러 코드가 FORBIDDEN으로 떠야 하는데 UNAUTHENTICATED로 잘못 설정되어있었습니다.
---

fix: change GQL Error code

---

frontend-client/components/EditorHeader.tsx

요청에 따라 코드 초기화 아이콘 변경하였습니다
| 기존 | 변경 |
|--------|--------|
| <img width="186" alt="image" src="https://github.com/skkuding/codedang/assets/19747913/753adcd8-0db0-4909-bc70-177e00098964"> | <img width="196" alt="image" src="https://github.com/skkuding/codedang/assets/19747913/9b95c57e-37b5-4298-8791-7d6442e81710"> |
---

fix(fe): replace code reset icon

---

frontend-client/app/problem/[problemId]/submission/_components/SubmissionDetail.tsx
frontend-client/components/EditorDescription.tsx
frontend-client/components/EditorHeader.tsx
frontend-client/package.json
pnpm-lock.yaml

Close #1292 
Close #1485 
문제 제출 후 정답일 때 축하 효과를 넣어요
https://github.com/skkuding/codedang/assets/19747913/aa7789a4-e1b4-470f-913e-ea77652ea6ab
- 제출 결과에 표시되는 메모리 형식을 정정했어요
- input / output 샘플 복사 관련 코드를 custom hook으로 리팩토링했어요
- Submission 정보 페이지에 잘못 들어간 10초 sleep 코드를 지웠어요 (#1485)
---

feat(fe): add confetti effect on accepted

---

backend/package.json
pnpm-lock.yaml
renovate.json

https://github.com/nest-modules/mailer/issues/1119
@nest-modules/mailer 1.11.0에서 `css-inline` 의존성 때문에 에러가 발생해요...
임시로 다운그레이드 합니다
---

fix: downgrade @nestjs-modules/mailer

---

Caddyfile

이메일 인증 때 CORS 때문에 인증이 되지 않아요...
Caddyfile의 CORS 정책을 수정했습니다
---

fix: allow email auth headers for cors

---

frontend-client/app/(main)/contest/[contestId]/page.tsx
frontend-client/app/(main)/notice/[id]/page.tsx
frontend-client/app/admin/_components/ApolloProvider.tsx
frontend-client/app/admin/problem/[id]/page.tsx
frontend-client/app/admin/problem/create/page.tsx
frontend-client/app/admin/problem/utils.ts
frontend-client/app/layout.tsx
frontend-client/components/CheckboxSelect.tsx
frontend-client/components/CodeEditor.tsx
frontend-client/components/OptionSelect.tsx
frontend-client/components/auth/SignUpEmailVerify.tsx
frontend-client/components/auth/SignUpRegister.tsx
frontend-client/lib/auth.ts
frontend-client/lib/constants.ts
frontend-client/lib/utils.ts
frontend-client/lib/vars.ts
frontend-client/middleware.ts
frontend-client/types/type.ts

language, level 상수 배열들이 이곳저곳에서 각자 선언해서 사용하고 있어서 통합했고 `vars.ts`에서 `constants.ts`로 파일명을 바꿨습니다!
---

refactor(fe): change vars to constants and remove duplication

---

frontend-client/app/admin/problem/[id]/page.tsx
frontend-client/app/admin/problem/create/page.tsx
frontend-client/components/EditorDescription.tsx

1. sample의 input ouput의 공백 줄바꿈 탭을 ␣  ↵  ↹ 로 수정
2. input output을 드래그에서 복사하는 것을 disable
3. 이슈 #1498 에서 수정한 inputDescription outputDescription은 다시 되돌리고 inputDescription과 outputDescription을 Texteditor로 수정
Closes #1505 
---

feat(fe): change input output whitespace visible

---

frontend-client/components/EditorDescription.tsx

output 설명에 input 설명이 표시되길래 고쳤어요
---

fix(fe): fix wrong output description

---

backend/apps/client/src/submission/submission.service.ts

Closes #1534
`submitToContest` 또는 `submitToWorkbook` 함수에서 submission을 생성할 때 `contestId`, `workbookId`를 포함하지 않는 문제를 수정합니다.
Get Submission 시 codeSize가 포함된 submission 정보를 불러오지 못하는 문제가 있습니다. #1271 머지 시 해결될 것으로 보입니다.
---

fix(be): include contest-id or workbook-id to submission if provided

---

.github/workflows/cd-dev.yml
.github/workflows/cd-prod.yml
apps/backend/Dockerfile

fix(infra): update context path for cd-dev pipeline

---

.github/workflows/cd-prod.yml

fix(infra): update terraform dir in cd-prod

---

apps/frontend/app/(main)/_components/ProblemCards.tsx
apps/frontend/app/(main)/page.tsx
apps/frontend/components/auth/SignIn.tsx
apps/frontend/components/auth/SignUpWelcome.tsx

- main page contests 주석처리, 등등
---

fix(fe): change login modal and main page contests

---

apps/infra/modules/codedang-infra/backend/admin-task-definition.tftpl

fix(infra): add missing curly bracket in tftpl

---

pnpm-lock.yaml

package.json과 pnpm-lock file 버전 불일치를 수정합니다.
---

fix: fix pnpm-lock file

---

apps/backend/package.json
pnpm-lock.yaml

일단 Prisma Tracer관련 버전 오류가 있는 것 같아서 버전을 내렸습니다.
오늘 중으로 Issue 생성 후 추가 작업 하겠습니다! 
---

fix(infra): fix prisma instrumentation dependency issue

---

apps/frontend/components/auth/HeaderAuthPanel.tsx

- <img width="501" alt="스크린샷 2024-03-17 오후 1 55 32" src="https://github.com/skkuding/codedang/assets/59248080/112616b3-39eb-4a1a-b5af-acb8285b733b">
- logout 상태이며 반응형일때도 hamburger button 기능 추가
---

feat(fe): fix hamburger button when not logged in

---

apps/frontend/app/(main)/problem/page.tsx

window tab이 바뀔 때마다 refetch 해오는 문제를 해결합니다 
캐싱을 위해 stale time을 추가했습니다

fix(fe): fix refetch on window focus option

---

apps/backend/apps/client/src/problem/problem.repository.ts

- 총 문제 개수를 계산할 때 exposeTime 조건이 없어 실제로 가져오는 문제와 total 개수 불일치하는 문제 해결
---

fix(be): modify total problem calculating logic

---

apps/frontend/app/admin/contest/[id]/page.tsx
apps/frontend/app/admin/contest/create/page.tsx
apps/frontend/app/admin/problem/page.tsx
apps/frontend/components/DataTableAdmin.tsx

1. contest edit 페이지 완성했습니다
edit 페이지에서도 문제를 추가로 import하거나 삭제할 수 있습니다.
2. create contest 페이지와 edit contest 페이지에서
FaAngleLeft에 Link 태그를 달아줬습니다
왼쪽 아이콘 누르면 모두 admin/contest로 이동합니다
Closes #1590 
---

feat(fe): connect remove problem from contest api

---

apps/backend/apps/client/src/submission/submission.controller.ts

chore(be): remove console.log

---

apps/backend/apps/client/src/submission/submission.service.ts

contest의 제출 내역을 불러올 때는 problem의 exposetime을 검사할 필요가 없습니다.
따라서 해당 문제를 수정합니다.
---

fix(be): remove expose-time condition for problem in contest

---

apps/frontend/app/admin/contest/[id]/page.tsx
apps/frontend/app/admin/contest/_components/Columns.tsx
apps/frontend/app/admin/contest/create/page.tsx
apps/frontend/app/admin/contest/page.tsx

1. Contest의 visibility를 변경할 수 있음
2. Ongoing contest 일 때는 visibility를 수정할 수 없음
3. icon hover 하면 tooltip 올라옴
4. 대회에 문제를 import 하면 해당 문제의 visibility가 false됨
Closes #1597 
---

feat(fe): handle visibility of contest and problem

---

apps/frontend/app/admin/contest/[id]/page.tsx
apps/frontend/app/admin/contest/_components/Columns.tsx
apps/frontend/app/admin/contest/create/page.tsx
apps/frontend/app/admin/contest/page.tsx
apps/frontend/package.json
pnpm-lock.yaml

contest 스키마 변경에 따라 FE 코드에서 contest config를 unpack합니다.
+ cmdk의 breaking change로 인하여 v1에서 v0.2.1 로  revert 합니다. 
---

fix(fe): unpack contest config

---

apps/frontend/app/(main)/_components/TimeDiff.tsx

- 기존 '1400d' 형식으로 'D-1400'으로 변경
close #1621 
---

fix(fe): change contest time form

---

apps/frontend/app/contest/[contestId]/problem/[problemId]/page.tsx
apps/frontend/app/contest/error.tsx
apps/frontend/components/EditorDescription.tsx

contest의 problem을 불러올 때 problem/${problemId}로 불러오던 것을 contest/${contestId}/problem/${problemId}로 수정함
에러 페이지 추가해서 잘못된 접근 막음

feat(fe): restrict non-existent contest problem

---

.devcontainer/devcontainer.json

fix: create .env before running container

---

apps/frontend/app/admin/problem/[id]/edit/page.tsx
apps/frontend/app/admin/problem/create/page.tsx

problem을 create edit 할 때
zod schema의 title max length를 200으로 수정했습니다.
Closes #1640 
title을 textarea가 아니라 input에 받기도 하고 width가 고정되어 있어
title이 너무 길어지면 한 눈에 보기 어렵긴 하네요
---

chore: increase problem title length limit to 200

---

apps/backend/apps/client/src/submission/submission.controller.ts
apps/backend/apps/client/src/submission/submission.service.spec.ts
apps/backend/apps/client/src/submission/submission.service.ts

Admin 계정으로 로그인해도 자신이 생성한 contest submission 외에는 조회하지 못하는 문제를 수정합니다.
---

fix(be): make admin to get all contest submissions

---

apps/frontend/app/(main)/_components/Footer.tsx
renovate.json

fix: upgrade renovate golang constraint version

---

.gitignore

for re-triggering vercel deploy
---

fix(infra): rebuild vercel

---

apps/frontend/app/admin/_components/GroupSelect.tsx
apps/frontend/components/CheckboxSelect.tsx
apps/frontend/components/DataTableLangFilter.tsx

Shadcn CommandList 관련 breaking change 코드 수정.
CommandList 부분이 이제는 의무화 돼서 Command 이용한 부분에 Command List 추가해 놓았습니다!
---

fix(fe): add CommandList

---

apps/frontend/components/auth/SignUpRegister.tsx

Register버튼 누르고 post 요청 직후에 disable 되고, 만약 error가 뜨면 disable 해제되게 구현해놓았습니다!
---

fix(fe): disable register button

---

docker-compose.yml

promtail 경로가 제대로 설정되어있지 않아서 재설정했습니다! 
---

fix(infra): change promtail path

---

.github/workflows/cd-stage.yml
docker-compose.yml

#1675 에서 checktout directory를 빼먹어서 마저 수정했습니다! 
---

fix(infra): update checkout directory for promtail

---

apps/infra/modules/codedang-infra/ecs-api-admin-service-asg.tf
apps/infra/modules/codedang-infra/ecs-api-client-service-asg.tf

github action error 수정
'stepScalingPolicyConfiguration.metricAggregationType' 추가
---

fix(infra): add metricAggregationType in asg

---

apps/frontend/components/ui/command.tsx

update shadcn command component 
---

fix(fe): update commandlist

---

.github/workflows/ci.yml
apps/frontend/__tests__/components.test.tsx
apps/frontend/__tests__/utils.test.ts
apps/frontend/package.json
apps/frontend/vitest.config.ts
pnpm-lock.yaml

- 설정이 간편해 관리하기 편한 vitest와 component render를 위한 Testing Library 설치
- 간단하게 예제 테스트 케이스 3개 생성(단순 utils 함수 2개와 Component 한개)
---

feat(fe): add vitest for frontend unit testing

---

apps/infra/modules/codedang-infra/ecs-api-asg.tf

- 프기실 수업이 끝나 인스턴스 유형을 다시 t3a.small로 바꿉니다(Downgrade).
---

fix(infra): downgrade instance type of api

---

apps/frontend/app/layout.tsx
apps/frontend/package.json
apps/frontend/tailwind.config.ts
pnpm-lock.yaml

Close #1705 
Dynamic subset 기능을 활용해, 한국어 폰트 중 필요한 글자의 폰트만 불러와 폰트 로딩 속도를 최적화합니다.
(2.1MB -> ~30KB)
https://github.com/orioncactus/pretendard?tab=readme-ov-file#%EA%B0%80%EB%B3%80-%EB%8B%A4%EC%9D%B4%EB%82%98%EB%AF%B9-%EC%84%9C%EB%B8%8C%EC%85%8B
---

perf(fe): use dynamic subset of pretendard

---

apps/frontend/app/(main)/_components/ProblemCards.tsx
apps/frontend/app/(main)/contest/[contestId]/@tabs/problem/page.tsx
apps/frontend/app/(main)/contest/_components/FinishedContestTable.tsx
apps/frontend/app/(main)/notice/_components/NoticeTable.tsx
apps/frontend/lib/pagination.ts
apps/frontend/lib/useInfiniteScroll.ts

#1507 
위 pr에서 get Api 반환 형태 변경(data, total) 관련해서 interface 수정 등 코드 수정해놓았습니다.
이후 다듬어야 할 부분 다음주 월요일까지 진행해놓을게요~
Close #1707 
---

feat(fe): change codes for changed get api return

---

apps/frontend/app/admin/contest/[id]/page.tsx
apps/frontend/app/admin/contest/_components/Columns.tsx
apps/frontend/app/admin/contest/create/page.tsx
apps/frontend/app/admin/contest/page.tsx
apps/frontend/app/admin/problem/[id]/edit/page.tsx
apps/frontend/app/admin/problem/[id]/page.tsx
apps/frontend/app/admin/problem/_components/Columns.tsx
apps/frontend/app/admin/problem/_components/UploadDialog.tsx
apps/frontend/app/admin/problem/create/page.tsx
apps/frontend/app/admin/problem/page.tsx
apps/frontend/app/admin/problem/utils.ts
apps/frontend/app/admin/user/page.tsx
apps/frontend/components/DataTableAdmin.tsx
apps/frontend/graphql/contest/mutations.ts
apps/frontend/graphql/contest/queries.ts
apps/frontend/graphql/problem/mutations.ts
apps/frontend/graphql/problem/queries.ts
apps/frontend/graphql/user/queries.ts

graphql 쿼리들을 page.tsx에서 분리해서 graphql 폴더 안에 정리했습니다.
폴더 구조는 다음과 같습니다.
```
graphql
├── contest
│   ├── mutations.ts
│   └── queries.ts
├── problem
│   ├── mutations.ts
│   └── queries.ts
└── user
└── queries.ts
```
Closes #1642 
원래는 queries.ts, mutations.ts가 아닌
queries.graphql, mutations.graphql 로 만들어서 사용하려 했으나
codegen으로 타입이 제대로 안 만들어져서 일단 .ts로 진행했습니다.
---

refactor(fe): refactor graphql query files

---

apps/frontend/components/EditorLayout.tsx

get Api형식 변경(total정보 추가)으로 인한 Contest Problem 서버컨포넌트에러, interface 수정
```
interface ContestProblemProps {
data: ContestProblem[]
total: number
}
```
close #1751 
---

fix(fe): change contest problem interface

---

.github/workflows/cd-stage.yml

fix e2e test run bruno collection script (typo)
close #1761 
---

fix(infra): fix e2e test run bruno collection script

---

apps/frontend/app/(main)/notice/_components/NoticeTable.tsx

fixedNotices가 undefined 일때 서버에러 발생
undefined 확인코드로 방지
`fixedNotices == undefined ? [] : fixedNotices`

fix(fe): fix notice stage server error

---

apps/backend/apps/client/src/problem/dto/problem.response.dto.ts
apps/backend/apps/client/src/problem/problem.repository.ts

Get Problem By ID api 호출 시 template이 불러와지지 않는 문제를 해결합니다.
---

fix(be): include-template-in-problem-select-option

---

apps/backend/apps/admin/src/problem/problem.service.spec.ts

현재 CI pipeline backend unit test error가 나도 CI test 통과를 합니다. 그래서 main에 5개 정도 unit test error가 누적됐는데, 그 중 admin problem module의 unit test error를 resolve합니다.
---

fix(be): resolve admin problem test error

---

apps/backend/apps/client/src/group/group.service.spec.ts

현재 CI pipeline backend unit test error가 나도 CI test 통과를 합니다.  
그래서 main에 5개 정도 unit test error가 누적됐는데, 그 중 client group module의 unit test error를 resolve합니다.
---

fix(be): resolve client group unit test error

---

apps/backend/apps/client/src/submission/submission.service.spec.ts

현재 CI pipeline backend unit test error가 나도 CI test 통과를 합니다. 그래서 main에 5개 정도 unit test error가 누적됐는데, 그 중 client submission module의 unit test error를 resolve합니다.
---

fix(be): resolve client submission test error

---

apps/frontend/app/admin/problem/[id]/edit/page.tsx
apps/frontend/app/admin/problem/create/page.tsx

* problem create 페이지와 problem edit 페이지에 Template 필드를 추가했습니다
* language를 추가/삭제하면 language에 해당하는 template도 추가/삭제 됩니다.
Closes #1760 
본 PR은 Admin에서 Template 코드를 포함하여 문제를 생성/수정하는 내용이며
Client의 Code Editor에서 문제를 받아와 스켈레톤 코드를 보여주기 위해서는
추가적인 코드 수정이 필요합니다.
---

feat(fe): add skeleton code field to admin problem

---

apps/frontend/app/(main)/_components/ProblemCards.tsx
apps/frontend/app/(main)/notice/_components/NoticeTable.tsx

Notice 및 ProblemCard에서 문제라고 추정되는 부분을 수정합니다.
로컬에서도, 개인적으로 fork해서 Vercel에서 배포해봤을 때도 에러가 재현이 안되어서 부득이하게 console.log 를 넣게 되었습니다. 
에러 나기 전과 유사하게 동작하도록 고쳤으니 동작하긴 할테지만,
로직에는 문제가 없는 것 같은데, Vercel(특히 저희 Stage에서만) 안되는 이유가 뭘까요.. 
(1777 에러핸들링 이슈는 작업중입니다.)
---

fix(fe): fix vercel server component render on Notice, ProblemCard

---

apps/frontend/app/(main)/error.tsx
apps/frontend/app/(main)/notice/error.tsx
apps/frontend/app/(main)/problem/error.tsx
apps/frontend/components/ErrorDetail.tsx

Notice페이지, Problem페이지 Error Handling 문구 각 페이지에 맞게 변경, Reload 방식 변경
router.refresh -> window.location.reload()
에러 문구를 props로 전달받앗 에러 화면 띄워주는 ErrorDetail 컴포넌트 이용해 Notice, Problem, Main error.tsx에서 이용
---

fix(fe): change notice problem error handling

---

.github/workflows/cd-prod.yml
.github/workflows/cd-stage.yml

github Actions yaml 파일의 build-args 선언 파트에서 잘못된 표기를 하여, 수정하였습니다.
---

fix(infra): resolve github actions build-args typo

---

.github/workflows/cd-prod-target.yml
.github/workflows/cd-prod.yml

Close #1745 
현재 분리한 `storage`와 `network`의 배포를 위한 github actions를 추가했습니다.
배포 flow는 다음과 같습니다. 
- 기존 cd-prod : 기존과 작동 방식은 동일합니다~! 다만, ecs가 포함되어있는 terraform codedang proj만 배포됩니다.
- cd-prod-target : network 또는 storage에 수정사항이 생겨서 반영하고 하는 경우에만 별개로 트리거합니다.
- 추가로, network 또는 storage 는 해당 프로젝트 배포 후, codedang proj 역시 이어서 배포되도록 설정했습니다. 
이전 Terraform PR들 머지되고 나서 마지막으로 머지예정입니다!
pr: #1727 (storage) #1737 (network) #1736 (codedang) 
---

feat(infra): github action for targeted terraform proj

---

apps/infra/production/codedang/variables.tf
apps/infra/production/network/variables.tf
apps/infra/production/storage/variables.tf

fix(infra): set variables as sensitive valuse

---

.github/workflows/cd-prod-target.yml
.github/workflows/cd-prod.yml
apps/infra/production/codedang/iam_ecs_instance_role.tf
apps/infra/production/codedang/iam_ecs_task_execution_role.tf

terraform apply 명령어를 수정합니다! plan.out이 뒤에 와야해요 ㅎㅎ
---

fix(infra): fix tf apply command

---

apps/infra/production/codedang/codedang_service_iris.tf

iris ecs task definition의 aws_ecr_repository 이름 부분에 오타가 있어 수정하였습니다.
---

fix(infra): resolve iris ecr uri typo

---

scripts/deploy.sh

closes #1826 
setup 스크립트에 testcase를 초기화 하는 것이 동작하지 않아서 버킷에 이미지 업로드가 정상적으로 등록되지 않은것으로 보입니다.
이를 수정합니다.
---

fix(infra): change bucket initialization script

---

apps/backend/apps/client/src/contest/contest.service.spec.ts
apps/backend/apps/client/src/contest/contest.service.ts
collection/client/Contest/Get contest by ID/Succeed.bru

Get Contest by ID로 요청을 보냈을 때,
해당 Contest의 invitationCode 유무 여부를 받아옵니다.
---

feat(be): get invitation code

---

docker-compose.yml

localhost:9000으로 접근했을 때 stage.codedang.com/console로 redirect되는 문제를 해결합니다.
---

fix: delete minio-browser-redirect-url

---

apps/backend/prisma/migrations/20240722070636_add_problem_template_default_value/migration.sql
apps/backend/prisma/schema.prisma

Closes #1849
Problem model의 template 속성에 기본 값을 추가합니다.
---

feat(be): add problem template default value

---

apps/frontend/components/EditorHeader.tsx
apps/frontend/components/EditorResizablePanel.tsx

Problem 생성시 Template 없이 생성된 Problem 접근시 발생하는 undefined 에러 핸들.
- TemplateString이 undefined일 경우를 체크
---

fix(fe): handle undefined template error

---

collection/client/Contest/Get contest by ID/Succeed.bru
collection/client/Submission/Create Submission/404: No Contest found.bru
collection/client/Submission/Create Submission/Succeed.bru
collection/client/Submission/Create Submission/Succeed: Contest(AC).bru
collection/client/Submission/Create Submission/Succeed: Contest(TLE).bru
collection/client/Submission/Create Submission/Succeed: Contest(WA).bru

Bruno 에서 query 문법 문제로 문서가 불러와지지 않는 문제를 해결합니다. 
---

fix(be): fix bruno query grammar

---

apps/backend/apps/client/src/contest/contest.service.spec.ts
apps/backend/apps/client/src/contest/contest.service.ts
collection/client/Contest/Get contest by ID/Succeed.bru

Contest를 반환하는 API에서 enableCopyPaste 속성을 함께 가져올 수 있도록 수정합니다.
---

chore(be): return including enable-copy-paste

---

.github/workflows/cd-stage.yml
collection/client/User/Delete Own Account/Succeed.bru

CD -stage과정에 포함되어 있는 백엔드 e2e-test 를 disable합니다.
현재 문서화 과정에 문제가 많지만 수정하는 데에 시간이 오래걸린다고 판단하여, 추후 고친 후에 다시 stage과정에 포함시킵니다.
Bruno 에서 delete user api를 사용하지 못하도록 임시적으로 비활성화합니다. 현재 누군가가 stage에서 이를 실행할 경우 다른 API가 정상적으로 작동하지 않습니다. 
closes #1870
---

fix(ci): disable backend e2e-test on cd-stage

---

.github/ISSUE_TEMPLATE/feature-request.yml

https://github.com/skkuding/codedang/issues/1875 Notion task와의 연동을 위한 사전 작업입니다.
---

chore: update issue template

---

.github/ISSUE_TEMPLATE/feature-request.yml

fix: fix typo

---

.devcontainer/devcontainer.json
docker-compose.yml

closes #1886
local minio 와 stage minio 컨테이너를 분리합니다.
---

fix(infra): separate local minio and stage minio container

---

.devcontainer/devcontainer.json
docker-compose.yml

fix(infra): 1886 separate stage local minio container

---

apps/frontend/components/CodeEditor.tsx
apps/frontend/components/EditorLayout.tsx
apps/frontend/components/EditorResizablePanel.tsx
apps/frontend/types/type.ts

Contest의 enableCopyPaste 값이 false일 경우 코드에디터에서의 복사, 잘라내기, 붙여넣기를 막았습니다
close #1783
Contest를 통해 들어간 문제가 아니거나 submission일 경우 디폴트값은 일단 false로 설정했습니다.
---

feat(fe): add editor copy paste preventing

---

apps/backend/prisma/migrations/20240801120143_add_cascade_on_announcement_model/migration.sql
apps/backend/prisma/schema.prisma

announcement model에 연관된 contest, problem 데이터에 cascade 옵션을 추가합니다.
---

chore(be): add cascade on announcement model

---

apps/frontend/app/(main)/page.tsx

메인 페이지 캐러셀 링크를 수정합니다.
close #1917
---

fix(fe): change carousel link

---

apps/frontend/app/(main)/_components/ProblemCards.tsx

메인 화면의 Problems 섹션이 Submission 수가 가장 높은 3가지 문제를 왼쪽부터 차례로 노출하도록 변경했습니다!
Before
After
closes TAS-517
---

chore(fe): sort problems by submission

---

.npmrc

pnpm@9.7.0 부터 해당 옵션을 true로 설정하면, `package.json`에 명시된 `packageManger` 버전에 맞게 자동으로 설치 및 변경해주는 옵션입니다.
> https://github.com/pnpm/pnpm/releases/tag/v9.7.0
다만, 아직 corepack이 안정 단계가 아니라  `corepack enable` 명령어로 corepack을 활성화 시켜줘야 한다는 점..
---

chore(pnpm): add manage-package-manager-versions

---

apps/backend/apps/client/src/contest/contest.service.ts
collection/client/Contest/Get finished contests/Succeed.bru

fix(be): fix typo

---

apps/frontend/next.config.js

sentry parameter를 잘못 줘서 sentry config url 을 다시 설정합니다. 
---

fix(fe): sentry config url

---

apps/frontend/app/admin/problem/_components/Columns.tsx
apps/frontend/app/admin/problem/page.tsx
apps/frontend/app/admin/problem/utils.ts

지윤님의 isvisible PR Merge에 따라서 프론트 빌드가 되지 않는 부분을 고칩니다 
---

fix(fe): problem cannot be null

---

.github/workflows/ci.yml

확장자가 없는 파일의 코드 스타일을 체크하지 않습니다 
---

fix(ci): don't check style on file with no file extension

---

apps/frontend/package.json
docker-compose.yml

deploy storage container에 env file을 inject하도록 변경합니다, 
---

fix(cd): minio container setting

---

collection/admin/Submission/Get Contest Submission Summaries/Succeed.bru

admin get contest submissions api 문서를 추가합니다.
---

docs(be): add admin get contest submissions api docs

---

apps/backend/apps/client/src/email/templates/email-auth.hbs

이메일 인증 코드당 로고 수정했습니다.
closes TAS-428
---

fix(fe): change email logo

---

.devcontainer/devcontainer.json
collection/client/Contest/Get contest by ID/Succeed.bru
collection/client/Contest/Get finished contests/Succeed.bru
collection/client/Contest/Get ongoing & upcoming contests/Succeed.bru
collection/client/Contest/Get registered finished contests/Succeed.bru
collection/client/Problem/Get problem by ID/Succeed.bru

params:query는 삭제된 문법으로 보입니다.
브루노에서 이 문법으로 독스가 안보이는 경우가 많아 수정합니다.
+ devcontainer default extension에 git graph 넣어주세요오오 
---

fix(docs): fix bruno params:query to query

---

apps/iris/Dockerfile
apps/iris/src/service/sandbox/langConfig.go

Iris 이미지 빌드시 파이썬 3.12 버전을 사용하도록 수정
---

fix(iris): python version

---

apps/infra/production/codedang/container_definitions/admin_api.json
apps/infra/production/codedang/container_definitions/client_api.json

재배포 오류 해결을 위해(재배포가 원활히 되도록) 임시로 ecs task definition resource를 낮춥니다
---

fix(infra): modify cpu reservation to deploy new task definitions

---

apps/frontend/app/admin/contest/[id]/edit/page.tsx
apps/frontend/app/admin/contest/create/page.tsx
apps/frontend/app/admin/contest/utils.ts
apps/frontend/components/DataTableAdmin.tsx
apps/frontend/graphql/contest/mutations.ts
apps/frontend/graphql/problem/queries.ts

importContestProblem 변경에 따라 프론트엔드 측의 type을 바꾸었습니다.
id 1 문제를 import 시에 오류가 발생하여 확인 필요합니다. 
---
close 777

fix(fe): add score field at contestProblem

---

apps/infra/production/network/README.md
apps/infra/production/network/public_network.tf

Closes TAS-790
NAT Gateway를 NAT Instance로 대체하기 위한 작업이 모두 완료되어 NAT Gateway를 삭제합니다.
---

feat(infra): delete nat-gateway

---

apps/frontend/components/auth/HeaderAuthPanel.tsx

logout 버튼 클릭 시 home으로 redirect되도록 수정함
close TAS-798
---

fix(fe): redirect to home when user logged out

---

apps/frontend/components/EditorHeader.tsx

test 기능 미구현으로 test 버튼을 숨깁니다
closes TAS-803
---

chore(fe): hide test button

---

apps/frontend/app/admin/contest/[id]/edit/page.tsx
apps/frontend/app/admin/contest/create/page.tsx

enableCopyPaste, isJudgeResultVisible에 맞게
Toggle의 title도 위와 같이 변경했습니다!
Closes TAS-799
---

chore(fe): edit admin contest toggle title text

---

apps/backend/apps/admin/src/contest/model/score-summary.ts

getContestScoreSummries api에 userId field를 추가합니다 
---

fix(be): add userId field in usercontestscoresummarywithuserinfo

---

apps/backend/apps/admin/src/contest/contest.service.ts
apps/backend/apps/admin/src/contest/model/contest-submission-summary-for-user.model.ts
apps/backend/apps/admin/src/submission/model/contest-submission.model.ts
apps/backend/apps/admin/src/submission/submission.service.ts
collection/admin/Contest/Get Contest Submission Summaries of User/Succeed.bru
collection/admin/Submission/Get Contest Submission Summaries/Succeed.bru

Submission list에서 submission detail로 향하는 링크를 구현할 수 있도록 submission id를 Participant api에서 같이 반환합니다. 
---

feat(be): give submission id in participant api

---

apps/backend/apps/admin/src/contest/contest.service.ts
apps/backend/apps/admin/src/contest/model/contest-submission-summary-for-user.model.ts
apps/backend/apps/admin/src/submission/model/contest-submission.model.ts
apps/backend/apps/admin/src/submission/submission.service.ts
collection/admin/Contest/Get Contest Submission Summaries of User/Succeed.bru
collection/admin/Submission/Get Contest Submission Summaries/Succeed.bru

order, problemId를 submission api에 추가합니다
---

feat(be): give order and problemId on submission admin apis

---

apps/backend/apps/client/src/problem/dto/related-problems.response.dto.ts

related problems response에서 id field가 없어지면 프론트에서 많은 부분이 변경되어야 하므로 (현재 contest problem id를 통해서 하고 있는 것이 많음)
revert 합니다. 
---

revert(be): revert related-problems-reponse id field

---

apps/frontend/app/(main)/settings/page.tsx

chore(fe): delete comments

---

apps/frontend/app/(main)/problem/_components/Columns.tsx
apps/frontend/app/admin/_components/ConfirmNavigation.tsx

client problem list에서 Solved를 Success Rate로 변경했습니다!(근데 figma랑 엄청 다른 점이 많네요... 일단 후순위로 둔 건가요?)
\+ ConfirmNavigation 파일은 그냥 노랑 경고 지우고 싶어서 변경했는데 너무 사소한 거라 같이 올립니다...(전 PR에 올렸어야 됐는데 머지돼버려서...ㅎㅎ)
closes TAS-539
---

chore(fe): change solved to success rate

---

apps/backend/apps/admin/src/problem/problem.service.ts

uploadProblems API의 input으로 어떤 언어도 지원하지 않는 문제가 포함된 파일이 주어지는 경우, 서버가 종료되는 문제를 수정합니다.
---

fix(be): resolve upload-problem error

---

apps/frontend/app/admin/contest/utils.ts
apps/frontend/app/admin/problem/_components/TestcaseField.tsx
apps/frontend/app/admin/problem/_components/TestcaseItem.tsx
apps/frontend/app/admin/problem/create/page.tsx
apps/frontend/app/admin/problem/utils.ts

Closes TAS-738
Closes TAS-836
Closes TAS-835
Closes TAS-821
---

fix(fe): fix testcase field and admin forms

---

apps/frontend/app/admin/contest/_components/ImportProblemTableColumns.tsx
apps/frontend/app/admin/problem/_components/Columns.tsx
apps/frontend/graphql/problem/queries.ts

`createTime` 대신 `updateTime`을 보여줍니다.
closes TAS-875
---

chore(fe): minor update to the admin problem table

---

apps/iris/Dockerfile
apps/iris/go.mod
renovate.json

fix(be): downgrade go version

---

apps/backend/.mocharc.json
apps/backend/.swcrc
apps/backend/apps/client/src/main.ts
apps/backend/nest-cli.json
apps/backend/package.json
apps/backend/webpack.config.js
pnpm-lock.yaml

nest 프로젝트에 webpack 대신 swc 를 사용하도록 수정함

fix(be): apply swc on nest

---

apps/backend/apps/admin/src/problem/problem.service.ts

Closes TAS-879
Upload Problems API를 사용해 생성된 문제들을 기본 `invisible`로 세팅합니다.
---

chore(be): set invisible when problems created from excel file

---

apps/frontend/app/(main)/contest/_components/ContestTabs.tsx
apps/frontend/app/(main)/contest/_components/FinishedContestTable.tsx
apps/frontend/app/(main)/contest/_components/FinishedTableColumns.tsx
apps/frontend/app/(main)/contest/_components/RegisteredContestTable.tsx
apps/frontend/app/(main)/contest/_components/RegisteredTableColumns.tsx

contest table - clarification 삭제
contest list - total score 삭제
close TAS-849
close TAS-851
---

chore(fe): edit contest table and list

---

apps/frontend/app/(main)/_components/ContestCard.tsx

Contest card 의 진행 동그라미 삭제
close TAS-850

chore(fe): remove contest card progress circle

---

apps/frontend/components/InsertDialog.tsx
apps/frontend/components/TextEditor.tsx

5MB 이상의 이미지 업로드 시 caution Dialog를 띄웁니다.
close TAS-834
가독성을 위해 리팩토링 완료 
---

chore(fe): add alert when image size larger than 5mb

---

apps/backend/apps/admin/src/main.ts

100KB가 넘어가는 Testcase를 포함한 문제를 생성하려고 시도하면 `request entity too large` 에러가 뜹니다.
Ex) 
```python
def calculate_max_discount(prices):
prices.sort(reverse=True)
discount = 0
for i in range(2, len(prices), 3):
discount += prices[i]
return discount
def main():
with open('input.txt', 'r') as f:
n = int(f.readline().strip()) 
prices = list(map(int, f.readline().strip().split())) 
max_discount = calculate_max_discount(prices)
with open('output.txt', 'w') as f:
f.write(str(max_discount) + '\n')
if __name__ == '__main__':
main()
``` 
로 생성한 testcase input을 가지고 문제를 만들려고 시도하면 실패합니다. 
1. Nest Admin app에서 body size limit configuration을 10MB로 설정합니다.
2. 또한 이렇게 Admin app에서 `BodyParser`의 `Option`을 변경하기 위해 expressjs를 사용하도록  명시적으로 선언합니다. (Nest는 Express / FastAPI 에 대한 추상화를 해두었고, FastAPI를 명시적으로 사용하지 않으면 실제로는 …

fix(be): change admin app body size limit configuration

---

apps/backend/apps/admin/src/problem/problem.service.ts

fix(be): update problem edit api

---

apps/frontend/app/(main)/layout.tsx
apps/frontend/components/Cover.tsx

모든 페이지에서 세로 스크롤이 생기면 가로 스크롤바도 함께 나타나는 현상 픽스 (며칠째 그대로길래 태스크 만들어서 PR 올립니다)
AS-IS
TO-BE
closes TAS-916
---

fix(fe): prevent horizontal scrollbar from appearing

---

apps/backend/apps/admin/src/problem/problem.service.ts

Closes TAS-917
Production 환경에서 S3에 업로드된 이미지의 URL을 정상적으로 반환하지 않는 문제를 해결합니다.
---

fix(be): add image url for production env

---

apps/frontend/app/admin/problem/[id]/edit/page.tsx
apps/frontend/app/admin/problem/_components/ExampleTextarea.tsx
apps/frontend/app/admin/problem/_components/LimitForm.tsx
apps/frontend/app/admin/problem/_components/TestcaseField.tsx
apps/frontend/app/admin/problem/_components/TestcaseItem.tsx
apps/frontend/app/admin/problem/page.tsx
apps/frontend/graphql/problem/queries.ts

submission이 존재하는 문제의 테스크케이스, limit 수정을 제한한다.
Close TAS-882

fix(fe): block testcase and limit edit when submission exist

---

apps/backend/apps/client/src/submission/submission.service.ts

캐시에 테스트케이스를 저장하기 전에 먼저 Run 요청 메세지를 보내도록 수정

fix(be): set testcases on cache before publiush message

---

apps/frontend/app/contest/[contestId]/problem/[problemId]/submission/_components/Columns.tsx
apps/frontend/app/contest/[contestId]/problem/[problemId]/submission/_components/SubmissionDetail.tsx

Contest Problem Editor에서 Blind text color 수정
red -> neutral
Closes TAS-949
---

chore(fe): change blind text color from red to neutral

---

apps/backend/apps/client/src/submission/class/judger-response.dto.ts
apps/backend/apps/client/src/submission/submission-sub.service.ts
apps/backend/apps/client/src/submission/submission.service.ts
apps/backend/apps/client/src/submission/test/submission-sub.service.spec.ts
apps/iris/src/handler/judge-handler.go

Test 제출시 코드 실행 output을 추가로 반합니다.
Close TAS-905

feat(iris): pass run output when test submission

---

apps/frontend/app/admin/contest/[id]/_components/SubmissionDetailAdmin.tsx
apps/frontend/components/DataTableAdmin.tsx
apps/frontend/graphql/submission/queries.ts

사실 스크롤바 위치 등의 문제 때문에 디자인적인 부분에서 살짝 야매로 해결했었는데 마땅한 해결책이 안 떠올라 admin 파트이고 internal error 문제도 빨리 해결해야 하는 만큼 일단 이대로 완성했습니다..!
closes TAS-861
---

feat(fe): create submission detail modal

---

apps/backend/apps/client/src/user/dto/signup.dto.ts

fix(be): use is-optional

---

apps/frontend/components/EditorHeader.tsx
apps/frontend/components/EditorResizablePanel.tsx
apps/frontend/stores/editor.ts

problem editor에서 test/submit 버튼을 누른 후 코드가 사라지는 문제가 있었다. loading 변수를 useEffect에 넣어서 submit/test가 끝나면 다시 코드를 가져오도록 수정
close TAS-976

fix(fe): resolve code disappearing problem after test/submit

---

apps/frontend/app/admin/problem/create/_components/CreateProblemAlertDialog.tsx

[Before]
[After]
Create Problem modal 안내 문구를 변경하였습니다.
Closes TAS-988
---
- [o] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [o] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [o] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

fix(fe): fix CreateProblem modal

---

apps/frontend/components/auth/SignUpRegister.tsx

로그인 페이지에서 학과 이름이 길면 안 뒷 부분이 안 보이는 문제를 해결.
Tooltip 기능 사용.
Closes TAS-833
---

chore(fe): create signup hover

---

apps/frontend/components/auth/UpdateInformation.tsx

To continue using our service,
you must update your information.
You must your information by October 31.
해당 문구를
You **must update below information**
to continue using our service (~ 2024-10-31).
으로 수정
Closes TAS-997
---

chore(fe): fix updatenow text

---

apps/frontend/app/(main)/contest/[contestId]/@tabs/problem/page.tsx

ongoing/upcoming 상관없이 로그인 후에는 Register to access the problems of this contest. 문구가 출력되는 상황이었습니다. 
기획/디자인 해둔 뷰 문구에 따르면
1. 로그인 전 : Log in first to check the problems.
2. ongoing 일 때 : Please register first to view the problem list
3. upcoming일 때 : You can access after the contest started
로 수정되어야 하기에 해당 내용을 수정하였습니다. 
[로그인 전]
[로그인 후 ongoing]
[로그인 후 upcoming]
Closes TAS-1000
- 코드의 경우 app-main-contest-contestID-layout.tsx를 참고하였습니다.

fix(fe): fix contestdenied message

---

apps/frontend/app/admin/contest/create/page.tsx

fix(fe): hotfix build error

---

apps/frontend/app/admin/contest/[id]/(overall)/@tabs/submission/page.tsx
apps/frontend/app/admin/contest/[id]/participant/[userId]/page.tsx

submission take 1000 -> 5000 으로 늘렸습니다

fix(fe): fix submission take number

---

apps/backend/apps/client/src/problem/problem.controller.ts
apps/backend/apps/client/src/problem/problem.service.ts
apps/backend/apps/client/src/submission/submission.controller.ts
apps/backend/apps/client/src/submission/submission.service.ts

Client Problem, Submission 모듈을 문서화 합니다. 
대회 액세스 정책의 경우 기획과 많이 연관되어 있어,
처음 보는 사람이 이해하기 매우 어려울 것 같아 기획 명세서 링크도 @see로 첨부했습니다.
간단한 로직들은 굳이 로직 달지 않고, 설명이 필요한 부분만 달았어요.
추가로 주석이 필요해보이는 부분이 있다면 말씀해주세요 :)
closes TAS-1046
---

docs(be): add jsdoc comment on client problem, submission module

---

apps/backend/apps/admin/src/contest/contest.service.ts
apps/backend/apps/admin/src/contest/model/score-summary.ts

hotfix
getContestScoreSummaries api 반환값에 major값을 추가합니다.
---

chore(be): add major to contest-score-summary api

---

collection/admin/Contest/Get Contest Score Summaries/Succeed.bru
collection/client/Submission/Get Submissions/Succeed.bru

docs(be): remove unused vars in bruno

---

apps/frontend/app/(client)/(code-editor)/_components/BackCautionDialog.tsx
apps/frontend/app/(client)/(code-editor)/_components/EditorHeader.tsx
apps/frontend/app/(client)/(code-editor)/_components/EditorResizablePanel.tsx

user가 코드를 저장하지 않고 뒤로 가기를 시도할 경우 경고 모달 띄운다.
새로 고침을 시도할 경우 모달을 띄운다.
contest 문제를 푸는 중에도 코드를 저장하지 않고 문제를 이동하려고 하면 경고창을 띄운다.
Close TAS-1011
Close TAS-1012

fix(fe): show modal when user navigates a page without saving a code

---

apps/frontend/app/admin/contest/[contestId]/edit/page.tsx

submission이 존재해도 문제 추가/삭제와 점수/순서 변경이 가능하도록 하였습니다! 최대한 덜 건드리고 구현하였는데 아마 문제 없지 않을까 싶습니다..!
(submission이 존재하는 Contest입니다)
closes TAS-1045
---

feat(fe): enable contest problem list change always

---

apps/frontend/app/admin/contest/[contestId]/(overall)/@tabs/submission/_components/SubmissionDetailAdmin.tsx
apps/frontend/app/admin/contest/[contestId]/(overall)/@tabs/submission/_components/SubmissionTable.tsx
apps/frontend/graphql/problem/queries.ts
apps/frontend/graphql/submission/queries.ts

- Summary에 realName studentId major 추가
- Table에서 Sample Hidden testcase 구분해서 표시
- 틀린 testcase 표시 및 맞춘 testcase 개수 표시
1041번 Task에 추가로 Input Expected Output을 Table에서 보여주는 내용이 있는데
아직 submission에 대해서는 실제 output을 보여줄 수 없기 때문에
다음 배포 때 구현 진행하겠습니다!
---

feat(fe): add major realName studentId in submission modal

---

apps/frontend/app/(client)/(code-editor)/_components/EditorHeader/EditorHeader.tsx
apps/frontend/app/(client)/(code-editor)/contest/[contestId]/problem/[problemId]/submission/_components/DataTable.tsx
apps/frontend/app/(client)/(code-editor)/problem/[problemId]/submission/_components/DataTable.tsx

code editor에서 코드를 한 번도 저장하지 않고 submission에서 테이블 행 클릭 시 alert 띄워짐. 
Close TAS-1059

fix(fe): alert after click submission in code editor

---

apps/backend/apps/admin/src/contest/contest.service.ts

hotfix
Score Summary 계산 시, 대회에 포함되지 않은 문제의 제출 내역을 무시합니다.
---

fix(be): ignore submissions for problems not included in contest

---

apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/AddUserTestcaseDialog.tsx
apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/useUserTestcasesForm.ts

모달 닫힐 때 form을 기본값으로 초기화합니다.
https://github.com/user-attachments/assets/831a996b-3c3a-40f4-a332-c4c30c728317
closes TAS-1069
---

fix(fe): fix user testcase form initialization bug

---

apps/frontend/app/(client)/(code-editor)/_components/EditorHeader/EditorHeader.tsx

**문제 상황**
문제가 여러 개인 contest에서 문제를 한 번 이동한 후 뒤로가기를 2번 시행했을 때 예상치 못한 페이지로 이동합니다.
**추가**
제 노트북에서는 해당 문제가 매우 희박한 확률로 일어나서 우선 PR을 올리고 PR의 coolify를 통해 모바일 환경에서 확인하려고 합니다. 그래서 이거 보신 분들은 이 문구가 지워지기 전까지 이 PR 잠깐 무시해주시면 감사하겠습니다!
Close TAS-1066

fix(fe): comment out popstate

---

apps/infra/production/codedang/message_queue_aws.tf

fix(infra): update MQ engine version for compatibility

---

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/page.tsx
apps/frontend/package.json
pnpm-lock.yaml

error boundary 추가했습니다
Action item: 코드 리뷰 시 에러 핸들링하고 있는지 확인하기! 에러 핸들링을 TODO로 남기면 안됨!! 😢 
closes TAS-1097
---

fix(fe): handle contest problems api error using error boundary

---

apps/frontend/app/admin/problem/_components/ProblemsDeleteButton.tsx

api 응답이 속한 contest가 없으면 undefined가 아니라 빈 문자열로 온다
close TAS-1098

fix(fe): fix delete problem error

---

apps/frontend/app/(client)/(code-editor)/contest/[contestId]/finished/problem/[problemId]/page.tsx
apps/frontend/app/(client)/(code-editor)/contest/[contestId]/problem/[problemId]/submission/[submissionId]/page.tsx
apps/frontend/app/(client)/(code-editor)/problem/[problemId]/page.tsx
apps/frontend/app/(client)/(code-editor)/problem/[problemId]/submission/[submissionId]/page.tsx
apps/frontend/app/(client)/(main)/contest/[contestId]/layout.tsx

NextJS route가 제공하는 params 객체의 프로퍼티들의 타입들은 `string` 입니다!
---

chore(fe): fix route params type

---

apps/backend/apps/client/src/submission/submission-sub.service.ts

올바른 JudgeResult를 사용하도록 NestJS의 rabbitmq consumer 로직을 수정합니다.

fix(be): using correct judge result code

---

.gitignore

Datagrip 사용 후 남는 .idea 디렉토리를 git에서 추적하지 않도록 합니다.
---

chore(be): add .idea in gitignore

---

apps/infra/production/codedang/codedang_api.tf
apps/infra/production/codedang/codedang_iris.tf
apps/infra/production/codedang/codedang_service_client.tf
apps/infra/production/codedang/codedang_service_iris.tf

방학 기간에는 실사용자가 없으므로 스펙을 줄여 비용을 절감합니다. 
---

fix(infra): reduce resource spec for vacation

---

apps/frontend/app/admin/page.tsx

- Admin 대시보드에 이미지 가운데 정렬함
closes TAS-815

fix(fe): change dashboard image alignment

---

apps/iris/src/service/sandbox/langConfig.go

fix(iris): python parameter change

---

apps/frontend/package.json
pnpm-lock.yaml

`valibot` 의존성을 `devDependencies`에서 `dependencies`로 옮겨요..
---

fix(fe): add valibot to dependecies

---

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/_components/RegisterButton.tsx
apps/frontend/app/admin/notice/_components/CreateNoticeForm.tsx
apps/frontend/app/admin/notice/_libs/schemas.ts

fix(fe): replace zod with valibot

---

apps/frontend/.gitignore
apps/frontend/app/admin/contest/_components/ImportDialog.tsx
apps/frontend/package.json

- 빌드 에러 수정
- `pnpm analyze` 스크립트 추가
---

chore(fe): fix build error and add analyze script

---

apps/frontend/libs/auth.ts
apps/frontend/libs/auth/getServerSession.ts
apps/frontend/next.config.js
apps/frontend/package.json

번들 사이즈 실화임??ㅋ
| Before  | After |
| ------------- | ------------- |
| <img width="572" alt="image" src="https://github.com/user-attachments/assets/fd834952-ece3-4570-8ac0-28b38f7686d5" />  | <img width="579" alt="image" src="https://github.com/user-attachments/assets/8da932a8-d5f2-4ef2-9339-dd56ad7b32d5" />  |
| <img width="1582" alt="image" src="https://github.com/user-attachments/assets/0b535afd-02db-41bd-813b-61db253df7bd" /> | <img width="1582" alt="image" src="https://github.com/user-attachments/assets/635f21ae-95fe-42fa-9f13-37c300a9b6da" /> |
</div>
---

chore(fe): split server-side module and apply sentry tree shaking

---

apps/backend/apps/admin/src/submission/submission.service.ts

contest submission 정렬에 사용되는 sort key의 변수명을 수정합니다.
---

chore(be): rename sort key for contest submission

---

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/_components/GoToFirstProblemButton.tsx
apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/page.tsx

fix(fe): fix `GotoFirstProblemButton` error

---

apps/frontend/sentry.client.config.ts

chore(fe): remove replay function in sentry

---

apps/frontend/app/(client)/(main)/contest/_components/ContestTabs.tsx

- Contest tab layout 맞지 않는 문제 해결
close TAS-1276
---

fix(fe): fix contest tab layout

---

apps/frontend/app/admin/_components/MangementSidebar.tsx

setIsMainSidebarExpanded(true)을 지웠습니다.

chore(fe): fix infinite rerender

---

apps/backend/apps/client/src/announcement/announcement.service.ts

update time 순서로 정렬이 아니라 create time 순서로 정렬으로 기획이 확정되어 해당 부분을 변경합니다.
---

fix(be): change announcement orderby

---

apps/backend/apps/admin/src/assignment/assignment.resolver.ts
apps/backend/apps/admin/src/assignment/assignment.service.spec.ts
apps/backend/apps/admin/src/assignment/assignment.service.ts
apps/backend/apps/admin/src/assignment/model/assignment.input.ts
apps/backend/apps/client/src/assignment/assignment.service.spec.ts
apps/backend/apps/client/src/assignment/assignment.service.ts
collection/instructor/Assignment/Create Assignment/Succeed.bru
collection/instructor/Assignment/Create Assignment/[ERR] End Time Earlier than Start Time.bru
collection/instructor/Assignment/Create Assignment/[ERR] Nonexistent Group.bru
collection/instructor/Assignment/Delete Assignment/Succeed.bru
collection/instructor/Assignment/Duplicate Assignment/Succeed.bru
collection/instructor/Assignment/Get Assignment Score Summaries/Succeed.bru
collection/instructor/Assignment/Get Assignment Score Summary of User/Succeed.bru
collection/instructor/Assignment/Get Assignment/NOT_FOUND.bru
collection/instructor/Assignment/Get Assignment/Succeed.bru
collection/instructor/Assignment/Get Assignments/Succeed.bru
collection/instructor/Assignment/Get Belonged Assignments by Problem ID/Succeed.bru
collection/instructor/Assignment/Import Problems to Assignment/Succeed.bru
collection/instructor/Assignment/Import Problems to Assignment/[ERR] Nonexistent Assignment.bru
collection/instructor/Assignment/Update Assignment/Succeed.bru
collection/instructor/Assignment/Update Assignment/[404] Nonexistent Assignment.bru
collection/instructor/Assignment/Update Assignment/[422] End Time Earlier than Start Time.bru

feat(be): add week to assignment

---

apps/infra/production/codedang/message_queue_aws.tf
apps/infra/rc/storage/message_queue_aws.tf
docker-compose.yml

현재 MQ 버전이 지원하지 않는다고 합니다.. 
최신 버전으로 업그레이드 합니다.
---

fix(infra): upgrade version rabbitMQ

---

.github/workflows/rc-deploy.yml

fix(infra): resolve terraform ci-cd

---

.github/workflows/rc-deploy.yml

fix(infra): delete lock false and update ci-cd

---

apps/infra/production/codedang/message_queue_aws.tf
apps/infra/rc/storage/message_queue_aws.tf

fix(infra): update mq version to execute terraform

---

apps/frontend/app/admin/group/[groupId]/assignment/_components/AssignmentTableColumns.tsx
apps/frontend/graphql/assignment/mutations.ts
apps/frontend/graphql/assignment/queries.ts

#2384 에 따라 프론트엔드 정상 빌드를 위해 프론트엔드 graphql 변경사항을 반영합니다.
---

fix(fe): follow add week on frontend graphql queries

---

apps/infra/production/codedang/message_queue_aws.tf
apps/infra/rc/storage/message_queue_aws.tf

fix(infra): set MQ minor_verision_upgrade

---

apps/backend/apps/client/src/submission/submission.service.ts

Get Contest Submissions API에서 problem Id와 title을 반환합니다!
---

chore(be): get contest submissions problem id and title

---

apps/backend/apps/admin/src/user/model/groupMember.model.ts
apps/backend/apps/admin/src/user/user.service.spec.ts
apps/backend/apps/admin/src/user/user.service.ts
apps/backend/apps/client/src/user/user.service.ts
collection/instructor/User/Get Group Member/Succeed.bru
collection/instructor/User/Get Group Members/Succeed.bru

instructor 페이지를 작성하기 위한 필수 필드를 추가합니다. 
getGroupMembers에서 isGroupLeader 여부를 같이 반환하고,
getUserByEmail에서 userid도 같이 반환합니다. 
---

feat(be): add necessary fields on instructor page

---

apps/frontend/app/(client)/(main)/course/[courseId]/_components/CourseInfoBox.tsx
apps/frontend/app/(client)/(main)/course/[courseId]/_components/Sidebar.tsx
apps/frontend/app/(client)/(main)/course/[courseId]/layout.tsx
apps/frontend/app/(client)/(main)/course/_components/CourseCard.tsx
apps/frontend/app/(client)/(main)/course/page.tsx

- CourseInfoBox 디자인 수정 및 API 연결
- Sidebar에서 courseId 못 불러오던 문제 해결
Closes TAS-1318
---

chore(fe): modify course info box UI

---

apps/frontend/graphql/assignment/mutations.ts
apps/frontend/graphql/assignment/queries.ts

assignment에서 invitationcode를 삭제합니다. 
(백엔드 PR #2402 따라갑니다.)
---

fix(fe): remove invitationcode on assignment

---

apps/frontend/app/(client)/(main)/course/[courseId]/_components/AssignmentAccordion.tsx

- Complete / Incomplete 배지 추가
- Accordion Content 스타일 수정
Closes TAS-1334
---

feat(fe): add complete badge in assignment accordion

---

apps/backend/apps/admin/src/assignment/model/assignment.input.ts

fix(be): update assignment week is nullable

---

apps/backend/apps/admin/src/submission/submission.resolver.ts
apps/backend/apps/admin/src/submission/submission.service.ts
collection/instructor/Submission/Get Assignment Submission/Succeed.bru

권서진의 특별 퀘스트
UserId, Assignment Id, Problem Id로 Submission detail 가져오기
---
Closes TAS-1352

feat(be): get assignment submission by user id

---

apps/frontend/app/(client)/(code-editor)/contest/[contestId]/problem/[problemId]/leaderboard/_components/LeaderboardPaginatedTable.tsx

solved problem을 세는 로직을 수정하였습니다. 
기존: score가 1인 문제의 개수를 셈
수정: score가 0이 아닌 문제의 개수를 셈
cloese TAS-1353

fix(fe): fix counting solved problem logic

---

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/_components/RenderProblemColumn.tsx

불필요한 info data 삭제하였습니다! (0 지움)
---
closes tas-1342

chore(fe): delete info data

---

apps/backend/apps/admin/src/assignment/model/score-summary.ts
apps/backend/apps/client/src/assignment/assignment.service.ts
apps/frontend/app/admin/course/_components/CreateCourseButton.tsx

fix(fe): return isAutoFinalizeScore, isFinalScoreVisible

---

apps/frontend/app/(client)/(main)/contest/_components/ContestSubBanner.tsx

- contest main page 'read more' 문구 text 크기 변경
closes TAS-1367
---

chore(fe): change text size

---

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/_components/RegisterButton.tsx
apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/page.tsx

upcoming 일 때 버튼이 보이게 수정하였습니다~
---
closes tas-1366

feat(fe): make visible Register Button when upcoming

---

apps/frontend/app/admin/course/[courseId]/grade/_components/GradeAssignmentTable.tsx
apps/frontend/app/admin/course/[courseId]/grade/_components/GradeAssignmentTableColumns.tsx
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/_components/Columns.tsx
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/_components/ParticipantTable.tsx
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/error.tsx
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/page.tsx
apps/frontend/app/admin/course/[courseId]/grade/page.tsx
apps/frontend/graphql/assignment/queries.ts
apps/frontend/graphql/problem/queries.ts

Grade 완성. Score Review Status는 백엔드 합산 코드 완료 후 추가 구현 예정. CSV 양식에 대해 추가 논의가 필요하긴 할 듯. 또한 학생의 문제 cell을 눌렀을 때 해당 문제로 이동해야 할까? 일단 서진이 형 코드 에디터 구현 끝나면 생각하자.
closes TAS-1349
---

feat(fe): add instructor grade assignment detail page

---

apps/backend/apps/admin/src/assignment/assignment.resolver.ts
apps/backend/apps/admin/src/assignment/assignment.service.ts
collection/instructor/Assignment/Get Assignment Problem Record (Grade)/Succeed.bru

instructor get assignment problem record api를 추가합니다.
closes TAS-1376
---

feat(be): add instructor get assignment problem record api

---

apps/backend/apps/client/src/user/user.service.spec.ts
apps/backend/apps/client/src/user/user.service.ts
apps/frontend/app/(client)/(main)/settings/_components/EmailSection.tsx
apps/frontend/app/(client)/(main)/settings/_components/LogoSection.tsx
apps/frontend/app/(client)/(main)/settings/_components/context.ts
apps/frontend/app/(client)/(main)/settings/_libs/schemas.ts
apps/frontend/app/(client)/(main)/settings/page.tsx
apps/frontend/app/(client)/_libs/apis/profile.ts
apps/frontend/components/auth/SignUp/SignUp.tsx
apps/frontend/components/auth/SignUp/SignUpEmailVerify.tsx
apps/frontend/components/auth/SignUp/SignUpRegister.tsx
apps/frontend/components/shadcn/input.tsx
apps/frontend/libs/constants.ts
apps/frontend/types/type.ts

회원가입 / 계정 정보 관련하여 여러 가지 수정사항을 반영합니다.
1. [[skku.edu](http://skku.edu/)](http://skku.edu/) 로만 가입할 수 있게 변경합니다. (프론트 / 백엔드 변경)
- 신규 가입만 막습니다. 
- 안내를 위해 디자인도 일부 수정했습니다. 예솔님이 디자인을 새로 해주시긴 했는데.. 일부만 차용했습니다.. 
- shadcn Input component에 `round-full` 을 적용했습니다. 디자인팀에서 input과 버튼 모두 rounded full 로 하기로 결정한 걸로 알아서, 이 참에 바꿨어요 
Before
After
2. 회원가입 할 때 Last name, First name을 한글도 입력할 수 있게 합니다.
- regex로 한글과 영어만 입력가능하게 했습니다.
- 회원정보 수정할 때도 한글과 영어 입력가능하게 했습니다.
3. Settings에 이메일도 볼 수 있도록 추가 / 디자인 일부 수정
- 가입 이후에는 자신이 가입한 이메일을 볼 수가 없다는 문제가 있어, Settings 페이지에 이메일 필드를 추가했습니다. (Email은 수정은 불가능합니다.)
- 회원정보 수정 페이지에서 md 이하이면 로고가 사라지도록 했습니다. 
Before
After
closes TAS-1381
---

feat: force skku.edu email when signup and settings page minor change

---

apps/frontend/app/(client)/(code-editor)/_components/EditorLayout.tsx

로그인 안했을 때 finished contest 의 problem에 접근하면 문제가 발생하여 문제가 발생하지 않도록 수정하였습니다!
closes TAS-1385

fix(fe): fix error when access to ended contest problem without login

---

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/_components/BiggerImageButton.tsx

이미지 모달의 버튼의 디자인과 크기 등을 피그마에 맞추어 수정하였습니다.
---
closes tas-1357

feat(fe): modify imgModalDesign

---

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/announcement/_components/Columns.tsx
apps/frontend/types/type.ts

새로 변경된 contestannouncement api 에 맞추어 announcement column 부분을 수정하였습니다. (problemId -> problemOrder)
정상동작합니다.
---
closes.

feat(fe): modify announcement column to match new api

---

apps/frontend/app/admin/_components/DescriptionForm.tsx
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/_components/EditorLayout.tsx
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/_components/FinalScoreForm.tsx
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/_components/SubmissionAssesment.tsx
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/_components/SubmissionAssessment.tsx
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/_components/UpdateAssignmentProblemRecordForm.tsx
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/_libs/schemas.ts
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/layout.tsx
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/page.tsx
apps/frontend/components/TextEditor.tsx
apps/frontend/graphql/assignment/mutations.ts
apps/frontend/graphql/assignment/queries.ts
collection/instructor/Assignment/Get Assignment Problem Record (Grade)/Succeed.bru

코드에디터에서 사용하는 건 처음이라
`isDarkmode` 를 추가하여
bgColor와 border 조절할 수 있도록 했습니다
`useQuery`로 `comment` 정보 불러온 후에
`DescriptionForm` 을 불러와야 기존 `comment` 가 채워진 채로
렌더링 되는데 이 순서를 강제하기 위해
`loading` 상태 하나 추가했습니다
Closes TAS-1379
---

feat(fe): impl grade detail assessment panel

---

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/page.tsx
apps/frontend/types/type.ts

<li>변경된 Contest api 에 맞추어 기존의 코드를 수정하였습니다.</li>
<li>잘 적용된 모습을 확인할 수 있습니다.(e.g. contest 16)</li>
---

feat(fe): change contestsummary to match new api

---

apps/frontend/app/(client)/(code-editor)/_components/AssignmentProblemDropdown.tsx
apps/frontend/app/(client)/(code-editor)/_components/EditorLayout.tsx
apps/frontend/app/(client)/_libs/apis/assignmentProblem.ts
collection/client/login.js

Assignment Code Editor에서
assignment와 problem 정보 못 불러오는 버그 해결했습니다
간단하게 groupId만 추가했어요!
Closes TAS-1393
Reset Save Submit 전부 잘 되고
Test만 좀 문제가 있는데 저희 문제는 아닌 것 같아요!
---

fix(fe): resolve assignment code editor bug

---

apps/backend/apps/client/src/assignment/assignment.service.spec.ts
apps/backend/apps/client/src/assignment/assignment.service.ts
apps/frontend/app/(client)/(main)/course/[courseId]/_components/AssignmentAccordion.tsx
apps/frontend/app/(client)/(main)/course/[courseId]/_components/AssignmentLink.tsx

(기존) Assignment List에서 Upcoming Assignment를 들어갈 수 있지만 에러가 난다. (백엔드에서는 막아놨기 때문)
(변경) Assignment List에서 Upcoming Assignment는 과제 타이틀과 왼쪽 점을 회색으로 표시한다.
, 만약 누를 경우 토스트를 통해 "Cannot participate upcoming assignment"를 띄운다. (Assignment Detail 로 들어갈 수 없다.)
정상적으로 진행 가능 
(기존) Ongoing일 때 Assignment를 한번이라도 들어간 적이 있다면 Finished간 된 이후에도 들어갈 수 있으나, Ongoing일 때 Assignment를 들어가지 않았을 경우, Finished가 된 Assignment를 들어갈 수 없다.
(변경) Ongoing일 때 Assignment를 들어간 적이 없더라도 Finished Assignment를 참여할 수 있다.
closes TAS-1384
---

fix(fe): error handling when assignment is not started, allow assignment participation when finished

---

apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/_components/EditorLayout.tsx
apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/page.tsx
apps/frontend/graphql/assignment/queries.ts
apps/frontend/graphql/submission/queries.ts

`geAssignmentSubmission` 을 `getAssignmentLatestSubmission` 으로 수정했습니다
---

chore(fe): change query name to latest submission

---

apps/frontend/app/admin/course/[courseId]/assignment/_components/ImportDialog.tsx
apps/frontend/app/admin/course/[courseId]/assignment/create/page.tsx

Management-Course-Assignmnet-Create 화면에서 디자인 미흡한 사항 개선하였습니다.
1. 소문자를 대문자화
2. Cancel 버튼 동그랗게
3. 버튼 글자&아이콘 가운데 정렬
---

chore(fe): modify management course assignment create design

---

apps/backend/Dockerfile

Alpine 기반 Docker 이미지는 기본적으로 Bash를 포함하지 않습니다. 
코드당은 SWC 컴파일러를 도입했으며, 아래의 사진에서 볼 수 있듯이 swc-node 는 bash를 필요로 합니다.
따라서 Alpine 기반 Docker 이미지에 Bash를 추가합니다.
---

feat(infra): add bash in image to execute swc-node

---

apps/backend/apps/client/src/user/dto/signup.dto.ts
apps/backend/apps/client/src/user/dto/social-signup.dto.ts
apps/backend/apps/client/src/user/dto/updateUser.dto.ts

Real name 에서 한글도 accept 하는 부분에서 validator를 변경하지 않아 변경합니다 
---

fix(be): allow hangul in real name backend

---

.github/workflows/cd-prod-frontend.yml

add production github action that triggers only frontend
amplify deployment만 트리거하는 github action을 생성합니다. 
백엔드 배포는 필요없고 프론트엔드 배포만 필요할 때 사용합니다 
---

feat(fe): add production github action that triggers only frontend

---

apps/frontend/instrumentation.ts
apps/frontend/sentry.client.config.ts

chore(fe): change sentry dsn

---

apps/frontend/next.config.js

chore(fe): remove sentry

---

apps/frontend/app/admin/contest/[contestId]/(overall)/@tabs/submission/_components/SubmissionTable.tsx
apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/(overall)/@tabs/submission/_components/SubmissionTable.tsx
apps/frontend/app/admin/user/_components/UserTable.tsx

`take: 1000` 으로 감당이 안돼서
조만간 터질 것 같은
`GET_GROUP_MEMBERS`
`GET_CONTEST_SUBMISSIONS`
`GET_ASSIGNMENT_SUBMISSIONS`
이렇게 3개만 5000으로 늘렸습니다!
---

fix(fe): increase take of user and submissions

---

apps/backend/apps/client/src/submission/submission.controller.ts
apps/backend/apps/client/src/submission/submission.service.ts
collection/client/Submission/Get Latest Assignment Problem Submission/Succeed.bru
collection/client/Submission/Get Latest Assignment Problem Submission/[404] Nonexistent Submission.bru

Assignment의 특정 문제에 가장 최근 제출한 submission을 가져옵니다
---
Closes TAS-1405

feat(be): add client getLatestAssignmentProblemSubmission

---

apps/frontend/app/admin/course/[courseId]/user/_components/InviteButton.tsx

Invite modal에서 whitelist를 적용한 후 새로고침 없이 모달을 껐다 켜면 whitelist가 적용된 것이 없어지는 버그를 수정합니다.
createWhitelist mutation 이후 getWhitelist query를 refetch 하도록 설정하였습니다.
추가적으로, 모달을 reopen하면 invitation code와 whitelist 설정을 refetch하도록 설정했습니다. (아마도 여러 사람이 설정을 건들 수 있을 것 같아서 설정했어요)
---

feat(fe): refetch whitelist and invitation code on modal reopen

---

apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/edit/_components/ConfirmModal.tsx
apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/edit/_components/EditAssignmentForm.tsx

진행중이거나 끝난 과제에서
문제를 삭제하거나 점수를 변경하려 할 때
경고 모달을 띄우도록 구현했습니다
Closes TAS-1409
---

fix(fe): resolve import assignment problem bug

---

apps/frontend/app/(client)/(main)/course/[courseId]/assignment/[assignmentId]/@tabs/page.tsx
apps/frontend/app/(client)/(main)/course/[courseId]/assignment/[assignmentId]/_components/TotalScoreLabel.tsx

Student Assignment page의 점수 API를 연결합니다. 
---

feat(fe): fetch score on student assignment page

---

apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/_components/SubmissionAssessment.tsx
apps/frontend/graphql/problem/queries.ts

Problem의 Max Score을 받아와서 보여주도록 수정했습니다
Closes TAS-1406
---

chore(fe): get assignment problem max score

---

apps/backend/apps/client/src/submission/submission.service.ts
apps/backend/apps/client/src/submission/test/submission.service.spec.ts
collection/client/Submission/Get Assignment Submissions/Succeed.bru

getAssignmentSubmissions에서 assignment와 problem에 관한 정보가 너무 없어서 제출 기록을 보여줄 때 불필요한 API 호출이 생깁니다.
따라서 getAssignmentSubmissions의 assignmentProblem에 메타데이터를 추가하여 사용할 수 있게 합니다.
변경된 response
```
{
"data": [
{
"id": 14,
"user": {
"username": "user01"
},
"createTime": "2025-03-07T16:39:14.492Z",
"language": "Cpp",
"result": "WrongAnswer",
"codeSize": 88
},
{
"id": 13,
"user": {
"username": "user01"
},
"createTime": "2025-03-07T16:39:11.714Z",
"language": "Cpp",
"result": "WrongAnswer",
"codeSize": 88
}
],
"total": 2,
"assignmentProblem": {
"order": 0,
"problem": {
"id": 7,
"title": "천재 디자이너"
},
"assignment": {
"id": 19,
"isJudgeResultVisible": true,
"title": "24학년도 성민규 과제"
}
}
}
```
closes TAS-1420
---

feat(be): add assignmentProblem in getAssignmentSubmissions

---

apps/frontend/app/admin/course/[courseId]/assignment/page.tsx
apps/frontend/app/admin/course/[courseId]/grade/page.tsx

Management - Course - Assignment
: 페이지 제목과 설명이 사이에 있어야 할 margin을 넣었습니다.
Management - Course - Grade
: 설명문구를 적절하게 수정하였습니다.
---
closes TAS-1424

fix(fe): modify description and apply marign

---

apps/frontend/app/(client)/(main)/course/[courseId]/assignment/[assignmentId]/@tabs/page.tsx
apps/frontend/app/(client)/(main)/course/[courseId]/assignment/[assignmentId]/_components/TotalScoreLabel.tsx

#2512 를 급하게 배포하느라 변경하지 못한 API 변경사항은 프론트에서도 반영합니다 
---

fix(fe): follow score api response change

---

apps/backend/apps/admin/src/submission/submission.service.ts
apps/backend/apps/client/src/assignment/assignment.service.ts
apps/backend/apps/client/src/submission/submission.service.ts

- submissionTime으로 채점 시각인 updateTime 대신 실제 제출 시각인 createTime 사용
---
Closes TAS-1442

fix(be): use createTime instead of updateTime as submissionTime

---

apps/backend/apps/admin/src/contest/contest.service.spec.ts
apps/backend/apps/admin/src/contest/contest.service.ts
apps/backend/apps/admin/src/contest/model/contest.input.ts
apps/backend/apps/admin/src/problem/mock/mock.ts
apps/backend/apps/client/src/contest/contest.service.spec.ts
apps/backend/apps/client/src/contest/contest.service.ts
apps/backend/apps/client/src/submission/test/submission.service.spec.ts
apps/backend/prisma/migrations/20250123114853_contest_leaderboard/migration.sql
apps/backend/prisma/migrations/20250313061215_add_unfreeze_column/migration.sql
apps/backend/prisma/schema.prisma
collection/admin/Contest/Create Contest/Succeed.bru
collection/admin/Contest/Import Problems to Contest/Succeed.bru
collection/admin/Contest/Update Contest/Succeed.bru

기존의 input에 새로운 column 적용을 위해 추가합니다
unfreeze가 가능하도록 변경하는 기능이 없어 추가했습니다.
---
closes TAS-1447

feat(be): update contest input

---

apps/frontend/app/(client)/(code-editor)/_components/EditorHeader/EditorHeader.tsx
apps/frontend/app/(client)/(code-editor)/contest/[contestId]/problem/[problemId]/submission/[submissionId]/page.tsx
apps/frontend/app/(client)/(code-editor)/contest/[contestId]/problem/[problemId]/submission/_components/SubmissionDetail.tsx
apps/frontend/app/(client)/(code-editor)/course/[courseId]/assignment/[assignmentId]/problem/[problemId]/submission/[submissionId]/_components/SubmissionDetail.tsx
apps/frontend/app/(client)/(code-editor)/course/[courseId]/assignment/[assignmentId]/problem/[problemId]/submission/[submissionId]/page.tsx

1. 기존 코드에디터에서는 submit 버튼을 누르면 contest 와 일반 problem 일 때 submission detail page 로 라우팅이 되었으나,  assignment 는 페이지가 만들어지지 않아 url을 설정하지 않았습니다.
2. 현재 submission detail 페이지가 만들어져 url을 바꿉니다 ㅎㅎ
---
closes.

feat(fe): change href for assignment submission

---

apps/backend/prisma/migrations/20250318172841_fix_problem_field_enum_typo/migration.sql
apps/backend/prisma/schema.prisma

Update Problem에서 internal server error가 발생하는 문제 수정
---

fix(be): fix problem update error

---

apps/backend/apps/admin/src/announcement/announcement.service.spec.ts
apps/backend/apps/admin/src/announcement/announcement.service.ts
apps/backend/apps/admin/src/announcement/model/create-announcement.input.ts
apps/backend/apps/admin/src/contest/contest.service.spec.ts
apps/backend/apps/admin/src/contest/contest.service.ts
apps/backend/prisma/seed.ts
collection/admin/Announcement/Create Announcement/Succeed.bru
collection/admin/Announcement/Create Announcement/[ERR] Has No Contest Id.bru
collection/admin/Announcement/Create Announcement/[ERR] Non Existent Contest.bru
collection/admin/Announcement/Create Announcement/[ERR] Non Existent Problem.bru
collection/admin/Contest/Create Contest/Succeed.bru
collection/admin/Contest/Import Problems to Contest/[ERR] Nonexistent Contest.bru
collection/admin/Contest/Remove Problems From Contest/Succeed.bru
collection/admin/Contest/Remove Problems From Contest/[ERR] Nonexistent Contest.bru
collection/admin/Problem/Update ContestProblems Order/Succeed.bru

- order 다 0으로 초기화되는 문제 수정
- contest 별로 order 0부터 시작하도록 seed 수정
- create announcement 할 때 contest problem order로 받아오도록 수정
---

fix(be): change input format from id to order

---

.github/workflows/rc-deploy-target.yml
.github/workflows/rc-deploy.yml

PR #2537 fix 3
workflow 호출 방식를 잘못된 step단위에서 올바른 job단위로 고쳤습니다.
rc-deploy-target.yml에서 storage를 무조건 destroy하지 말고, 존재하는 storage 리소스 유무에 따라 동적으로 destroy를 실행할지 말지 바꿈
---

feat(fix): fix update rc workflow

---

apps/frontend/app/admin/course/[courseId]/user/_components/DeleteUserButton.tsx

Management - Course - Member
삭제 모달 디자인 반영하였습니다.
---
closes TAS-1468

feat(fe): change delete member modal design

---

apps/frontend/app/admin/problem/_components/ProblemTableColumns.tsx
apps/frontend/app/admin/problem/_components/UseInfoModal.tsx

Management - Problem 테이블
- 행의 값들을 재정렬하였습니다.
- 글자색을 회색으로 변경하였습니다.
- Use Info 모달을 위한 열을 추가했습니다. (모달은 디자인 완성전이라 틀만 만들었습니다.)
- Update Time을 시각 단위까지 보이도록 수정했습니다.
closes TAS-1472

feat(fe): add updatetime and align column widths

---

apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/edit/page.tsx
apps/frontend/app/admin/course/[courseId]/assignment/_components/WeekComboBox.tsx
apps/frontend/app/admin/course/[courseId]/assignment/create/page.tsx

assignment create/edit 할 때 week `combobox`의 최대치를 course의 week수에 맞게 제한되도록 변경하였습니다.
closes TAS-1482
---

feat(fe): limit assignment create week

---

apps/frontend/app/admin/problem/_components/CodeForm.tsx
apps/frontend/app/admin/problem/_components/TemplateField.tsx
apps/frontend/app/admin/problem/_components/editor/CodeEditor.tsx
apps/frontend/app/admin/problem/_components/editor/editorConfig.ts
apps/frontend/app/admin/problem/_components/editor/formatConfigs.ts
apps/frontend/app/admin/problem/_components/editor/formatters.ts
apps/frontend/app/admin/problem/_components/editor/index.ts
apps/frontend/package.json
pnpm-lock.yaml

[format 예시 문제](https://2560.coolify.codedang.com/admin/problem/46/edit)
`tabWidth` 를 일괄 2로 바꿔버립니다~
Closes TAS-1471
---

feat(fe): parse indentation in template code

---

apps/frontend/app/admin/_components/code-editor/PreviewEditorLayout.tsx
apps/frontend/app/admin/_components/code-editor/PreviewEditorResizablePanel.tsx
apps/frontend/app/admin/course/[courseId]/assignment/_components/ImportProblemTableColumns.tsx
apps/frontend/app/admin/problem/[problemId]/edit/page.tsx
apps/frontend/app/admin/problem/[problemId]/page.tsx
apps/frontend/app/admin/problem/[problemId]/preview/page.tsx
apps/frontend/app/admin/problem/_components/ProblemTableColumns.tsx
apps/frontend/app/admin/problem/create/page.tsx

Problem Preview 페이지를 생성하고 언어 선택 기능을 추가하였습니다! 
closes TAS-1469
---

feat(fe): add problem preview page

---

apps/backend/apps/client/src/submission/mock/submissionResult.mock.ts
apps/backend/apps/client/src/submission/submission-sub.service.ts
apps/backend/apps/client/src/submission/test/submission-sub.service.spec.ts
apps/backend/prisma/migrations/20250323164730_add_output_on_submission_result_table/migration.sql
apps/backend/prisma/schema.prisma

fix(be): logging submit result output

---

docker-compose.yml

cgroup 에러를 해결하기 위한 hotfix입니다.
---

fix(infra): fix docker compose to deal with cgroup error

---

.github/workflows/rc-deploy-target.yml
.github/workflows/rc-deploy.yml

fix(infra): fix terraform existing resource checking

---

apps/backend/apps/admin/src/contest/contest.resolver.ts
apps/backend/apps/admin/src/contest/contest.service.ts
apps/backend/apps/admin/src/contest/model/contest-with-participants.model.ts
apps/backend/apps/admin/src/user/model/creationPermission.model.ts
apps/backend/apps/admin/src/user/model/user.output.ts
apps/backend/apps/admin/src/user/user.resolver.ts
apps/backend/apps/admin/src/user/user.service.spec.ts
apps/backend/apps/admin/src/user/user.service.ts
collection/admin/User/Update Creation Permission/Succeed.bru
collection/admin/User/Update Creation Permission/folder.bru

admin/getContest 의 userContest 로 return 되던 것을 userContestRoles로 변경하였습니다.
closes TAS-1511
---

fix(be): rename return value

---

.github/workflows/rc-build-image.yml
apps/infra/rc/storage/database.tf

DB username이 aws기본설정에 인해 더이상 변하지 않음으로, username 변경 감지 무시 조건을 삭제합니다.
---

fix(infra): remove db ignore attr checking exception

---

apps/backend/apps/admin/src/contest/contest.service.ts

- 기존에는 푼 문제들만 problemRecords에 들어갔는데, contest에 있는 모든 문제를 반환하도록 수정하였습니다
---

fix(be): return all problems record on admin leaderboard

---

.devcontainer/Dockerfile
apps/iris/Dockerfile
apps/iris/entrypoint.sh
apps/iris/src/service/sandbox/judger/langConfig.go
apps/iris/src/service/sandbox/sandbox.go
scripts/setup.sh

fix(iris): resolve memory limit exceeded not displayed

---

.devcontainer/Dockerfile
apps/iris/Dockerfile

fix(iris): update version of libjudger to fix segmenation fault

---

apps/frontend/app/(client)/_libs/apis/assignment.ts

post로 보내야하는 요청을 get으로 요청하고있어, 이를 수정하였습니다.
---

fix(fe): change get to post

---

apps/backend/apps/client/src/submission/submission-sub.service.ts
apps/backend/apps/client/src/submission/test/submission-pub.service.spec.ts
apps/backend/prisma/migrations/20250329135318_first_solver/migration.sql
apps/backend/prisma/schema.prisma

동시에 제출할 때 발생할 수 있는 동시성 문제를 해결합니다
- contest problem first solver table에 create함으로써 중복을 확인합니다.
closes TAS-1416
---

fix(be): first solver concurrency issue

---

apps/backend/apps/admin/src/problem/problem.service.ts
collection/admin/Problem/Get Problems/Succeed.bru

- contest에서 problem을 import할 때 problem의 creator username을 전달하고 있지 않습니다.
- getProblems api에 username을 추가해서 반환합니다.
---

chore(be): return username on getProblems

---

apps/frontend/app/admin/_components/DescriptionForm.tsx
apps/frontend/app/admin/contest/[contestId]/edit/_components/EditContestForm.tsx
apps/frontend/app/admin/contest/[contestId]/edit/page.tsx
apps/frontend/app/admin/contest/_components/ContestTableColumns.tsx
apps/frontend/app/admin/contest/_libs/schemas.ts
apps/frontend/app/admin/contest/create/_components/CreateContestForm.tsx
apps/frontend/app/admin/contest/create/page.tsx

- contest create more description 을 optional로 바꿉니다
closes TAS-1538
---

fix(fe): make contest create more description optional

---

apps/frontend/app/admin/contest/[contestId]/(overall)/@tabs/announcement/page.tsx
apps/frontend/app/admin/contest/[contestId]/(overall)/@tabs/leaderboard/_components/LeaderboardUnfreezeSwitchDialog.tsx
apps/frontend/app/admin/contest/[contestId]/(overall)/@tabs/submission/_components/SubmissionTable.tsx
apps/frontend/app/admin/contest/[contestId]/edit/_components/EditContestForm.tsx
apps/frontend/app/admin/contest/_libs/schemas.ts
apps/frontend/graphql/contest/mutations.ts
apps/frontend/graphql/submission/queries.ts

- contestId graphql 관련 프론트 코드 수정
- edit form schema 변경
closes TAS-1541
---

fix(fe): change contestId graphql change

---

apps/frontend/app/admin/contest/[contestId]/(overall)/@tabs/announcement/page.tsx
apps/frontend/app/admin/contest/[contestId]/(overall)/layout.tsx
apps/frontend/app/admin/contest/[contestId]/_components/ContestOverallTabs.tsx
apps/frontend/app/admin/contest/_libs/schemas.ts

admin announcement 페이지 qa 수정사항입니다.
1. select 를 하기전 default 로 general 이 나오게 하였고, valibot 도 함께 수정하였습니다
2. 이외에 자잘한 디자인을 수정하였습니다.
---

feat(fe): make default of select

---

apps/frontend/app/admin/problem/[problemId]/edit/page.tsx
apps/frontend/app/admin/problem/[problemId]/preview/page.tsx
apps/frontend/app/admin/problem/_components/ProblemTableColumns.tsx
apps/frontend/app/admin/problem/create/page.tsx

management problem preview에서 hidden TC가 보이던 문제 수정
closes TAS-1544
---

feat(fe): hide hidden tescases in preview

---

apps/frontend/app/(client)/(code-editor)/_components/EditorResizablePanel.tsx

fix(fe): resolve resizableEditor problem

---

apps/backend/apps/client/src/assignment/assignment.service.ts

Reveal JudgeResult/FinalScore 옵션 버그 수정과
Autofinalize 관련 버그 수정입니다
---
Closes TAS-1550

fix(be): fix reveal options and autofinalize

---

apps/backend/apps/admin/src/problem/problem.service.ts
apps/backend/apps/client/src/assignment/assignment.service.ts

assignment 정보 가져올때 isFinalScoreVisible, autoFinalizeScore도 가져오기
problem import 할때 order 에러핸들링
---

fix(be): fix assignment related bugs

---

apps/backend/apps/admin/src/contest/contest.service.ts
apps/backend/apps/admin/src/contest/model/contest.input.ts
collection/admin/Contest/Update Contest/Succeed.bru

종료된 대회의 leaderboard에 unfreeze 요청 보냈을 때 Bad Request Exception이 뜨는 오류를 수정했습니다.
---

fix(be): fix unfreeze error

---

apps/frontend/app/(client)/(code-editor)/_components/EditorDescription.tsx
apps/frontend/app/admin/_components/code-editor/EditorDescription.tsx

hint가 없을 때, hint 탭이 표시되지 않도록 합니다. 
closes TAS-1492
(1) 힌트가 없을 때는 아래 사진처럼 힌트 탭이 없어집니다.
(2) 힌트가 있을 때는 아래 사진처럼 힌트 탭이 생깁니다. 
프리뷰 화면도 확인한 결과입니다.
(1) 힌트없이 만들었을 때 프리뷰 화면
(2) 힌트가 있을 때 프리뷰 화면
---

feat(fe): preview hide hint if empty

---

apps/frontend/app/(client)/(code-editor)/_components/EditorResizablePanel.tsx
apps/frontend/components/CodeEditor.tsx

패널을 열고닫을 수 있는 버튼 2개 추가했습니다.
버튼이 lineNumber를 가리기 때문에 패딩 살짝쿵 넣어줬습니다.
사다리꼴 버튼 만들고 border 주는 방식이 독특함요
사이즈 다른 사다리꼴 2개 만들어서 포개면 border 처럼 보임
Closes TAS-1575
---

feat(fe): impl hide panel button

---

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/_components/RegisterButton.tsx
apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/_components/RenderProblemList.tsx
apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/page.tsx

대회를 생성했거나 `ContestManager` `ContestReviewer` 로 초대받으면
`isPrivilegedRole` 이 `true` 이고
이 경우 다음의 일이 벌어집니다..!
1. Upcoming 상태이고 Register 안 했을 때
- Problem List 확인 가능 (isPrivilegedRole을 조건문에 추가함)
- Contest Code Editor 접근 가능 (이건 그냥 원래 되어 있음)
2. Register 버튼 비활성화 (isPrivilegedRole일 때 disable)
Closes TAS-1576
---

fix(fe): break through contest problems by contest role

---

apps/backend/apps/client/src/assignment/assignment.service.ts
apps/backend/apps/client/src/submission/submission.controller.ts
apps/backend/apps/client/src/submission/submission.service.ts
apps/backend/apps/client/src/submission/test/submission.service.spec.ts
collection/client/Submission/Get Assignment Submission Summary/Succeed.bru
collection/client/Submission/Get Assignment Submission Summary/[403] Non participating assignment.bru
collection/client/Submission/Get Assignment Submission Summary/folder.bru

Client가 assignment 창에서 아코디언을 열었을때 TC result를 보여주기 위한 API입니다.
추후 getMyAssignmentProblemRecord에서는 submission 관련 내용을 제거하고 이 API를 사용할 예정입니다.
---
Closes TAS-1583

feat(be): implement getAssignmentSubmissionSummary

---

apps/backend/apps/admin/src/contest/contest.service.ts

update contest 에서 summary 데이터가 미포함된 요청을 보낼 경우 null이 되는 오류 수정 
---

fix(be): fix summary field problem

---

apps/backend/apps/client/src/contest/contest.service.ts
apps/backend/apps/client/src/submission/submission-sub.service.ts
collection/client/Submission/Create Contest Submission/Succeed.bru

fix(be): update contest record bug fix

---

apps/frontend/app/admin/_components/SummaryForm.tsx
apps/frontend/app/admin/_components/TitleForm.tsx
apps/frontend/app/admin/contest/[contestId]/edit/page.tsx

- Ongoing 일때 edit 안되게 처리해놓음
- Edit에서 Summary, Title 글자수가 0으로 초기화돼서, 내용이 있어도 0으로되는 문제 해결
- Summary, Title 글씨제한수 이상으로 작성 불가능하게
closes TAS-1591
---

fix(fe): resolve edit contest problems

---

apps/backend/apps/client/src/contest/contest.service.ts

freeze 상태일 때 freezeTime 이전의 submissionCount를 넣습니다. 
closes TAS-1606
---

fix(be): submission count before freeze

---

apps/frontend/app/admin/contest/[contestId]/edit/_components/EditContestForm.tsx
apps/frontend/app/admin/contest/[contestId]/edit/page.tsx
apps/frontend/app/admin/contest/_components/AddManagerReviewerDialog.tsx
apps/frontend/app/admin/contest/_components/ImportProblemTable.tsx
apps/frontend/app/admin/contest/create/page.tsx

- manager/reviewer 등록시 이메일 자동완성 기획 이해 잘못한거 수정
- contest import dialog에서 본인이 만든 문제만 확인(Import) 가능하도록
- 다음 배포때는 매니저, 어드민 둘다 만든 문제 확인하게 바꿀 예정
clioses-TAS1602
---

fix(fe): manager reviewer modal problems

---

apps/infra/rc/codedang/amplify.tf
apps/infra/rc/codedang/cloudfront.tf

구현되어 있지 않은 rc amplify terraform을 구축하였습니다.
또한 rc cloudfront.tf의 amplify domain을 새로 만든 amplify app domain으로 바꾸었습니다.
---

feat: add rc amplify terraform

---

apps/backend/apps/client/src/submission/submission.service.ts

Hidden T/C 결과를 숨겼을 때 
→ API에서 여전히 Hidden T/C 결과가 오는 문제를 해결했습니다.
closes TAS-1609

fix(be): filter hidden testcases from submission results

---

apps/backend/apps/admin/src/assignment/model/assignment-problem-record-input.ts
apps/backend/apps/client/src/submission/submission.service.ts

채점할때 점수 0으로 채점이 안되는 문제를 해결합니다.
---

fix(be): fix gql error when trying to grade with finalScore 0

---

apps/backend/apps/client/src/submission/submission-sub.service.ts
apps/backend/apps/client/src/submission/test/submission-sub.service.spec.ts

contest submission count에서 전체 문제 제출 횟수 -> 특정 문제 제출 횟수로 변경 
---

fix(be): fix contest problem submission count

---

apps/backend/apps/admin/src/notice/notice.resolver.ts
apps/backend/apps/admin/src/notice/notice.service.spec.ts
apps/backend/apps/admin/src/notice/notice.service.ts
apps/backend/apps/client/src/notice/notice.controller.ts
apps/backend/apps/client/src/notice/notice.service.spec.ts
apps/backend/apps/client/src/notice/notice.service.ts
apps/backend/prisma/migrations/20250403092824_remove_group_id_from_notice/migration.sql
apps/backend/prisma/schema.prisma
apps/backend/prisma/seed.ts
apps/frontend/app/(client)/(main)/notice/[noticeId]/page.tsx
apps/frontend/app/(client)/(main)/notice/_components/NoticeTable.tsx
apps/frontend/app/admin/notice/[noticeId]/page.tsx
apps/frontend/app/admin/notice/_components/CreateNoticeForm.tsx
apps/frontend/graphql/notice/mutation.ts
apps/frontend/graphql/notice/queries.ts
collection/admin/Notice/Create Notice/NOT_FOUND.bru
collection/admin/Notice/Create Notice/Succeed.bru
collection/admin/Notice/Delete Notice/NOT_FOUND.bru
collection/admin/Notice/Delete Notice/Succeed.bru
collection/admin/Notice/Get Notices/Succeed.bru
collection/admin/Notice/Get a Notice/NOT_FOUND.bru
collection/admin/Notice/Get a Notice/Succeed.bru
collection/admin/Notice/Update Notice/Succeed.bru
collection/client/Notice/Get all notices/Succeed.bru
collection/client/Notice/Get notice by ID/Succeed.bru

notice에서 groupId를 뺍니다.
프론트도 한번에 적용합니다.
closes TAS-1592
---

feat(be): remove group id from notice

---

.github/workflows/rc-acm-validation.yml
.github/workflows/rc-deploy-target.yml
.github/workflows/rc-deploy.yml
apps/infra/rc/acm-validation/main.tf
apps/infra/rc/acm-validation/outputs.tf
apps/infra/rc/acm-validation/variables.tf
apps/infra/rc/network/outputs.tf
apps/infra/rc/network/route53.tf

‼ RC서버의 도메인은 [[codedang.com](http://codedang.com/)](http://codedang.com) (production에서 사용중)의 서브도메인인 [[rc.codedang.com](http://rc.codedang.com/)](http://rc.codedang.com)을 사용하고 있습니다. 해당 rc.codedang.com도메인을 활성화 해주고 acm certificate validation을 위해서는 RC AWS계정의 rc.codedang.com도메인의 route53 NS레코드를 Production AWS계정의 codedang.com도메인의 route53 [rc.codedang.com](http://rc.codedang.com/) NS레코드로 수동으로 복사해주어야 합니다. 
💥 이전에는 rc배포중 terraform 자체적으로는 다른 AWS계정을 동시에 접근 및 작업 할 수 없기에, 위의 작업을 terraform코드내 자동화 하지 못하였습니다.
**‼ 하지만 CI/CD의 목적은 디테일을 모르는 사람도 배포를 쉽게 할 수 있게 돕는 것 이기 때문에, workflow 수정과 별도의 terraform 코드 폴더 추가를 통해 위의 작업을 자동화 해보고자 합니다.**
자동화 계획:
- route53.tf의 acm certificate validation부분을 별도의 테라폼 코드 폴더에 구축
- rc의 route53.tf에서 생성된 NS record를 외부 변수 output으로 저장
- workflow 흐름:
1. rc의 NS record를 terraform output명령어를 실행시켜 …

feat(infra): rc acm validation automation

---

.github/workflows/rc-acm-validation.yml

fix(infra): acm validation workflow fix

---

.github/workflows/rc-acm-validation.yml

fix(infra): fix rc acm validation workflow

---

.github/workflows/rc-acm-validation.yml

fix(infra): fix rc acm validation workflow3

---

.github/workflows/rc-acm-validation.yml

fix(infra): fix rc acm validation workflow5

---

.github/workflows/rc-acm-validation.yml

fix(infra): fix rc acm validation workflow6

---

apps/backend/apps/admin/src/contest/contest.service.ts

orderby로 가져온 후
contest의 상태에 따라 status를 부여하여 sort합니다.
추가적인 frontend 코드 수정은 불필요합니다
closes TAS-1617
---

feat(be): admin get contests order

---

apps/infra/production/codedang/.terraform.lock.hcl
apps/infra/production/codedang/codedang_service_admin.tf
apps/infra/production/codedang/codedang_service_client.tf
apps/infra/production/codedang/codedang_service_iris.tf
apps/infra/production/codedang/container_definitions/admin_api.json
apps/infra/production/codedang/container_definitions/client_api.json
apps/infra/production/codedang/container_definitions/fluentbit.json
apps/infra/production/codedang/container_definitions/iris.json
apps/infra/production/codedang/fluent-bit.conf
apps/infra/production/codedang/fluentbit.tf
apps/infra/rc/codedang/.terraform.lock.hcl
apps/infra/rc/codedang/codedang_service_admin.tf
apps/infra/rc/codedang/codedang_service_client.tf
apps/infra/rc/codedang/codedang_service_iris.tf
apps/infra/rc/codedang/container_definitions/admin_api.json
apps/infra/rc/codedang/container_definitions/client_api.json
apps/infra/rc/codedang/container_definitions/fluentbit.json
apps/infra/rc/codedang/container_definitions/iris.json
apps/infra/rc/codedang/fluent-bit.conf
apps/infra/rc/codedang/fluentbit.tf
apps/iris/main.go
apps/iris/src/connector/factory.go
apps/iris/src/connector/rabbitmq/connector.go
apps/iris/src/connector/rabbitmq/producer.go
apps/iris/src/loader/postgres.go
apps/iris/src/loader/s3.go
apps/iris/src/service/logger/logger.go

Grafana 로그 내용에서 'log' field 내용이 JSON으로 알맞게 parsing되도록 설정했습니다.
- production과 rc의 terraform 변경사항은 동일합니다.
- Iris에서 `panic()`을 호출할 경우 JSON 형태의 로그가 남지 않는 문제가 있어, `zap.Panic()`으로 변경하여 JSON 형태 로그 남도록 변경하였습니다. ([zap 공식 문서](https://pkg.go.dev/go.uber.org/zap#Logger.Panic))
- Grafana 대시보드에서 가독성을 개선하였습니다. (링크: https://grafana.codedang.com/goto/G4rwjZ1Hg?orgId=1)
링크: https://grafana.codedang.com/goto/G4rwjZ1Hg?orgId=1
---

feat(infra): parse logs with fluent-bit json parser

---

apps/backend/apps/admin/src/contest/contest.service.ts
apps/backend/apps/client/src/contest/contest.service.ts
apps/backend/apps/client/src/submission/submission-sub.service.ts

contest에서 대회 중 문제를 맞춘 경우 freeze 여부와 관계 없이 lastAcceptedTime이 update되도록 변경합니다.
---

chore(be): specify last accepted time for contest

---

apps/backend/apps/client/src/submission/submission.module.ts

@golevelup/nestjs-rabbitmq 버전이 업데이트되면서 바뀐 module 방식을 적용합니다.
---

fix(be): update rabbitmq module type for nest

---

apps/backend/prisma/migrations/20250506225054_add_duetime/migration.sql

fix(be): set duetime as endtime for existing records

---

apps/frontend/app/admin/problem/create/page.tsx

실습 문제 등을 생성할 때
Sample TC만 두는 경우가 많은데
Default TC가 Sample 1개 Hidden 1개로 설정되어 있으면
매번 Hidden 1개를 X 눌러서 지워주기 귀찮으니까
Default TC를 Sample 1개로 변경했습니다.
Closes TAS-1686
---

chore(fe): remove hidden tc from default value

---

apps/backend/apps/client/src/submission/class/judge-request.ts
apps/backend/apps/client/src/submission/submission-pub.service.ts
apps/backend/apps/client/src/submission/submission-sub.service.ts
apps/backend/apps/client/src/submission/submission.service.ts
apps/iris/src/handler/judge-handler.go

최근 대회 문제 채점에서, 하나의 TC라도 `Accepted`를 받지 못하면, 그 뒤 TC는 채점하지 않도록 (`stopOnNotAccepted`) 변경하였습니다.
참고: [feat(be): add feature to stop(cancel) judging once submission not accepted on a testcase](https://github.com/skkuding/codedang/pull/2739)
이때, Sample Testcase의 채점 결과가 최종 결과(Submission Result)에 포함되지 않도록 설정된 **대회**(`evaluateWithSampleTestcases`가 `false`인 대회)에서는 `stopOnNotAccepted` 기능과 충돌하여 정상적으로 채점이 되었음에도 `ServerError`가 나오는 Case를 확인하였습니다.
**해당 Case:**
Given: Sample Testcase의 채점 결과가 최종 결과(Submission Result)에 포함되지 않도록 설정된 **대회**(채점할 때 stopOnNotAccepted 적용됨)의 TC 1: Hidden / TC 2: Sample / TC 3: Hidden / TC 4: Hidden 인 문제에서,
When: TC 1, 3, 4는 맞고 Sample TC인 TC 2는 틀리는 코드 제출 시에,
Then: TC 1: Accepted / TC 2: WA / TC 3: Canceled / TC 4: Canceled => Submission Result: Server Error
정답인 코드를 제출했음에도, 채점 결과에 …

feat(be): judge only hidden testcase when evaluateWithSampleTestcases not set

---

apps/backend/apps/admin/src/contest/contest.service.ts

ongoing contest에서 freezeTime 그대로인 경우 오류 반환 케이스에서 제외
---

fix(be): freeze time validation in ongoing contest

---

apps/backend/apps/admin/src/contest/contest.service.ts
apps/backend/libs/auth/src/roles/contest-roles.guard.ts

현재 교수님이 admin 권한 가지고 있는 계정 사용중이셔서, contest 조회 관리를 super admin만 가능하도록 수정합니다.
closes TAS-1724
---

feat(be): only superadmin can see all contest

---

apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/(overall)/@tabs/page.tsx

… release time
solutionReleaseTime이 지난 문제들 아이콘이 보이도록..!
closes TAS-1723
---

feat(fe): show solution icon in assignment information

---

apps/frontend/app/admin/contest/_components/ImportDialog.tsx

problem module refactor 하다가 frontend code를 잘못 건드려서 수정했습니다. 
---

fix(fe): contestId bug fix

---

apps/frontend/app/admin/_components/FormSection.tsx
apps/frontend/app/admin/_components/Label.tsx
apps/frontend/app/admin/_components/SwitchField.tsx
apps/frontend/app/admin/contest/[contestId]/edit/page.tsx
apps/frontend/app/admin/contest/_components/AddManagerReviewerDialog.tsx
apps/frontend/app/admin/contest/_components/DisableCopyPasteForm.tsx
apps/frontend/app/admin/contest/_components/FreezeForm.tsx
apps/frontend/app/admin/contest/_components/SampleTestcaseForm.tsx

- skku.edu 외 다른 이메일 도메인 manager/reviewer로 추가 가능하게
- AS IS : 밑에 뜨는 자동완성 이메일을 눌러야만 등록 가능
- TO BE : 자동완성 클릭 뿐만 아니라 이메일 Input창 오른쪽에 등록 버튼 하나 추가 -> 클릭해서 추가 가능
- finished인 contest edit 불가하게(ongoing과 다르게 opacity는 안넣었습니다)
closes TAS-1727
---

fix(fe): email finished contest error

---

apps/frontend/app/(client)/(code-editor)/contest/[contestId]/problem/[problemId]/page.tsx
apps/frontend/app/(client)/(main)/contest/[contestId]/layout.tsx
apps/frontend/components/ChannelIO.tsx
apps/frontend/package.json
pnpm-lock.yaml

NPC 대회에서 소통 창구로 사용하기 위해(대회 문제 질문 등) 채널톡을 연결해둡니다.
일단은 Contest 페이지(상세 페이지, code-editor 페이지)에서만 표시되도록 설정해뒀습니다.
> [!Warning]
> 채널톡 plugin key를 환경변수로 주입해야합니다 (내용은 notion 환경변수(.env) 페이지 참고)
좌측 하단에 표시된 채널톡 버튼 클릭 시 다이얼로그 표시
테스트 링크: https://2784.coolify.codedang.com/contest/1/problem/3
---

feat(fe): add channel-talk button in contest

---

apps/frontend/app/(client)/(code-editor)/contest/[contestId]/problem/[problemId]/submission/_components/SubmissionDetail.tsx

>[!Note]
> 콘테스트에서만 적용되는 화면입니다.
기획변경!
콘테스트 코드 에디터에서 test case를 보여주지 않기로 했습니다.
또한 source code 부분을 최대 45줄까지 보여주는 것으로 변경되었습니다!
정리하면 아래와 같이 보이게 변경된 것입니다! 
공통 컴포넌트이므로 밍규를 리뷰어로 지정합니다! 근데 사실 콘테스트 외의 다른 페이지에서는 적용이 안되는 사항이므로 Assignment에서 문제가 없는 지 봐주시면 좋을 것 같습니다 :)
closes TAS-1668

feat(fe): remove test case in contest code editor

---

apps/backend/apps/client/src/contest/contest.service.ts
collection/client/Contest/Get Leaderboard/succeed.bru

> [!WARNING]
> contest leaderboard를 불러올 때 현재 로그인된 userId에 optional 옵션을 추가합니다..
---

chore(be): leaderboard userid optional

---

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/leaderboard/_libs/apis/getContestLeaderboard.ts
apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/leaderboard/page.tsx

백엔드 api에 맞춰서 변수명을 userRole에서 contestRole로 수정합니다.
closes TAS-1754

chore(fe): change variable name

---

apps/frontend/app/admin/problem/_components/ProblemTable.tsx
apps/frontend/app/admin/problem/_components/ProblemTableColumns.tsx

콘테스트에 포함되지 않은 문제는 isVisible toggle을 사용할 수 없도록 하였습니다.

feat(fe): no contest no visible toggle

---

pnpm-workspace.yaml

pnpm v10으로 업그레이드하면서(#2798) `pnpm deploy out` 명령어가 실패합니다.
새로 추가된 `inject-workspace-packages` 옵션을 `pnpm-workspaces.yml`에 추가하여 해결합니다.
CI Failure: https://github.com/skkuding/codedang/actions/runs/15341394511/job/43168125556
Reference: https://pnpm.io/docker#example-2-build-multiple-docker-images-in-a-monorepo
```
10 [builder 6/9] RUN pnpm --filter="@codedang/backend" deploy out
#10 0.871  ERR_PNPM_DEPLOY_NONINJECTED_WORKSPACE  By default, starting from pnpm v10, we only deploy from workspaces that have "inject-workspace-packages=true" set
#10 0.871 
#10 0.871 If you want to deploy without using injected dependencies, run "pnpm deploy" with the "--legacy" flag or set "force-legacy-deploy" to true
#10 ERROR: process "/bin/sh -c pnpm --filter=\"@codedang/backend\" deploy out" did not complete …
```

fix: allow pnpm deploy cmd with pnpm v10

---

apps/backend/apps/admin/src/submission/submission.service.ts
apps/backend/apps/client/src/assignment/assignment.service.spec.ts

ESLint warning들을 없앴습니다. (사용되지 않는 변수 제거)
---

fix(be): resolve eslint warnings

---

apps/frontend/app/admin/contest/page.tsx
apps/frontend/app/admin/course/[courseId]/assignment/page.tsx
apps/frontend/app/admin/course/[courseId]/exercise/page.tsx
apps/frontend/app/admin/course/[courseId]/user/_components/GroupTable.tsx
apps/frontend/app/admin/course/[courseId]/user/page.tsx
apps/frontend/app/admin/course/page.tsx
apps/frontend/app/admin/problem/page.tsx
apps/frontend/app/admin/problem/shared/page.tsx
apps/frontend/app/admin/user/page.tsx

페이지 제목 형식을 텍스트만 통일했습니다. 
- User
- Problem
- Course
- Course-Member
- Course-Assignment
- Course-Exercise
- Contest
Closes TAS-1779
기존 통일 형식은 다음과 같습니다.
1. (제목) XXXX(대문자) LIST
2. (소개) Here’s a xxxx(소문자) list you made
아래는 위 통일 형식에서 벗어나는 예외들입니다.
* User
부제는 추가하지 않았습니다.
=> 개발자만 보는 페이지이므로
* Problem → Shared Problem
부제 부분 변경본이 "Here's a problem list shared in other courses."인데 문법적으로 어색한가요?
* Course → Member
기존 : "Here’s a list of the instructors and members of the course"
변경본 : "Here’s a list of the instructors and students of the course"
⇒ member = instructor + student 이므로 표현을 더 정확하게 했습니다.
⇒ you made는 아니니까 뺐습니다.
---

chore(fe): unify management title text

---

apps/frontend/components/StatusTimeDiff.tsx

> [!NOTE]  
> 과제 제출 멘트가 과제 마감 이후에도 starts in으로 나오는 부분을 Submission ended로 수정하였습니다.
closes TAS-1744
---

fix(fe): fix submission message

---

apps/frontend/app/(client)/(code-editor)/_components/EditorLayout.tsx
apps/frontend/types/type.ts

테스트케이스 DB -> S3 마이그레이션 때문에 생긴 테스트케이스 순서 이슈를 해결합니다.
(문제 상황)
(해결)
---
Closes TAS-1867

fix(fe): resolve testcaseTable sample-testcase ordering issue

---

apps/frontend/app/(client)/(main)/_components/Modal.tsx
apps/frontend/app/(client)/(main)/_components/ModalInput.tsx
apps/frontend/app/(client)/(main)/course/_components/RegisterCourseButton.tsx
apps/frontend/components/shadcn/button.tsx

> [!CAUTION]
> Modal 컴포넌트는 아직 완성본이 아닙니다. 우선 Course Registration 모달이라도 잘 반영할 수 있을 만큼 구현하였고, addition이 길어서 승인 받으면 이후 다른 버전도 구현하여 적용할 예정입니다.
Design Guide에 있는 Modal 소/중/대 컴포넌트를 만드는 중입니다.
우선 Course Registration 모달에 만든 컴포넌트를 적용해보았습니다.
---
closes TAS-1872

refactor(fe): use refactored Modal for course registration flow

---

apps/backend/apps/admin/src/problem/services/problem.service.ts

문제 생성 시 solution(풀이) 필드가 누락되어 있던 것을 추가하여, 문제를 생성할 때 풀이 정보도 함께 저장되도록 수정하였습니다.
---

fix(be): add solution field to problem creation

---

apps/frontend/app/(client)/(main)/_components/InstagramCards.tsx
apps/frontend/app/(client)/(main)/_components/MiddleContestBanner.tsx
apps/frontend/app/(client)/(main)/_components/NewProblemCards.tsx
apps/frontend/app/(client)/(main)/_components/ServiceCards.tsx
apps/frontend/app/(client)/(main)/page.tsx

메인페이지를 여러 명이서 작업 중입니다.
충돌을 방지하기 위해 빈 컴포넌트를 만들어 넣었습니다.
---
closes tas-1880

chore(fe): make empty components to prevent crash

---

apps/backend/apps/admin/src/assignment/assignment.resolver.ts
apps/backend/apps/admin/src/assignment/assignment.service.ts
apps/backend/libs/auth/src/guard.decorator.ts
apps/backend/libs/auth/src/roles/group-leader.guard.ts
apps/backend/package.json
collection/admin/login.js
collection/instructor/Assignment/Get Belonged Assignments by Problem ID/Succeed.bru
collection/instructor/login.js
pnpm-lock.yaml
pnpm-workspace.yaml

getAssignmentsByProblemId에서 @UseGroupLeaderGuard() 전역 적용으로 인한 Forbidden Resource 에러가 생겼습니다.
특정 메서드에서 GroupLeaderGuard를 비활성화할 @UseDisableGroupLeaderGuard() 데코레이터가 없어서 발생하였습니다. 
UseDisableGroupLeaderGuard를 UseDisableAdminGuard와 동일한 패턴으로 구현하여 해결하였습니다.
---
closes TAS-1893

feat(be): impl UseDisableGroupLeaderGuard

---

apps/backend/apps/client/src/auth/auth.service.ts
apps/backend/libs/auth/src/jwt/jwt.interface.ts

JWT Token에 user의 role을 추가합니다.
추가된 payload
access_token
refresh_token
---
Closes TAS-1950

feat(be): add user role in JWT token

---

apps/backend/apps/admin/src/group/group.service.spec.ts
apps/backend/apps/admin/src/user/user.service.spec.ts
apps/backend/apps/admin/src/user/user.service.ts
apps/backend/apps/client/src/auth/auth.service.spec.ts
apps/backend/apps/client/src/group/mock/group.mock.ts
apps/backend/apps/client/src/submission/test/submission.service.spec.ts
apps/backend/apps/client/src/user/dto/signup.dto.ts
apps/backend/apps/client/src/user/dto/social-signup.dto.ts
apps/backend/apps/client/src/user/dto/updateUser.dto.ts
apps/backend/apps/client/src/user/user.service.spec.ts
apps/backend/apps/client/src/user/user.service.ts
apps/backend/libs/auth/src/jwt/jwt-auth.service.spec.ts
apps/backend/libs/auth/src/roles/roles.service.spec.ts
apps/backend/prisma/migrations/20250815081851_add_affirmation_to_user/migration.sql
apps/backend/prisma/migrations/20250818150736_add_college_to_user/migration.sql
apps/backend/prisma/schema.prisma
apps/backend/prisma/seed.ts
apps/frontend/libs/constants.ts
collection/client/User/Sign Up/Succeed.bru
collection/client/User/Update User/Optionally update.bru
collection/client/User/Update User/Update All Fields of User.bru
collection/client/User/Update User/[401] Incorrect current password.bru
collection/client/User/Update User/[422] current password needed to change password.bru

User 테이블에 사용자 단과대학 필드를 추가합니다.
https://www.notion.so/skkuding/250ef9cff54580da94eaca7a6cc70f8e
1. 프론트 작업 시작하면서 단과대학-학과 맞게 연결시켰는지 교차검증 한 번만 부탁드립니다 !
2. 프론트 작업 후에 기존 학과 리스트(majors)는 삭제해주세요~
---

feat(be): add affiliation column

---

apps/backend/apps/client/src/contest/contest.service.ts

getContestQnA에서 comments에 username을 포함하여 반환합니다.
---
Closes TAS-2024

chore(be): add username in comments

---

apps/backend/apps/admin/src/assignment/assignment.service.ts
collection/instructor/Assignment/Get Belonged Assignments by Problem ID/Succeed.bru

Problem이 어떤 Assignment/Exercise에 속해있는지 보여주는 API입니다.
과목 정보까지 가져오도록 수정합니다.
---
Closes TAS-1998

feat(be): add courseInfo to getAssignmentsByProblemId

---

apps/backend/apps/client/src/contest/contest.service.ts
apps/backend/apps/client/src/contest/dto/contest-qna.dto.ts
collection/client/Contest/Get Contest QnAs/Succeed.bru

get Contest QnAs에서 검색 필터를 추가합니다.
---
Closes TAS-2034

feat(be): add search filter in contestQnA

---

apps/k8s/argocd/applications/admin-api.yaml
apps/k8s/argocd/applications/argocd.yaml
apps/k8s/argocd/applications/client-api.yaml
apps/k8s/argocd/applications/frontend-preview.yaml
apps/k8s/argocd/applications/frontend.yaml
apps/k8s/argocd/applications/internal.yaml
apps/k8s/argocd/applications/iris.yaml
apps/k8s/argocd/applications/minio-stage.yaml
apps/k8s/argocd/applications/postgres-stage.yaml
apps/k8s/argocd/applications/rabbitmq.yaml
apps/k8s/argocd/applications/redis.yaml

Argo CD UI에서 application들을 filtering할 수 있도록 label을 추가합니다.
---

chore(infra): add labels to argocd apps for filtering

---

apps/backend/apps/admin/src/assignment/assignment.service.ts
pnpm-workspace.yaml

fix(be): do no allow autoFinalizeScore before dueTime

---

apps/k8s/admin-api/base/deployment.yaml
apps/k8s/client-api/base/deployment.yaml
apps/k8s/iris/overlays/stage/kustomization.yaml

지금 3번 서버 하나에 preview + stage가 배포된 상태라 리소스 사용량을 아껴봅시다...
---

fix(infra): allocate fewer resource to stage pods

---

apps/frontend/app/admin/course/_components/CourseFormFields.tsx
apps/frontend/app/admin/course/_components/CreateCourseButton.tsx
apps/frontend/app/admin/course/_components/CreateCourseForm.tsx
apps/frontend/app/admin/course/_components/InputForm.tsx
apps/frontend/app/admin/course/_components/UpdateCourseButton.tsx
apps/frontend/app/admin/course/_libs/schema.ts
apps/frontend/components/Modal.tsx

학수번호 정책에 따라 바꾸고, 디자인 edit course에도 반영하고, 리팩토링 좀 했습니당
취중코딩 폼 미쳤다....
---

feat(fe): change course code system

---

apps/backend/libs/instrumentation.ts
apps/infra/production/dns/.terraform.lock.hcl
apps/infra/production/dns/grafana.tf
apps/infra/production/dns/monitoring.tf
apps/infra/stage/server2/Caddyfile
apps/iris/src/instrumentation.go
apps/k8s/admin-api/base/configmap.yaml
apps/k8s/client-api/base/configmap.yaml
apps/k8s/iris/base/configmap.yaml

현재 배포 직전이라 로그 수집이 매우 중요합니다.
임시로 2번 서버에 구축된 모니터링 스택에 연결합니다.
---

fix(infra): connect monitoring

---

apps/k8s/argocd/applications/monitoring/loki.yaml
apps/k8s/monitoring/loki/values.yaml

로그 백엔드인 Loki를 [공식 Grafana Chart](https://artifacthub.io/packages/helm/grafana/loki)를 사용하여 배포합니다.
Closes TAS-2019
---

feat(infra): setup loki

---

apps/backend/apps/admin/src/notice/notice.resolver.ts
apps/backend/apps/admin/src/notice/notice.service.spec.ts
apps/backend/apps/admin/src/notice/notice.service.ts
apps/backend/apps/admin/src/notification/notification.listener.ts
apps/backend/apps/admin/src/notification/notification.service.spec.ts
apps/backend/apps/admin/src/notification/notification.service.ts

공지 알림 기능 구현입니다
---
Closes TAS-2082

feat(be): implement notice notification

---

apps/k8s/admin-api/overlays/stage/cors-middleware.yaml
apps/k8s/admin-api/overlays/stage/ingress.yaml
apps/k8s/admin-api/overlays/stage/kustomization.yaml
apps/k8s/client-api/overlays/stage/cors-middleware.yaml
apps/k8s/client-api/overlays/stage/ingress.yaml
apps/k8s/client-api/overlays/stage/kustomization.yaml

Caddyfile과 마찬가지로, [Traefik middleware](https://doc.traefik.io/traefik/reference/routing-configuration/http/middlewares/overview/)를 활용해서 CORS 적용하였습니다.
> annotation으로 붙인 middleware를 계속 Traefik이 못 찾아서 개고생했는데... `<namespace>-<name>@<provider>` 형태로 해야된다고 합니다. 꼭 확인해보시길... ~~열받음~~
> https://community.traefik.io/t/how-to-configure-middleware-with-kubernetes-ingress-middleware-xyz-does-not-exist/5016/5
---

fix(infra): apply cors rules to stage api server

---

apps/backend/apps/admin/src/contest/contest.service.ts
collection/admin/Contest/Get Contest QnA/Succeed.bru

getContestQnA에 username과 comments를 추가합니다.
getContestQnAs에 username을 추가합니다.
---
Closes TAS-2095

chore(be): add username and comments in get Contest QnA/QnAs of admin module

---

apps/frontend/app/(client)/(main)/notice/layout.tsx

feat(fe): implement responsive notice page for mobile

---

apps/frontend/app/admin/course/[courseId]/_components/AssignmentSolutionColumns.tsx
apps/frontend/app/admin/course/[courseId]/_components/AssignmentSolutionTable.tsx
apps/frontend/components/shadcn/date-time-picker-demo.tsx

create/edit assignment에서 solution이 있는 문제의 공개 option을 manually로 선택했을 때 무한 에러가 발생하며 화면이 멈추는 문제를 해결합니다. 
date time picker 자체를 수정해서 다른 페이지에 영향이 갈 게 있는지 확인해 봐야 할 듯합니다.
closes TAS-2100
---

fix(fe): fix solution manually infinite error

---

apps/k8s/argocd/applications/monitoring/otel-collector.yaml

otel collector 배포 대상을 고쳤습니다.
---

fix(infra): correct path in otel-collector configuration

---

apps/backend/apps/admin/src/assignment/assignment.service.ts
collection/instructor/Assignment/Get Belonged Assignments by Problem ID/Succeed.bru

chore(be): add groupId to getAssignmentsByProblemId

---

apps/infra/production/dns/monitoring.tf
apps/k8s/monitoring/grafana/values.yaml

feat(infra): launch grafana.codedang.com

---

apps/backend/apps/admin/src/notification/notification.service.ts
apps/backend/package.json
pnpm-lock.yaml

렌더링 해야하는 태그는 전부 제거
사용자가 명시적으로 입력한 태그는 디코딩
---

fix(be): sanitize push notification message

---

apps/backend/apps/client/src/assignment/assignment.service.ts
apps/backend/apps/client/src/problem/problem.service.spec.ts

fix(be): allow get assignment and problem before startTime for instructor

---

apps/frontend/app/(client)/(main)/course/[courseId]/_components/AssignmentAccordion.tsx
apps/frontend/app/(client)/(main)/course/[courseId]/_components/AssignmentLink.tsx
apps/frontend/app/(client)/(main)/course/[courseId]/_components/ExerciseAccordion.tsx
apps/frontend/app/(client)/(main)/course/[courseId]/assignment/[assignmentId]/_components/Columns.tsx
apps/frontend/app/(client)/(main)/course/[courseId]/assignment/[assignmentId]/page.tsx
apps/frontend/app/(client)/(main)/course/[courseId]/exercise/[exerciseId]/page.tsx

instructor는 assignment나 exercise가 시작되지 않았을 때에도 세부 페이지를 들어가 문제 목록을 확인할 수 있게 합니다.
closes TAS-2124
---

feat(fe): allow instructor access assignment before start time

---

apps/frontend/app/(client)/(main)/page.tsx

main page gap을 피그마에 맞게 수정했습니다!
메인페이지!
---

chore(fe): edit main page gap

---

apps/frontend/app/admin/problem/[problemId]/edit/_components/EditProblemForm.tsx
apps/frontend/app/admin/problem/[problemId]/edit/page.tsx

https://github.com/skkuding/codedang/commit/31d6927656263afdf8e56b4c5078d27c3f39be3a 에서 제출이 존재하는 testcase의 수정을 허용하는 코드가 반영되지 않은 채로 release에 배포되어 현재 main 브랜치와 차이가 존재합니다. 이를 hotfix로 해결합니다.
---

fix(fe): hotfix incorrect merge

---

.github/workflows/ci.yml

```sh
Starting minio service container
/usr/bin/docker pull bitnami/minio:latest
Error response from daemon: manifest for bitnami/minio:latest not found: manifest unknown: manifest unknown
Warning: Docker pull failed with exit code 1, back off 9.827 seconds before retry.
/usr/bin/docker pull bitnami/minio:latest
Error response from daemon: manifest for bitnami/minio:latest not found: manifest unknown: manifest unknown
Warning: Docker pull failed with exit code 1, back off 5.194 seconds before retry.
/usr/bin/docker pull bitnami/minio:latest
Error response from daemon: manifest for bitnami/minio:latest not found: manifest unknown: manifest unknown
Error: Docker pull failed with exit code 1
```
또 `bitnami/minio` 이미지가 말썽입니다.
정책상 `latest` 태그는 남겨 놓을 거라고 했는데 오늘 갑자기 해당 태그가 Docker hub 에서 …

fix(infra): replace bitnami/minio with lazybit/minio

---

infra/k8s/argocd/applications/monitoring/tempo.yaml
infra/k8s/monitoring/grafana/values.yaml
infra/k8s/monitoring/otel-collector/otel-collector.yaml
infra/k8s/monitoring/tempo/values.yaml

production의 tempo trace monitoring을 k8s기반으로 포팅 합니다.
otel collector에서 grpc프로토콜 port 4317번으로 tempo 컨테이너에게 데이터를 전송하고 tempo컨데이너는 http프로토콜 port 3200번으로 grafana 컨테이너에게 처리된 데이터를 전송합니다.
현재 trace 데이터는 컨테이너 로컬 db에 저장되어 있으나, 추후 별개의 minio컨테이너(log및 metric도 관리함)에 저장하여 관리할 계획입니다.
---

feat(infra): tempo k8s monitoring

---

apps/frontend/app/(client)/(main)/course/[courseId]/_components/AssignmentAccordion.tsx
apps/frontend/app/(client)/(main)/course/[courseId]/_components/ExerciseAccordion.tsx

https://github.com/skkuding/codedang/pull/3182
위 PR에서 각 problem과 대응되는 제출내역(Last submission)을 찾아 보여주는 작업을 했었는데요!
이번에는 제출내역(CompileError/Accepted/NoResult) 도 problem과 대응되는걸로 연동해놨어요!
이렇게 problemSubmission를 선언해서 두 곳에서 같이 쓰도록 해놨습니다.
자잘자잘한 수정사항은 다음과 같습니다.
- 과제/실습 없으면 빈 화면 대신 없다는 문구를 보여줌
- 아코디언에서 정렬이 안된 부분이 있어서 정렬 시켜놨습니다! <- addition/deletion 대부분 차지(내용적 수정은 없습니다)
---

fix(fe): match submission badge with according problem
