skkuding/codedang

.github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md
Contributing guideline과 code of conduct를 추가합니다.
정형화된 workflow를 갖춰 git의 활용도와 생산성을 높입니다.
Closes #3
---
=> docs: add contributing guideline

frontend/package.json, frontend/src/main.ts, pnpm-lock.yaml
pinia를 client store로 사용합니다. 
현재 store로 사용할만한 예제가 없어서 포함하지 않았지만, modular architecture pattern을 따르기 위해서는 모듈 안 stores 디렉토리를 만들고나서 client store를 정의합니다. [Example](https://github.com/shamscorner/vitesse-stackter-clean-architect/blob/de720ff76b89d01af235f53fc4fb01d160422396/src/orders/stores/order.ts)
closes #23
SSR을 사용할 경우 세팅에 있어서 변경이 필요합니다.
---
=> feat(fe): use pinia as client store

backend/prisma/migrations/20220620162501_basic_plan/migration.sql, backend/prisma/schema.prisma
기획 단계에서 도출된 [ERD diagram](https://www.erdcloud.com/d/jHCbTNnSieZSbPLDG)을 `schema.prisma`에 반영합니다.
Closes #56 
- `created_by` field는 `create_time`, `update_time`과 같은 metadata입니다. `OnDelete: SetNull` 옵션을 적용했습니다.
- [PostgreSQL과 Prisma model의 DB naming convention](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/use-custom-model-and-field-names)이 달라 `@@map` 을 사용해 table 이름을 직접 지정하였습니다.
- 지금까지 도출된 ERD diagram을 반영한 것으로 개발 과정에서 언제든지 수정될 수 있습니다.
- 문제은행 관련 테이블은 확정되지 않아 제외하였습니다.
---
=> chore(be): sync schema.prisma with ERD diagram

frontend/src/common/components/Atom/PageSubtitle.vue, frontend/src/common/components/Atom/PageTitle.vue, frontend/tailwind.config.js
- PageTitle, PageSubtitle component 구현
closes #73 
closes #92 
- 사용하려는 상위 컴포넌트에서 text props로 title 명을 전달해줍니다.
=> feat(fe): add pagetitle component

lefthook.yml, package.json, pnpm-lock.yaml, scripts/setup.sh
Resolves #44
기존 issue에서는 lint-staged를 사용하려고 했지만, lefthook이라는 라이브러리가 속도도 빠르고 기능도 다양해서 대신 사용했습니다.
lefthook repo: https://github.com/evilmartians/lefthook
---
=> feat: use lefthook to create git hooks

frontend/src/common/components/Molecule/CardItem.vue
- 반응형 CardItem 구현
close #69 
화면 크기 > 768px 일때
화면크기 <= 768 일때
- props 속성 ----- 수정되었습니다. 7월 3일
- borderColor (string) : border 색상 (green, gray)
- img (string) : image 경로
- title (string) : 왼쪽위에 위치할 글 -- bold 글씨
- additionalText (string) : 오른쪽 위에 위치할 글
- description (string) : 왼쪽 아래에 위치할 글 -- 회색 글씨
- coloredText (string) : 화면크기 768초과 일때 오른쪽 아래에 위치할 글 -- 초록 글씨
- coloredTextShort (string) : 화면크기 768이하일때 오른쪽 아래에 위치할 글 -- 초록 글씨
- 사용 예시 ----- 수정되었습니다. 7월 3일
```
<CardItem
border-color="gray"
img="/favicon.ico"
title="SKKUDING"
additional-text="Member: 23"
description="SKKU 코딩 플랫폼 개발 동아리입니다."
colored-text="Created by 하설빙"
colored-text-short="By 하설빙"
/>
```
---
=> feat(fe): add card-item component

frontend/env.d.ts, frontend/histoire.config.ts, frontend/package.json, frontend/src/common/components/Atom/AtomComponent.vue, frontend/src/common/components/Atom/PageSubtitle.story.vue, frontend/src/common/components/Atom/PageTitle.story.vue, frontend/src/common/components/Molecule/CardItem.story.vue, frontend/src/common/components/Molecule/MoleculeComponent.vue, frontend/src/histoire.css, frontend/src/histoire.setup.ts, pnpm-lock.yaml
Resolves #98 
Histoire를 이용해 Vue component 전용 문서를 만듭니다.
`/frontend` 디렉토리에서 `pnpm story` 명령어로 실행해볼 수 있습니다.
Histoire 문서: https://histoire.dev/
추후 작성 시 [Storybook 공식 예시](https://storybooks-official.netlify.app/)를 참고해서 만들면 좋을 것 같습니다.
---
=> feat(fe): use histoire for component documentation

frontend/src/common/components/Molecule/ProgressCard.story.vue, frontend/src/common/components/Molecule/ProgressCard.vue
워크북의 진행 상황을 나타내기 위한 card progress 구현
closes #78
closes #75
```
<ProgressCard
title="프로그래밍대회"
header="updated 3.30"
description="프로그래밍대회 기출문제 입니다."
type="problem"
total="10"
complete="6"
/>
```
---
=> feat(fe): add progress card component

frontend/src/common/components/Molecule/Tab.story.vue, frontend/src/common/components/Molecule/Tab.vue
tab component 구현
closes #77 
1. tab 항목들을 items라는 props로 Tab component로 전달합니다.
2. tab의 색상을 커스텀하는 경우에는 color props로 전달합니다. 
(group detail page에서는 해당 그룹에 해당하는 색깔에 맞춰 tab을 custom할 수 있습니다)
3. page에서 각 item에 해당하는 컴포넌트를 template으로 작성해주면 됩니다.
```
<Tab :items="items">
<template #notice>
notice
<detail /> // notice 버튼을 누르면 detail component가 tab 밑에 표시됩니다.
</template>
<template #contest>
contest
<contest />
</template>
</Tab>
```
tab component의 경우에는 사용자가 색상을 선택하여 적용해야 하기 때문에 동적으로 스타일을 적용할 수 있어야 합니다. 하지만 tailwind css에서는 동적으로 스타일을 적용할 수 없기 때문에 inline style으로 적용하였습니다. 
이 컴포넌트의 경우에는 사용자가 선택할 수 있는 모든 색상에 대해 config파일에 지정해둘 수 없기 때문에 safelist에 해당 스타일을 작성해두거나, 객체로 스타일을 적용하는 경우는 불가능하였습니다.
---
=> feat(fe): add tab component

backend/src/app.module.ts, backend/src/auth/auth.controller.spec.ts, backend/src/auth/auth.controller.ts, backend/src/auth/guard/jwt-auth.guard.ts, backend/src/common/decorator/public.decorator.ts, backend/src/common/decorator/roles.decorator.ts, backend/src/user/guard/roles.guard.ts, backend/tsconfig.json
`user`의 `role`을 기반으로 API 호출 권한을 확인하는 Guard를 구현합니다.
- `RolesGuard`를 사용하려면 `UserModule`을 import해야 합니다. 
-  `RolesGuard`를 사용하려면 아래 예시 코드처럼 해당 handler 또는 controller class에 `@UseGuards(RolesGuard)`, `@Roles(<Role Type>)`을 추가해야 합니다.
- handler(method)의 `@Roles`가 class의 `@Roles`보다 우선순위가 높습니다. class에 `@Roles(Role.SuperAdmin)`이 적용되어도 handler에 `@Roles(Role.GroupAdmin)`이 적용되었다면 해당 handler는 `GroupAdmin` 이상의 권한을 가진 모든 user가 접근이 가능합니다. 
- Role은 계층 구조를 가집니다(`User < GroupAdmin < SuperManager < SuperAdmin`)
```typescript
// example code
import { Controller, Get, UseGuards } from '@nestjs/common'
import { Role } from '@prisma/client'
import { Roles } from 'src/common/decorator/roles.decorator'
import { RolesGuard } from 'src/user/guard/roles.guard'
import { ExampleService } from './example.service' …
```
=> feat(be): implement role-based guard

frontend/src/common/components/Atom/Popover.story.vue, frontend/src/common/components/Atom/Popover.vue
어떤 요소를 click / hover 했을 때 나타나는 popover 구현
close #125 
close #135 
- `text` prop로 popover에 나타낼 text 내용을 작성하고, `content-id`에 hover/click 대상의 id값을 작성합니다.
- template content에 hover/click 대상을 작성합니다.
- `hover`를 prop으로 주어지면 content 내의 대상을 hover했을 때 popover가 trigger되고, `hover` prop이 주어지지 않으면 click 했을 때 trigger 됩니다.
```
<Popover
text="this is popover"
content-id="#pop"
hover
>
<template #content>
<Button id="pop">Button</Button>
</template>
</Popover>
```
---
=> feat(fe): add popover component

backend/src/auth/class/authenticated-user.class.ts, backend/src/auth/interface/authenticated-request.interface.ts, backend/src/auth/interface/authenticated-user.interface.ts, backend/src/auth/strategy/jwt.strategy.ts, backend/src/contest/contest-admin.controller.ts, backend/src/contest/contest.module.ts, backend/src/contest/dto/create-contest.dto.ts, backend/src/contest/dto/update-contest.dto.ts, backend/src/group/guard/group-manager.guard.ts, backend/src/group/guard/group-member.guard.ts, backend/src/notice/notice-admin.controller.ts, backend/src/notice/notice.controller.ts, backend/src/user/guard/roles.guard.ts
Resolves #171 
- RolesGuard에서 request.userRole을 추가합니다.
- GroupMemberGuard와 GroupManagerGuard에서 request.userRole을 확인해 superAdmin또는 superManager이면 true를 반환하도록 합니다.
- 기존 controller에 적절한 guard를 적용합니다.
- request.user.role 이런식으로 값을 추가할 수가 없어서(error: cannot set undefined attribute) request.userRole을 추가했습니다.
- **superAdmin 또는 superManager임을 확인하기 위한것이라면, RolesGuard에서 userRole 대신 isSuperUser 같은 boolean 값을 추가해주는게 더 좋을까요???**
---
=> chore(be): refactor roleGuard and group guards

backend/src/contest/contest.module.ts, backend/src/notice/notice.controller.ts
Resolves #184 
contest module에 usermodule이 import되지 않아 발생하는 "Can't resolve dependencies" 에러를 해결합니다.
---
=> fix(be): import usermodule in contest module

backend/prisma/migrations/20220925061759_unique_group_name/migration.sql, backend/prisma/schema.prisma
> Fixes #239
- 그룹 테이블의 `groupName` 필드에 unique attribute를 추가했습니다.
- #198 PR에서 중복 name이 제출되었을 경우에 대한 핸들링이 필요합니다.
---
=> chore(be): add unique attribute to group name field

frontend/env.d.ts, frontend/package.json, frontend/src/App.vue, frontend/src/common/components/Organism/Sidebar.vue, frontend/src/common/layouts/admin.vue, frontend/src/common/layouts/default.vue, frontend/src/common/layouts/empty.vue, frontend/src/main.ts, frontend/src/user/home/components/Carousel.vue, frontend/src/user/home/pages/index.vue, frontend/src/user/problem/pages/index.vue, frontend/vite.config.ts, pnpm-lock.yaml
Closes #212 
vite-plugin-vue-layouts plugin을 이용해서 layout을 만듭니다.
https://github.com/JohnCampionJr/vite-plugin-vue-layouts
`common/layouts` folder 안에 layout 파일을 만들고, 페이지 파일에서 원하는 layout을 지정합니다.
따로 layout을 지정하지 않으면 default.vue가 layout으로 적용됩니다.
```vue
<template>
...
</template>
<route lang="yaml">
meta:
layout: empty
</route>
```
---
=> feat(fe): add page layout

.gitpod.yml
GitPod의 Volar plugin(Vue Language Server)이 최신 버전이 공식적으로 올라오지 않아 language service가 충돌되는 문제가 있습니다.
비공식적으로 올라온 Volar plugin을 임시로 사용하고, 추후 문제가 해결되면 다시 공식 버전을 사용합니다.
공식 버전(0.30.1): https://open-vsx.org/extension/johnsoncodehk/volar
비공식 버전(0.40.6): https://open-vsx.org/extension/lukashass/volar
---
=> fix: use the latest volar plugin in gitpod

.gitpod.yml
GitPod에서 Vue extension(Voalr)이 제대로 동작하지 않는 문제를 해결합니다.
기존에 workaround로 사용한 비공식 버전(0.x.x) 대신, 최근 release된 정식 버전(1.x.x)을 사용합니다.
More info: #255 
---
=> fix: use official vue extension for gitpod

backend/prisma/schema.prisma
@typescript-eslint/naming-convention rule에 따라 object key가 camelCase를 따르도록 설정되어있습니다.
불가피한 경우 `// eslint-disable` 주석으로 비활성화하고 있지만, Prisma Schema에서 다른 model을 참조하는 field name들은 PascalCase에서 camelCase로 수정해도 무관한 것 같습니다.
---
=> fix(be): edit foreign field name to camel case

backend/src/contest/contest-admin.controller.ts, backend/src/contest/contest.service.spec.ts, backend/src/contest/contest.service.ts, backend/src/notice/notice-admin.controller.ts, backend/src/notice/notice.service.spec.ts, backend/src/notice/notice.service.ts
> Closes #345 
- User, Manager는 Admin 페이지에 접근할 수 없습니다.
- 페이지에서 보여지는 모든 레코드는 Open Space의 레코드입니다.
- 특정 그룹을 관리하기 위해서는 My Groups 페이지를 방문하여 관리 페이지를 열어야 합니다.
---
=> feat(be): expel manager from admin page

frontend/src/user/notice/composables/notice.ts, frontend/src/user/notice/pages/[id].vue, frontend/src/user/notice/pages/index.vue
notice list 페이지의 api를 연결했다.
close #320 
pagination 숫자가 바뀌면 다음 10개의 notice list를 가져오도록 했다.
추후에 numberOfPages를 api에서 가져오면 수정할 예정이다.
=> feat(fe): connect notice list page api

backend/src/auth/auth.controller.ts, backend/src/auth/guard/jwt-auth.guard.ts, backend/src/common/decorator/auth-ignore.decorator.ts, backend/src/common/decorator/public.decorator.ts, backend/src/contest/contest.controller.ts, backend/src/notice/notice.controller.ts, backend/src/user/user.controller.ts, backend/src/workbook/workbook.controller.ts
Closes #366 
- public.decorator.ts에 정의되어있었던 Public 데코레이터 이름을 AuthNotNeeded로 변경합니다.
- Public은 '대중의', '대중을 위한', '공공의'라는 뜻을 가진 형용사입니다. (출처: 옥스포드 영한사전)
- Authentication 유효성을 검증하는 기능과 데코레이터 이름이 일치하지 않아 혼란을 야기합니다.
- 파일 이름도 auth-ignore.decorator.ts로 변경합니다.
---
=> refactor: change decorator name 'Public' to 'AuthNotNeeded'

backend/nest-cli.json
Fixes #368 
- email template을 dist/src/email/templates에서 찾고 있는데 dist/email/templates에 복사되는 문제가 있었습니다.
- nest-cli.json에서 `"outDir": "dist/src"`옵션을 주어 해결했습니다.
---
=> fix: specify output directory in nest-cli.json

.github/workflows/ci.yml
#192 에서 구현한 CI에서의 pull request 제목 lint가 main branch에 push되었을 경우에도 실행됩니다.
main branch에 push할 경우 pull request 제목이 존재하지 않아 CI가 실패합니다.
pull request에서만 해당 CI hook을 실행하도록 수정합니다.
참고: https://github.com/skkuding/next/actions/runs/4142147317/jobs/7162474079
---
=> fix(ci): lint pr message only on pull request

backend/src/common/cache/cacheConfig.service.ts
GitPod 환경에서 redis에 연결이 되지 않는 문제를 해결합니다.
#278 에서 환경변수(`CACHE_DATABASE_PORT`) 이름에 생긴 오타를 수정합니다.
```
$ pnpm start
> backend@ start /workspace/codedang/backend
> nest start
[Nest] 3442  - 02/14/2023, 6:21:10 AM     LOG [NestFactory] Starting Nest application...
[Nest] 3442  - 02/14/2023, 6:21:10 AM     LOG [InstanceLoader] MailerModule dependencies initialized +43ms
[Nest] 3442  - 02/14/2023, 6:21:10 AM     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
[Nest] 3442  - 02/14/2023, 6:21:10 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 3442  - 02/14/2023, 6:21:10 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 3442  - 02/14/2023, 6:21:10 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms …
```
=> fix(be): fix typo of cache port environment variable

backend/src/auth/guard/jwt-auth.guard.ts, backend/src/common/decorator/auth-ignore.decorator.ts
Close #386 
`@AuthNotNeeded` decorator를 사용하지 않는 endpoint에서 authentication이 이루어지지 않습니다.
#367 에서 추가된 IS_AUTH_NEEDED_KEY의 metadata가 false로 변경되었는데, JwtAuthGuard에서 reflector가 반환하는 undefined와 false가 모두 negation 후 true를 반환합니다.
---
=> fix(be): fix not working authentication

backend/.mocharc.json, backend/package.json
Closes #398 
mocha config 중 "spec" option이 CLI에서 준 custom directory를 override하여 적용되지 않는 문제가 있습니다.
예를 들어 config의 `"spec": ["*/**/*.spec.ts"]`을 적용하면, CLI에서 `mocha src/user/user.service.ts`를 실행해도 모든 파일(`*/**/*.spec.ts`)에 대해 test가 수행됩니다.
따라서 config의 spec option을 제거하고, package.json의 `"test"` script는 `mocha "*/**/*.spec.ts"`로 직접 경로를 지정합니다.
**결론: 앞으로는 `pnpm mocha src/user`처럼 경로 지정해서 테스트할 수 있습니다!**
간결한 mocha 출력을 위해 reporter를 변경하였습니다.
참고: https://mochajs.org/#reporters
---
=> feat(be): fix mocha config to give custom directory

backend/src/workbook/workbook-admin.controller.ts, backend/src/workbook/workbook.controller.ts, backend/src/workbook/workbook.service.spec.ts, backend/src/workbook/workbook.service.ts
workbook을 가져오는 api에 id, title만 가져오는 select option을 추가했습니다.
admin과 user이 같은 service를 사용하기 때문에 추후에 구분할 필요가 있을 것 같습니다.
(admin이 user보다 더 많은 정보를 요구할 수 있기 때문)
close #392 
---
=> chore(be): get selected field in workbook api

backend/src/group/group.controller.ts, backend/src/problem/problem.controller.ts
Group List GET API에 `@AuthNotNeeded` 데코레이터를 추가합니다.
=> chore(be): add auth-not-needed decorator

backend/src/common/exception/business.exception.ts, backend/src/group/group.controller.ts, backend/src/group/group.service.ts
이미 가입된 그룹에 가입 요청을 보낼경우
**EntityAlreadyExistException('Group join record')** 말고
**InternalServerErrorException()** 예외를 던집니다.
joinGroupById 메소드 내에 이미 가입한 그룹인지 판단하는 부분에서 `Array.includes()` 메소드를 사용하는데,
이를 `Array.some()` 메소드로 변경합니다.
=> fix(be): fix throw inappropriate exception

backend/src/workbook/workbook.service.spec.ts, backend/src/workbook/workbook.service.ts
Close #436
id 필드가 없으면 cursor-based pagination이 정상 작동할 수 없어 해당 필드를 반환 값에 추가합니다.
---
=> chore(be): add id field to workbook list

frontend/src/common/components/Organism/Header.vue
모바일 화면에서 스크롤 시  잘못된 헤더 위치를 수정했습니다.
close #370 
---
=> fix(fe): change header position on mobile screen

backend/apps/client/src/user/user.service.ts
Group module의 `getUserRole`에서 user가 존재하지 않을 경우 발생하는 error의 오타를 수정합니다.
---
=> chore(be): fix typo in error message

backend/apps/client/src/group/group.service.spec.ts, backend/apps/client/src/group/group.service.ts, backend/apps/client/src/group/interface/group-data.interface.ts, backend/apps/client/src/group/mock/group.mock.ts, thunder-tests/thunderclient.json
Closes #532
Joined Group GET API에서 각 그룹에 대한 사용자의 `isGroupLeader` 여부 정보를 포함하도록 코드를 수정합니다.  
---
=> fix(be): modify joined group api response to include group leader info

frontend/src/user/contest/pages/index.vue
contest main page에 upcoming, ongoing, finished contest들이 보이도록 API를 연결 했으며 로그인 상태에 따라 참여중인 contest가 보이도록 했습니다!
추후에 finished 쪽에는 pagination component를 추가해야 될 것 같습니다!
close #524 
---
=> fix(fe): connect API to contest main page

backend/apps/admin/src/admin.module.ts, backend/apps/admin/src/group/group.module.ts, backend/apps/admin/src/group/group.resolver.spec.ts, backend/apps/admin/src/group/group.resolver.ts, backend/apps/admin/src/group/group.service.spec.ts, backend/apps/admin/src/group/group.service.ts, backend/apps/admin/src/group/model/group.input.ts, backend/apps/admin/src/group/model/group.output.ts, backend/apps/admin/src/user/user.module.ts, backend/apps/admin/src/user/user.resolver.ts, backend/apps/admin/src/user/user.service.ts, backend/apps/client/src/group/mock/group.mock.ts, backend/apps/client/src/notice/notice.service.spec.ts, backend/apps/client/src/workbook/workbook-admin.controller.ts, backend/libs/auth/src/guard.decorator.ts, backend/libs/auth/src/index.ts, backend/libs/auth/src/jwt/auth-ignore.decorator.ts, backend/libs/auth/src/jwt/jwt-auth.guard.ts, backend/libs/auth/src/roles/group-leader.guard.ts, backend/libs/auth/src/roles/group-member.guard.ts, backend/libs/auth/src/roles/roles.guard.ts, backend/libs/pipe/src/cursor-validation.pipe.ts, backend/prisma/migrations/20230629103918_delete_is_deleted_field_from_group/migration.sql, backend/prisma/schema.prisma, backend/prisma/seed.ts, thunder-tests/collections/tc_col_codedang-admin-api.json, thunder-tests/collections/tc_col_codedang-client-api.json
> Closes #170
admin 앱에서 사용될 Group CRUD API를 개발합니다.
- `RolesGuard`와 `GroupLeaderGuard`, `GroupMemberGuard` 사이에 존재하던 dependency를 제거하였습니다.
- admin 앱의 글로벌 가드로 `JwtAuthGuard` 및 `GroupLeaderGuard`를 설정해두었습니다.
- `RolesGuard`를 적용해야 할 경우, `@UseRolesGuard(role?)` 데코레이터를 사용합니다.
+ (데코레이터에 인자를 주지 않았을 때) 디폴트 role은 `Role.Admin`입니다.
+ 해당 데코레이터 **사용 시 `GroupLeaderGuard`의 적용은 해제**됩니다.
+ `RolesGuard`와 `GroupLeaderGuard`가 동시 사용되는 use case가 없고, 오히려 `RolesGuard` 적용 시 `GroupLeaderGuard`가 해제되어야만 동작하는 use case만 존재하기 때문에 이와 같이 구현하였습니다.
+ (또 하나로 뭉치지 않으면 핸들러 하나에 데코레이터만 네 개가 붙게 되니까요😱!)
+ TODO: 이에 따라 `@Roles(role)` 데코레이터가 필요하지 않아졌는데, client 앱의 admin controller에서 해당 데코레이터를 사용하고 있는 코드가 있어서, 해당 부분들이 admin 앱으로 모두 옮겨지면 삭제하겠습니다.  
*❗Added on 23.07.02.*
- Admin이 모든 그룹을 조회할 수 있는 `getGroups` 핸들러는 **Open Space를 포함한 모든 그룹의 목록**을 …
=> feat(be): add admin group crud apis

frontend/src/admin/pages/[groupId]/contest/[id]/CreateNoticeModal.vue, frontend/src/admin/pages/[groupId]/contest/[id]/index.vue, frontend/src/admin/pages/[groupId]/workbook/index.vue
group admin contest page의 contest 섹션에서 create 버튼을 누르면 뜨는 modal 구현
close #542 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/610"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(fe): create contest notice modal

frontend/src/common/components/Molecule/Modal.vue, frontend/src/common/components/Organism/AuthModal.vue
Close #613
`@click` event 대신 `@mousedown` event를 이용해 클릭된 위치만 인식하도록 합니다.
`KeepAlive` component로 입력 상태를 유지합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/615"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: prevent modal closed on dragging

frontend/src/admin/pages/[groupId]/index.vue, frontend/src/admin/pages/index.vue, frontend/src/common/components/Organism/Sidebar.story.vue, frontend/src/common/components/Organism/Sidebar.vue, frontend/src/common/layouts/admin.vue
group admin에서 사이드바를 클릭했을 때 잘못된 경로로 이동해서 이 부분을 수정했다.
close #606 
원래는 toggle-group을 사용해서 group id를 넘겨주는 방식으로 구현할 예정이었다. 
그런데 admin에서 group card를 눌러서 group admin 으로 이동했을 때, 다시 뒤로 가기 버튼을 눌러 admin으로 돌아가면 group admin의 sidebar가 유지된다. 그래서 현재 url을 보고 group admin인 경우 해당 sidebar가 나오도록 했다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/614"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(fe): fix sidebar bug

backend/apps/client/src/group/group.service.spec.ts, backend/apps/client/src/group/group.service.ts, backend/apps/client/src/group/interface/group-data.interface.ts, backend/apps/client/src/group/mock/group.mock.ts, thunder-tests/collections/tc_col_codedang-client-api.json
Closes #629 
`getGroup`에서 현재 그룹에 가입되어 있는 상태라면 `config` 와 `isGroupLeader`를,
그룹에 가입되어 있지 않은 상태라면 `config` 를 추가적으로 반환하도록 합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/630"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(be): modify get group api

backend/apps/client/src/group/group.service.spec.ts, backend/apps/client/src/group/group.service.ts, backend/apps/client/src/group/interface/group-data.interface.ts, backend/apps/client/src/group/mock/group.mock.ts, thunder-tests/collections/tc_col_codedang-client-api.json
> Closes #658 
기존에 `GetGroup`에서 유저가 가입되지 않은 그룹에 대해서`config`를 반환하였지만,
`config` 전체가 아닌, 그 중에서 `allowJoinFromSearch` 여부를 반환해 groupJoinModal에서 join button을 띄울 수 있도록 합니다.
또한, `GetGroup` 에서 유저가 가입되지 않은 그룹에 대해 반환할때, `showOnList`가 `true` 인 그룹에 대해서만 정보를 Return할 수 있도록 했습니다. (기존에는 `allowFromSearch`가 `true` 인 그룹에 대해서 반환하였으나, `allowFromSearch`가 `false`인 그룹도 모달창을 띄울 수 있도록 수정하였습니다.)
또한, `GetGroup` api 에서 `isJoined` 필드를 추가했습니다. (그룹에 가입되어 있다면 `isJoined:true`, 가입되어 있지 않다면 `isJoined:false`를 반환합니다.)
++) `getGroup`, `getGroups`, `getJoinedGroups` 에서 `createdBy` field를 제거하였습니다.
config 에서는 4개의 옵션이 있습니다.
그중 `showOnList`, `requireApprovalBeforeJoin` 은 backend단에서 처리하기때문에 보여줄 필요가 없어서 제외하였습니다.
마찬가지로 `allowJoinWithURL` 또한 지금단계에서는 필요없는 정보라고 판단해 `allowJoinFromSearch` 만을 반환하도록 수정하였습니다.
---
<a …
=> feat(be): modify getGroup and getGroups API

infra/modules/codedang-infra/cloudfront.tf
Cloudfront의 SSL certificate로 codedang.com 전용 certificate만 사용합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/672"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: use acm certificate only

infra/modules/codedang-infra/s3.tf
Close #678 
파일 내용으로 MD5 hash를 만들어, S3의 기존 파일 내용과 비교합니다.
두 hash 값이 다르면 object를 다시 생성합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/680"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(cd): add etag to s3 object

frontend/src/common/components/Molecule/NewCard.vue, frontend/src/user/home/components/ContestItem.vue, frontend/src/user/home/pages/index.vue
- PC 화면
- <img width="1624" alt="Screenshot 2023-07-27 at 8 38 25 PM" src="https://github.com/skkuding/codedang/assets/50468628/67e7c0dd-a945-4072-a625-85205361b970">
- 모바일 화면
- <img width="726" alt="Screenshot 2023-07-27 at 8 38 36 PM" src="https://github.com/skkuding/codedang/assets/50468628/65900592-85f0-405b-9936-1263f9cee4c2">
- vueuse 활용하여 date 표시
- contest가 pending 상태일 때에는 process 바 미표시
close #668 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/674"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(fe): change card design in a home page

frontend/src/main.ts
Admin GraphQL API에서 auth 처리가 안되는 문제를 해결합니다.
GraphQL base url로 도메인을 명시하지 않도록 수정합니다!
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/704"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(fe): use internal base url for graphql

.github/workflows/devserver.yml, infra/dev/Caddyfile
Close #710 
Dev 서버 (dev.codedang.com)에서 index(/)를 제외한 나머지 경로에서 새로고침 시 404를 반환하는 에러가 발생하여 Caddyfile을 수정하였습니다. 
(추가) EC2 runner에서 용량 부족 문제가 발생하여 docker prune하는 코드를 추가하였습니다. 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/711"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: udpate Caddyfile to handle reload

backend/apps/admin/src/main.ts, backend/apps/admin/src/problem/problem.resolver.ts
ValidationPipe가 admin 앱에 전역으로 걸려 있어, 오브젝트 타입 input에서 class-validator의 validation 데코레이터가 달려있지 않은 모든 필드가 지워지고 있었습니다(...) 필요한 핸들러에만 파이프를 달아 문제를 해결합니다.
GraphQL에서 MIME Type을 validation할 수 있는 타입을 제공한다면 나중에 GraphQL Input Type을 활용하도록 바꾸는 것도 괜찮을 것 같습니다!
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/726"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(be): remove validation pipe from admin-global pipe

backend/package.json, pnpm-lock.yaml
node-argon2 0.31.0의 release에 arm build가 포함되어있지 않아, downgrade합니다.
https://github.com/ranisalt/node-argon2/releases/tag/v0.31.0
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/766"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: downgrade argon2

frontend/src/common/store/auth.ts
#779 에서 반영된 CORS 세팅을 frontend에도 반영하기 위해 axios의 `withCredentials` option을 enable합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/788"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(fe): enable cookie in local developement

frontend/src/common/components/Organism/PaginationTable.vue, frontend/src/user/home/components/ContestItem.vue
- contest 게시판에 date가 이상하게 표현되는 거 고침
- computed는 Ref로 반환해서 .value를 붙여야 했는데 안 붙여서 생겼던 오류
- 추가로 pagination table에 type error 떠서 수정함(issue에 관련 없지만 사소한 오류라서 같이 PR 올림)
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/787"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(fe): contest item display a wrong date string

frontend/src/user/problem/pages/[id]/index.vue
- 문제 설명에 제한 조건 표시
- margin top -> gap으로 변경
close #791 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/792"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(fe): display problem limit information

infra/modules/codedang-infra/redis.tf
Deploy Action에서 발생한 Error를 해결합니다. 
Elasticache 의 log delivery configuration를 변경하기 위해서 apply-immediately parameter 설정합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/798"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(infra): set apply imediately to elasticache

.github/workflows/deploy.yml, backend/apps/client/src/email/email.service.spec.ts, backend/apps/client/src/email/mailerConfig.service.ts, backend/package.json, pnpm-lock.yaml
ECS에서 SES로 이메일 전송 시 아래와 같은 에러가 발생합니다.
SES에 explicit하게 credential provider를 전달합니다.
```json
{
"message": "Could not load credentials from any providers",
"error": "Internal Server Error",
"statusCode": 500
}
```
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/800"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(be): add explicit credential provider to sdk

infra/modules/codedang-infra/ecs-admin.tf, infra/modules/codedang-infra/ecs-client.tf, infra/modules/codedang-infra/redis.tf
Close #808 
개발 환경과 동일하게 Redis를 single instance 형태로 생성합니다.
추후 안정성 강화가 필요할 경우 Sentinel 모드로의 확장을 고려하면 되지 않을까 싶습니다!
* Redis 구성 (참고)
* Single instance : 단일 node(write / read)
* Sentinel : 다중 node (1 write node / 다중 read nodes) - Elasticache에서는 Multi-AZ로 설정하는 듯 보입니다. 
* Cluster : 다중 node (다중 write nodes / 다중 read nodes)
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/809"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: use single instance in redis

backend/apps/client/src/submission/dto/judger-response.dto.ts, backend/apps/client/src/submission/submission.service.spec.ts
#776 에서 추가한 type validation 중 error가 비어있는 경우도 올바르게 처리하도록 수정합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/816"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(be): validate judger response without error

frontend/src/common/components/Organism/Sidebar.vue
admin 페이지에도 main tab을 추가하고 logo를 클릭하면 codedang main 페이지로 이동되게 만듬
close #821 
---
=> feat(fe): add main tab and change logo link

frontend/src/common/components/Organism/Sidebar.vue
- 서브 페이지로 들어가면 탭에 활성화 표시가 되지 않았던 문제 해결
- 그냥 fullPath.startWith를 쓰면 main tab이 항상 활성화되는 문제가 있어서 조건을 추가함
close #824 
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/827"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(fe): change active filter condition

infra/modules/codedang-infra/cloudfront.tf
배포판에서 POST api 요청에 403이 반환되는 문제를 해결합니다.
Cloudfront에서 API의 모든 값을 서버로 forward하고, caching을 적용하지 않습니다.
(동일한 path, body, token이어도 JWT 만료 등에 따라 반환 값이 빈번하게 바뀝니다)
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/845"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(infra): disable cache for api request

infra/modules/codedang-infra/cloudfront.tf
[Deploy #54](https://github.com/skkuding/codedang/actions/runs/6046678284)에서 누락된 cloudfront `cached_methods`를 추가합니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/851"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(infra): add required cloudfront methods

.github/workflows/deploy.yml, infra/modules/codedang-infra/backend/client-task-definition.tftpl, infra/modules/codedang-infra/ecs-api-admin.tf, infra/modules/codedang-infra/ecs-api-asg.tf, infra/modules/codedang-infra/ecs-api-client.tf, infra/modules/codedang-infra/ecs-iris-asg.tf
Close #865 
ECS instance를 ARM 기반에서 x86 64bit으로 다시 전환합니다.
ECS-API 에서 사용하는 instance 개수를 1개(default)로 줄이고, 
ECS Admin과 Client task의 사양을 조정했습니다.
* ECS API Admin task ( 0.5vCPU, 0.5Mem) - 1개
* ECS API Client task ( 1vCPU, 0.5Mem) - 1개
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/867"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(infra): change ecs cpu to x64

.github/workflows/deploy.yml, .github/workflows/devserver.yml
GitHub Action job의 `working-directory` 옵션은 `run`이 있을 때만 쓸 수 있다고 하네요...
Docker context로 대체하였습니다.
참고: https://github.com/docker/build-push-action/issues/169#issuecomment-705392716
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/880"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(infra): replace dir to docker context

infra/modules/codedang-infra/ecs-api-asg.tf, infra/modules/codedang-infra/ecs-iris-asg.tf, infra/modules/codedang-infra/security-group.tf
Close #869 
1. 이미지 AMI를 수정했습니다.
- 기존 AMI : ami-056fad42304856ccf 
Graviton-based instance에 최적화되어있어서, 오류가 나지 않았을까 예상해봅니다.
- 변경 AMI : ami-05db432abf706dc01
iris ec2 instance의 SSH 접속 Security Group 추가했습니다.
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/887"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(infra): use proper ec2 ami 

Caddyfile
Close #892 
로컬에서 API 문서 작업할 때 사용하는 vitepress 서버(localhost 5555)에서 
dev server로  Request를 보낼 수 있도록 dev server를 설정합니다 
CORS는 해결해서 통신은 가능하도록 열어놨습니다! 
다만 `log in` API를 거치고 나서 다른 API를 테스트하는 경우 
직접 token을 복붙해서 사용해야하는 불편함이 있더군요... 
혹시 이 부분은 해결이 안되나요??
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/893"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(infra): allow api docs to use dev server

.github/workflows/deploy.yml
배포 GitHub Action 중 aws-actions/amazon-ecr-login에서 권장하는 대로 `mask-password` 옵션을 활성화합니다.
https://github.com/skkuding/codedang/actions/runs/6322475741/job/17168172282#step:4:14
공식 문서에서도 활성화를 권장하네요.
https://github.com/aws-actions/amazon-ecr-login#docker-credentials
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/900"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(infra): enable masking ecr login

.npmrc
Close #902
store-dir 옵션은 환경 변수 인식이 안되는 문제가 있어,
hard link를 해제하여 해결하였습니다. (`clone-or-copy`)
https://pnpm.io/npmrc#package-import-method
---
<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/904"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: disable pnpm hard link

frontend/src/common/store/auth.ts, frontend/vite.config.ts
로컬에서 dev.codedang.com으로 API를 호출할 때 `authorization` 헤더가 추가되지 않는 문제를 해결합니다.
Vite proxy 설정을 했는데도 API 호출이 Vite에서 일어나는 게 아니라 브라우저 내에서 redirection되는 문제를 발견하였습니다.
(왜 되는지는 모르겠지만...) Vite proxy 설정에서 target URL을 `http://` => `https://`로 변경하니까 됐습니다.
---
=> fix(fe): auth header is not added in local

frontend/src/common/components/Organism/Header.vue
Close #976 
헤더의 네비바 중 기능이 숨겨진 두 가지(Group, Contest)를 뒤로 보내고 Notice, Problem을 앞 순서로 변경했습니다.
변경된 순서 : Notice Problem Group Contest
간단한 변경이지만 이슈가 존재하여 hotfix 대신 새로운 브랜치를 만들었습니다.
---
=> fix(fe): fixed nav bar items order

backend/Dockerfile
Docker container 실행 시 `pnpm deploy out` 이후 `npm run build` 결과값인 dist 폴더 안의 파일을 실행하도록 경로를 수정합니다.
---
=> fix(infra): wrong docker dist directory

frontend/src/common/components/Organism/Header.vue
Close #1002 
- notice - contest - problem - group
→ notice - problem - contest - group로 순서 변경
노션에는 기존 순서가 "notice - contest - problem - group"로 되어 있었으나 실제로는 "notice - problem - group - contest" 였음. "notice - problem - contest - group"로 순서 변경함
---
=> chore(fe): navbar order changed

frontend/src/common/components/Organism/Login.vue
Close #1008 
로그인 모달의 로고를 코드당 로고로 변경
로그인 모달의 색을 파란색으로 변경(회원가입 모달과 통일)
---
=> fix(fe): changed logo, color of login modal

iris/go.mod
Gitpod 실행 시 `setup.sh` 실행 과정에서 아래와 같은 에러가 출력됩니다.
```
go: errors parsing go.mod:
/workspace/codedang/iris/go.mod:3: invalid go version '1.21.4': must match format 1.23
```
`go.mod` 파일에서도 아래처럼 에러가 나와 VSCode에서 Go language server가 정상적으로 동작되지 않습니다.
관련 이슈: https://github.com/golang/go/issues/61888
`go.mod`에 명시된 최소 버전을 낮춰 에러를 없앱니다.
---
=> fix(iris): use older go version in go.mod

backend/libs/constants/src/time.constants.ts, iris/go.mod
fixes #1025 
Refresh token cookie에 path 속성을 추가합니다.
production 일 땐 `/api/auth/reissue`, 아닐 땐 `/auth/reissue`로 설정됩니다.
---
=> fix(be): set cookie path option for refresh token

backend/apps/client/src/problem/mock/problem.mock.ts, backend/apps/client/src/problem/problem.repository.ts, backend/apps/client/src/problem/problem.service.spec.ts, backend/apps/client/src/problem/problem.service.ts
Closes #866 
problem에 딸린 problemTag에서 id만 뽑아와서 list로 놓고, tag에서 해당 row만 한번에 뽑아온 후 해당되는 id 매칭해서 보내주는 방식으로 변경했습니다!
실제로 속도가 빨라지는지, test코드는 따로 신경쓰지 못했습니다...
---
=> feat(be): reduce db access in getproblems

Caddyfile
email 인증할 때 frontend에서 header를 못 읽어오는 문제를 해결했습니다.
Caddyfile의 cors header에 email-auth를 추가하였습니다.
---
=> fix(infra): allow cors for email-auth

.github/workflows/cd-dev.yml, docker-compose.yml
Close #1026 
Github Actions(cd-dev) 이후에 스테이지 서버에서 Docker mount된 변경된 파일들이 Caddy Container에 반영이 안되는 문제를 해결합니다. 
호스트에서 도커 컨테이너로 파일 전송하기 위한 방법으로 docker mount 방법이 아닌 docker copy 방법으로 변경하였습니다.
---
=> fix(infra): modify cd-dev.yml and docker-compose.yml to solve 404 Error

frontend-client/app/notice/_components/NoticeTable.tsx
- Add Write column in Notice table
- 반응형에 따른 width 비율 조정
close #1118 
---
=> feat(fe): add writer section at notice table

backend/apps/client/src/problem/problem.controller.ts, backend/apps/client/src/problem/problem.repository.ts, backend/apps/client/src/problem/problem.service.ts, backend/prisma/schema.prisma, collection/client/Problem/Search Problem Title/Succeed.bru
`Problem`의 `title` field를 검색하는 api를 구현했습니다.  
본래는 [postgreSQL의 full-text search](https://www.prisma.io/docs/orm/prisma-client/queries/full-text-search)를 사용하여 구현하려 했으나, 띄어쓰기로 나눠진 단어 단위로만 검색이 됐습니다.  
그래서 Prisma의 `contains`를 사용하여 글자 단위 검색을 구현했습니다.  
텍스트량이 많은 필드는 full-text search를 이용하여 구현해 보는 것도 방법이라고 생각이 됩니다.
상기 이미지의 검색 결과를 보면, `사`라는 텍스트가 포함만 되어도, `Problem`들이 검색이 됩니다.  
하지만, full-text search를 쓸 경우, `사이클` 혹은 `경사`라는 단어를 검색해야 비로소 검색이 됩니다.  
closes #1117 
---
=> feat(be): implement problem title search api

frontend-client/components/ui/sonner.tsx
기존에는 system의 theme를 가져와서 sooner의 theme를 설정하기 때문에 system이 dark mode 일 경우 sooner에 dark theme가 적용됨.
하지만 우리는 아직 dark mode를 고려하지 않기 때문에 해당 부분들은 일단 주석 처리하고 sooner의 theme를 light로 고정시킴
---
=> fix(fe): fixed light theme in sonner

infra/modules/codedang-infra/variables.tf
Tfvars에서 사용하는 GITHUB_CLIENT_ID 및 GITHUB_CLIENT_SECRET 값을 `sensitive`로 설정합니다 
---
=> fix(infra): set github token for oauth as sensitive in tfvars

backend/apps/admin/src/contest/contest.service.spec.ts, backend/apps/admin/src/contest/contest.service.ts, backend/apps/admin/src/group/group.service.spec.ts, backend/apps/admin/src/group/group.service.ts, backend/apps/admin/src/problem/problem.service.spec.ts, backend/apps/admin/src/problem/problem.service.ts, backend/apps/admin/src/user/user.service.spec.ts, backend/apps/admin/src/user/user.service.ts, backend/apps/client/src/contest/contest.service.spec.ts, backend/apps/client/src/contest/contest.service.ts, backend/apps/client/src/group/group.service.spec.ts, backend/apps/client/src/group/group.service.ts, backend/apps/client/src/notice/notice.service.spec.ts, backend/apps/client/src/notice/notice.service.ts, backend/apps/client/src/problem/problem.repository.ts, backend/apps/client/src/problem/problem.service.spec.ts, backend/apps/client/src/workbook/workbook.service.spec.ts, backend/apps/client/src/workbook/workbook.service.ts, backend/libs/prisma/src/prisma.service.ts
Close #1155 
Cursor 값이 주어지지 않은 경우 Prisma query에 cursor 값을 설정하지 않습니다.
이를 위해 `PrismaService`에 `getPaginator` 함수를 만들었습니다.
```ts
const paginator = this.prisma.getPaginator(cursor)
const data = await this.prisma.model.findMany({
...paginator,
take
})
```
```ts
// cursor가 ID가 아닌 경우
const paginator = this.prisma.getPaginator(cursor, (value) => ({
contestId_problemId: {
contestId,
problemId: value
}
}))
```
---
=> fix(be): remove default cursor value

.devcontainer/devcontainer.json, backend/apps/client/src/problem/dto/related-problems.response.dto.ts, collection/client/Problem/Get contest problems/Succeed.bru, collection/client/Problem/Get group contest problem by ID/Succeed.bru, collection/client/Problem/Get group contest problems/Succeed.bru, collection/client/Problem/Get group workbook problem by ID/Succeed.bru
problem의 related problems response dto를 수정하였습니다.
get group workbook problems 및 get group contest problems 요청 시 기존에는 problemID와 title, difficulty를 반환해 주었습니다.
여기에 acceptRate와 submissionCount를 추가하였습니다.
bruno collection의 client/problem 내의 assert 문서를 수정하였습니다.
---
=> feat(be): add accept rate to problem api

backend/apps/client/src/problem/problem.controller.ts, backend/apps/client/src/problem/problem.repository.ts, backend/apps/client/src/problem/problem.service.spec.ts, backend/apps/client/src/problem/problem.service.ts, backend/apps/client/src/problem/schema/problem-order.schema.ts, backend/libs/pipe/src/index.ts, backend/libs/pipe/src/zod-validation.pipe.ts, backend/package.json, collection/client/Problem/Get all problems/Succeed.bru, pnpm-lock.yaml
Close #1123 
Problem 목록 API(`/problem`)에 정렬 옵션을 추가합니다.
사용 방법은 Bruno docs에 추가해뒀습니다.
---
=> feat(be): add order option to problem list api

backend/apps/client/src/submission/dto/judger-response.dto.ts, backend/apps/client/src/submission/mock/submission.mock.ts, backend/apps/client/src/submission/mock/submissionResult.mock.ts, backend/apps/client/src/submission/submission.controller.ts, backend/apps/client/src/submission/submission.service.spec.ts, backend/apps/client/src/submission/submission.service.ts, backend/prisma/migrations/20240104063238_change_submission_id_type/migration.sql, backend/prisma/migrations/20240104072555_change_submission_result_table_name/migration.sql, backend/prisma/schema.prisma, backend/prisma/seed.ts
Closes #1139 
원래는 Submission ID의 type이 String이었는데, 이를 정렬가능하게 바꾸기 위하여 SERIAL (INTEGER AUTOINCREMENT)으로 변경합니다.
또한, 기존 submission result 테이블에서 typo가 있어 이를 수정했습니다.
- SQL문을 손수 작성했으니 확인바랍니다.
---
=> feat(be): change submission id type

backend/apps/admin/src/contest/contest.resolver.ts, backend/apps/admin/src/group/group.resolver.ts, backend/apps/admin/src/problem/problem.resolver.ts, backend/apps/admin/src/user/user.resolver.ts
fixes #1167
> We should be aware that when we declare our type as a nullable union (e.g. string | null), we need to explicitly provide the type to the @Field decorator.
(참고: https://typegraphql.com/docs/0.17.4/types-and-fields.html) 
---
=> fix(be): provide type to the nullable Args explicitly in GraphQL

backend/apps/client/src/contest/contest.service.spec.ts, backend/apps/client/src/contest/contest.service.ts
close #1179 
#1144 에서는 Ongoing Contest와 Upcoming Contest에 대해 참여자 수를 같이 조회할 수 있도록 하였습니다.
본 PR에서는 Finished Contest에 대해서도 참여자 수를 조회하는 기능을 포함합니다.
- 참여자 수를 계산할 때, Prisma의 _count 기능을 사용하여 contestRecord의 수를 출력하도록 변경
- select option에 _count가 포함되었을 때의 반환 타입을 지정하여 관련 함수 및 test code에서 사용할 수 있게 함
- 응답 객체에 포함되는 `{_count.contestRecord: 1}`을 `{participants: 1}`로 변경
자잘한 버그를 수정합니다.
- getContestByGroupId에서 registeredContest를 반환할 때, ContestRecord에서 데이터를 조회해야 하는데, Contest에서 데이터를 조회하고 있었습니다. (사용자가 참여중인 contest를 찾아야 하는데, 사용자가 생성한 contest를 찾고 있었던 셈)
- getFinishedContests에서 take parameter가 prisma query에 전달되지 않아 pagination이 제대로 동작하지 않는 오류를 수정합니다.
---
=> feat(be): add participants number in finished contest GET API response

frontend-client/app/(main)/_components/Badge.tsx, frontend-client/app/(main)/_components/ContestCard.tsx, frontend-client/app/(main)/_components/Footer.tsx, frontend-client/app/(main)/_components/ProblemCard.tsx, frontend-client/app/(main)/_components/TimeDiff.tsx, frontend-client/app/(main)/page.tsx, frontend-client/components.json, frontend-client/components/ui/card.tsx
- card component 통합 및 추가 refactor 요소가 보이지만 일단 스타일 위주로 수정함
- badge 흰색으로 고정
- ellipse 스타일 추가
- footer 반응형 부분 고치고 요소들 구조 수정함
- more button shadcn으로 바꿈
- card component 뉴욕 디자인으로 바꿈
---
=> refactor(fe): change card and footer design

docker-compose.yml
Closes #1208 
promtail 컨테이너를 로깅이 필요한 서비스 컨테이너가 띄워지고 나서 띄워지도록 수정합니다.
=> fix(cd): promtail docker-compose change

backend/libs/logger/src/pino-option.logger.ts
closes #1174
request 객체에 user id과 request id를 추가하여 로그 분석 시 용이하도록 합니다.
user id는 로그인이 된 사용자에 한해서 확인 가능합니다.
request id는 모든 요청에 대해 부여됩니다. `Cryto.randomUUID()`를 사용하여 부여합니다.
---
=> feat(be): add user info and request id for logging

collection/admin/login.js, collection/client/login.js
close #1241
`login.js`에서 사용되는 axios call에 5초의 timeout 제한을 두었습니다.
AxiosError가 발생한 경우, pre-script에서 발생한 에러라는 것을 알리기 위해 에러 메세지를 수정합니다.
- timeout 5초 적절할까요?
- pre-script에서의 timeout 설정만 수행합니다. 본 요청의 timeout 옵션은 Bruno App - Collection - Preferences - General - `Request Timeout (in ms)`에서 설정 가능합니다. 코드로 넣는 방법은 찾지 못했습니다.
---
=> fix: add timeout option in bruno pre-script axios call

frontend-client/lib/utils.ts, frontend-client/middleware.ts
- reissue 과정에서 401 뜨면 logout 되게 설정
- 일단 임시로 fetch 10초마다 revalidate하게 설정
- 추후에 페이지 별로 잘 설계하면 좋을 것 같음
---
=> fix(fe): change reissue logic and add revalidate option

frontend-client/app/(main)/_components/AuthModal.tsx, frontend-client/app/(main)/_components/HeaderAuthPanel.tsx, frontend-client/app/(main)/_components/SignIn.tsx, frontend-client/app/(main)/_components/SignUp.tsx, frontend-client/app/(main)/_components/SignUpEmailVerify.tsx, frontend-client/app/(main)/_components/SignUpRegister.tsx, frontend-client/app/(main)/_components/SignUpWelcome.tsx, frontend-client/package.json, frontend-client/stores/authModal.ts
아래와 같이 조건 불일치 문구가 떠도 기존과 다르게 모달 height가 늘어납니다.
* 트랜지션 간 timeout 길이 조정으로 해결
enter(150ms) timeout(180ms) leave(100ms) 로 수정
timeout과 leave은 동시에 시작되나 leave 이후에 80ms의 시간이 남아서
transition이 정상적으로 작동됩니다. 
(leave와 timeout 시간 차가 넉넉하지 않으면 애니메이션이 튑니다)
전부 flex로 다루기에는
뒤로 가기 버튼이 없다 생기면서 코드당 로고가 움직이기에
뒤로 가기 버튼, 코드당 로고, 모달 전환 버튼은 absolute로 고정했습니다.
Close #1265 
DialogHeader, DialogFooter 사용을 시도했으나 
불필요한 여백도 생기고 별다른 이점이 없었습니다. 
---
=> fix(fe): change auth modal responsive

docker-compose.yml
폴더를 만드는 권한이 iris 컨테이너에 없어서 채점이 안되는 이슈를 해결했습니다.
docker-compose.yml에 들어간 read-only 옵션을 지우니까 해결됐어요
제 실수로 iris가 안 돌아가고 있었네요 😅
---
=> fix(iris): resolve iris folder creation failure

backend/apps/client/src/submission/submission.service.ts, backend/prisma/migrations/20240201082532_add_codesize_to_submission/migration.sql, backend/prisma/schema.prisma
closes #1282
Submission 모델에 `codeSize` 필드를 추가하고 Submission 정보를 READ할 때 함께 표시되도록 합니다.
---
=> chore(be): add code-size field to submission model

backend/apps/admin/src/contest/contest.resolver.ts, backend/apps/admin/src/group/group.resolver.ts, backend/apps/admin/src/problem/problem.resolver.ts, backend/apps/admin/src/user/user.resolver.ts
Closes #1294 
`groupId`, `contestId` 등을 `@Arg()`를 통해 전달받을 때 graphql scalar type을 명시하지 않으면 Int가 Float로 지정되는 문제를 해결합니다.
아래 코드와 같이 `@Args()`의 옵션으로 `type: () => Int`가 명시되어있지 않은 부분에 추가했습니다.
만약 `type`이 명시되어있지 않으면, 타입스크립트에서 `number`에 대해 schema.gql에서 Float로 지정됩니다. (그래서 Bruno 작성할 때 타입을 Int로 지정하면 에러남)
```
@Args('take', { type: () => Int, defaultValue: 10 }) take: number
```
`take`에 기본값 10 설정 되어있지 않은 부분이 있어 함께 추가했습니다.
---
=> fix(be): add missing type to admin server

frontend-client/app/(main)/contest/_components/Columns.tsx, frontend-client/app/(main)/notice/_components/Columns.tsx, frontend-client/app/(main)/problem/_components/Columns.tsx
- Data table들의 title에 ellipsis 속성을 주어 text overflow를 처리합니다.
- contest에서 name대신 title을 사용하도록 했습니다.
close #1333
=> feat(fe): edit Data Table's title area

backend/apps/admin/src/problem/problem.resolver.ts, backend/apps/admin/src/problem/problem.service.ts, collection/admin/Problem/Get Tags/Succeed.bru
Closes #1338
Tag 정보들을 가져오는 api를 추가합니다.
---
=> feat(be): add get tags api

iris/go.mod, renovate.json
Close #1342
Gitpod에서 Go 버전을 1.19.1을 쓰기 때문에, Renovate bot이 Go를 업데이트 할 때에도 해당 버전에서 지원하는 버전 형식으로 업데이트하도록 해요.
---
=> fix(deps): fix invalid go version format in go.mod

frontend-client/app/(main)/_components/ProblemCard.tsx, frontend-client/app/(main)/_components/ProblemCards.tsx, frontend-client/app/admin/layout.tsx, frontend-client/components/TextEditor.tsx, frontend-client/types/type.ts
Close #1365 
Tiptap의 `useEditor`로 `editor` 객체가 반환되는데 시간이 걸려, 사용자에게 text editor가 바로 보여지지 않습니다.
아래처럼 fallback 효과를 추가했습니다.
https://github.com/skkuding/codedang/assets/19747913/3ee665d5-5a1f-4ffa-8428-cdeffc15839a
---
=> fix(fe): add fallback style of text editor

frontend-client/app/(main)/_components/HeaderAuthPanel.tsx, frontend-client/app/(main)/_components/SignIn.tsx, frontend-client/app/(main)/_components/SignUpEmailVerify.tsx
1. ID를 User ID로 수정
2. email 버튼 클릭 없이 엔터만 눌러도 전송
3. Verification Code input에 arrows 제거
4. 5분 타이머 설정
5. dialog 바깥 클릭으로 인한 모달 닫힘 방지
Close #1380 
---
=> fix(fe): edit login and signup modal

.github/workflows/cd-prod.yml
CD Pipeline이 동작이 잘 안됩니다...
`terraform.tfvars`를 만들 때 환경변수 내 쌍따옴표(`"`)가 제대로 전달되지 않았네요
https://github.com/skkuding/codedang/actions/runs/7912234474/job/21598329578
---
=> fix(cd): double quotes in tfvars are missing

infra/modules/codedang-infra/cloudfront.tf, infra/modules/codedang-infra/ecs-api-asg.tf, infra/modules/codedang-infra/ecs-iris-asg.tf
Cloudfront에서 Amplify로 frontend(Next.js) 요청을 보낼 때, host 헤더가 포함되어 요청이 제대로 동작하지 않습니다.
Host 헤더를 제외하도록 Cloudfront의 origin policy를 변경합니다.
추가로 ECS의 EC2 instance 이름을 API와 iris를 통일시켰습니다.
---
=> fix(infra): exclude host header for traffic to amplify

frontend-client/app/(main)/_components/SignIn.tsx, frontend-client/app/layout.tsx
Sonner의 duration을 5000->2000으로 줄이고, 닫기 버튼을 추가했습니다.
메시지를 Login Successful로 바꿈
close #1417
=> fix(fe): edit sonner duration, message

iris/src/service/sandbox/langConfig.go
파이썬 버전에 따라 __pycache__ 에 생기는 바이트 파일의 파일 명이 달라집니다. 따라서 하드코딩된 바이트 파일명이 일치 하지 않으면 오류가 발생합니다. 따라서, 채점 시 해당 바이트 코드를 실행 시키지 않고, 파이썬 코드를 직접 실행시키도록 수정하였습니다.
---
=> fix(be): python exec args

Caddyfile, frontend-client/app/admin/problem/[id]/page.tsx
몇 주 간의 노력 끝에... dev 서버 타임아웃의 원인을 찾았습니다.
요약하면 HTTP Keep-Alive 세팅이 원인이었습니다.
지금 서버 구성은 아래 그림처럼 되어있는데, backend의 Node.js는 기본적으로 Keep-Alive timeout이 5초로 설정되어있습니다. 반면 Caddy에서 backend 방향으로는 2분으로 설정되어있고요.
```mermaid
flowchart LR
사용자 --- Caddy
subgraph 서버
Caddy --- backend
end
```
이렇게 reverse proxy의 keepalive 세팅값이 backend보다 길면 타임아웃이 뜰 수 있다고 합니다.
backend에서는 keepalive가 만료되었지만 reverse proxy에서는 기존 커넥션으로 요청 보내면 이미 끊긴 상태인 거죠.
> 참고1: [My NodeJS app show 502 error for no reason](https://stackoverflow.com/questions/66911457/my-nodejs-app-show-502-error-for-no-reason)
> 참고2: [NestJS 혹은 Express에서 간헐적으로 502 응답이 오는 경우](https://velog.io/@dramatic/NestJS-%ED%98%B9%EC%9D%80-Express%EC%97%90%EC%84%9C-%EA%B0%84%ED%97%90%EC%A0%81%EC%9C%BC%EB%A1%9C-502-%EC%9D%91%EB%8B%B5%EC%9D%B4-%EC%98%A4%EB%8A%94-%EA%B2%BD%EC%9A%B0) …
=> fix(infra): turn keep-alive off for caddy backend

backend/apps/client/src/problem/dto/problem.response.dto.ts, backend/apps/client/src/problem/problem.repository.ts
기존 getProblem을 통해서는 sample field를 가져오지 않는다는 문제가 있었습니다.
이에 Expose field를 수정하고, 원래는 updatetime, problemid, createtime 등 모든 정보를 다 받았지만, select해 sampleId, input, output만을 가져오도록 수정했습니다.
---
=> fix(be): modify getProblem sample field

.github/workflows/cd-dev.yml, Caddyfile, backend/apps/admin/src/admin.module.ts, backend/apps/client/src/app.module.ts
#1437 에서 완전히 타임아웃 에러가 해결된 거 같지 않아서 좀 고쳐봅니다
NestJS의 타임아웃 값을 61초로 늘렸고(기본 5초), Caddy의 servers.timeouts.idle 값을 60초로 조정했습니다.
---
=> fix(infra): use longer timeout value

frontend-client/app/admin/problem/create/page.tsx
1. hint source의 switch를 조작해도 textarea가 생성 안됨
showHint showSource 상태 추가
2. samples testcases add 버튼 눌러도 추가 안됨
react-hook-form의 watch를 통해
watchedSamples, watchedTestcases로 해결
create 과정에서 정상적으로 추가돼서 확인할 수 있습니다
Closes #1478 
---
=> fix(fe): fix create problem page

backend/apps/admin/src/admin.module.ts, backend/libs/logger/src/apollo-plugin.logger.ts, backend/libs/logger/src/index.ts, backend/libs/logger/src/pino-option.logger.ts
close #1472
HTTP request에 포함된 body도 로그에 남도록 설정을 추가합니다.
GraphQL 요청에 대해서도 body에 관련 정보가 모두 포함됩니다.
추가로, Apollo Server가 던지는 validation failed error 등의 에러가 기존 admin exception filter를 거치지 않는 문제를 식별하였습니다.
Apollo Server가 반환하는 모든 종류에 대한 에러를 기록하는 플러그인을 만들어 admin 모듈의 공급자로 등록해 두었습니다.
---
=> feat: add log data of request body

collection/client/User/(TODO) Send Pin for Password Reset/401- Unauthorized.bru, collection/client/User/(TODO) Send Pin for Password Reset/Succeed.bru
Closes #1493
비밀번호를 초기화하는 api sendPinForPasswordReset에 대한 Bruno docs의 잘못된 부분을 수정합니다.
- 로그인이 필요하지 않은 기능임에도 불구하고 pre-script로 로그인이 들어가있음
- 잘못된 이메일(등록되지 않은 이메일)이 작성되어있어야 하는 에러 관련 docs에 제대로 된 이메일이 들어가있음
---
=> docs(be): fix send-pin-for-pw-reset-api docs

frontend-client/app/admin/problem/_components/Columns.tsx, frontend-client/components/DataTableAdmin.tsx
기존에는 업데이트 요청 -> 새로운 데이터 요청 -> visible 여부 render라서 느리게 switching이 되었음
render용으로 state 따로 만들어 업데이트 요청과 render간 delay 없앰
좋은 해결방법은 아닌 것 같아서 나중에 데이터 수정 데이터 표시 로직 같이 얘기할 필요 있어보임
---
=> fix(fe): remove delay at switching visible option

frontend-client/app/admin/problem/[id]/page.tsx, frontend-client/app/admin/problem/_components/ExampleTextarea.tsx, frontend-client/app/admin/problem/create/page.tsx, frontend-client/components/TextEditor.tsx
inputDescription outputDescription hint ExampleTextarea 가 resize가 가능하도록 하고 height를 min-height로 수정했습니다.
Closes #1497 
---
=> feat(fe): change textarea and texteditor resizable

frontend-client/app/admin/layout.tsx, frontend-client/app/admin/problem/_components/Columns.tsx, frontend-client/app/admin/problem/page.tsx, frontend-client/components/DataTableAdmin.tsx
fetching(useMutation) -> updating cache data -> useQuery의 data updating -> data table rerendering -> page 0으로 되돌아가짐
위 상황 때문에 초기 화면으로 바뀌기 때문에 요청은 보내지만 caching은 하지 않도록 했으나 이러면 다른 페이지 갔다가 돌아오면 변경 전 내용을 보여주기 때문에 더 검색해보니 react table에 `autoResetPageIndex: false` 옵션을 주면 page index를 초기화 시키지 않는 것을 알 수 있었음
---
=> fix(fe): prevent to go first page in admin data table

Caddyfile
프론트엔드에서 `Email-Auth` 값을 못 읽는다고 해서 Caddyfile에 CORS 설정 추가했어요
---
=> fix(infra): expose email auth header with cors request

frontend-client/app/contest/[contestId]/problem/[problemId]/layout.tsx, frontend-client/app/contest/[contestId]/problem/[problemId]/page.tsx, frontend-client/app/contest/[contestId]/problem/[problemOrder]/layout.tsx, frontend-client/components/DataTable.tsx, frontend-client/components/EditorDescription.tsx, frontend-client/components/EditorLayout.tsx, frontend-client/components/EditorResizablePanel.tsx, frontend-client/lib/utils.ts
- API 변경으로 인해 Undefined으로 떴던 contest problem의 Index 부분을 고쳤습니다.
- 현재는 문제의 순서를 찾기 위해 문제 리스트를 가져와 맞는 부분을 찾는데 이는 비효율적으로 추후 contestId와 problem order로 problem detail 정보를 가져오는 API가 만들어지면 수정할 필요가 있음
- 따라서 구현이 비효율적으로 보이지만 어쩔 수 없었음...
---
=> fix(fe): change index based number to letter

backend/apps/client/src/contest/contest.service.ts, backend/apps/client/src/problem/problem.service.spec.ts, backend/apps/client/src/problem/problem.service.ts, collection/client/Contest/Get contest by ID/Succeed.bru
`User`가 `Contest` 정보를 가져올 때, 해당 `Contest`에 이미 등록했는지/안했는지를 알 수 있는 `isRegistered` property를 추가했습니다. (기존의 `canRegister`에서 변경한 것입니다.)
변수명이 `가입할 수 있는가?`에서 `이미 가입했는가?`로 바뀐 만큼 기존의 로직들에서 해당 변수의 boolean값들이 toggle돼야 해서, 그렇게 처리했습니다.
---
=> fix(be): convert can register property into is registered

apps/backend/apps/admin/src/problem/problem.module.ts, apps/backend/apps/admin/src/problem/problem.resolver.ts, apps/backend/apps/admin/src/problem/problem.service.ts, collection/admin/Problem/Get Contest Problems/Succeed.bru, collection/admin/Problem/Get WorkbookProblems/Succeed.bru
Closes #1556 
GraphQL 요청의 결과로 반환된 ContestProblem의 Problem 내부의 값을 조회할 수 있도록 구현합니다.
같은 방법으로 WorkbookProblem에 대해 구현합니다.
---
=> chore(be): add resolve-field for contest-problem, workbook-problem

apps/iris/src/observability/metric.go
panic 함수 사용시 iris 서버가 다운될수 있어서 fmt 함수로 에러를 프린트하게 변경하였습니다
=> fix(infra): change panic to print

apps/backend/apps/client/src/group/group.service.spec.ts, apps/backend/libs/prisma/src/index.ts, apps/backend/libs/prisma/src/transaction.extension.ts
Close #1561 
Backend Unit Test에서 Transaction Rollback을 이용하는 기능을 구현했습니다.  
`prisma.service.ts`에 있는 `PrismaService` Class를 `GroupService`에 주입하는 대신, 새로 만든 `transaction.extension.ts`의 transactionextension을 PrismaClient에 extend하여서, extended된 PrismaClient를 `PrismaService`에 주입했습니다. 이를 이용해 transaction client를 unit test 상에서 구현했습니다.  
`트랜잭션_클라이언트.$commit()`, `트랜잭션_클라이언트.$rollback()`을 통해, Transaction 커밋과 롤백을 이용할 수 있습니다.  
```typescript
beforeEach(async function () {
this.timeout(0)
//transaction client
tx = await prisma.$begin()
const module: TestingModule = await Test.createTestingModule({
providers: [
GroupService,
{ provide: PrismaService, useValue: tx },
ConfigService,
{
provide: CACHE_MANAGER,
useFactory: () => ({
set: () => [],
get: () => []
})
}
]
}).compile()
service = …
```
=> feat(be): implement transaction rollback in unit test

apps/backend/apps/admin/src/main.ts, apps/backend/apps/admin/src/metric.ts, apps/backend/apps/admin/src/tracer.ts, apps/backend/apps/client/src/main.ts, apps/backend/apps/client/src/metric.ts, apps/backend/apps/client/src/tracer.ts, apps/infra/modules/codedang-infra/backend/admin-task-definition.tftpl, apps/infra/modules/codedang-infra/backend/client-task-definition.tftpl, apps/infra/modules/codedang-infra/iris/task-definition.tftpl, apps/iris/main.go, apps/iris/src/observability/metric.go, apps/iris/src/observability/tracer.go
Closes #1573 
`OTEL_EXPORTER_OTLP_ENDPOINT` 환경변수를 `localhost:4318`로 전달하는 경우와 `127.0.0.1:4318`로 전달하는 경우의 동작이 다릅니다. 
```
sudo -E OTEL_EXPORTER_OTLP_ENDPOINT=127.0.0.1:4318 APP_ENV=production go run main.go
2024/03/19 10:20:51 internal_logging.go:57: "msg"="parse url" "error"="parse \"127.0.0.1:4318\": first path segment in URL cannot contain colon" "input"="127.0.0.1:4318"
```
```
sudo -E OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4318 APP_ENV=production go run main.go
{"level":"info","ts":"2024-03-19T10:21:05.466Z","caller":"runtime/proc.go:271","msg":"Server Started"}
```
아마 OTEL에서 `OTEL_EXPORTER_OTLP_ENDPOINT`를 비롯한 몇몇 환경변수들을 지정해 놓았는데,
go에서 이 환경변수들에 대해서 추가적인 확인을 하는 과정에서 발생하는 오류로 보입니다! [참고 - otlptracehttp go](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp#With …
=> fix(infra): change otel_endpoint env name

apps/backend/apps/client/src/problem/problem.repository.ts, apps/backend/apps/client/src/problem/problem.service.ts
기존 getProblems service 코드에서는 db에서 정해진 개수의 Problem을 take한 뒤, exposeTime으로 filter했습니다.
이때문에 db에서 가져온 개수와 최종 return되는 problem 개수가 달라졌습니다.
그래서 db에서 problem을 가져올 때 exposeTime을 체크해서 가져올 수 있도록 합니다.
---
=> chore(be): fix getProblems

apps/backend/apps/admin/src/contest/contest.service.ts
Contest에 Problem을 추가할 때, 기존 Problem의 exposeTime을 무시하고 무조건 현재 Problem이 추가되는 Contest의 endTime으로 exposeTime이 변경되는 문제를 해결합니다.
예를 들어 Contest 1에 Problem이 속해있었고, Contest 1의 endTime이 2024-12-01이라면 Problem의 exposeTime은 2024-12-01입니다. 그런데 endTime이 2024-08-01인 Contest 2에 Problem을 추가하면 Problem의 exposeTime이 2024-08-01로 변경됩니다.
이렇게 되면 Contest 1에도 Problem이 아직 존재하는데 Contest 2가 먼저 종료되면 Problem이 공개되어버립니다.
Problem의 exposeTime이 현재 추가하려고 하는 Contest의 endTime보다 작은 경우(다시 말해 현재 추가중인 Contest가 Problem의 exposeTime보다 늦게 끝나는 경우)에만 exposeTime을 Contest의 endTime으로 세팅하도록 수정해 문제를 해결합니다.
---
=> fix(be): add problem expose time change condition

apps/backend/apps/admin/src/contest/contest.service.spec.ts, apps/backend/apps/admin/src/contest/contest.service.ts
PR #1584 의 버그 수정
problem의 exposeTime을 업데이트하는 과정에서 exposeTime을 바꾸는 조건이 충족되지 않는 경우 exposeTime 조정 없이 ContestProblem이 생성되어야하는데, transaction에 묶여있어 ContestProblem도 생성되지 않는 문제를 해결합니다.
=> fix(be): resolves bug problems disappear when import problems to contest

apps/frontend/app/admin/user/_components/Columns.tsx, apps/frontend/app/admin/user/page.tsx
- 당장 가입된 유저들을 확인할 정도로만 구현했습니다.
- 구현 과정에서 admin page의 페이지 및 컴포넌트들을 봤는데 중복된 코드들이 너무 많은 것 같아요! 일단 layout 통합해서 page들간 중복 코드 제거 할 필요가 있어 보입니다!
- 이는 현재 이슈들 해결 한 후 개선해봅시다!
close #1575 
---
=> feat(fe): implement a admin user page

apps/frontend/app/(main)/contest/[contestId]/@tabs/_components/RegisterButton.tsx, apps/frontend/app/(main)/contest/[contestId]/@tabs/page.tsx, apps/frontend/app/contest/[contestId]/problem/[problemId]/submission/[submissionId]/page.tsx, apps/frontend/app/contest/[contestId]/problem/[problemId]/submission/_components/Columns.tsx, apps/frontend/app/contest/[contestId]/problem/[problemId]/submission/_components/DataTable.tsx, apps/frontend/app/contest/[contestId]/problem/[problemId]/submission/_components/SubmissionDetail.tsx, apps/frontend/app/contest/[contestId]/problem/[problemId]/submission/_components/dataIfError.ts, apps/frontend/app/contest/[contestId]/problem/[problemId]/submission/loading.tsx, apps/frontend/app/contest/[contestId]/problem/[problemId]/submission/page.tsx, apps/frontend/lib/pagination.ts
contest top에서 ongoing일 때 registered상태이면 첫 문제로 가는 버튼 생성
contest editor 페이지의 contest submission tab 구현
pagenation에 withauth 옵션 추가
문제들이 자꾸 사라져서 해결 후에 다시 작업해야 할 것 같습니다
close #1577
---
=> feat(fe): edit contest buttons and tabs

apps/backend/apps/client/src/submission/submission.controller.ts, apps/backend/apps/client/src/submission/submission.service.spec.ts, apps/backend/apps/client/src/submission/submission.service.ts, collection/client/Submission/Get Submission by ID/Succeed.bru, collection/client/Submission/Get Submissions/Succeed.bru
get Submission 시에 contestId가 껴있으면 빈 배열이 반환되는 문제를 수정합니다.
getContestSubmission과 getSubmission을 합쳤습니다.
---
=> fix(be): integrate get-submission and get-contest-submission

apps/backend/apps/client/src/submission/submission.service.ts
Closes #1601
contest submissions를 불러올 때 자신이 제출한 submissions만을 반환하도록 수정합니다.
대회의 제출 목록에는 자신이 제출한 내역만을 보여야 하기 때문에, userID 조건을 추가해 자신이 생성한 submission만을 가져오도록 수정합니다.
---
=> fix(be): add user-id condition for get-contest-submissions

apps/frontend/app/admin/contest/_components/Columns.tsx, apps/frontend/components/DataTableColumnHeader.tsx
- 기존 admin contest page에서 'Period, Register(participant), Visible'에 대해서 정렬 기능을 추가합니다.
- Visible은 문구를 'Asc, Desc'가 아닌 'Hidden First, Visible First'로 구현.
- <img width="227" alt="스크린샷 2024-03-25 오전 11 29 35" src="https://github.com/skkuding/codedang/assets/59248080/b406dba8-ef14-42a1-a3dd-df6eb8664085">
- <img width="194" alt="스크린샷 2024-03-25 오전 11 29 48" src="https://github.com/skkuding/codedang/assets/59248080/586c4a39-7e52-49ce-b58d-d2fd2bb38ac4">
- <img width="179" alt="스크린샷 2024-03-25 오전 11 30 20" src="https://github.com/skkuding/codedang/assets/59248080/66da67ab-c5c4-4046-b586-31d079d2152a">
---
=> fix(fe): allow ascending and descending order for admin contest list

apps/frontend/app/(main)/contest/[contestId]/@tabs/_components/RegisterButton.tsx
기존에 contest top에서 registered 버튼을 눌러 참가한 상태에서 다른 탭을 왔다갔다 하면 버튼 상태가 참가 이전 상태로 초기화되었습니다.
또한 뒤로가기 버튼으로 contest page로 이동 시 참가 여부가 업데이트 되지 않는 오류가 있었습니다.
isRegistered state 대신 refresh를 사용하여 contest에 참가하거나 삭제할 시 re-fetching을 통해 isRegistered값을 새로 불러오고 컴포넌트를 재랜더링합니다. 
close #1604
---
=> fix(fe): remove isRegistered state and add refreshing

apps/frontend/app/(main)/contest/_components/ContestTabs.tsx
- contest detail page에서 standings tab 비활성화
---
=> fix(fe): hide a standings tab

apps/backend/prisma/migrations/20240326030257_add_mapping_to_is_rank_visible/migration.sql, apps/backend/prisma/schema.prisma
새벽에 머지된 pr에서 매핑을 깜박해서 그 부분만 수정해 올립니다 !
PostgreSQL 상에서 매핑된 column 이름만 바뀌어서 백엔드 코드에서는 바뀌는 사항 없습니다 !
---
=> feat(be): add mapping to RankVisible

apps/infra/modules/codedang-infra/network.tf
close #1617 
terraform을 실행하면 `aws_route_table.private-ecs`가 상태가 같아도 계속 업데이트 되는 현상이 발생해요.
찾아보니, aws api가 gateway랑 nat이랑 되게 유연하게 받아들여요.
즉, gateway에 nat id를 전달해도 aws에서는 nat으로 인식해서 nat id값을 저장하는데
테라폼에서는 nat id가 아니라 gateway id로 코드에 적혀있으니 실제 값이랑 달라서 계속 업데이트를 하는거죠!
그래서 nat으로 바꾸면 이런 현상이 사라졌어요.
이 브랜치에서 완벽 fix 했습니다 !
기능에는 무리 없는 내용인데 계속 plan하면 뜨는게 불편해서 없애버렸습니당.
---
=> fix(infra): change incorrect argument in private route table

apps/infra/modules/codedang-infra/ecs-api-admin.tf, apps/infra/modules/codedang-infra/ecs-api-client.tf, apps/infra/modules/codedang-infra/ecs-iris.tf
resolve #1595 
#1596 force_new_deployment를 추가했음에도 ecr 이미지를 자동으로 업데이트 하지 않아 아래 깃헙 이슈 보고 해결했어요~
https://github.com/hashicorp/terraform-provider-aws/issues/13931 
일단 terraform plan에서는 당연히 arn에서 familiy로 수정했으니 update하는 건 뜨는데 그 이후는 cd 이후에 해봐야 알 것 같아요
기존 task_definition에 arn을 할당한 특별한 이유가 있나요?
---
=> fix(infra): change task definition attribute from arn to family

apps/frontend/app/(main)/contest/_components/FinishedContestTable.tsx, apps/frontend/components/DataTable.tsx, apps/frontend/next.config.js
기존에는 데이터가 없으면 No result만 보여줬지만 상황에 따라 다른 메시지도 보여줄 수 있도록 수정
오류를 발생시키던 next.js 설정 빼기
---
=> feat(fe): add DataTable empty message property

apps/frontend/app/admin/contest/create/page.tsx, apps/frontend/app/admin/problem/create/page.tsx
contest와 problem 생성 시
create 버튼을 누르면 isCreating이 true로 바꿉니다
(조건이 맞지 않아 생성이 안되는 경우 isCreating을 다시 false로 바꿉니다)
isCreating이 true일 때는 create 버튼이 disabled 됩니다.
Closes #1632 
---
=> fix: disable create button while isCreating is true

apps/infra/modules/codedang-infra/rabbitmq.tf
Close #1645 
MQ의 Exchange가 durable 설정이 되어있지 않으면 broker 가 재실행될 때 마다 exchange가 사라집니다. 
AWS RabbitMQ의 life cycle이나 restart 되는 시점에 대해서는 조금 더 찾아보고 정리해볼게요! 
(이따 스터디 때 공유하는 게 목표! ㅎㅎ)
---
=> chore(infra): set exchange as durable

apps/frontend/app/(main)/contest/_components/ContestCardList.tsx
Contest page에서 Contest 상태(upgoing/registered/ongoing) 상관없이 Contest Card를 기간순(startTime 순)으로만 정렬
- <img width="1709" alt="스크린샷 2024-04-27 오후 8 48 24" src="https://github.com/skkuding/codedang/assets/59248080/807c9c9e-ff73-4fe2-8b9e-ee7a0f9115e6">
---
=> fix(fe): change contest to startTime ascending order

apps/iris/Dockerfile, apps/iris/entrypoint.sh, apps/iris/main.go, apps/iris/src/observability/metric.go
1. APP_ENV값 dockerfile에서 삭제했습니다.
APP_ENV에서 production으로 박아버려서 stage환경에서도 production의 APP_ENV값을 사용하고 있습니다. 어차피 production환경에서 taskdefinition에 APP_ENV값을 production으로 설정하니, 생략하였습니다.
2. iris dockerfile이 shell script를 기본적으로 실행하게 바뀌었습니다.
shell script에서는 APP_ENV값(production 유무) 에 따라, iris 실행시 container id를 받아오는 command를 실행하고, 해당 값을 main.go함수의 인자로 넘겨서 그 값으로 metric config를 시행합니다.
3. main.go 함수 실행시 (`./iris` 커맨드 실행시) prod 환경에서 container ID를 인자로 넘겨서, 이를 metric provider의 containerID로 설정하는 과정을 추가하였습니다. 이것보다 깔끔한 로직을 찾기가 힘들었습니다 !
추가로, dockerfile에서 entrypoint는, **기본적으로 컨테이너가 생성된 후** 에 시행되는 것으로 확인하였습니다. (직접 검증하였습니다)
=> feat(cd): edit iris dockerfile to run sh to get containerId

apps/backend/apps/client/src/user/user.service.ts, apps/backend/libs/logger/src/pino-option.logger.ts
Closes #1674
회원가입 api에 대한 load test용 username, email, pin을 추가하고, 해당 값들이 입력되면 중복 체크 로직 등을 통과하도록 구현합니다.
**테스트하실 때 sign-up api는 브루노의 Script를 주석처리해놓고 호출하셔야 합니다**
같은 테스트용 username과 email을 통해 api를 반복해서 호출하면 unique constraint때문에 db에 유저 정보를 생성할 수 없습니다. 따라서 다음과 같은 과정을 통해 해결합니다.
1. 테스트용 username, email, pin이 입력된 form이 회원가입 api로 제출됨
2. 유저 정보를 db에 생성할 때 username과 email에는 랜덤한 숫자를 붙여서 저장 (두 필드가 unique이기 때문에 무적 username, email을 사용한다고 해도 테스트 중 실제 db에 유저 정보를 생성할 때는 계속 다르게 바꿔서 넣어줘야합니다) - 예를 들어 무적 username이 "load", 무적 이메일이 "load@gmail.com" 이라고 하면 db에 저장할 때마다 "load49439", "load49439@gmail.com" 이런식으로 뒤에 랜덤 숫자 붙여서 저장
---
=> feat(be): add username, email, pin for load test

apps/infra/modules/codedang-infra/backend/admin-task-definition.tftpl, apps/infra/modules/codedang-infra/backend/client-task-definition.tftpl, apps/infra/modules/codedang-infra/ecs-api-admin-service-asg.tf, apps/infra/modules/codedang-infra/ecs-api-admin.tf, apps/infra/modules/codedang-infra/ecs-api-asg.tf, apps/infra/modules/codedang-infra/ecs-api-client-service-asg.tf, apps/infra/modules/codedang-infra/ecs-api-client.tf, apps/infra/modules/codedang-infra/ecs-iris-service-asg.tf
API ECS의 resource 정책을 수정했습니다. 
일단, task의 cpu를 soft limit으로 설정해서, container들의 cpu 리소스를 공유할 수 있도록 설정했습니다. 
추가적으로 EC2 instance 1개 당 2개의 Task만 생성될 수 있도록 리소스를 제한했습니다
---
=> feat(infra): update asg in api cluster

.devcontainer/devcontainer.json
현재 VSCode devcontainer에서 extension을 신규로 설치할 때 Installing 과정에서 더 진행이 되지가 않는 경우가 발생합니다.
(VSCode version > 1.86.2 에서  발생)
원활한 extension 설치를 위해 extension을 설치할 때 verifySignature를 disable합니다. (아래 이슈 참고)
이미 build된 컨테이너에서는 `killall vsce-sign`를 실행해 이 문제를 일시적으로 해결할 수 있습니다. 
https://github.com/microsoft/vscode-remote-release/issues/9628
---
=> chore: disable vscode extension verifySignature

apps/frontend/components/EditorResizablePanel.tsx
- code editor에 입력시 Resizable panel이 전부 rerender되는 이슈가 있었음
- store을 분리시켜서 해결
- profiler 기준 render 수행시간 `7.9ms` -> `4.1ms`로 감소
-  문자 하나를 입력 했을 때 기준
---
=> fix(fe): prevent unnecessary rerenders in editor page

.github/workflows/ci.yml
Close #1696 
Backend(client / admin), Frontend 코드 변경이 있을 때에만 CI job을 실행시켜요.
[dorny/paths-filter](https://github.com/dorny/paths-filter) job을 활용했어요.
Branch protection rule을 적용하기 위해, 코드 변경이 없어도 job은 실행되게 했어요.
코드 변경이 없으면 job만 실행되고 build는 하지 않습니다.
---
=> feat(ci): run ci depending on code change

apps/infra/modules/codedang-infra/ecs-api-asg.tf
- 원활한 수업 사용을 위해 api instance type을 t3a.small에서 t3a.xlarge로 임시적으로 바꿉니다.
---
=> fix(infra): upgrade instance type of client api

apps/frontend/components/TextEditor.tsx
텍스트 에디터의 창 크기를 조절할 수 있도록
resize-y 속성을 추가했습니다.
https://github.com/skkuding/codedang/assets/97675977/ee430478-e7f1-43b0-b1ad-c1337e8710e3
Closes #1703 
---
=> chore: add resize attribute to text editor

scripts/setup.sh
terraform 설정할때 aws credential 사용하는 문제가 있었습니다.
개인 aws 계정이 default라고 되어있다면 그 계정의 credential을 terraform이 사용하여 Access Denied가 뜹니다.
skkuding aws configure 세팅에서 profile이름을 skkuding으로 하고
환경변수인 AWS_PROFILE을 설정함으로써 이를 막을 수 있습니다.
- bashrc에 AWS_PROFILE 설정하는 부분 추가했어용 ^0^
---
=> fix(infra): set aws profile as skkuding

apps/infra/modules/codedang-infra/network.tf
테라폼 프로젝트를 분리하는 과정에서 `aws_eip.nat_eip`를 data로 import해야하는 상황이 생겼는데, 
기존에 tag가 없어서 불러오기가 까다로워, 해당 값을 추가했습니다. 
---
=> fix(infra): add tag name into aws eip

apps/backend/libs/auth/src/roles/group-member.guard.ts
Closes #1721
GroupMemberGuard에서 group이 OPEN_SPACE_ID이면 로그인 상태여도 user role이 주입되지 않는 문제를 해결합니다.
---
=> fix(be): inject user role in groud-member-guard

apps/frontend/app/admin/problem/[id]/edit/page.tsx, apps/frontend/components/TextEditor.tsx
admin의 problem editor description에서 tab 키 입력 시 indent가 되지 않는 오류를 해결했습니다. 
Texteditor로 통일 완료했습니다.
<del><img width="839" alt="image" src="https://github.com/skkuding/codedang/assets/113789141/ec85e4b9-8bfc-404b-b383-1fd06d7ac708">
-edit problem
-create problem
다음과 같이 edit problem 창이랑 create problem 창을 비교했을 때 둘의 input, output description 컴포넌트가 다른 이유가 무엇인가요? Textarea와 Texteditor 를 각각 사용하고 있습니다. 
</del>
close #1750
=> feat(fe): implement indent extension

apps/frontend/components/auth/HeaderAuthPanel.tsx
Signup 모달 입력 도중에 나갔을 때 다시 Signup을 누르면 모달이 초기화되어 최초 화면부터 뜨는 문제를 수정
email verification code를 보낸 후 나갔다 Signup을 누르면 다시 이메일을 입력하는 화면부터 뜨는데 인증 번호를 입력하는 화면이 떠야 하는지에 대해서는 추후 논의 
Closes #1754 
---
=> chore(fe): prevent signup modal reset

apps/frontend/app/problem/[problemId]/submission/_components/Columns.tsx
problem의 submission 페이지에서 username이 null인 user가 있으면 런타임 에러가 나는 오류가 존재함. 그럴 경우 username을 'Unknown User'라고 표기해 버그 해결
앞으로 username이 null인 경우는 절대 발생하지 않을 것이므로 지금처럼 'Unknown User'라고 표기할지, 아예 제출 내역을 숨길지는 추후 결정
---
=> fix(fe): handle null user in submission

apps/frontend/app/(main)/_components/ProblemCards.tsx, apps/frontend/app/(main)/notice/_components/NoticeTable.tsx
여전히 Vercel에서 problemCards를 렌더링하는 도중 에러가 발생하여, data fetching할 때 사용하는 변수 이름을 렌더링 할 때 쓰는 변수와 다르게 지정합니다. 기존에도 두 변수는 스코프가 분리되어 있으므로 문제가 없음이 보장되어야 하지만, Vercel 로그를 확인해보니 두 변수가 혼동되어 사용되고 있음을 알 수 있었습니다. 
이미지 확인하시면 problems response는 data와 total로 구성되어 있어야 하지만, 무슨 이유에서인지 problem response 안에 problems과 total이 들어있음을 확인할 수 있습니다.
이에 따라 같은 이유로 NoticeTable 부분도 변경합니다. 
---
=> fix(fe): fix Vercel problemCard server component error

apps/frontend/app/admin/problem/_components/UploadDialog.tsx
=> chore(fe): disable close when click outside modal

apps/frontend/components/EditorHeader.tsx, apps/frontend/components/EditorResizablePanel.tsx, apps/frontend/types/type.ts
store에 저장된 코드가 없다면, 서버에서 받아온 스켈레톤 코드를 store에 저장하도록 했습니다. 
- 언어를 변경할 때마다 해당 스켈레톤 코드가 표시됩니다
https://github.com/skkuding/codedang/assets/97675977/5572ca78-587b-4778-b924-04d7bd39be26
Closes #1781 
---
=> feat(fe): show skeleton code on code editor

apps/frontend/components/ui/textarea.tsx
현재 shadcn textarea 컴포넌트에 tab선택시 indent가 적용되지 않는데, 해당 기능이 기본으로 적용되는게 좋겠다고 판단해서 추가합니다.
- 이를 위해서 shadcn컴포넌트를 모아놓은 ui폴더의 textarea컴포넌트를 수정합니다.
---
=> feat(fe): add indent when tab at textarea

apps/frontend/app/admin/contest/[id]/page.tsx, apps/frontend/app/admin/contest/create/page.tsx, apps/frontend/graphql/contest/mutations.ts, apps/frontend/graphql/contest/queries.ts
Contest Create/Edit Page에
Register Code 필드를 구현했습니다.
- Switch를 토글하면 register code가 null이 됩니다
- Edit 페이지에서는 다른 필드들과 마찬가지로 import problem할 때 localStorage에 저장됩니다.
Closes #1814 
zod schema에서 optional 대신 nullish를 사용했습니다.
nullish는 null을 허용하기 때문에 토글 했을 때 빈 스트링이 아니라 null을 넣어줄 수 있습니다
Hint, Source 등과 같이 선택적으로 입력하는 필드들도 같은 방식으로 개선할 수 있을 것 같습니다.
---
=> feat(fe): add register code field

apps/frontend/app/admin/problem/[id]/page.tsx, apps/frontend/components/EditorDescription.tsx, apps/frontend/lib/renderKatex.ts
katex 를 렌더링하는 함수를 lib에 분리했습니다.
close #1820
=> refactor(fe): separate katex rendering function

apps/infra/stage/Caddyfile, docker-compose.yml
closes #1824 
Stage서버의 Minio (오브젝트 저장소 S3대체) 의 웹 콘솔을 접속할 수 있게 추가하였습니다. 
stage.codedang.com/bucket/ 으로 접속하시고, 아이디비밀번호는 따로 공유드립니다.
---
=> feat(infra): apply minio web conolse on stage server

apps/infra/stage/Caddyfile, docker-compose.yml
closes #1828 
Image Upload 를 위한 프록시 설정을 추가하였습니다.
기존의 Minio Console의 URI를 /bucket으로 설정하였지만,
해당 URI를 실제 Object Resource에 접근하기 위한 URI로 변경하였고,
Web Console은 그 의미에 맞추어 /console로 설정하였습니다.
따라서, Web Console접근은 https://stage.codedang.com/console/  로 접근하시면 되고('/' 잊지 말아주세요)
resource 접근은 https://stage.codedang.com/bucket/{bucket_name}/{resource_name}
으로 가져오시면 됩니다.
**127.0.0.1로 가져오시면 안됩니다.**
---
=> feat(infra): add image upload proxy

apps/infra/production/codedang/codedang_service_admin.tf, apps/infra/production/codedang/codedang_service_client.tf, apps/infra/production/codedang/container_definitions/admin_api.json, apps/infra/production/codedang/container_definitions/client_api.json, apps/infra/production/codedang/modules/service_autoscaling/variables.tf
- API ECS 설정을 수정하였습니다 (Admin, Client)
- CPU의 Soft limit을 EC2 인스턴스 전체 용량의 30% 수준으로 낮추었습니다 (기존에는 50% 수준)
- Memory의 Hard limit을 삭제하였습니다. 따라서, Soft limit만 존재합니다. Memory의 soft limit은 EC2 인스턴스 전체 용량의 25% 정도로 설정되어있습니다.
Close #1836 
---
=> feat(infra): change api ecs cpu soft limit and delete memory hard limit

apps/frontend/app/(main)/_components/ProblemCard.tsx, apps/frontend/app/(main)/page.tsx, apps/frontend/components/ui/button.tsx
메인 페이지의 ProblemCards를 리디자인하고 See more 버튼의 active시 색상이 변경되도록 수정함
Closes #1844 
---
=> feat(fe): redesign problemcard component and see-more button

apps/backend/prisma/migrations/20240805054610_add_map_image/migration.sql, apps/backend/prisma/schema.prisma
Image 모델에 @@map()이 설정되지 않아 Grafana에서 Image 테이블에 대한 조회가 정상적으로 이루어지지 않는 문제를 해결합니다. 
** 기존 Image table Drop에 관련하여
- 아직 production에서 Image Upload 기능을 사용하지 않아 데이터 손실에 대해 걱정하지 않아도 됩니다.
---
=> fix(be): add map to image model

apps/backend/apps/client/src/contest/contest.controller.ts, apps/backend/apps/client/src/contest/contest.service.spec.ts, apps/backend/apps/client/src/contest/contest.service.ts, collection/client/Contest/Get finished contests/Succeed.bru
closes TAS-685
get finished contests API 호출 시 유저가 해당 대회에 등록되었는지를 표시하는 `isRegistered` 필드를 포함해 반환합니다.
---
=> feat(be): return is-registered field together when get-finished-contests api is called

apps/frontend/app/(main)/_components/Header.tsx
Header 왼쪽에 여백이 존재하던 문제를 해결했습니다!
closes TAS-687
Before:
After:
---
=> chore(fe): remove-header-left-margin

apps/frontend/app/(main)/_components/ContestCard.tsx, apps/frontend/app/(main)/_components/ContestCards.tsx, apps/frontend/app/(main)/_components/ProblemCard.tsx, apps/frontend/app/(main)/_components/ProblemCards.tsx, apps/frontend/app/(main)/page.tsx
메인 페이지의 Contest Card와 Problem Card의 개수와 디자인이 반응형으로 조절되도록 변경했습니다!
일반 노트북:
1024px:
390px:
Figma와 달리 일단 1024px까지 양 옆의 마진은 고정하지 않고 유동적으로 변하도록 내버려두었습니다..!
---
=> feat(fe): adjust main page card number responsively

docker-compose.yml
Stage 환경을 Production 환경과 동일시하기 위해 Stage 내 API 서버와 Iris 서버의 메모리, CPU 의 스펙을 제한하였습니다. 
API server hard limit 은 EC2 t3a.small 의 스펙으로 설정하였습니다.
---
=> feat(infra): add limits for API and Iris in stage

docker-compose.yml
기존에는 minIO의 ID와 PW가 파일에 노출되어 있었다.
Github Actions의 secrets를 사용해 해당 값을 환경 변수로 설정해 주어 사용함으로써 노출을 피할 수 있다.
Close #1952
---
=> fix(cd): hide minio's id and password

apps/backend/apps/admin/src/main.ts
local 환경 admin 백엔드 API서버에서, 프론트 local 환경(localhost:5525)의 CORS를 허용합니다.
현재 client측 API서버에는 프론트 local 환경 CORS가 허용되어 있어 잘 작동하지만, admin측은 작동하지 않아 프론트 개발할때 불편하여 개선합니다. 
closes TAS-718
---
=> chore(be): enable cors on local env backend admin

docker-compose.yml
local-storage 컨테이너와 deploy-storage 컨테이너가 CD-stage 과정 중 docker compose 명령어에 의해 충돌이 생겼습니다.
이를 해결하기 위해 local-storage 에 profile 을 추가합니다.
Closes TAS-721
---
=> fix(infra): add profiles for local minio container

apps/frontend/app/admin/contest/_components/Columns.tsx, apps/frontend/app/admin/problem/_components/Columns.tsx, apps/frontend/components/DataTableAdmin.tsx
Admin의 Problem List와 Contest List에서 title을 제외한 부분을 클릭했을 시 링크 연결이 되지 않는 문제를 수정했습니다! 이제 가장 왼쪽의 Checkbox, Visible의 토글과 아이콘을 제외하고 어느 부분을 클릭해도 제대로 연결됩니다!
closes TAS-705
closes TAS-706
---
=> feat(fe): improve datatableadmin click

.github/actions/setup-pnpm/action.yml, .github/workflows/ci.yml
- `setup-pnpm action`:  `setup-node`가 지원하는 cache 기능을 사용하는 것으로 변경
- `ci` workflow:
- dev dependencies만 설치하도록 변경 -> 30초 시간 절약
- prettier은 json 문법 등 다양한 파일들을 style check 하기 때문에 grep 부분 지움
- 이렇게 하면 `.prettierignore`과 같은 파일도 prettier가 체크해서 parser 오류가 뜸 -> `--ignore-unknown` 옵션으로 해결
dev dependencies만 설치해서 ci 같은 경우엔 1분에서 30초로 시간 절약
close #1858 
---
=> fix(ci): change pnpm cache logic and check style all files

apps/frontend/app/admin/layout.tsx, apps/frontend/app/admin/notice/page.tsx, apps/frontend/app/admin/page.tsx
Management  페이지 좌측 상단 로고 추가 && 하단 quit 버튼 삭제
Dashboard, Notice 문구 중앙정렬
closes TAS-559
---
=> fix(fe): change management layout

.env.development, docker-compose.yml
이전 PR에서 minIO username / password를 변수를 통해 inject하도록 변경한다는 PR을 올렸는데,
deploy storage에는 적용하지 않았길래 적용했습니다.
또한 local storage의 username/password를 환경변수에서 inject하도록 변경하였는데 
env.development에 해당 환경변수가 추가되어 있지 않아 로컬에서 setup.sh이 정상적으로 작동하지 않아 이 부분을 수정합니다.
---
=> fix(infra): inject minIO info from env.development

apps/frontend/app/(main)/_components/ContestCard.tsx, apps/frontend/app/(main)/_components/Header.tsx, apps/frontend/app/(main)/contest/_components/ContestCardList.tsx, apps/frontend/app/(main)/contest/layout.tsx, apps/frontend/app/(main)/layout.tsx, apps/frontend/app/(main)/notice/layout.tsx, apps/frontend/app/(main)/page.tsx, apps/frontend/app/(main)/problem/layout.tsx, apps/frontend/components/auth/HeaderAuthPanel.tsx
1. Main 페이지에서 Contest 카드랑 Problem 카드 사이 여백 늘림
2. Contest 페이지 캐러셀 모바일에서는 2개 되도록 수정
3. line-clamp로 ... 이 되어도 뒤에 문자가 살짝 보이는 버그 (height 지워서 해결)
4. 로그인 완료 후 헤더에 유저 아이콘 크기 변경
5. 헤더 사이즈 변경
Closes TAS-710
---
=> feat(fe): change main page components design

apps/backend/apps/client/src/email/templates/email-auth.hbs
이메일 인증 코드당 로고 재수정합니다.
- 기존 SVG형식이 gmail에서 인식이 되지않음.
---
=> fix(fe): change email logo

apps/frontend/app/admin/_components/SwitchField.tsx, apps/frontend/app/admin/contest/create/page.tsx
1. Contest Create에서 invitation code 필드가 안 보였던 버그 해결
2. invitation code에 입력된 내용이 숫자 6자가 아닐 때 에러 메시지 상시 표시
Closes TAS-568
Closes TAS-737
---
=> fix(fe): fix admin contest invitation code

apps/frontend/app/(main)/_components/ContestCards.tsx, apps/frontend/app/(main)/_components/ProblemCards.tsx
나타나는 Contest Card가 2개이하일때 나타나는 Server Error 해결했습니다.
앞으로 Finished인 Contest는 ContestCard로 나타나지 않습니다.
추가로 ContestCard, ProblemCard가 2개 이하일때 카드 배칙를 바꿨습니다!
- 앞쪽부터 차례대로 정렬되게 바꿨습니다
closes TAS-715
---
=> fix(fe): fix contest card server error

apps/frontend/lib/auth/authorize.ts, apps/frontend/lib/utils.ts
API Fetch 중 에러가 발생할 경우 res를 반환하지 않고 http error를 throw하는 safeFetcher를 구현합니다.
기존 fetcher는 `!res.ok`일 경우 에러 핸들링을 했지만, 
safeFetcher는 try catch나 error.tsx등을 통해서 에러 핸들링을 하도록 개선합니다.
점진적으로 기존 fetcher를 safeFetcher로 개선합니다. 
---
=> chore(fe): make safeFetcher that throws http error

apps/frontend/components/EditorLayout.tsx
프론트 빌드가 안되서 빠르게 hotfix합니다.
지금 프론트 빌드를 머지 옵션에서 꺼놔서 안 잡힌 것 같네요..! (시간이 오래걸려서 꺼놨는데, 그래도 빌드되는 거는 로컬이든 액션이든 확인하시구 머지해주세요..!)
---
=> fix(fe): editor layout problem type

apps/backend/apps/client/src/submission/submission.service.ts, apps/backend/apps/client/src/submission/test/submission.service.spec.ts, apps/iris/Dockerfile, apps/iris/go.mod, apps/iris/src/service/sandbox/langConfig.go
1. 파이썬 버전 3.9로 통일
현재 devcontainer의 경우 Debian 11(bullseye) 기반 이미지를 사용중이라 3.9 버전을
stage 및 production 서버에 사용되는 iris 이미지의 경우 우분투 24.04 기반 이미지를 사용하고 있어서
개발환경 및 배포환경에서 파이썬 3.9 버전을 사용하도록 강제함
2. cpuTime 로직 변경
채점 속도가 0ms 보다 빠른경우 null 이 아닌 0을 반환하도록 수정함
Close TAS-759
---
=> fix(be): modify sandbox python version and judge result cpu-time

apps/frontend/app/admin/contest/[id]/edit/page.tsx, apps/frontend/app/admin/contest/create/page.tsx
백엔드에서 import problem to contest시 visible property를 업데이트하므로, 프론트엔드에서 따로 updateProblem API를 호출하지 않습니다. 
---
=> fix(fe): don't update visible property on importing problem to contest

apps/frontend/app/admin/user/_components/Columns.tsx, apps/frontend/components/DataTablePagination.tsx
Admin User List의 column header 명칭을 수정하고, checkbox가 없는 관계로 테이블 왼쪽 하단의 ~row selected 문구를 삭제하였습니다!
Before:
After:
텍스트를 백틱(``)으로 수정한 것은 paginationbar를 가운데 정렬할 때 justify-between 특성상 그냥 빈 div를 넣는 것이 간편할 것이라고 생각했기 때문입니다!
closes TAS-695
검색과 정렬 기능을 추가는 해야 할 것 같은데, 검색을 id, 이름, 이메일 중 무엇으로, 아니면 동시에 여러 개에서 해야 할지 정해야 할 것 같습니다!
---
=> chore(fe): change admin user list column header

apps/frontend/components/CodeEditor.tsx, apps/frontend/components/EditorDescription.tsx, apps/frontend/public/24_copy.svg
Problem Description의 Input이나 Output의 복사 버튼을 눌렀을 때 토스트가 뜨도록 하였고, 복붙이 막혀있는 Contest의 대회에서 복사, 붙여넣기, 잘라내기를 했을 때도 토스트가 뜨도록 변경하였습니다..!
closes TAS-538
---
=> feat(fe): show toast when copied

apps/backend/prisma/seed.ts
seed data에 Admin user가 user profile이 없어 Settings페이지에서 테스트해볼 수 없어 
admin user profile data를 추가합니다.
---
=> fix(be): fix admin user profile seed

apps/backend/apps/admin/src/contest/contest.service.spec.ts, apps/backend/apps/admin/src/contest/contest.service.ts
1. import problem api 에서 이미 contest에 속한 problem을 import하려고 하면, 기존 대회 endTime보다 새로 import할 대회의 endTime이 더 나중일 경우에만 problem의 visibleLockTime update됩니다. 만약 그렇지 않을 경우, problem.update는 에러를 throw합니다. 이렇게 에러를 throw할 경우, contestProblem.create도 transaction으로 묶여있기 때문에 contestProblem.create도 같이 롤백됩니다.
정상적인 로직이라면 problem.update는 실패하더라도 contestProblem.create는 성공해야합니다. 이에 따라, update가 아닌 updateMany를 사용하여 where 조건에 걸리는 record가 하나도 없더라도 에러를 반환하지 않습니다. 
2. 이 문제의 디버깅이 매우 어려웠던 이유는 DB 업데이트에서 오류가 나더라도 에러를 잘 핸들링하는 것이 아니라 `continue` 했기 때문이 큽니다. 에러를 suppress하는 것은 문제를 찾는 데에 큰 어려움을 줍니다. 따라서, contestProblem을 create 하기 전 contestProblem이 이미 있는지 확인하고, update대신 updateMany로 바꿉니다. suppress하기 위해 들어가 있는 try catch문을 없앱니다. 
이 경우 에러가 나지 않고 response로 새로 추가된 contestProblem이 반환되므로, 프론트에서도 정보를 더 잘 활용할 수 있을 것입니다. 
---
=> fix(be): change import problem transaction error logic

apps/frontend/app/(main)/settings/page.tsx, apps/frontend/components/auth/HeaderAuthPanel.tsx
프로덕션의 Admin role의 유저들은 옛날에 생성되었으므로 studentId, major, realName을 가지지 않습니다.
Admin user는 이런 정보를 가지지 않으므로, update user info modal을 띄우지 않습니다.
settings 페이지에서 userProfile.realName이 없더라도 렌더링 오류가 나지 않도록 변경합니다.
---
=> fix(fe): admin role doesn't have to update studentId and major

apps/backend/apps/admin/src/contest/contest.service.ts, apps/backend/apps/admin/src/contest/model/score-summary.ts, apps/backend/apps/client/src/submission/submission-sub.service.ts, apps/backend/apps/client/src/submission/test/submission-sub.service.spec.ts
closes TAS-788
같은 문제에 대해 여러번의 submission이 있었을 때, 점수 계산의 기준을 "가장 높은 점수를 획득한 Submission" 에서 "마지막에 제출한 Submission" 으로 변경합니다.
추가로, 점수 계산 시 각 문제의 획득 점수가 무조건 100으로 표시되는 오류를 수정합니다.
---
=> feat(be): calculate score based on latest submission only

apps/infra/production/codedang/modules/cluster_autoscaling/cluster.tf
Closes TAS-789
ECS Cluster Managed Scalingd을 사용하여 ECS 클러스터의 용량을 자동으로 관리하기 위해 capacity provider strategy를 설정합니다.
<각 parameter 설명>
- weight: Capacity Provider가 여러 개 있을 경우, 작업이 이 Provider에 할당될 비율을 지정합니다. 단일 Capacity Provider를 사용할 때는 중요하지 않지만, 여러 Provider를 사용하는 경우 비율을 통해 리소스 할당을 조정할 수 있습니다. 현재 capacity provider가 1개밖에 없기 때문에 최댓값인 100으로 설정했습니다.
- base: 특정 Capacity Provider에서 최소 몇 개의 작업이 실행되어야 하는지를 설정합니다. 이 값을 통해 특정 Provider에서 항상 일정 수 이상의 작업이 실행되도록 보장할 수 있습니다.
ECS Cluster 기본 strategy를 설정하였지만 서비스별로 설정할 수도 있습니다
---
=> feat(infra): add capacity provider strategy to ecs cluster

apps/backend/apps/admin/src/contest/contest.resolver.ts, apps/backend/apps/admin/src/contest/contest.service.ts, apps/backend/apps/admin/src/contest/model/score-summary.ts, collection/admin/Contest/Get Contest Score Summaries /Succeed.bru, collection/admin/Contest/Get Contest Score Summary of User/Succeed.bru
Closes TAS-460
getContestScoreSummaries API를 생성합니다.
기획과는 다르게 Sort는 자동으로 StudentId기준으로 되도록 하였고,
Search 기능은 구현하지 않았습니다.
다른 우선순위 높은 task부터 진행하고, 구현할게여
GetScoreSummaries API 는 실제로 한 유저의 Summary만 가져오므로, GetContestScoreSummary 로 rename합니다.
GetContestScoreSummaries 와 GetContestScoreSummary 의 일관성을 위해서 이렇게 네이밍 했습니다. 
---
=> feat(be): implement getContestScoreSummaries api

apps/backend/apps/client/src/submission/interface/testcase.dto.ts, apps/backend/apps/client/src/submission/submission.service.ts, apps/backend/apps/client/src/submission/test/submission.service.spec.ts
submission 생성시 testcaseId를 s3에 있는 json 파일이 아닌 problemTestcase DB 테이블에서 받아오도록 수정
=> fix(be): get testcase-ids from postgresql not s3 when create submission

apps/frontend/components/EditorDescription.tsx, apps/frontend/components/EditorResizablePanel.tsx
- Problem Editor Sample Input Output의 길이가 길고, 줄바꿈없이 띄어쓰기만 있을시에 Output이 잘려서 보이는 현상 밑에와 같이 해결했습니다!
- 
closes TAS-775
---
=> fix(fe): fix Sample input output scroll design

apps/frontend/app/admin/contest/[id]/participant/[userId]/_components/SubmissionColumns.tsx, apps/frontend/components/DataTableAdmin.tsx
participant 페이지의 score 테이블 행을 누르면 에러가 생기는 현상을 이동하지 않게 함으로써 해결하였고, 추가로 ip가 null일 때 빈칸으로 보이는 걸 'Unknown'으로 수정하였습니다!
close TAS-816
---
=> fix(fe): remove link from participant score table

apps/backend/apps/client/src/submission/submission.service.ts, apps/backend/apps/client/src/submission/test/submission.service.spec.ts
Closes TAS-786
Contest에서 한번 ACCEPTED를 받으면 다시 제출할 수 없도록 되어 있던 로직을 기획 변경에 따라 재제출이 가능하도록 변경합니다.
---
=> feat(be): allow re-submission when user already passed problem

apps/infra/production/codedang/codedang_api.tf, apps/infra/production/codedang/codedang_iris.tf, apps/infra/production/codedang/codedang_service_client.tf, apps/infra/production/codedang/modules/cluster_autoscaling/autoscaling.tf, apps/infra/production/codedang/modules/cluster_autoscaling/variables.tf
- 배포 안정화 작업이 완벽하지 않아, 즉 Scale Up/Down에 대한 확신이 없어 API Auto Scaling Group만 desired capacity를 2개로 올립니다. 즉 API의 경우 기본 인스턴스 개수가 2개입니다.
- ECS Service 중 Client의 경우 트래픽 분산을 위해 배포 시 컨테이너 기본 개수를 2개로 설정합니다.
Closes TAS-828
---
=> feat(infra): increase api asg desired capacity and ecs client service desired count

apps/backend/apps/client/src/submission/submission.service.ts
Closes TAS-852
isJudgeVisible == false로 세팅되어있는 대회에서, Result만 가려지고 CpuTime과 Memory Usage를 가리지 않아 결과에 대해 유추할 수 있습니다. 이 문제를 해결합니다.
cpuTime과 memoryUsage는 isJudgeVisible==false인 경우 `null`로 반환됩니다.
---
=> fix(be): return cpu-time and memory-usage null when is-judge-visible is false

apps/backend/apps/admin/src/contest/contest.module.ts, apps/backend/apps/admin/src/contest/model/problem-score.input.ts, apps/backend/apps/admin/src/problem/model/testcase.input.ts, apps/backend/apps/admin/src/problem/problem.module.ts, apps/backend/apps/admin/src/problem/scalar/int-score.scalar.ts, collection/admin/Problem/Create Problem/Succeed.bru
Closes TAS-862
0 이상의 정수만을 받는 `IntScore` GraphQL Scalar Type을 만들고, score와 scoreWeight에 적용해 0 이상의 정수만을 받을 수 있도록 수정합니다.
---
=> fix(be): check if score or score-weight is non-negative integer

apps/backend/apps/client/src/contest/contest.service.ts, apps/backend/apps/client/src/problem/problem.service.spec.ts, apps/backend/apps/client/src/problem/problem.service.ts
Closes TAS-886
`isJudgeResultVisible === false` 인 경우 getContestProblems API의 결과로 반환되는 `maxScore`, `score`를 null로 대체합니다.
---
=> feat(be): redact max-score, score when is-judge-result-visible of contest is false

apps/backend/apps/client/src/submission/submission-sub.service.ts, apps/backend/apps/client/src/submission/test/submission-sub.service.spec.ts
Closes TAS-841
Problem 조회 시 Accepted Rate가 0으로 표시되는 문제를 수정합니다.
---
=> feat(be): add accepted-rate calculating logic when submission created

apps/frontend/components/ContestStatusTimeDiff.tsx
contest timer toast duration을 10초로 늘립니다.
원래는 2초가 기본값이지만, 옵션으로 인자를 넘겨서 default값을 오버라이드합니다.
closes TAS-853 
---
=> feat(fe): longer contest timer toast

apps/frontend/app/(main)/contest/[contestId]/@tabs/problem/page.tsx, apps/frontend/app/admin/contest/[id]/_components/Columns.tsx, apps/frontend/app/admin/contest/[id]/edit/page.tsx, apps/frontend/app/admin/contest/_components/ImportProblemTable.tsx, apps/frontend/app/admin/contest/_components/ImportProblemTableColumns.tsx, apps/frontend/app/admin/contest/create/page.tsx, apps/frontend/app/admin/contest/page.tsx, apps/frontend/app/admin/problem/create/page.tsx, apps/frontend/app/admin/problem/page.tsx, apps/frontend/components/DataTableAdmin.tsx, apps/frontend/components/DataTableProblemFilter.tsx, apps/frontend/components/EditorLayout.tsx, apps/frontend/components/OptionSelect.tsx
**주의: 한 PR에 너무 많은 태스크를 해결하였습니다... 죄송합니다..!**
1. admin problem list는 Update 내림차순으로, admin contest list는 Period 내림차순으로 디폴트 정렬을 설정하였습니다. initialState와 state를 동시에 이용하는 건 불가능하다길래 state의 초깃값을 설정하는 방식으로 변경하였습니다.
2. import 모달 테이블에서 체크된 문제를 최우선으로 앞에 두도록 하였습니다. enableImport가 참일 경우 항상 체크 여부를 커스텀 정렬보다 우선순위를 높게 설정하였습니다.
3. import 모달 테이블에서 20개 초과 문제를 체크할 수 없도록 하였습니다. 5개 문제를 한꺼번에 체크하는 헤더의 체크박스에도 로직을 적용하였습니다. 만일 20개를 넘어가게 된다면 작동하지 않으면서 toast를 띄웁니다. 문제의 정렬을 선택하는 OptionSelect에서도 5개를 넘어가면 스크롤바가 나오도록 변경하였고, 클라이언트에서도 문제를 20개까지 가져오도록 수정하였습니다.(?take=20을 임의로 줬는데, 백엔드에서 기본값을 변경하는 게 맞을지도요..?)
4. import 문구를 import / edit 문구로 변경하였습니다.
5. contest 점수를 0 이상의 점수만 입력받도록 하였습니다. 서진이형이 테스트케이스에서 적용한 방식을 따라했는데, focus를 잃는다고 바로 뜨는 것이 아니라 edit/create 버튼을 눌러야 경고가 뜨도록 되어 있는 것 같습니다.
6. contest overall의 submission 페이지에서 문제 제목이 길면 필터 …
=> feat(fe): improve datatableadmin order

apps/frontend/app/admin/contest/[id]/(overall)/@tabs/_components/Columns.tsx, apps/frontend/app/admin/contest/[id]/(overall)/@tabs/page.tsx, apps/frontend/app/admin/contest/[id]/(overall)/@tabs/submission/page.tsx, apps/frontend/app/admin/contest/[id]/(overall)/layout.tsx, apps/frontend/app/admin/contest/[id]/participant/[userId]/page.tsx, apps/frontend/components/DataTableAdmin.tsx, apps/frontend/graphql/contest/queries.ts, collection/admin/Contest/Get Contest Score Summary of User/Succeed.bru
1. Contest overall participant page에서 score table에만 횡스크롤을 적용시켜 Edit 버튼과 기간이 스크롤해야 나타나는 문제를 해결하였습니다.
2. Contest overall participant page의 score table 위에 Participant 수를 추가하였습니다.
3. Contest overall의 Participant Detail Page, All submissions Page에서 submission이 10개만 노출되는 것을 1000개로 늘렸습니다. (bruno에 take가 명시되어 있지 않아 바꾸었는데 괜찮겠죠?)
4. Contest overall participant page의 검색 input의 placeholder를 'Search Name'으로 수정하였습니다. 
5. Contest overall에서 검색이 안 되는 문제를 해결하였습니다. **(꽤 유익할 만한 정보가 있습니다..!)**
Contest overall participant page에서 검색을 했을 때 어떤 Contest는 대소문자 구분없이 일부만 match되도 잘 뜨고 어떤 Contest는 처음부터 끝까지 정확히 일치해야만 뜨는 현상이 있었습니다. 몇 시간동안 머리를 싸매며 검색한 결과, filterFn을 따로 설정하지 않았을 때 디폴트 값은 'auto'로 이는 column의 첫 번째 값을 기준으로 필터링 방식을 결정하는데, realName의 경우 string | null type이고, Contest의 첫 번째 realName이 운 나쁘게 null인 경우 'equals'(===)으로 …
=> feat(fe): apply scrollarea only to score table

apps/frontend/app/(main)/contest/[contestId]/@tabs/page.tsx, apps/frontend/app/admin/contest/[id]/(overall)/layout.tsx, apps/frontend/app/admin/problem/[id]/page.tsx, apps/frontend/components/EditorDescription.tsx, apps/frontend/components/KatexContent.tsx, apps/frontend/components/TextEditor.tsx
TextEditor 내의 HTML이 `<p></p>` 일 때만 placeholder를 표시하는 방식으로 수정했습니다
Contest Detail의 description에도 KatexContent를 적용해서 katex 수식이 보이도록 했습니다.
Closes TAS-839
Closes TAS-840
katex를 보여주는 곳마다 중복된 코드가 있어 KatexContent를 컴포넌트화 했습니다
---
=> fix(fe): fix text editor placeholder, componentize katex

apps/backend/apps/admin/src/problem/model/template.input.ts, apps/backend/apps/admin/src/submission/model/submission-detail.output.ts, apps/backend/apps/admin/src/submission/submission.resolver.ts, apps/backend/apps/admin/src/submission/submission.service.ts, collection/admin/Submission/Get Submission Detail/Succeed.bru
Admin에서 Submission을 submission ID를 통해서 받아올 수 있도록 구현합니다. 
기존에는 `Client - get submission by id` api에 Admin 권한을 뚫어서 사용하고 있었으나, client api가 과도하게 복잡해져 바꿀 필요가 있었고, admin / client간의 독립성을 높여 유지보수에 용이할 것으로 보입니다. 
`Admin - get submission by id` api는 submission ID만으로 모든 데이터를 가져올 수 있습니다. `Client - get submission by id` api는 여러 권한 검사와 response validation이 포함되어 있지만, 
admin에서는 각종 권한 검사와 response validation을 수행하지 않으므로, 프론트엔드에서 사용할 때 각 시나리오(contest, problem List, workbook ... ) 별로 잘 구분하여 사용하면 좋을 것 같습니다.
- `Admin get Submission by Id`의 response는 `Submission` model에서 기본적으로 depth가 1인 필드만 가져옵니다.
- User 쪽과 비슷하게 response를 구성하면서도, 원하는 정보를 최대한 받아올 수 있도록 (어차피 graphql을 사용하므로) 최대한 선택권을 열어둡니다.
- 단 `SubmissionResult`는 `TestcaseResult`를 변형하여 반환하고, `code`도 raw json을 string 형태로 변형하여 반환합니다. 
closes TAS-906
---
=> feat(be): add admin get submission by id api

apps/backend/apps/admin/src/submission/model/submission-detail.output.ts, apps/backend/apps/admin/src/submission/submission.service.ts, collection/admin/Submission/Get Submission Detail/Succeed.bru
admin get submission by id api에서 user / contest / problem 정보도 같이 받아오도록 추가합니다.
백엔드에서 정보를 같이 주지 않으면 프론트 코드 구조상 이를 구현하기가 어렵습니다. 
Admin API라서 많이 호출될 일은 없기 때문에 일단은 비효율적이지만 간단하게 user, contest, problem의 모든 relational field를 불러오도록 했습니다.
join이 너무 많아져서 비효율적이긴 해서, 추후에 GraphQL에서 동적으로 요청한 필드에 대해서만 select를 하도록 변경하면 좋을 것 같습니다.  <- Admin에서 Graphql을 사용하는만큼 Query의 경우에 Response의 자유도를 높이고, 요청하는 필드에 대해서만 on-demand로 select하도록 다른 Admin API들도 같이 적용하면 좋겠네요! 
---
=> feat(be): add double depth field to admin get submission api

apps/backend/apps/client/src/submission/submission-sub.service.ts

iris에서 채점할 코드 실행 중 Compile Error 발생 시 mq로 전송되는 메세지의 judgeResult 속성이 null로 세팅됩니다.
이 경우를 Test 전용 메세지를 핸들링하는 handleRunMessage 함수에서 처리하지 않아, Compile Error가 발생하는 코드를 Test를 통해 제출 시 무한 Judging이 발생합니다. (일반 Submit은 상관 없음)
위 문제를 해결합니다.
---
=> fix(be): add condition for compile-error when run test

apps/backend/apps/admin/src/contest/contest.resolver.ts, apps/backend/apps/admin/src/contest/contest.service.ts, apps/backend/apps/admin/src/submission/model/get-contest-submission.input.ts, apps/backend/apps/admin/src/submission/submission.service.ts, collection/admin/Contest/Get Contest Score Summaries/Succeed.bru, collection/admin/Submission/Get Contest Submissions/Succeed.bru
Closes TAS-898
- Admin Contest Overall 페이지에서 유저의 realName으로 검색하는 기능
- All Submissions 페이지에서 Contest에 속한 문제로 필터링하는 기능
을 구현합니다.
---
=> feat(be): implement search in contest overall apis

apps/infra/production/network/public_network.tf
Closes TAS-925
지난 학기에 비용 절감을 위해 NAT Gateway를 삭제하여 더 이상 이를 위한 Elastic IP가 불필요합니다. 불필요한 비용 청구를 방지하기 위해 테라폼 코드에서 해당 코드를 삭제합니다.
---
=> fix(infra): remove aws elastic ip for nat gateway

apps/frontend/app/(main)/contest/[contestId]/@tabs/_components/RegisterButton.tsx, apps/frontend/app/admin/_components/SwitchField.tsx, apps/frontend/app/admin/contest/[id]/_components/Columns.tsx, apps/frontend/app/admin/problem/_components/TestcaseItem.tsx, apps/frontend/components/auth/ResetPasswordEmailVerify.tsx, apps/frontend/components/auth/SignUpEmailVerify.tsx, apps/frontend/package.json, apps/frontend/tailwind.config.ts, pnpm-lock.yaml
type이 number인 input의 스핀 버튼을 없애기 위한 코드가 반복되었는데
tailwind config의 addUtilities를 이용해서
`hide-spin-button` 를 추가했습니다.
추가로 멀쩡하던 
```
require('tailwind-scrollbar-hide')
```
가 lint에 걸려서 당황했는데 쓰고 있는 곳이 아예 없어서
plugin에서 빼고, 패키지도 지웠습니다.
Closes TAS-930
---
=> refactor(fe): add hide spin button util style

apps/backend/apps/client/src/submission/submission.controller.ts, apps/backend/apps/client/src/submission/submission.service.ts, apps/backend/apps/client/src/submission/test/submission.service.spec.ts
submission 모듈에서 에러 핸들링 로직을 글로벌 예외 처리 메커니즘으로 통합합니다. 컨트롤러와 서비스에서의 로컬 에러 처리를 제거하고, 레포지토리에서 발생하는 Prisma 예외는 적절한 Business exception으로 변환하여 전체적인 백엔드 코드의 일관성을 높입니다.
controller에서 에러 처리하는 로직 제거
모든 try catch 블록 제거 / 서비스에서 발생한 예외를 그대로 글로벌 에러로 전파시킴
---
=> refactor(be): improve client submission module error handling logic

apps/backend/apps/client/src/problem/problem.controller.ts, apps/backend/apps/client/src/problem/problem.repository.ts, apps/backend/apps/client/src/problem/problem.service.spec.ts, apps/backend/apps/client/src/problem/problem.service.ts
`problem` 모듈에서 에러 핸들링 로직을 글로벌 예외 처리 메커니즘으로 통합합니다. 컨트롤러와 서비스에서의 로컬 에러 처리를 제거하고, 레포지토리에서 발생하는 Prisma 예외는 적절한 Business exception으로 변환하여 전체적인 백엔드 코드의 일관성을 높입니다.
1. controller에서 에러 처리하는 로직 제거
모든 try catch 블록 제거 / 서비스에서 발생한 예외를 그대로 글로벌 에러로 전파시킴
2. `problem.repository.ts`에서 Prisma 예외를 비즈니스 예외로 변환.
Prisma 예외 코드에 의존하지 않고 비즈니스 로직에 맞는 예외를 던지도록 수정함.
`findUniqueOrThrow`를 `findUnique`로 변경하고 결과가 없을 때 Exception을 발생시킴.
3. Prisma `upsert`에서 에러 핸들링 추가
upsert를 하는 메서드에서는 Prisma 에러가 날 수 있으므로, try catch로 에러를 잡아 적절한 비즈니스 예외로 변환함. 
---
=> refactor(be): improve client problem error handling logic

apps/infra/production/codedang/codedang_service_admin.tf, apps/infra/production/codedang/codedang_service_client.tf, apps/infra/production/codedang/codedang_service_iris.tf
closes TAS-931
이전에 ECR 레포지토리에 배포되어 있던 도커 이미지 파일을 자동으로 제거하는 수명 정책을 추가합니다.
<왜 최근 6개의 이미지를 킵하나요?>
저희 코드당은 배포 시 Docker Buildx를 사용합니다. 여러 플랫폼에 대한 빌드를 지원하며, 이 때에 두 개의 image와 한 개의 image index 파일 (총 3개의 파일)이 생성되어 ECR에 저장 됩니다. 따라서, 최신의 이미지 파일과 직전 이미지 파일을 보존하기 위해 직전 6개의 파일을 저장해 두도록 설정하였습니다.
<적용 방법>
깃헙 액션에서 이미지를 제거하는 방법, 그리고 AWS ECR에서 수명 정책을 생성하는 방법, 총 두 가지의 선택지가 있었습니다.
기존 코드당 테라폼 코드에서는 이미 콘솔 내에서 생성된 레포지토리를 참조하는 방식으로 짜임새가 맞추어져 있어, 테라폼으로 수명 정책을 추가하는 것으로도 문제가 없음을 판단하였습니다.
또한, 깃헙 액션 상에서 코드를 작성할 경우, 각 CD 파일에서 admin, client, iris에 대한 레포지토리에 각각 접근해야 하기 때문에 코드 상 중복이 많아지고, 유지 관리에 어려움이 발생할 수 있다고 판단, 최종적으로 수명 정책을 테라폼 내에서 추가하는 것으로 결정하였습니다.
---
=> feat(infra): add lifecycle policy to ecr repositories

apps/infra/production/storage/s3_gateway_vpc_endpoint.tf
NAT 인스턴스의 ECS와 S3 간의 커뮤니케이션을 대체하기 위해 gateway vpc endpoint를 추가하였습니다.
이 기능이 작동하는지 테스트하려면, NAT instance public ip를 허용하는 S3 bucket policy를 지운후,
ECS와 S3 간의 통신이 여전히 유지되는 경우,
이 게이트웨이 vpc 엔드포인트가 제대로 작동하는 것으로 간주하여 테스트 할수 있을것 같습니다.
Closes TAS-887
PR #2122와 코드 작성내용은 같지만, gateway vpc endpoint가 s3와 독점적으로 통신하는 점을 비추어 볼때, 연관성이 더욱 있는 /storage directory로 (원래는 /network directory) gateway vpc endpoint 코드 파일을 옯겼습니다.
---
=> feat(infra): created gateway vpc endpoint for communication between ECS and S3

scripts/setup.sh
- Devcontainer에서 Frontend build 과정 중 JavaScript heap out of memory 에러를 방지합니다.
- [https://velog.io/@kwontae1313/build-과정-중-JavaScript-heap-out-of-memory-에러](https://velog.io/@kwontae1313/build-%EA%B3%BC%EC%A0%95-%EC%A4%91-JavaScript-heap-out-of-memory-%EC%97%90%EB%9F%AC)
- 위 레퍼런스를 참고하여 Devcontainer의 postInstallation script인 `scripts/setup.sh` 에 노드에 메모리를 기본으로 약 4GB 할당하도록 변경합니다. (Default: 약 2GB -> 변경: 약 4GB)
---
=> fix(fe): allocate more memory to node in devcontainer for smooth frontend build

apps/frontend/app/admin/contest/[id]/edit/page.tsx, apps/frontend/graphql/submission/queries.ts
- Contest에 Submission이 존재하는지 확인하고
존재하는 경우, Problem Import 관련 요청을 보내지 않습니다.
- 만약 Contest에 Submission이 존재하고
관리자가 Contest 관련 정보와 Problem을 추가로 Import한 경우
경고 토스트가 생성되고, Contest 관련 정보만이 Update 됩니다.
https://github.com/user-attachments/assets/1114d9af-31bf-4583-a775-501d5129351c
Contest Description을 수정하고, Problem을 추가로 Import 했지만
Submission이 존재하기 때문에, warning toast가 생성되었고
Contest Description만 Update 되었습니다
Closes TAS-958
---
=> fix(fe): show warning when editing contest if submission exists

apps/frontend/app/(main)/settings/_components/MajorSection.tsx
settings major section에서 scrollbar 2개 나타나는 문제 재해결
---
=> fix(fe): fix scrollbar

apps/frontend/components/EditorDescription.tsx
- 힌트가 길 때 자동으로 줄바꿈 되도록 수정합니다. 이때 단어 기준으로 줄바꿈됩니다.
- 개행문자를 유지하면 줄바꿈이 되다 보니 아래 사진처럼 이상하게 보일 수 있는데 그렇다고 개행문자를 무시할 순 없어서 유지하는 방향으로 수정했습니다.
closes TAS-960
---
=> chore(fe): wrap the line of the hint automatically

apps/frontend/app/admin/contest/_components/Columns.tsx
admin contest table의 period 타임 포맷을 12시간제에서 24시간제로 수정했습니다!
(task 핑계로 리팩토링 덜 하고 싶었는데 4글자 바꾼 게 다라서 안 되겠네요...ㅋㅋㅋㅋ)
closes TAS-961
---
=> chore(fe): fix admin contest time format

apps/frontend/components/EditorHeader.tsx, apps/frontend/components/EditorResizablePanel.tsx, apps/frontend/stores/editor.ts
QA 중 User Contest 첫 문제 수동 저장 오류가 발견되었다. 오류는 아니지만 language 변수를 문제에 상관없이 전역으로 하나만 저장하기 때문에 발생한 불편함이어서 문제별로 마지막으로 설정한 language를  저장하도록 localstorage에 language를 저장하는 key를 바꿨다.
close TAS-987
=> fix(fe): change language's storekey to include problemId and contestId

apps/frontend/app/admin/contest/_components/ImportProblemTable.tsx, apps/frontend/app/admin/contest/_components/ImportProblemTableColumns.tsx
`ImportProblemTable` 데이터에 score 정보를 포함하도록 합니다.
https://github.com/user-attachments/assets/ecf18a2b-82ea-4178-9131-9c4e432df179
closes TAS-979
---
=> fix(fe): restore the score of the problems when the new problems are imported

apps/frontend/app/admin/problem/_components/ExampleTextarea.tsx, apps/frontend/app/admin/problem/_components/TestcaseField.tsx
submission이 존재해 테스트케이스를 수정할 수 없는 경우 테케 추가/삭제 버튼이 보이지 않도록 합니다. ([피그마](https://www.figma.com/design/c7RefqPCB4HC9DuFhT7eFg/%EC%BD%94%EB%93%9C%EB%8B%B9-%EB%A6%AC%EB%94%94%EC%9E%90%EC%9D%B8-(2024ver)?node-id=3104-9040&t=Z23hwZbwq8N83MJl-1)에서 제시한 대로 수정했습니다)
closes TAS-989
---
=> fix(fe): not show add/delete buttons when testcase cannot be edited

apps/frontend/app/admin/contest/[id]/_components/Columns.tsx, apps/frontend/app/admin/contest/[id]/edit/page.tsx, apps/frontend/components/OptionSelect.tsx
Contest에 Submission이 존재하는 경우
- import 버튼을 숨깁니다
- Contest Problem List에서 score, order 수정을 막습니다
- score order 필드를 클릭하면 수정할 수 없다는 토스트가 노출됩니다
Closes TAS-1002
---
=> fix(fe): block editing problem when contest has submission

apps/frontend/app/admin/contest/[id]/(overall)/@tabs/submission/_components/Columns.tsx, apps/frontend/app/admin/contest/[id]/_components/SubmissionDetailAdmin.tsx, apps/frontend/app/admin/contest/[id]/participant/[userId]/_components/SubmissionColumns.tsx, apps/frontend/components/DataTableAdmin.tsx
source code가 submission detail modal을 넘어가는 문제를 직접 높이를 지정함으로써 해결하고 'Test case' 사이 띄워쓰기를 제거하였으며, 표 간격도 조절하였습니다. submission table에서 accepted가 초록색으로 표시되지 않는 문제도 같이 해결했습니다.
closes TAS-980
closes TAS-999
---
=> fix(fe): prevent submission detail modal overflow

apps/frontend/app/admin/contest/_components/ImportProblemTable.tsx, apps/frontend/app/admin/contest/create/page.tsx
이미 임포트된 문제들의 순서를 유지하도록 합니다.
다음과 같은 정책을 따릅니다. 
```
기존 문제들은 오름차순대로 순서 유지 && 빈 번호를 채워서 앞으로 당겨짐. 새 문제는 뒤에 차례대로 추가됨.
예시 1) 기존 문제 A(0), B(1), C(2) 존재하는 상황에서 B를 삭제하고 새 문제(D, E)를 추가한다고 가정
A(0), C(2->1), D(2), E(3)
예시 2) 기존 문제 A(0), B(0), C(2) 존재하는 상황에서 C를 삭제하고 새 문제(D, E)를 추가한다고 가정
A(0), B(0), D(1), E(2)
```
https://github.com/user-attachments/assets/58f2cc9d-067f-4138-b90c-d1aeb8179067
closes TAS-979
---
=> fix(fe): restore the imported problem order

apps/frontend/components/EditorHeader.tsx
Submit과 Save에 대해 공통적으로 `Successfully saved the code` 토스트 노출
Submit인 경우 `Successfully submitted the code` 토스트 노출
Save나 Test의 경우 `Successfully saved the code` 토스트 노출
submissionId가 세팅되고 loading이 true인 상태여야 useInterval 안의 submission 탭으로 이동이 트리거 되는데
loading이 바로 false로 바뀌는 바람에 넘어가지 못하고 있었던 것 같습니다!
---
=> fix(fe): differentiate toast messages for save and submit actions

apps/frontend/app/(main)/settings/page.tsx
- Settings 에서 이름, 학과 변경할때 current password 입력하지 않아서 변경이 되지 않는 버그 해결
close TAS-1004
---
=> fix(fe): fix save button bug

apps/backend/apps/admin/src/contest/contest.service.ts
closes TAS-981
getContestScoreSummary 함수에서 불필요한 예외를 던지는 문제를 해결합니다.
---
=> fix(be): no not-found exception in get-score-summaries api

apps/infra/production/storage/database.tf, collection/client/environments/Stage.bru
Closes TAS-1006
RDS의 자동 업데이트가 허용 되어 있었으나, 테라폼 콘솔 내에서는 마이너 버전의 업데이트 이전 버전이 작성되어 있어 배포에 오류가 발생하고 있었습니다. 적어도 테라폼에서는 DB 버전의 다운그레이드를 지원하지 않습니다.
따라서, 메이저 버전만을 명시해 마이너 버전은 '현 상태'와 마찬가지로 자동으로 업데이트 되도록 버전을 "14.10" 에서 "14"로 재명시 하였습니다.
---
=> fix(infra): set portgres version to 14 to avoid downgrade errors and ensure latest minor updates

apps/frontend/components/EditorDescription.tsx
input, output description 에서 katex를 렌더링하지 않고 있습니다.
어드민에는 katex를 넣는 기능이 있지만, 클라이언트에서는 katex를 렌더링하지 않습니다.
페어가 맞지 않아 이를 변경합니다.
---
=> fix(fe): render katex in editor input, output description

apps/frontend/app/admin/contest/[id]/(overall)/@tabs/submission/_components/Columns.tsx, apps/frontend/app/admin/contest/[id]/_components/SubmissionDetailAdmin.tsx, apps/frontend/app/admin/contest/[id]/participant/[userId]/_components/SubmissionColumns.tsx, apps/frontend/app/admin/problem/[id]/_components/Columns.tsx, apps/frontend/app/contest/[contestId]/problem/[problemId]/submission/_components/Columns.tsx, apps/frontend/app/contest/[contestId]/problem/[problemId]/submission/_components/SubmissionDetail.tsx, apps/frontend/app/problem/[problemId]/submission/_components/Columns.tsx, apps/frontend/app/problem/[problemId]/submission/_components/SubmissionDetail.tsx, apps/frontend/components/TestcasePanel.tsx, apps/frontend/components/TestcaseTable.tsx, apps/frontend/lib/utils.ts, apps/frontend/tailwind.config.ts
- `getResultColor` 유틸 함수 생성
- 삼항 연산자로 작성하던 중복되는 코드들을 `getResultColor`로 대체
- tailwindcss dynamic classname 인식을 위해 safeList에 추가
Closes TAS-957
건든 파일들 Result Color 적용됐는지 전부 확인 완료했습니다~
---
=> refactor(fe): create getResultColor and replace related codes

apps/frontend/app/admin/_components/table/DataTableMultiSelectFilter.tsx, apps/frontend/app/admin/_components/table/DataTableProblemFilter.tsx, apps/frontend/app/admin/contest/[id]/edit/page.tsx, apps/frontend/app/admin/contest/_components/ContestProblemColumns.tsx, apps/frontend/app/admin/contest/_components/ContestProblemTable.tsx, apps/frontend/app/admin/contest/_components/ContestTable.tsx, apps/frontend/app/admin/contest/_components/ContestTableColumns.tsx, apps/frontend/app/admin/contest/_components/DuplicateContestButton.tsx, apps/frontend/app/admin/contest/_components/ImportProblemButton.tsx, apps/frontend/app/admin/contest/_components/ImportProblemTable.tsx, apps/frontend/app/admin/contest/_components/ImportProblemTableColumns.tsx, apps/frontend/app/admin/contest/create/page.tsx, apps/frontend/app/admin/contest/page.tsx, apps/frontend/app/admin/layout.tsx, apps/frontend/app/admin/problem/_components/ContainedContests.tsx, apps/frontend/app/admin/problem/_components/ProblemTable.tsx, apps/frontend/app/admin/problem/_components/ProblemTableColumns.tsx, apps/frontend/app/admin/problem/_components/ProblemsDeleteButton.tsx, apps/frontend/app/admin/problem/_components/UploadDialog.tsx, apps/frontend/app/admin/problem/page.tsx, apps/frontend/app/admin/user/_components/Columns.tsx, apps/frontend/app/admin/user/_components/UserTable.tsx, apps/frontend/app/admin/user/page.tsx
아래 컴포넌트들 리팩토링했습니다. 아래 순서대로 보시는게 리뷰하기 편할거예요!
- User table (`/admin/user`)
- Contest table (`/admin/contest`)
- Problem table (`/admin/problem`)
- Import problem table (`/admin/contest/create`, `/admin/contest/edit`)
- Contest problem table (`/admin/contest/create`, `/admin/contest/edit`)
자잘한 픽스들
- 어드민 페이지 레이아웃 픽스
- 필터 적용 시 페이지 인덱스 초기화 안되는 거 수정 (기존 data table admin에서도 안됐음)
---
=> refactor(fe): replace data table admin component to new components (1)

apps/backend/apps/client/src/submission/submission-sub.service.ts, apps/backend/apps/client/src/submission/submission.service.ts, apps/backend/libs/cache/src/keys.ts
Closes TAS-1008
기존 Test API 에서 각 테스트 케이스 결과를 반환하는 Redis key 가 unique 하지 않음을 발견했습니다. 이 때문에 API 서버 확장 시 공유 자원에 대한 경합이 발생하는 문제가 있었습니다. 이를 해결하기 위해 Redis key 를 unique 하게 구성하여 각 테스트 케이스 결과가 독립적으로 저장되도록 수정했습니다.
[특이사항]
프론트에서 polling 하고 있는 getTestResult API 는 기존에는 O(1) 의 비용으로 접근하였습니다. 이 PR 이 적용된다면 테스트케이스 개수가 k 일 때, O(k)의 비용이 발생하게 됩니다. 이는 여러 테스트 케이스의 결과를 개별적으로 접근해야 하기 때문입니다.
---
=> fix(be): update redis test key for race condition

apps/frontend/components/EditorLayout.tsx
contest editor의 문제 dropdown list에서 현재 풀고 있는 문제의 글자 색상을 변경하고 submit한 문제들의 오른쪽에 check icon을 표시하도록 개선하였습니다. figma에는 아이콘의 크기가 12px이라고 명시되어 있으나 margin 차이 문제인지 비교했을 때 너무 작아서 일단 제 임의대로 16px로 설정했습니다.
closes TAS-1014
---
=> feat(fe): improve editor problems dropdown list ui

apps/backend/apps/admin/src/contest/contest.service.ts, apps/backend/apps/admin/src/problem/problem.resolver.ts, apps/backend/apps/admin/src/problem/problem.service.ts, collection/admin/Problem/Update ContestProblems Scores/Succeed.bru
contest problem을 수정하는 API가 존재하지 않아 이를 수정하는 API 만드는 작업을 하였습니다
order를 수정하는 api는 이미 있고, score말고 수정해야 하는 필드가 없어서 score만 수정하는 방식으로 구현하였습니다.
UseRolesGuard 필요할 것 같아서 일단 적용시켜놨는데 밑에 order같은 경우에는 UseRolesGuard 없어서 이거 관련해서 좀 알려주세요
---
=> feat(be): make update contest probelm score api

apps/frontend/app/(client)/(code-editor)/_components/EditorHeader/EditorHeader.tsx, apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/AddUserTestcaseDialog.tsx, apps/frontend/stores/editor.ts
- 브라우저 뒤로가기 버튼 눌렀을 때 json parsing error 발생하는 거 수정
- 코드 저장 방식 변경됨에 따라 이전에 local storage에 저장된 코드 가져오는 방식 수정
+) user testcase textarea placeholder 추가
기존 코드 저장 방식: `JSON.stringify`, `JSON.parse` 사용 (asdf => "asdf" 이렇게 저장됨)
하지만 code가 문자열인데 애초에 stringify 처리할 필요가 없었고 없앴더니 "asdf" 이렇게 표시됨.
local storage 버저닝보다는 `JSON.parse`를 호출해 코드 저장 방식 바뀌기 전에 저장된 코드인지 확인하여 처리
---
=> fix(fe): fix json parsing error in the code editor

apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/AddUserTestcaseDialog.tsx, apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/TestcasePanel.tsx, apps/frontend/app/(client)/(code-editor)/_components/WhitespaceVisualizer.tsx
무한 루프로 print 하는 등 output이 너무 커질 경우, 
길이 제한을 두어 클라이언트가 터지는 것을 방지했습니다.
현재 기준은 10만자로 설정했으며, 기획팀과 논의 후 확정되면 수정하겠습니다.
추가로 10만자가 넘어가면 Input Output 상관 없이
WhitespaceVisualizer에서 visualize 과정을 skip 합니다.
정리하자면 Test 기능에서 Output의 경우에만 10만자를 넘어가면 10만자까지만 slice 해서 보여주고
모든 곳에서 사용하는 WhitespaceVisualizer에서 10만자를 넘어가는 경우 visualize를 안합니다.
- Wrong Testcase Number에서 Sample / User 구분하도록 수정
- AddTestcaseModal에서 Sample Testcase resize 안되던 버그 해결
---
=> fix(fe): truncate huge size output

apps/frontend/app/admin/contest/[contestId]/_components/ContestOverallTabs.tsx
- Excel 파일 문제별 점수가 모두 추출되지 않는 문제 발생
- 해당 문제 발생 이유: scoreData를 사용해서 problemId를 가져오기에 user가 제출하지 않은 경우 배열에 problemId 포함 X 
- GET_CONTEST_PROBLEMS에서 problemId를 가져오는 방식으로 수정
[문제 해결]
<화면>
<엑셀 파일>
closes TAS-1055
---
=> feat(fe): fix excel export score data

apps/frontend/app/(client)/(code-editor)/_components/EditorHeader/RunTestButton.tsx
```
"userTestcases": [
{
"id": 1,
"in": "1 1",
"out": "2"
}
]
```
`input` `output`이 아닌 `in` `out` 이었습니당..
이제 정상적으로 채점되는 것을 확인할 수 있습니다!
Closes TAS-1068
---
=> fix(fe): fix user testcase judging bug

apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/TestcaseTable.tsx, apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/useTestResults.ts
- 확인된 문제: 테스트 시 모든 테스트 케이스들이 채점이 되는데 백엔드 응답 속도가 빨라서 (특히, user testcase 결과 가져올 때) 채점이 안된 것처럼 보일 수 있음. 😮 
- 해결 방법: 테스트 중이라면 Judging 텍스트를 보이도록 해 테스트 했다는 것을 사용자가 인지할 수 있게 함.
closes TAS-1071
+) 추가 버그 수정: polling 시도 횟수 초기화
https://github.com/user-attachments/assets/9a33b186-80c8-4c69-a331-786c3c78aa93
---
=> fix(fe): show "Judging" text while testing

apps/frontend/app/(client)/(code-editor)/_components/EditorResizablePanel.tsx, apps/frontend/app/(client)/(code-editor)/_components/context/TestcaseStoreProvider.tsx
유저 테스트케이스가 저장될 localStorage key에 contestId 값을 추가해 contest가 다를 경우 user testcase를 공유하지 않도록 합니다.
> 시험에 연습했던 problem이 그대로 출제되었을 경우에 user testcase가 그대로 남아있는 문제가 생길 수 있으므로, contest가 다를 경우 user testcase를 공유하지 않도록 수정해주시면 감사하겠습니다
closes TAS-1070
---
=> fix(fe): fix bug with user testcases remaining in the contest

apps/frontend/app/(client)/(code-editor)/contest/[contestId]/finished/problem/[problemId]/page.tsx
대회가 끝나서 exit 버튼을 누르면 contest main page가 아닌 contest problem list로 가도록 변경합니다. 
closes TAS-1062
---
=> fix(fe): change finished contest exit to route contest problem list

apps/backend/apps/admin/src/contest/contest.service.ts, apps/frontend/app/admin/contest/_components/DuplicateContestButton.tsx
Frontend change: duplicate contest button이 disabled 되었을 때 tooltip이 제대로 적용되지 않는 문제를 해결합니다.
참고: https://github.com/shadcn-ui/ui/issues/1022
Backend change: duplicate contest를 할 때 contest problem Score도 같이 복제합니다. 
---
=> fix: fix duplicate contest bugs

apps/frontend/app/admin/contest/[contestId]/_components/ContestOverallTabs.tsx
**<디자인&버튼 관련>** 
- isCurrentTab return 부분 편집으로 인한 Contest Overall tab UI 선택 표기 오류를 해결하였습니다.
**<헤더 관련>** 
- Excel 파일 추출 내역에 username을 추가하였습니다. 
- Excel 파일 추출 헤더 순서를 Contest Overall 페이지에서 보이는 순서와 일치시켰습니다. 
- 헤더 부분 표기에 만점/총/배점 정보를 추가하였습니다. 이로 인해 csvData에는 해당 점수만 표시합니다.
**<csvData 관련>**
- 제출 전부 완료 시 별도의 Submit 텍스트가 아니라, 제출한 개수를 동일하게 표시합니다. 
- 제출하지 않은 문제의 경우 '0'이 아니라 '-'로 미제출을 표시합니다. 
- 총 획득 점수와 세부 problem 점수의 경우 _1. 소수점 3자리까지 2. 반올림 없이_ 표시합니다. 
closes TAS-1054
closes TAS-1056
closes TAS-1063
---
=> fix(fe): fix excel export

apps/frontend/app/admin/contest/_components/ContestProblemColumns.tsx
- Contest Create 및 Edit에서 score sum이 계산이 안됨
- 근데 새로고침을 하니까 갑자기 계산이 됨
Input에 들어가는 `defaultValue`를 `value`로 수정하니 해결되었습니다
`defaultValue`는 첫 렌더링 때만 유효하고
`value`는 필드 값이 상태에 따라 변경되기 때문에
점수가 불러와지거나 수정될 때 바로바로 반영됩니다!
Closes TAS-1060
---
=> fix(fe): fix score sum bug

apps/frontend/app/admin/problem/[problemId]/edit/_components/BelongedContestTable.tsx, apps/frontend/app/admin/problem/[problemId]/edit/_components/ScoreCautionDialog.tsx
**문제 상황**
1. 문제의 테스트 케이스 별 점수 수정 후, 해당 문제를 포함하는 contest에서의 배점을 0점으로 설정
2. 다시 문제의 테스트 케이스 별 점수 수정 후 ScoreCautionDialog이 나왔을 때 위의 단계에서 0점으로 설정했던 contest가 여전히 수정 전 배점으로 표시됨
**문제 원인 및 해결 방안**
해당 데이터를 가져오는 api가 ScoreCautionDialog에 2번째 접근 시에는 호출되지 않았기 때문이다. 이 API는 useSuspenseQuery를 통해 호출되고 있었다. 
https://github.com/apollographql/apollo-client/issues/10478
위의 issue를 보면 useSuspenseQuery 가 cache 업데이트를 감지하지 못하는 문제가 있어서 해결했음을 확인할 수 있다. 현재 우리가 사용하는 apollo/client 버전에서 적용이 되어야 맞다. 왜 지금도 안되는지 모르겠지만 빠른 문제 해결을 위해 `fetchPolicy: 'network-only'` 를 추가했다.
close TAS-1073
=> fix(fe): add fetch policy to useSuspenseQuery

apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/TestcasePanel.tsx, apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/TestcaseTable.tsx, apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/useTestResults.ts, apps/frontend/types/type.ts
User testcase id와 기존에 존재하던 Sample testcase id가 함께 관리되어 발생하는 id문제를 해결하였다. 예로, Sample testcase가 2개 추가된 상태에서 User testcase를 추가하면 #3번째 id가 부여되는 문제를 User testcase는 따로 #1부터 시작하도록 하였다.
---
closes TAS-1057
=> fix(fe): differentiate sample and user id

apps/frontend/app/admin/contest/[contestId]/_components/SubmissionDetailAdmin.tsx, apps/frontend/components/shadcn/alert.tsx
Testcase가 수정되면, 기존 Testcase는 삭제되고 새로운 Testcase가 생성되게 됩니다.
이때 기존 Submission들의 Testcase Judge Results(SubmissionResult model) 는 모두 삭제되므로 (Cascade 설정), 채점 결과를 불러오더라도 Testcase별 채점 결과를 볼 수 없습니다.
이때, Testcase Judge Results Not Available이를 Alert 박스 안에 보여주어 사용자가 인지할 수 있도록 합니다.
AdminSubmissionDetail 모달의 Layout도 약간 조정하였습니다. 
사진 참고해주세요
closes TAS-1078
closes TAS-1078
---
=> feat(fe): add testcase judge results not available alert when testcase is outdated

apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/TestcasePanel.tsx
Wrong Testcase Number를 보여줄 때 Judging 상태인 testcase들도 표시되는 문제를 픽스합니다.
**AS-IS**
https://github.com/user-attachments/assets/498cd529-1051-4f92-8bd7-bb3cbe7e39d7
**TO-BE**
https://github.com/user-attachments/assets/90bc4fef-1429-485e-8af2-4d8cda9a4b62
closes TAS-1087
---
=> fix(fe): fix wrong testcase summary ui

apps/frontend/app/(client)/(code-editor)/_components/ContestProblemDropdown.tsx, apps/frontend/app/(client)/(code-editor)/_components/EditorDescription.tsx, apps/frontend/app/(client)/(code-editor)/_components/EditorHeader/EditorHeader.tsx, apps/frontend/app/(client)/(code-editor)/_components/EditorLayout.tsx, apps/frontend/app/(client)/(code-editor)/contest/[contestId]/problem/[problemId]/layout.tsx, apps/frontend/app/(client)/(code-editor)/contest/[contestId]/problem/[problemId]/page.tsx, apps/frontend/app/(client)/(code-editor)/problem/[problemId]/layout.tsx, apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/_components/GoToFirstProblemButton.tsx, apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/_components/RegisterButton.tsx, apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/page.tsx, apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/problem/page.tsx, apps/frontend/app/(client)/(main)/contest/[contestId]/_libs/utils.ts, apps/frontend/app/(client)/_libs/apis/contestProblem.ts, apps/frontend/app/(client)/_libs/apis/types.ts, apps/frontend/app/(client)/_libs/queries/contestProblem.ts, apps/frontend/app/(client)/layout.tsx, apps/frontend/package.json, apps/frontend/types/type.ts, pnpm-lock.yaml
```
app/(client)/_libs
- apis
- contestProblem.ts
- problem.ts 
- contest.ts
- notice.ts
- submission.ts
- type.ts (공용 타입)
- queries
- contestProblem.ts 
```
**`apis` 폴더**
- API 호출 함수, request params 타입 관리, response 타입 관리
- 여기저기서 선언되던 api response 타입들을 한 곳에서 관리합니다.
- API 호출 함수를 사용함으로써 따로 타입 선언을 하지 않아도 됩니다.
- 만약 백엔드 API 응답이 수정되면 한 곳에서만 타입 수정하고, 나머지 타입 에러들을 고치면 됩니다.
- 리팩토링 하면서 실제 백엔드 API 응답과 다르게 선언된 타입들을 고칠 수 있었습니다.
- 여기서 선언된 API 호출 함수들은 `safeFetcher(WithAuth)`를 사용해야 합니다.
**`queries` 폴더**
- query 옵션 관리
- 쿼리 키는 계층적 구조를 따릅니다. 자세한 내용은 아래 블로그를 참고해주세요~
- 참고: [Query Keys를 관리하는 기준과 방법](https://velog.io/@bo-like-chicken/Query-Keys%EB%A5%BC-%EA%B4%80%EB%A6%AC%ED%95%98%EB%8A%94-%EA%B8%B0%EC%A4%80%EA%B3%BC-%EB%B0%A9%EB%B2%95)
- `RegisterButton` 컴포넌트 리팩토링 (`useEffect` -> Tanstack Query)
1. API 호출 함수, …
=> refactor(fe): use tanstack query for client-side data fetching

apps/frontend/app/(client)/(main)/_components/ProblemCard.tsx, apps/frontend/app/(client)/(main)/_components/ProblemCards.tsx, apps/frontend/app/(client)/(main)/page.tsx, apps/frontend/app/(client)/(main)/problem/_components/Columns.tsx, apps/frontend/app/(client)/_libs/apis/problem.ts, apps/frontend/types/type.ts
- `ProblemCards` 컴포넌트를 서버 컴포넌트로 변경합니다. (`useEffect` 제거)
- 타입 수정: `Problem` 타입과 `ContestProblem` 타입이 서로 의존하지 않도록 분리하고, Bruno에서 테스트한 대로 타입 수정합니다.
- Problem 테이블에서 info 컬럼 삭제합니다. (백엔드 응답에 `info`가 없고, 피그마에도 이 컬럼이 없어서 삭제했습니다.)
closes TAS-1094
---
=> refactor(fe): change problem cards component to server component

apps/backend/apps/admin/src/contest/contest.service.ts
문제를 생성하고나서 대회에 속하지 않을때에 belongend contest modal이 렌더링되지 않는 이슈를 해결합니다. 
백엔드에서 belonged contest api를 불렀을 때에 문제가 대회에 속하지 않으면 에러가 아닌 빈 리스트를 반환합니다.
프론트엔드 예외처리도 추가해야하지만, 핫픽스이니 이정도로 진행합니다
---
=> fix(be): fix belonged contest modal issue

apps/infra/production/codedang/codedang_iris.tf, apps/infra/production/codedang/codedang_service_iris.tf, apps/infra/production/codedang/modules/service_autoscaling/appautoscaling_scale_up.tf
가정 : 128MB 메모리제한 문제, 시간제한 2~3초, 테스트케이스 10개 이내. 
128MB 메모리제한이고 테스트케이스 10개를 가진 문제에 대해 안정적인 채점을 체공하려면, **IRIS 컨테이너는 1.28GB 이상의 메모리를 가져야 합니다.** 
이에 따라 IRIS 컨테이너 스펙을 조정합니다.
---
=> fix(infra): change iris spec for stability in parellel grading

apps/iris/src/handler/judge-handler.go
병렬적으로 처리되고 있던 tc 채점을 직렬화합니다.
---
=> feat(iris): serialize testcase judging

apps/iris/src/common/constants/constants.go, apps/iris/src/handler/judge-handler.go
코드 실행 결과 발생하는 출력의 길이를 제한합니다.
** 몇 자로 제한할지 결정 필요함
---
=> feat(iris): limit judge result output

apps/backend/apps/client/src/submission/submission.controller.ts, apps/infra/production/codedang/codedang_service_client.tf, apps/infra/production/codedang/codedang_service_iris.tf, apps/iris/src/common/constants/constants.go, apps/iris/src/handler/judge-handler.go
테스트케이스 채점을 직렬화하고 코드 실행 중 발생하는 출력의 크기를 제한합니다.
---
=> feat(iris): serialize testcase judging and limit output size

apps/frontend/app/admin/problem/_components/TestcaseItem.tsx
admin - problem - TestcaseItem.tsx 에서 점수 비율 반영하는 input 태그 위에서 스크롤시 의도치 않은 값 변경이 이뤄지는 문제점을
event handler를 사용해서 blur처리하여서 해결하였습니다
---
closes TAS-1124
=> fix(fe): fix mouse scroll cursor problem

apps/frontend/components/auth/HeaderAuthPanel.tsx
(before)
(after)
드롭다운 리스트 열었을 때 화살표 아이콘이 회전하도록 수정했습니다.
closes TAS-756
=> fix(fe): fix drop down button rotate

apps/backend/Dockerfile
Alpine Linux 3.21를 base image로 하는 node 20.18.1-alpine version과 
prisma 5.x 호환성 문제로 node.20.18.0으로 revert합니다.
관련 이슈: https://github.com/prisma/prisma/issues/25817
prisma 6.x에서 문제가 해결되었으며, 
https://github.com/skkuding/codedang/pull/2275 에서 node 버전도 같이 업그레이드할 수 있게 하겠습니다.
---
=> revert(cd): revert node image version from 20.18.1 to 20.18.0

apps/frontend/app/(client)/(main)/_components/ContestCards.tsx, apps/frontend/app/(client)/(main)/_components/ProblemCards.tsx, apps/frontend/app/(client)/(main)/page.tsx
closes TAS-807
Contest/Problem 없을 시 타이틀이 보이지 않도록 수정하였습니다.
Contest/Problem 있을 때의 사진입니다.
Problem만 있을 때의 사진입니다.
둘 다 없을 때의 사진입니다.
- 둘 다 없을 때 어색해 보여서 Contest/Problem 이 없을 시 제목 밑에 No Contest / No Problem 이 있으면 좋지 않을까 제안해봅니다~
---
=> style(fe): delete the title if no data

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/leaderboard/page.tsx, apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/notice/page.tsx, apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/qna/page.tsx, apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/statistics/page.tsx, apps/frontend/app/(client)/(main)/contest/_components/ContestTabs.tsx
- Contest user 페이지 새로운 디자인 반영을 위해서 우선 Contest Tabs 5개로 늘림
- Overview, Notice, Leaderboard, Statistics, Q&A
- 우선 Overview 먼저 작업 예정이라서 나머지 4개의 탭은 밑에와 같이 임시로 'Temporary ~~' 문구 추가해놓았습니다.
closes TAS-1177
---
=> fix(fe): add temporary tabs for contest page

apps/frontend/app/admin/contest/create/page.tsx
문제 상황
create contest 스키마에서 `invitationCode`가 `nullable`로 설정되어 있었지만, 
초기값이 없어 `undefined`로 처리되고 있었습니다. 
이로 인해 `invitationCode`가 없을 때, 유효성 검사가 통과되지 못합니다.
해결 방법
초기에는 `nullable`을 `nullish`로 변경하는 방법을 고려했으나,
`invitationCode`의 초기값을 명시적으로 `null`로 설정하는 방식으로 해결했습니다.
---
=> fix(fe): resolve bug blocking contest creation without invitation code

apps/frontend/app/(client)/(main)/_components/Cover.tsx
배너 위 여백과 헤더의 height가 일치하지 않아 헤더의 디자인이 좋지 않게 보인다는 의견이 많아,
사용자 페이지의 배너 위 여백을 헤더와 일치하게 변경합니다.
AS-IS:
TO-BE:
---
=> fix(fe): align banner top margin with header height

apps/frontend/next.config.js, apps/frontend/package.json
작은 **pnpm dev 성능 비교** 실험
환경: Window OS, RAM 16GB, CPU 11th Gen Intel(R) Core(TM) i7
**실험 결과**
1. 기존
Ready까지 평균 6.1초, 처음 GET / 까지 평균 34.607
2. instrumentation만 제거
Ready까지 평균 1.66초, 처음 GET / 까지 평균 33.51
4. turbo만 적용
Ready까지 평균 3.2초, 처음 GET / 까지 평균 10.70
5. instrumentation 제거 + turbo 적용
Ready까지 평균 1.51초, 처음 GET / 까지 평균 11.08
**결론**
결과적으로 Ready 시간은 약 75% 감소했고, GET /  시간은 68% 감소했습니다. Ready까지의 시간 단축은 instrumentation 방지, GET /의 시간은 turopack 사용이 큰 영향을 미쳤습니다.
회의 때 말한 instrumentation.ts 관련 warining 문제는 turbo 활성화하니 나오지 않아서 따로 처리 하지는 않았습니다. 
+) turbopack이 지금 베타여서 기능이 온전하지 않을 수 있으니, 개발 중 수정하지 않은 부분에서 의문사한다면 --turbo 옵션을 제외하고 다시 해보길 추천드립니다! frontend/package.json의 scrpit 중 dev에서 `--turbo` 옵션만 지우면 됩니다
=> chore(fe): use turbo

apps/frontend/app/(client)/(main)/course/_components/FinishedAssignmentTable.tsx, apps/frontend/app/(client)/(main)/course/_components/FinishedTableColumns.tsx
요청해주신 contest의 FinishedTableColumns을 course에 복사해서 새로 import했습니다!
---
closes TAS-1253
=> feat(fe): copy FinishedTableColumns.tsx from contest to course

apps/frontend/app/(client)/(main)/course/_components/Dashboard.tsx
course dashboard의 디자인을 개선하였습니다! 전체적인 틀만 Figma와 비슷하게 하고 완성은 백엔드 Course와 Assignment가 완전히 구현됐을 때 할 예정입니다.
closes TAS-1235
---
=> feat(fe): modify course dashboard design

apps/frontend/app/(client)/(code-editor)/_components/EditorResizablePanel.tsx
- resize handle에 hover 됐는데 패널 사이즈 조절이 안됨
- 사실 resize handle은 기능이 없고 resize 가능하다는 표시일 뿐이었음
- resize handle에 hover나 active 효과가 있지만, 기능은 없음...
- 이는 resize handle로만 사이즈를 조절할 수 있다고 사용자에게 혼동을 줄 수 있음
- resize handle을 없애자!
패널 경계에 hover하면, 커서 모양이 바뀌기 때문에
사이즈 조절이 가능함을 사용자에게 알리기 충분하다고 판단했습니다
Closes TAS-1259
---
=> chore(fe): remove handle from resizable panel

apps/infra/stage/coolify/caddy/Dockerfile, apps/infra/stage/coolify/caddy/acme-challenge.caddy, apps/infra/stage/coolify/caddy/docker-compose.yml
서버 1에서 돌아가는 Coolify의 리버스 프록시인 Caddy의 설정을 기록하고, 
TLS certificate를 얻기 위한 세 가지 ACME Challenge 중 HTTP challenge나 TLS-ALPN challenge가 아닌 DNS Challenge를 이용하도록 변경합니다. (참고: [Caddy ACME Challenges](https://caddyserver.com/docs/automatic-https#acme-challenges))
Route53에서 DNS를 사용하기 위해 Dockerfile로 caddy-dns/route53 모듈을 설치하여 Caddy 이미지를 새로 빌드하고, 이를 기반으로 컨테이너를 띄웁니다. acme-challenge.caddy를 dynamic configure으로 caddy에 추가하여 DNS-01 challenge를 사용합니다. 
참고: Caddy wiki - [How to use DNS provider modules in Caddy 2](https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148)
Closes TAS-1228
- Caddy는 기본적으로 https://caddyserver.com/docs/automatic-https#dns-challenge 에 언급되어 있는 것처럼, 세 가지의 ACME Challenge를 사용할 수 있습니다.
- HTTP challenge와 TLS-ALPN challenge는 다음과 같은 이유에서 비효율적이라고 판단되었습니다:
- Caddy 로그를 확인해보았을 때 …
=> chore(infra): record coolify caddy changes and apply dns-01 challenge as acme protocol

apps/frontend/app/admin/contest/[contestId]/_components/ContestOverallTabs.tsx, apps/frontend/app/admin/contest/[contestId]/edit/_components/EditContestForm.tsx, apps/frontend/app/admin/contest/_components/ContestTable.tsx, apps/frontend/app/admin/contest/_components/ContestTableColumns.tsx, apps/frontend/app/admin/contest/_components/DuplicateContestButton.tsx, apps/frontend/app/admin/contest/create/_components/CreateContestForm.tsx, apps/frontend/graphql/contest/mutations.ts, apps/frontend/graphql/contest/queries.ts
Contest API에서 groupId 제거에 따른 mutations, queries 파일에서 groupId 제거
close TAS-1288
---
=> fix(fe): change mutations and queries file for gql

apps/backend/apps/client/src/submission/submission-pub.service.ts, apps/backend/apps/client/src/submission/submission-sub.service.ts, apps/backend/apps/client/src/submission/submission.service.ts, apps/backend/libs/cache/src/keys.ts
hotfix
Test, User Test API 호출에 대해 생성된 TestSubmission ID를 Cache Get/Set에 사용합니다.
UserId로 TestSubmission을 조작할 시, 생성된 TestSubmission 레코드 업데이트가 불가능한 문제를 해결합니다.
이제 Test / User-Test API 호출 시 일반 Submission과 마찬가지로 생성된 Test Submission 객체를 반환합니다.
---
=> fix(be): use test-submission id for test, user-test api

apps/backend/apps/admin/src/group/group.resolver.ts, apps/backend/apps/admin/src/group/group.service.spec.ts, apps/backend/apps/admin/src/group/group.service.ts, apps/backend/apps/admin/src/group/model/group.output.ts, apps/backend/prisma/migrations/20250222113752_add_ondelete_cascade_to_workbook_and_assignment/migration.sql, apps/backend/prisma/schema.prisma, collection/instructor/Course/Duplicate Course/Succeed.bru, collection/instructor/Course/Update Course/Succeed.bru
이전 학기의 Course를 추가하거나 같은 학기여도 같은 수업의 다른 분반을 만들기 위해 필요한 기능입니다.
---
Closes TAS-1306
=> feat(be): add course duplicate api

apps/backend/apps/client/src/submission/submission-sub.service.ts
hotfix
Test API로 제출된 코드 채점 도중 CompileError가 발생하는 경우 Judging이 무한하게 유지되는 버그를 수정합니다.
---
=> fix(be): infinite judging when compile error occurs

apps/frontend/app/(client)/(main)/_components/Cover.tsx, apps/frontend/app/(client)/(main)/contest/_components/ContestTabs.tsx
contest 배너와 탭 간격 수정하였습니다.(py-[22.5px])
---
closes tas-1365
=> style(fe): fix the gap between banner and Tap

apps/frontend/app/admin/_components/table/DataTableProblemFilter.tsx, apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/(overall)/@tabs/submission/page.tsx, apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/(overall)/layout.tsx, apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/participant/[userId]/_components/ScoreColumns.tsx, apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/participant/[userId]/_components/ScoreTable.tsx, apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/participant/[userId]/_components/SubmissionColumns.tsx, apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/participant/[userId]/_components/SubmissionTable.tsx, apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/participant/[userId]/page.tsx, apps/frontend/app/admin/course/[courseId]/assignment/_components/AssignmentProblemListLabel.tsx, apps/frontend/app/admin/course/[courseId]/assignment/_components/AssignmentTable.tsx, apps/frontend/app/admin/course/[courseId]/assignment/_components/AssignmentTableColumns.tsx
아까 깜박하고 못 만든 participant page를 만들었습니다. 특이사항으로는 datatableproblemfilter의 재사용을 위해 contestId뿐 아니라 groupId와 assignmentId를 받을 수 있게 확장하였는데, 오히려 코드가 더러워져 그냥 두 개로 분리할 걸 그랬나 싶기도 하네요... 어쨌든 작동은 잘 합니다.
\+ 사소하게 week column 없었던 거 추가
closes TAS-1358
assignments/_components의 AssignmentProblemColumns 파일을 보면서 미처 ContainedContests를 ContainedAssignments로 못 바꿨다는 걸 깨달았는데 백엔드의 GetAssignmentsByProblemId 코드를 보니 groupId를 받는 걸로 보아 현재 course 안에서 같은 문제를 공유하는 assignment들을 가져오는 것 같은데 뭔가 그러면 너무 쓸모없을 것 같아 일단 바꾸지 않고 냅뒀습니다. 관련해서 Figma에 댓글 남겼으니 한 번 확인해주세요!
P.S. 하루에 12시간 코딩하니까 죽을 것 같아요...
---
=> feat(fe): add instructor assignment participant page

apps/backend/apps/client/src/contest/contest.service.ts, apps/backend/apps/client/src/problem/problem.controller.ts, apps/backend/apps/client/src/problem/problem.service.ts, collection/client/Problem/Get Contest Problems/Succeed.bru
- 현재 contest problem controller에서 auth guard가 막고 있어, 로그인 하지 않으면 끝난 contest여도 문제 목록을 볼 수 없도록 되어있습니다.
- UserNullWhenAuthFailedIfPublic guard를 추가하여 이 문제를 해결하였습니다.
- userId 가 null인 경우를 고려할 수 있도록 service code를 수정하였습니다.
---
closes TAS-1383
=> feat(be): disable contest problems auth guard

apps/frontend/app/(client)/(main)/_components/StatusBadge.tsx, apps/frontend/app/(client)/(main)/course/[courseId]/_components/CourseInfoBox.tsx, apps/frontend/app/(client)/(main)/course/_components/CourseCard.tsx, apps/frontend/app/(client)/(main)/course/_components/CourseMainBanner.tsx, apps/frontend/app/(client)/(main)/course/page.tsx, apps/frontend/components/shadcn/carousel.tsx
Before:
After: 
보민님이 올려주신 것 이외에 추가로 `CarouselPrevious`, `CarouselNext` 버튼이 `-translate-y-1/2` 속성 때문에 위쪽으로 좀 튀어나오더라고요... Course List 뿐 아니라 유자차쪽 `ContestFeatureList` 쪽에서도 동일한 현상이 있는 듯해 한꺼번에 변경했습니다!
댓글로 남겨주신 Course 메인 페이지의 카드 및 My Course 타이틀의 가로 위치(가로 길이 전체 1440 기준 맨 좌측과의 간격 116)의 경우에는 제 짧은 지식으로는 기기 넓이에 따라 가로 간격을 픽셀 단위로 변경하는 게 어려울 것 같아 수정하지 않았습니다. 현재 `CourseCardList`의 최대 넓이가 `max-w-7xl`(1280px)로 설정되어 있는데 그냥 (1440-116*2=1208px)로 하면 되는 건지... 좋은 방법 있으신 분 알려주세요!!
closes TAS-1387
솔직히 2px 차이까지 눈치채고 알려주실 필요까진 없다고 생각했으나... 코드당이 건강해지는 과정이라고 생각하고 열심히 작업했습니다!! (그래도 앞으로는 좀만 눈을 작게 뜨고 확인해주셔도...ㅎㅎ)
---
=> feat(fe): change init design qa

apps/frontend/app/admin/_components/table/DataTable.tsx, apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/_components/Columns.tsx, apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/_components/ParticipantTable.tsx
기존에는 getHref를 통해 Row 단위로만 링크를 추가할 수 있었지만, columns.tsx에서 meta: link를 추가하면 Cell 단위로 링크를 이동할 수 있도록 변경했습니다. 솔직히 이렇게 Tanstack table의 meta를 활용해도 되는지 잘 모르겠고, type 관련해서도 좀 조잡하긴 합니다. 하지만 유저의 특정 문제 점수를 클릭했을 때 해당 문제로 이동하는 기능은 반드시 필요하겠다는 생각이 들어 이렇게라도 구현해야 할 것 같았습니다. 
결론: Management Course Grade Assignment Table에서 그냥 Row를 누르면 해당 유저의 첫 번째 문제로 이동, A / B / C 등 문제 Column의 Cell을 누르면 해당 유저의 해당 문제로 이동.
closes TAS-1386
---
=> feat(fe): improve management course grade table link

apps/backend/apps/admin/src/problem/problem.service.ts
changeVisibleLockTimeToIsVisible이 배열을 받으면 배열을, Problem 하나만 받으면 하나만 반환하도록 변경합니다..
~~찾기 어려웠어요 ㅠㅠㅠㅠ~~ 
---
=> fix(be): fix changeVisibleLockTimeToIsVisble not to convert type

apps/frontend/app/admin/problem/[problemId]/edit/page.tsx, apps/frontend/app/admin/problem/create/_components/CreateProblemForm.tsx, apps/frontend/app/admin/problem/create/page.tsx
admin 계정이 아닐 시 problem create에서 `isVisible` 값을 false로 고정하고 변경 불가능하게 하였으며, problem edit에서 역시 admin 계정이 아닐 시 `isVisible` 값을 변경 불가능하게 하였습니다.
Instructor 계정으로 들어간 problem create 화면: 
closes TAS-1408
---
=> feat(fe): lock problem isvisible false when not admin

apps/frontend/app/admin/user/_components/Columns.tsx, apps/frontend/app/admin/user/_components/UserTable.tsx, apps/frontend/graphql/user/queries.ts
`GET_GROUP_MEMBERS` 를  `GET_USERS` 로 대체
기존에 groupId: 1의 member 들만 UserTable에 노출됐었는데
드디어 group과 상관 없이 모든 user들이 보입니다!
role, canCreateCourse, canCreateContest, lastLogin, createTime 등이 Column에 추가되었습니다
---
=> fix(fe): modify user table query from group members to users

apps/backend/apps/admin/src/problem/problem.service.ts
create problem에서는 user role이 admin이 아닐 때 isvisible을 true로 변경하는 지 검사하지만, 
update 할 때는 이것을 검사하지 않아 아직 visible을 true로 변경할 수 있었습니다. 수정하지 못하도록 바꿉니다. 
---
=> fix(be): cannot make is visible on update problem when not admin

apps/frontend/components/auth/HeaderAuthPanel.tsx
모바일 환경에서 나오는 헤더 대신 나오는 드롭다운에 
Course를 추가하고, Management 사이드바도 최신 로직을 반영합니다.
추가적으로, 데스크탑 드롭다운을 펼치고 브라우저 창의 길이를 줄여 md 이하가 되었을 때 해당 dropdown이 보이지 않게 변경합니다.
closes TAS-1421
---
=> feat(fe): add course and fix management menu in mobile authModal

apps/frontend/app/(client)/(code-editor)/course/[courseId]/assignment/[assignmentId]/problem/[problemId]/submission/[submissionId]/page.tsx, apps/frontend/app/(client)/(code-editor)/course/[courseId]/assignment/[assignmentId]/problem/[problemId]/submission/_components/SubmissionPaginatedTable.tsx, apps/frontend/app/(client)/(code-editor)/course/[courseId]/assignment/[assignmentId]/problem/[problemId]/submission/page.tsx, apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/_components/Columns.tsx, apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/_components/ParticipantTable.tsx, apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/_components/EditorLayout.tsx, apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/_components/EditorResizablePanel.tsx, apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/_components/SubmissionSummary.tsx, apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/_components/SubmissionTestcase.tsx, apps/frontend/app/admin/course/[courseId]/grade/assignment/[assignmentId]/user/[userId]/problem/[problemId]/page.tsx
- submission 없을 때의 grade code-editor 구현했습니다 물론 여전히 finalScore 및 comment 입력은 가능합니다
- participant table에서 assignment가 finished가 아닐 때 토스트 노출하도록 했습니다
Closes TAS-1427
---
=> fix(fe): impl grade code editor without user submission

apps/frontend/app/(client)/(main)/_components/Cover.tsx
1. contest inner banner 또는 problem 배너의 이미지가 늦게 렌더링되는 문제가 있었습니다.
2. next 의 이미지 컴포넌트에서 사용할 수 있는 priority 속성을 활용하여 렌더링 속도를 빠르게 했습니다.
첫 번째 사진은 우선순위가 앞에 있지 않아 x-cache가 miss 된 모습입니다.
두 번째 사진은 캐시도 잘 들어가고, 우선순위가 높아져 렌더링이 빨라진 모습입니다.
closes.
---
=> chore(fe): put priority for Banner img

apps/frontend/app/(client)/(main)/course/[courseId]/grade/_components/SubmissionDetailModal.tsx, apps/frontend/app/(client)/_libs/apis/assignmentSubmission.ts, apps/frontend/app/(client)/_libs/queries/assignmentSubmission.ts
Get Assignment Submissions → 마지막 제출 결과만 필요한데 → 모든 제출결과가 오고 있어서 →
Get Latest Assignment Submission를 사용하도록 변경하였습니다.
closes TAS-1438
=> fix(fe): switch last submission api

apps/frontend/app/(client)/(code-editor)/_components/EditorHeader/EditorHeader.tsx, apps/frontend/app/(client)/(code-editor)/_components/EditorHeader/RunTestButton.tsx
1. 기존에 문제를 풀 때 유저케이스를 추가한 다음, submit을 누른 후 test를 누르면 터지지 않아야 하는 컨페티가 터지는 경우가 발생했습니다.
2. 컨페티는 useInterval 안에 있는데, useInterval 가 작동하는 조건은 isSubmitting 이 true일때와 submissionId가 true일 때 입니다.
3. 다른 컴포넌트(EditorHeader)에 있는 useInterval가 test 버튼을 눌렀을 때 작동하는 이유는 useInterval가 setIsSubmitting을 false로 바꾸기 전에 컨페티가 비동기적으로 터지기 때문이라고 생각했습니다. 
4. 따라서 test button 안에 isSubmitting 을 false 를 넣었습니다.
---
=> feat(fe): try to fix bug Confetti-add-setIsSubmitting

apps/frontend/app/(client)/(main)/_components/Header.tsx
- 맥의 라이브텍스트 기능 때문에 코드당 로고를 텍스트로 인식하여 커서가 저렇게 나옵니다.
- cursor-pointer만 적용해주면 해결됩니다.
---
Closes TAS-1446
=> fix(fe): fix codedang-with-text logo cursor bug

.github/workflows/rc-deploy.yml
PR #2537 의 rc-deploy workflow에서 rc-build-image workflow 호출을 checkout action이전에 중복해서 쓰는 오류를 해결합니다.
---
=> feat(fix): fixing rc workflow update

apps/frontend/app/admin/_components/ConfirmNavigation.tsx, apps/frontend/app/admin/_components/code-editor/CopyButton.tsx, apps/frontend/app/admin/_components/code-editor/EditorDescription.tsx, apps/frontend/app/admin/_components/code-editor/EditorSampleField.tsx, apps/frontend/app/admin/_components/code-editor/ReferenceDialog.tsx, apps/frontend/app/admin/_components/code-editor/WhitespaceVisualizer.tsx, apps/frontend/app/admin/problem/[problemId]/edit/page.tsx, apps/frontend/app/admin/problem/_components/PreviewEditorLayout.tsx, apps/frontend/app/admin/problem/_components/PreviewEditorResizablePanel.tsx, apps/frontend/app/admin/problem/create/_components/CreateProblemForm.tsx, apps/frontend/app/admin/problem/create/page.tsx
Problem Create/Edit 버튼 옆에 Preview 기능을 추가하였습니다. 서버에 저장된 값을 미리보는 게 아니라 현재 페이지 `Form`에 채워진 값을 가져와야 하기 때문에 createPortal와 methods.getValues를 이용하였습니다. CopyButton, EditorSampleField, ReferenceDialog, WhitespaceVisualizer는 client/(code-editor) 폴더에 있는 코드와 완전 동일하지만, 이를 위해 frontend/components 폴더로 옮기는 것은 맞지 않아 보여 일단 복붙해놓았습니다. 
closes TAS-1465
이번에는 API를 이용하지 않기 때문에 `EditorLayout` 관련 컴포넌트들을 새로 만들었지만, Problem Table이나 상세 페이지 등에서 쓰일 Preview 페이지는 #2544 에서 옮긴 `EditorLayout`을 이용할 예정입니다. 채점 화면의 왼쪽 패널과 Preview 화면의 왼쪽 패널은 아예 다르기 때문에 아무래도 prop을 하나 만들어 grade인지, problem preview인지 확인해서 `EditorDescription`을 다르게 적용해야 할 것 같습니다. 
템플릿 코드가 여러 개인 경우는 고려하지 않았는데, 그냥 그 때 가서 하는 게 맞을 것 같습니다...ㅎㅎ
---
=> feat(fe): add problem preview when creating or editting

.github/workflows/rc-deploy-target.yml, .github/workflows/rc-deploy.yml, apps/infra/rc/storage/database.tf
rc-deploy.yml과 rc-deploy-target.yml의 rc-deploy-codedang job에 종속되있던 ecs image build&upload image step이 별도의 job으로 분리되면서 rc-deploy-codedang job의 name을 image build&upload는 하지않고 deploy만 한다고 명시하였습니다.
또한, storage가 terraform apply될때마다 RDS instance설정이 변경되지 않았음에도 불구하고, 재생성되는 것을 방지 하도록 재생성을 강제하는 attribute인 RDS instance의 username의 변경사항을 테라폼이 재생성 여부를 결정할때 무시하도록 설정합니다.
---
=> feat(fix): fix update rc workflow (5) and remove repeated db replacement

.github/workflows/rc-deploy-target.yml
rc-deploy-target.yml에서 storage배포 옵션을 선택하였을때, 다시 storage폴더에서 terraform apply를 하는 것 만으로는 network변경사항을 storage폴더에 반영을 하지 못합니다. (terraform destroy후 terraform apply필요)
따라서, storage폴더에 테라폼 리소스가 없는걸 보장시킨후(리소스가 있다면 terraform destroy실행) terraform plan&appply실행을 함.
---
=> feat(infra): update rc workflow (6)

apps/frontend/app/(client)/(code-editor)/_components/EditorResizablePanel.tsx
좌측 패널을 열고 닫을 수 있는 버튼을 추가했습니다
패널 열림
패널 닫힘
Closes TAS-1455
---
=> chore(fe): implement hide panel button in code editor

apps/frontend/app/admin/_components/table/DataTableDeleteButton.tsx, apps/frontend/libs/utils.ts
DataTable의 기본 Delete모달을 수정하였습니다.
closes TAS-1477
=> feat(fe): redesign datatable delete modal

apps/backend/apps/admin/src/problem/problem.service.spec.ts, apps/backend/apps/admin/src/problem/problem.service.ts
버그 재현 방법
1. 문제를 2개 이상 import 한다
2. update contest problems order 시 order 배열에 중복 값을 넣어서 하나 이상의 problem Id를 포함하지 않도록 배열을 구성하여 요청한다 (ex. [1, 2, 3, 1, 1, 1])
3. 포함되지 않은 problemId 의 order가 -1이 된다
해결방법
contest problem 의 problemId 중 order에 포함되지 않는 것이 있다면 unprocessable data exception을 throw 하도록 한다.
---
closes TAS-1500
=> fix(be): throw error when contest problemId is missing from orders

.github/workflows/rc-mask-db.yml
RC서버에서 존재하는 관리자 계정을 admin계정에서 비번을 알고 있는 super계정으로 대체합니다. 그럼으로써 이전에는 RC에서 admin계정으로  비밀번호를 모르고 있어 로그인이 불가했지만, super계정을 비밀번호를 알고 있음으로 로그인이 가능할 것으로 예상합니다.
---
=> fix(infra): fix RC's superuser password problem

.github/workflows/rc-build-image.yml, .github/workflows/rc-deploy.yml, apps/infra/rc/storage/variables.tf
rc-deploy workflow중 codedang배포과정 중 중복되는 terraform destroy 구문을 제거하고, postgres및 rabbitmq username을 rc용 tfvars파일로 부터 각각 주입받습니다. 
rc-deploy workflow로 codedang폴더 배포 중, storage에서 생성된 rabbitmq username과 codedang에서 주입받는 rabbitmq username간 불일치가 발생하여 생긴 오류를 해결합니다. storage와 codedang폴더 모두 rc용 tfvars파일로 부터 각각 주입 받도록 바꿉니다. 
---
=> fix(infra): fix rc workflow and rabbitmq username mismatch

apps/frontend/app/admin/contest/[contestId]/edit/_components/EditContestForm.tsx
- change default score to 1 when importing problem to contest
closes TAS-1521
---
=> fix(fe): change default score to 1 when importing problem to contest

apps/frontend/app/admin/_components/FormSection.tsx, apps/frontend/app/admin/_components/TimeForm.tsx, apps/frontend/app/admin/_components/TitleForm.tsx, apps/frontend/app/admin/_components/VisibleForm.tsx, apps/frontend/app/admin/contest/[contestId]/edit/page.tsx, apps/frontend/app/admin/contest/create/page.tsx, apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/edit/page.tsx, apps/frontend/app/admin/course/[courseId]/assignment/create/page.tsx, apps/frontend/app/admin/problem/[problemId]/edit/page.tsx, apps/frontend/app/admin/problem/create/page.tsx, apps/frontend/components/shadcn/date-time-picker-demo.tsx
- admin contest create/edit 작업하면서 problem, course assignment created/edit 페이지의 레이아웃이 깨져서 레이아웃 수정 해놓았습니다
- 추가로 글씨 폰트 및 캘린더 아이콘은 유자차 피그마 디자인 기준으로 수정됐습니다
closes TAS-1526
---
=> fix(fe): change admin problem and course assignment create edit layout

apps/backend/apps/admin/src/contest/model/contest.input.ts, apps/backend/prisma/migrations/20250330014034_contest_description_nullable/migration.sql, apps/backend/prisma/schema.prisma, collection/admin/Contest/Create Contest/Succeed.bru
contest description이 null이어도 되는데, 현재는 그렇지 못하게 되어있어 수정합니다
closes TAS-1539
---
=> fix(be): contest description nullable

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/page.tsx
KatexContent 를 사용하여 tag가 적용되어 보이도록 하였습니다.
- 기존 more description
- 현재 more description
closes TAS-1543
---
=> fix(fe): contest more description cover with katex

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/leaderboard/error.tsx, apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/leaderboard/page.tsx
1. 현재 진행중인 대회일 때 error 페이지로 갈 수 있도록 하였습니다.
2. 끝난 대회의 데이터가 없을 때 데이터가 없음을 명시하였습니다.
---
=> feat(fe): make error handling of client leaderboard

apps/backend/apps/admin/src/assignment/assignment.service.spec.ts, apps/backend/apps/admin/src/assignment/assignment.service.ts
Management 페이지에서 isFinalScoreVisible이 true임에도 finalScore가 오지 않는 버그 해결
---
=> fix(be): fix finalScore not visible on management page bug

apps/backend/apps/admin/src/submission/submission.service.ts, apps/backend/prisma/migrations/20250331141128_optional_problem_testcase_io_field/migration.sql, apps/backend/prisma/schema.prisma
> Detail: https://www.notion.so/skkuding/Testcase-S3-180ef9cff54580459becdd2bfb2609f3?pvs=4
테스트케이스 값을 데이터베이스에서 S3로 migration하기 위해, `ProblemTestcase` 테이블의 `input`과 `output` field 값을 optional로 변경합니다.
- 앞으로 새로 생성되는 테스트케이스들은 `input`과 `output` 값이 null로 저장될 예정입니다.
- 대신 `input`과 `output`은 S3에 파일로 저장됩니다.
- 대부분의 마이그레이션이 완료되면, 기존 테스트케이스들도 S3에 파일 생성 후 `input`과 `output` 필드를 null로 변경 예정입니다.
- 모든 마이그레이션이 완료되면 `input`과 `output` 필드를 제거할 예정입니다.
---
=> feat(be): make ProblemTestcase input/output field optional for migration

apps/frontend/app/admin/problem/_components/CodeForm.tsx
Template 필드에서 내용을 전부 지우면 자동으로 토글이 닫혀버리는 버그를 해결했습니다.
`hasValue` 값의 변화에 따라 토글을 열고 닫는 로직에서, 사용자가 입력을 모두 지운 후 `setValue`가 트리거되면서 다시 `hasValue`가 `false`가 되고, 이에 따라 `useEffect`가 다시 호출되는 문제가 있었습니다. 이로 인해 의도치 않게 토글이 닫히는 현상이 발생했습니다.
이를 해결하기 위해, `CodeForm`이 초기 렌더링될 때만 `hasValue`를 기준으로 토글을 열지 말지를 결정하도록 수정했습니다. 이후에는 `hasValue`의 변화로 인한 불필요한 토글 상태 변경을 막아 UX를 안정화했습니다.
Closes TAS-1573
---
=> fix(fe): prevent toggle change when template is cleared

apps/frontend/app/(client)/(code-editor)/course/[courseId]/assignment/[assignmentId]/finished/problem/[problemId]/page.tsx
- 과제 마감기간이 지나서, 뒤로 돌아가려는 exit버튼을 누를때, Assignment Detail페이지로  이동합니다.
- 이전에 Info/Problem 탭이 분리됐을  당시, 로직이 그대로 남아있었어용..
---
=> fix(fe): route to assignment detail when click exit

apps/frontend/app/(client)/(code-editor)/_components/SubmissionTable.tsx, apps/frontend/app/(client)/(main)/_components/DataTable.tsx
client datatable에 링크가 연결되어 있을 때 `<Link>`가 아닌 `onClick={router.push()}`로 구현되어 있어서 해당 row를 Ctrl + 클릭하거나 우클릭을 통해 새 탭에서 여는 등의 동작이 불가능해 개선했습니다. admin에 도입하지 않은 이유는 버그도 있고, assignment grade의 경우 cell 단위로 링크가 연결되어 있는데, <Link>를 사용할 시 충돌이 발생할 수 있으며 애초에 grade 관련 대격변이 있을 것 같았기 때문입니다.
딱히 복잡한 건 없고 핵심은 그냥 TableRow를 `'table-row'` tailwind className을 가진 Link로 바꾼 것입니다.
closes TAS-1574
---
=> feat(fe): improve datatable link

apps/frontend/app/admin/contest/[contestId]/edit/_components/EditContestForm.tsx, apps/frontend/graphql/user/queries.ts
Edit Contest 에서 setManager 를 위해 getUsers 를 queries.ts 에 추가하였습니다!
closes.
---
=> docs(fe): make another getUsers query for setManager

apps/frontend/app/(client)/(code-editor)/_components/EditorResizablePanel.tsx, apps/frontend/components/CodeEditor.tsx, apps/frontend/components/shadcn/scroll-area.tsx
코드 에디터에 글씨 크기 조절 버튼을 추가합니다.
- 글씨 크기는 최솟값 6px, 최댓값 120px로 설정했습니다.
- 글씨 크기가 기본값(16px)이 아니면 reset 버튼과 현재 글씨 크기를 보여줍니다. (애니메이션도 넣었어요!)
- 길게 누르면 글씨 크기가 빠르게 변경됩니다.
https://github.com/user-attachments/assets/e4cbce7b-1bd8-41a8-a84f-87d86838b7da
- 스크롤 관련해서 리팩토링 했습니다. (불필요한 `ScrollArea` 삭제)
- 이제 CodeEditor가 항상 height가 100%입니다. (어디를 클릭하든 커서 focus 가능!)
---
=> feat(fe): add zoom in/out button to code editor

apps/frontend/app/(client)/(code-editor)/_components/EditorResizablePanel.tsx
suspenseQuery를 useQuery로 바꿨습니다!
상황: 공용 컴포넌트에서 reactQuery의 useSuspenseQuery를 사용할 때
문제:  contestId가 있을 때는 문제가 없지만, contestId가 없는 경우에도 공용 로직을 유지하기 위해 다음과 같이 queryFn에서 null을 반환하는 구조를 사용함
const { data: freezeTime } = useSuspenseQuery({
queryKey: freezeQueryKey,
queryFn: () => {
if (!contestId) {
return Promise.resolve(null)
}
return fetchFreezeTime(contestId)
}
})
처음에는 문제가 없어 보였지만, 새로고침 등의 상황에서 React Query가 캐시된 null 값을 사용하지 않고, queryFn을 다시 실행하는 현상이 발생함
이때 Promise.resolve(null)을 반환하더라도, React Query가 이를 성공(fulfilled) 상태로 인식하지 못해,
Suspense fallback에서 빠져나오지 못하는 문제가  생김
이 문제는 queryKey에 contestId가 포함되지 않아 React Query가 쿼리를 제대로 식별하거나 캐싱을 활용하지 못한 것이 주요 원인으로 보임. 그래서 useQuery를 써서 suspense에 빠지지 않도록 바꿨습니당...
=> fix(fe): resolve freeze query error

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/leaderboard/_components/LeaderboardRow.tsx
원래 테이블 값에 마우스를 갖다 대면 submission이 나오도록 되있는데요,
unfreeze 상태인 값에 갖다 대면 나오지 않는 것이 맞는 것 같아서 그렇게 수정했습니다.
=> chore(fe): unactivate unfreeze tooltip

apps/backend/apps/client/src/assignment/assignment.service.ts, apps/backend/apps/client/src/problem/mock/problem.mock.ts, apps/backend/apps/client/src/problem/problem.service.spec.ts, apps/backend/apps/client/src/problem/problem.service.ts, apps/backend/apps/client/src/submission/submission.service.ts, apps/backend/apps/client/src/submission/test/submission.service.spec.ts
이제 무조건 judge result는 다 보여줍니다.
isHiddenTestcaseVisible이 false면 isHidden이 true인 테스트케이스는 학생에게 아예 없는 존재처럼 나타납니다.
또한, raw score는 이제 학생에게 보이지 않습니다. 
예) 
- 샘플테스트케이스 전부 맞았는데 히든테스트케이스에 오답이 있어도 isHiddenTestcaseVisible이 false일 경우 submissionResult는 Accepted
- TC Result에서 개수를 보여줄때 isHiddenTestcaseVisible이 false이면 히든 테스트케이스는 개수에 포함하지 않음
이번 배포때 급하게 포함되어야 해서 필드명을 변경하지 않고 isJudgeResultVisible을 그대로 사용했습니다. 추후 태스크에서 정리할 예정입니다.
Submission 모듈에서 assignment와 contest가 지독하게 엮여있는데(getSubmission), isHiddenTestcaseVisible로 필드명을 변경하게 되면 분기가 진짜 폭발할 것 같습니다... 아예 서로 메서드를 분리하는게 어떤지...?
---
Closes TAS-1597
=> feat(be): use isJudgeResultVisible as isHiddenTestcaseVisible

apps/frontend/app/(client)/(main)/course/[courseId]/_components/AssignmentAccordion.tsx, apps/frontend/app/(client)/(main)/course/[courseId]/_components/SubmissionDetailModal.tsx, apps/frontend/app/(client)/_libs/apis/assignmentSubmission.ts, apps/frontend/app/admin/_components/DescriptionForm.tsx, apps/frontend/app/admin/_components/TextEditor.tsx, apps/frontend/components/CodeEditor.tsx
- DarkMode여부에 따라서, 글자색을 다르게 했습니다.
- 제출하지 않은 경우에도, 모달을 열 수 있도록 했습니다.
- CodeEditor의 showZoom분기 위치를 수정하여, 보이지 않아야하는 막대를 없앴습니다.
---
closes TAS-1610
=> fix(fe): editor text color theme

apps/backend/apps/client/src/contest/contest.service.ts, collection/admin/User/Get Users/Succeed.bru
1. 대회 진행 중 freezeTime 이후에 제출했으나 여전히 오답일 경우에 leaderboard의 isFrozen 값이 true로 바뀌지 않는 오류를 수정합니다
2. get Users docs 수정 
---
=> fix(be): fix contest leaderboard frozen

apps/iris/main.go
status.codedang.com 은 현재 codedang.com과 codedang API, stage.codedang.com 등만 상태를 확인할 수 있습니다.
채점 서버인 Iris 서버 또한 uptime kuma로 상태를 확인하기 위해서 main.go에 goroutine으로 http request에 응답하는 코드를 추가했습니다.
closes TAS-1564
CORS 문제를 해결하기 위해 추가해 둔 코드가 올바른 것인지, 9999번 포트를 사용하고 있는데 이것이 괜찮은 것인지 확인해주세요.
docker-compose.yml을 확인했을 때 iris는 network_mode가 host이므로, 호스트의 9999번 포트를 공유하는 것 같습니다.
---
- [v] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [v] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [v] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue …
=> feat(infra): add goroutine in iris server for status check

apps/backend/apps/admin/src/submission/submission.resolver.ts, apps/backend/apps/admin/src/submission/submission.service.ts
Admin Guard가 걸려있는것을 없애고, getSubmission, getAssignmentLatestSubmission에서 요청한 유저가 해당 submission의 group leader인지 확인하는 로직을 추가했습니다.
---
=> fix(be): fix permission issues on getSubmission

apps/infra/production/network/cloudfront.tf, apps/infra/stage/server2/Caddyfile
#2613 에서 구현된 Submission download URL을 지원하기 위해 reverse proxy에서 admin API 서버로 forwarding하도록 수정합니다.
- Stage 환경: Caddyfile에 `/submission/download/*` handler 추가
- Production 환경: Cloudfront behavior에 `/submission/download/*`추가
Terraform plan 실행 결과 apply 완료 (diff 없음)
```
❯ terraform plan -lock=false -var-file=vars.tfvars
data.aws_cloudfront_origin_request_policy.allow_all: Reading...
data.aws_lb.client_api: Reading...
aws_route53_zone.codedang: Refreshing state... [id=Z02931601ELG5RAXUQ69W]
aws_eip.for_nat: Refreshing state... [id=eipalloc-00fc90e08dd7456c8]
data.aws_cloudfront_cache_policy.disable: Reading...
aws_vpc.main: Refreshing state... [id=vpc-0aa77aaba41d75afe]
data.aws_lb.admin_api: Reading...
...
aws_route53_record.certificate["codedang.com"]: Refreshing state... …
```
=> fix(infra): add submission download url to reverse proxy

.github/workflows/rc-destroy-target.yml, .github/workflows/rc-destroy.yml
새로 추가된 acm-validation폴더를 destroy하는 기능을 rc-destroy과 rc-destroy-target workflow에 추가하였습니다.
---
=> feat(infra): add destroy acm-validation folder functionality in destroy workflows

apps/infra/rc/codedang/fluentbit.tf
#2703 에서 생긴 codedang-internal bucket의 이름 충돌을 해결합니다
---
=> fix(infra): remove bucket name conflict in rc

apps/frontend/app/admin/problem/[problemId]/edit/_components/EditProblemForm.tsx
#2632 에서 `ProblemTestcase` model의 `input`, `output` field가 optional로 바뀌면서 frontend 페이지에서 타입 에러가 발생하였습니다.
추후 testcases만 get 또는 update할 graphql query/mutation을 만들 예정이지만, 그 전에 임시로 type 에러를 해결하기 위해 input/output field에 빈 string 값을 저장합니다.
---
=> fix(fe): use correct type of problem testcase from graphql schema

apps/frontend/app/(client)/(code-editor)/_components/EditorResizablePanel.tsx, apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/TestcasePanel.tsx
다가오는 NPC 대회에서 아직 'run' 기능을 제공하기엔 안정화가 되지 않았기 때문에 대회에서만 run 기능을 숨겨둡니다.
| Contest | Non-contest |
|----------|---------------|
| <img width="396" alt="image" src="https://github.com/user-attachments/assets/091ae19f-2c03-4b9c-bd39-feacdd259a2d" /> | <img width="369" alt="image" src="https://github.com/user-attachments/assets/53f4cce9-f82a-4f30-8124-b1f7d36fb4f6" /> |
---
=> feat(fe): hide 'run code' tab on contest

apps/frontend/app/(client)/(code-editor)/_components/EditorHeader/EditorHeader.tsx, apps/frontend/app/admin/contest/[contestId]/(overall)/@tabs/leaderboard/_components/LeaderboardUnfreezeSwitchDialog.tsx, apps/frontend/app/admin/contest/[contestId]/(overall)/@tabs/leaderboard/page.tsx
- Situation
admin의 leaderboard 페이지에서 unfreeze leaderboard 스위치 토글이 비활성화( 콘테스트가 끝나기 전에는 unfreeze 기능을 사용할 필요가 없으므로 비활성화돼있음!!! ) 돼있을 때, 체크 쪽으로 되어 있었는데 그 모습은 자연스럽지 않아보였습니다. 그 이유로 unfreeze가 비활성화돼있는 동안 스위치가 켜지지 않는 쪽으로 수정하였습니다. 
- lmplementation
토글이 deactivated 상태에서 switch 기본값을 false로 주었습니다.
바꾸기 전
바꾼 후
closes TAS-1619
=> fix(fe): fix switch toggle

apps/backend/apps/admin/src/contest/contest.service.ts, collection/admin/Contest/Get Contest/Succeed.bru
admin의 getContest api에 contest 참여자 정보 중 userId를 추가로 불러오도록 수정합니다.
---
=> chore(be): get participation info to admin get contest

apps/frontend/app/(client)/(code-editor)/_components/EditorResizablePanel.tsx
https://github.com/user-attachments/assets/fd07342f-f4d7-4e73-8ce7-36ce6d104629
좌측 혹은 TC Result 패널을 숨기는 버튼을 클릭하여 포커스된 상태에서
엔터키를 누르면 버튼이 동작되는 버그를 막기 위해
`HidePanelButton` 에서 Enter KeyDown을 막았습니다
Closes TAS-1599
---
=> chore(fe): disable enter key for hide panel button

apps/backend/apps/client/src/submission/class/judge-request.ts, apps/backend/apps/client/src/submission/class/judger-response.dto.ts, apps/backend/apps/client/src/submission/submission-pub.service.ts, apps/backend/apps/client/src/submission/submission-sub.service.ts, apps/backend/apps/client/src/submission/submission.service.ts, apps/backend/apps/client/src/submission/test/submission-pub.service.spec.ts, apps/backend/libs/constants/src/submission.constants.ts, apps/backend/prisma/migrations/20250508115525_add_canceled_on_result_status_enum/migration.sql, apps/backend/prisma/schema.prisma, apps/iris/src/handler/errors.go, apps/iris/src/handler/interface.go, apps/iris/src/handler/judge-handler.go, apps/iris/src/handler/resultCode.go, apps/iris/src/router/response.go
현재 구현으로 사용자가 코드를 제출할 경우 채점 서버는 해당 제출에 대해 모든 테스트케이스를 채점을 하려고 시도합니다. 
강의에서는 중간에 틀린 TC가 있더라도 점수를 계산하기 위해서는 모든 TC를 계산하는 것이 맞았기 때문에 그렇게 진행했었습니다. 
하지만, 대회의 경우에는 다음 두 가지 특성으로 인해, 하나의 TC라도 틀리면 그 이후에는 채점을 안하는 것이 좋다고 판단됩니다.
- 테스트케이스가 굉장히 많고 제출도 많아 로드를 최대한 줄이는 것이 중요하다.
- 대회는 ICPC Rule을 따르기 때문에, 하나의 TC라도 틀리면 문제가 틀린 것이 되기 때문에 모든 테스트케이스를 돌려볼 필요가 없다.
이에 따라, 이 PR에서는,
1. IRIS (채점 서버)에 `StopOnNotAccepted` 기능을 구현합니다. `StopOnNotAccepted` 기능이 활성화된 채점 요청은, 테스트케이스 중 하나라도 `Accepted`가 아니면 나머지 테스트케이스는 실제로 실행하지 않고 `CANCELED` 상태로 처리합니다.
- 이전 테스트케이스가 실패한 경우 이후 테스트케이스를 취소하는 로직 구현
- 취소된 테스트케이스 처리 로직을 sendCancelResults 함수로 분리
2. 백엔드에서는 대회에서만 `StopOnNotAccepted = true` 옵션을 주어 채점 요청을 보내도록 하였고, 그 외의 요청은 default(StopOnNotAccepted = False`로 처리합니다. 
테스트 결과 Canceled가 잘 작동합니다.
테스트 과정:
1. TC 4개 가진 문제 생성 -> 대회 생성 후 문제 import 
- …
=> feat(be): add feature to stop(cancel) judging once submission not accepted on a testcase

apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/edit/_components/EditAssignmentForm.tsx, apps/frontend/app/admin/course/[courseId]/assignment/_libs/schemas.ts, apps/frontend/app/admin/course/[courseId]/assignment/create/_components/CreateAssignmentForm.tsx
gql 스키마 충돌을 피하기 위해 
`createAssignment` 와 `updateAssignment` 2개의 mutation에서
`dueTime` 을 임시로 `endTime` 과 동일하게 설정했습니다.
Closes TAS-1703
> [!NOTE]
> 향후에는 dueTime을 인풋으로 받아 별도로 처리하도록 수정할 예정입니다.
---
=> fix(fe): set dueTime to be equal to endTime temporarily

apps/frontend/app/(client)/(code-editor)/_components/EditorResizablePanel.tsx, apps/frontend/app/(client)/(code-editor)/_components/context/ReFetchingSubmissionStoreProvider.tsx, apps/frontend/app/(client)/(code-editor)/contest/[contestId]/problem/[problemId]/submission/_components/SubmissionPaginatedTable.tsx
>[!Note]
> contest의 submission tab에 새로고침 버튼을 추가했습니다!
**왜?**
>[!Warning]
> submission이 leaderboard가 새로고침하는 것을 보고 부러움을 느꼈기 때문 ㅠㅠ
진짜 이유: Contest Submission에서 테스트케이스별로 채점 결과가 나오는데, 2초 간격으로 10번까지 결과를 가져온 이후에는 결과 업데이트가 안되어서, 하드 리프레쉬(Ctrl + R)를 해야만 결과가 다시 가져와 집니다.
그래서 Soft refresh가 가능하도록 하기 위해서 submission refresh 버튼을 추가!
---------------
구현은 leaderboard refresh와 마찬가지로 zustand를 이용해서 refreshTrigger 변수를 handling 하는 방식으로 했습니다. 
화면으로 보면 다음과 같습니다. 
closes TAS-1671
=> feat(fe): add refresh button on submission tab

apps/backend/apps/admin/src/contest/contest.service.spec.ts, apps/backend/apps/admin/src/contest/contest.service.ts, apps/backend/apps/admin/src/contest/model/contest.input.ts, collection/admin/Contest/Update Contest/Succeed.bru, collection/admin/Contest/Update Contest/[ERR] Limited Modifiable Fields in Ongoing Contest.bru
Contest가 진행중일 때(Ongoing) 수정 가능한 필드를 제한합니다.
- Ongoing 상태에서는 End Time, Freeze Time만 수정 가능하도록 제한
- 단, Freeze Time의 경우 현재 시각이 Freeze Time 이전이어야 하고, 변경된 Freeze Time은 기존 Freeze Time 이후여야 함
---
=> feat(be): change editable items in ongoing contest

apps/backend/apps/admin/src/contest/contest.module.ts, apps/backend/apps/admin/src/contest/contest.resolver.ts, collection/admin/Contest/Get Contests/Succeed.bru, collection/admin/Notice/Get Notices/Succeed.bru
Admin Get contest 시 생성자에 대한 정보(createdBy)가 return되지 않고 있습니다.
resolve field를 사용하여 이를 해결합니다.
- n+1 문제가 발생합니다.
다음의 PR에서 해결 완료 후 머지될 때 같이 반영하겠습니다
https://github.com/skkuding/codedang/pull/2682
---
=> feat(be): add createdBy in contest resolver

apps/backend/libs/constants/src/submission.constants.ts
로드 테스트 중 발견된 오류를 수정하였습니다.
Python 실행 시 cputime 제한 조건을 (cputime)*3 + 2 로 수정
---
=> fix(be): update python3 cputime limit

apps/frontend/app/admin/contest/[contestId]/edit/page.tsx, apps/frontend/app/admin/contest/_components/DisableCopyPasteForm.tsx, apps/frontend/app/admin/contest/create/page.tsx
기획 변경에 따라 admin page의 enable copy paste 문구를 disable copy paste로 변경하였습니다! 그리고 변경에 알맞게 switch의 true/false 여부를 설정하였습니다. 
Contest create/edit 각 페이지에서 변경된 화면을 확인할 수 있습니다.
>[!Note]
> enableCopyPaste 변수명을 변경하는 것은 큰 작업으로 예상되어... (백엔드 속성명도 enableCopyPaste니까!) 
> enableCopyPaste 변수명을 유지하면서 ui에서 반대로 값을 보여주는 형태로 구현하였습니다. 
closes TAS-1717
=> feat(fe): make enableCopyPaste UI to disableCopyPaste UI in contest create/edit

apps/frontend/app/(client)/(code-editor)/_components/EditorHeader/EditorHeader.tsx
기획 변경에 따라 코드에디터의 버튼 위치를 다음과 같이 수정합니다. 
콘테스트를 포함한 모든 에디터를 사용하는 화면에 적용됩니다.
problem, assignment, contest의 code editor 모두에서 위와 같은 모습으로 보이는 것입니다.
공통 컴포넌트이므로 BOXERCAT 님을 리뷰어로 지정합니다!
> [!TIP]
> 리뷰어들에게 꿀팁! 이 코드는 그냥 컴포넌트의 위치만 복붙으로 바꿔준 것입니다! css나 문법 같은거를 꼼꼼히 봐주지 않아도
> 문제 없을 거에요! 여러분 화면에서도 위와 같이 보이는 지, 버튼은 잘 동작하는 지와 같은 것들을 위주로 봐주시면 좋을 것 같아요!
closes TAS-1719
=> feat(fe): change code editor header buttons position

apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/(overall)/@tabs/assessment/_components/Columns.tsx, apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/(overall)/@tabs/assessment/_components/ParticipantTable.tsx
- raw score 없애고 final score 이름 total로 바꾸기
- csv에서도 마찬가지로 다운 받으면 raw score 없고 total 만 있음
- Switch랑 CSV Download 버튼 UI 수정
---
=> chore(fe): modify assignment detail assessment ui

apps/frontend/app/(client)/(code-editor)/_components/EditorHeader/EditorHeader.tsx, apps/frontend/app/(client)/(code-editor)/_components/EditorResizablePanel.tsx, apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/TestcasePanel.tsx
Continue from #2716
Contest에서 run 버튼과 탭을 모두 표시하지 않습니다. (기존 PR에서는 탭만 지웠네요...)
---
=> fix(fe): hide run button and tab on contest

apps/backend/apps/admin/src/contest/contest.service.ts, apps/backend/apps/admin/src/problem/services/problem.service.ts, apps/backend/apps/client/src/contest/contest.service.ts
대회 종료 후 문제 공개가 가능하도록, Contest Admin/Manager에게 Visible 설정 권한을 추가 부여합니다.
> [!NOTE]
> 현재 Admin 이상의 권한이 없으면 문제의 Visible 설정이 불가능합니다.
> (Super, Admin 계정만 설정 가능)
---
=> fix(be): extend contest problem visible authority

apps/frontend/app/admin/contest/_components/ContestTable.tsx, apps/frontend/app/admin/contest/_components/ContestTableColumns.tsx
admin contest list가 올바르게 sorting된 상태로 나타나지 않는 문제가 있었기에 이를 해결했습니다. 
As is
To be
closes TAS-1654
=> chore(fe): change default sort algorithm

apps/frontend/app/(client)/(code-editor)/_components/ReferenceDialog.tsx
1. PyPy3을 지원하게 되어 code editor의 documentation modal의 table에 PyPy3 row를 추가하였습니다. 
2. **time limit**과 **memory limit** 표시를 추가하였습니다. 
3. 디자인이 바뀌어서 css를 수정하였습니다.
***AS IS***
***TO BE***
> [!Tip]
> Preview에서 변경 사항을 확인하고 싶다면 코드에디터 들어가서 description tab에서 제일 밑으로 내리면  
> document 버튼을 찾으실 수 있어요 :)
ㄹㅇ 공컴이므로 BoxerCat을 리뷰어로 지목할게요!
closes TAS-1737
=> feat(fe): add PyPy3 documentation and change document modal design

apps/backend/apps/client/src/contest/contest.controller.ts, apps/backend/apps/client/src/contest/contest.service.spec.ts, apps/backend/apps/client/src/contest/contest.service.ts, collection/client/Contest/Get Leaderboard/succeed.bru
대회 leaderboard를 열람할 때 대회 역할에 따른 열람 권한 구분을 위해 userRole 정보를 함께 반환합니다
---
=> chore(be): return user role to contest leaderboard

.github/workflows/cd-stage.yml
#2705 에서 cd-stage.yml에서 .env를 생성할 때 redirection이 잘못 되어 기존 .env 값이 지워지는 이슈를 해결합니다.
```sh
echo "${{ secrets.ENV_DEVELOPMENT }}" > .env
echo "${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT_URL }}" > .env  # overriding .env
```
---
=> fix(cd): prevent stage env being overridden

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/leaderboard/_libs/apis/getContestLeaderboard.ts, apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/leaderboard/page.tsx
클라이언트 리더보드는 기존에 대회가 끝나기 전에는 볼 수 없도록 되어있었습니다.
그러나! NPC 측의 요청에 따라서 Contest Admin과 Contest Manager는 대회가 끝나기 전에도 리더보드를 볼 수 있도록 변경합니다.
- 아래 스크린 샷은 콘테스트 어드민이 진행중인 리더보드를 보는 장면입니다!
> [!Tip]
> 정리하면 아래와 같음
>
> **대회 진행동안 client Contest Leaderboard 볼 수 있는 권한**
> Contest Admin 있음!
> Contest Manager 있음!
> Contest Participant 없음...
> 나머지 없음...
=> feat(fe): allow contest admin and manager to see the client leaderboard before finish

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/leaderboard/page.tsx
***AS IS***
client leaderboard가 refresh 될 때, 리더보드 데이터가 fetch되기 전에 
리더보드에 dummy 값이 들어가는데 이후 데이터가 fetch 되면 리더보드가 주욱 길어지는 모션이 나왔습니다.
>> 콘테스트 진행 동안 클라이언트 리더보드는 대회장 앞에 띄워져 있을 것이고 수시로 새로고침됩니다. 이 때 주욱 길어지는 모션이 
지속적으로 나온다면 대회를 하면서 신경 쓰일 수 있을 것 같아서 모션이 나오지 않도록 수정하였습니다. 
***TO BE***
client leaderboard를 refresh 할 때, 데이터가 fetching 되기 전까지 아예 리더보드를 렌더링하지 않습니다.
> [!Tip]
> 단순합니다! loading 일 때 리더보드 테이블을 렌더링하지 않습니다! 그 부분을 확인해주시면 감사하겠습니다.
closes TAS-1746
=> feat(fe): remove string cheeze

.env.development, apps/backend/apps/admin/src/main.ts, apps/backend/apps/client/src/main.ts, apps/iris/main.go
[이전 PR](https://github.com/skkuding/codedang/pull/2809)에서 모니터링 여부가 기본적으로 비활성화 되는 버그가 발생했습니다.
이제 기본적으로 모니터링을 활성화합니다.
따라서 production, rc, stage 환경에서 별다른 설정 없이 모니터링이 활성화됩니다.
대신 개발 환경에서는 `.env.development`의 설정에 따라 모니터링이 비활성화됩니다.
---
=> fix(infra): enable instrumentation for default

apps/infra/production/codedang/codedang_service_iris.tf
Iris를 on-prem 서버로 옮기면서 ECS의 Iris service를 down-scale합니다.
나중에 on-prem 서버에 문제가 생기면 수동으로 숫자 변경 후 terraform apply하면 될 것 같습니다.
---
=> chore(infra): scale down ecs iris service to 0

apps/frontend/app/admin/course/[courseId]/_components/AssignmentProblemTable.tsx, apps/frontend/app/admin/course/[courseId]/assignment/_components/AssignmentProblemColumns.tsx, apps/frontend/app/admin/course/[courseId]/exercise/[exerciseId]/(overall)/@tabs/page.tsx, apps/frontend/app/admin/course/[courseId]/exercise/[exerciseId]/edit/page.tsx, apps/frontend/app/admin/course/[courseId]/exercise/_components/ExerciseProblemColumns.tsx, apps/frontend/app/admin/course/[courseId]/exercise/create/page.tsx, apps/frontend/graphql/problem/mutations.ts
> [!Note]
> AssignmentProblemTable 컴포넌트에서 isExercise를 통해 로직을 분기했습니다. 
> isExercise에 따라 createExerciseColumns / createAssignmentColumns이 호출됩니다.
> [!IMPORTANT]  
> Create Exercise, Edit Exercise, Exercise Detail에 적용되는 변경사항입니다.
closes TAS-1771
=> feat(fe): remove score setting when creating or updating exercise

apps/k8s/argocd/argocd.yaml, apps/k8s/argocd/internal.yaml, apps/k8s/argocd/iris.yaml
Argo CD 파이프라인을 세팅합니다. target 브랜치는 임시로 main 브랜치로 설정했고, 앞으로 `apps/k8s` 폴더에 있는 yaml 파일들을 자동으로 읽어 배포합니다.
- 더 쉬운 유지보수와 가시성을 위해, Argo CD UI로 설정하는 대신 yaml 파일로 declarative하게 구성하였습니다.
- 지금은 argocd / iris / internal 폴더 각각에 대한 Application 리소스를 생성하였습니다. 
- 추후 release 브랜치가 구성되면 main 브랜치 대신 release 브랜치에서 yaml을 읽도록 설정하면 될 듯 합니다.
---
=> feat(infra): setup argocd for iris and basic k8s setup

apps/frontend/components/auth/HeaderAuthPanel.tsx
심심해서 Header의 Auth패널을 리팩토링해 보았습니다.
리팩토링하면서 보안상 문제 (햄부기메뉴에서 권한 확인이 한단계 부족했던점) 등을 개선할 수 있었습니다.
유자차의 권한도 한층 더 이해할 수 있었습니다. 추가로 더 가독성을 높이기 위해 변수명을 일부 수정하였습니다.
> [!WARNING]  
> 리팩토링 한다고 했는데, 6줄이나 더 늘어나서 심란함
---
closes TAS-1814
=> refactor(fe): improve header auth

.github/workflows/cd-stage.yml
스테이지 서버 배포 시 파이프라인에서 각 서비스(Client-API, Admin-API, Iris)의 이미지의 `latest` 태그를 pull 하여 배포했었습니다.
하지만 2달 전의 업데이트를 마지막으로 `latest` 태그 대상이 갱신되지 않았습니다.
참고로 현재 해당 `latest` 태그는 `sha256:0ab69c4d8fe0ce5498bb992d36bdf34f4710d69d5f4905a6d44d94dd442f9267` 커밋을 가리키고 있습니다.
따라서 앞으로 stage 환경에 배포시 각 서비스의 이미지에 `latest` 태그를 붙입니다.
---
=> feat(infra): add 'latest' tag for each service image in CD stage workflow

apps/backend/apps/admin/src/contest/contest.service.ts, apps/backend/apps/client/src/contest/contest.service.ts, apps/backend/prisma/migrations/20250712001015_add_register_due_date_to_contest/migration.sql, apps/backend/prisma/migrations/20250718141441_add_register_due_time/migration.sql, apps/backend/prisma/migrations/20250719052507_set_register_due_date_default/migration.sql, apps/backend/prisma/schema.prisma
prisma migration 에러에 대한 hotfix
- fix(be): modify registerduetime schema optional에 대한 commit revert
- registerDueTime의 default를 now()로 설정
---
=> fix(be): set register due time default

apps/backend/prisma/migrations/20250712001015_add_register_due_date_to_contest/migration.sql, apps/backend/prisma/migrations/20250719052507_set_register_due_date_default/migration.sql
Contest 테이블에 추가된 `register_due_time` field가 default 값 없이 `NOT NULL`로 설정되어 migration failure가 발생합니다.
Prisma 공식 가이드에 따라 해당 migration을 rollback하고 default 값이 추가된 migration을 적용합니다.
https://www.prisma.io/docs/orm/prisma-migrate/workflows/patching-and-hotfixing#failed-migration
참고: #2861, #2875, #2876
> [!Warning]
> 직접 스테이지 서버에서 rollback 작업이 필요합니다.
> `pnpm prisma migrate resolve --rolled-back "20250712001015_add_register_due_date_to_contest"`
---
=> fix(be): resolve migration failure for new field in contest table

apps/backend/apps/client/src/group/group.service.spec.ts, apps/backend/apps/client/src/notification/notification.controller.ts, apps/backend/apps/client/src/notification/notification.service.spec.ts, apps/backend/apps/client/src/notification/notification.service.ts, apps/backend/apps/client/src/submission/submission.service.ts, apps/backend/prisma/seed.ts, apps/backend/schema.gql, collection/client/Notification/Get Notifications/Succeed.bru, collection/client/Notification/Get Unread Count/Succeed.bru
getNotifications에서 isRead를 기준으로 필터링을 가능하게 합니다.
읽지 않은 알림의 개수를 조회하는 api를 추가합니다.
seed 데이터를 수정했습니다.
---
Closes TAS-1955
=> feat(be): implement notification filtering and unread count api

.github/workflows/ci.yml
Merge queue 기능을 적용하기 위해 PR이 merge queue에 추가됐을 때 CI를 실행하도록 설정합니다.
---
=> chore(ci): run ci when enqueued to merge-queue

apps/backend/package.json, pnpm-lock.yaml
@nestjs/apollo 패키지가 아직 express v5와 apollo/server v5를 지원하지 않아 아래처럼 에러가 발생합니다.
임시로 v4로 다운그레이드합니다.
```
node:internal/modules/esm/resolve:314
return new ERR_PACKAGE_PATH_NOT_EXPORTED(
^
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './express4' is not defined by "exports" in /Users/dotol/Workspace/codedang/node_modules/.pnpm/@nestjs+apollo@13.1.0_@apollo+server@5.0.0_graphql@16.11.0__@nestjs+common@11.1.6_class_d90de14be5dfef1e32fa4a3016cbd552/node_modules/@apollo/server/package.json
at exportsNotFound (node:internal/modules/esm/resolve:314:10)
at packageExportsResolve (node:internal/modules/esm/resolve:661:9)
at resolveExports (node:internal/modules/cjs/loader:657:36)
at Function._findPath (node:internal/modules/cjs/loader:749:31)
at Function._resolveFilename …
```
=> fix: revert apollo/server upgrade to v5 for nestjs/apollo compatability

apps/k8s/argocd/applications/redis-prod.yaml
stage 환경에만 `spec.destination.name` 속성을 사용했던 실수가 있었습니다.
이제 production 환경에서도 이를 적용합니다.
---
=> fix(infra): correct server field to use production name in redis-prod

apps/infra/production/codedang/message_queue_aws.tf, apps/k8s/client-api/deployment.yaml, apps/k8s/client-api/external-secret.yaml
현재 client-api가 external-secret을 불러오지 못해 pod 실행이 안됩니다.
> one or more objects failed to apply, reason: error when patching "/dev/shm/1159703879": ExternalSecret.external-secrets.io "client-api-aws-secrets" is invalid: spec.data[6].remoteRef: Required value (retried 5 times).
`client-api-aws-secrets`에서 사용된 template이 external secret에서 제공하는 spec 문법에 맞지 않아 에러가 발생합니다.
template을 고치는 방법도 있지만, terraform에서 RabbitMQ API url을 제공하기 때문에 해당 값을 AWS secret manager에 저장합니다.
추가로 redis url도 고쳤습니다.
---
=> fix(infra): don't use template in k8s external secret

apps/backend/apps/client/src/contest/contest.controller.ts, apps/backend/apps/client/src/contest/contest.service.ts, apps/backend/apps/client/src/contest/dto/contest-qna.dto.ts, collection/client/Contest/Get Contest QnAs/Succeed.bru, collection/client/Contest/Get Contest QnAs/[404] Nonexistent Contest.bru
1. GET 메서드에서 Request Body를 사용할 수 없으므로 이를 Query Parameter로 변환합니다.
2. filter 중 카테고리 관련 로직이 의도대로 작동하지 않는 점을 수정합니다.
기존 필터로는 General과 Problem을 모두 선택한 경우에도 problemId에 대한 조건이 AND로 들어가게 되어 General 카테고리가 무시되는 문제가 있어 이를 OR로 묶었습니다.
---
Closes TAS-2016
=> fix(be): change Request Body to Query in getContestQnAs

apps/frontend/app/admin/contest/[contestId]/(overall)/@tabs/leaderboard/page.tsx, apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/(overall)/@tabs/assessment/_components/ParticipantTable.tsx, apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/(overall)/@tabs/page.tsx, apps/frontend/app/admin/course/[courseId]/exercise/[exerciseId]/(overall)/@tabs/page.tsx
현재 management 쪽 contest leaderboard, assignment/exercise information, assignment assessment 페이지를 접속하고 **새로고침**(또는 URL 직접 입력해서 접속)을 하면, **순식간에 수천개의 graphql 쿼리를 무한으로 요청**하면서 페이지가 로딩되지 않는 심각한 버그가 존재합니다. 이전에 새 탭으로 열기가 디폴트인 submission별 assessment 화면에서도 발견해 급히 [useSuspenseQuery를 useQuery로 대체함으로써 해결했었던](https://github.com/skkuding/codedang/pull/2931/commits/73d949b7d4d513098169583070b617b5063f0b53) 문제인데, 이 페이지들에서도 같은 문제가 존재하는 것을 확인해 동일한 방법으로 수정하였습니다. 8/13 Preview에서는 정상적으로 동작하고, 8/15 Preview에서는 동일한 문제가 발생한다는 점을 봤을 때 8/14에 머지된 next.js 15 업그레이드가 원인일 확률이 매우 높아보입니다. 다만 변경점을 읽어보아도 정확한 이유를 발견하진 못해 현재로선 최선의 방법인 것 같습니다...
이 페이지들 외에도 다른 페이지들에 문제가 없는지 확인 부탁드립니다. 
closes TAS-2047
---
=> fix(fe): prevent infinite refetch when refresh

apps/k8s/argocd/applications/redis.yaml
- Redis의 버전으로 혼동한 Chart의 버전을 수정했습니다.
```sh
helm search repo ot-helm
```
위 명령어로 차트 버전 확인 가능하니 다른 분들은 저처럼 실수하지 마시길!
---
=> fix(infra): update targetRevision to 0.16.5 in redis.yaml

apps/k8s/iris/overlays/stage/kustomization.yaml
스테이지 환경에서 iris를 기존 20개 대신 3개의 pod만 띄우도록 조정합니다.
---
=> fix(infra): reduce number of iris pods in stage

.github/workflows/cd-stage.yml, apps/infra/stage/server2/Caddyfile
Caddy로 들어오는 frontend stage 트래픽을 Coolify 대신 kubernetes로 forward합니다.
Kubernetes 내 frontend의 API URL도 stage.codedang.com으로 수정해두었습니다.
---
=> feat(infra): forward stage frontend to k8s instead of coolify

apps/k8s/argocd/applications/admin-api.yaml, apps/k8s/argocd/applications/client-api.yaml, apps/k8s/argocd/applications/frontend.yaml, apps/k8s/argocd/applications/iris.yaml
Argo CD에서 image-updater를 적용해도 이미지가 새로 pull되지 않는 문제가 있습니다. (fronend는 10일 전 이미지 사용 중)
지금 ApplicationSet이 모든 spec을 강제로 sync해, argocd-image-updater가 image를 변경해도 다시 ApplicationSet의 이미지로 변경되거나 초기화되는 것이 문제였습니다.
ApplicationSet의 `ignoreApplicationDifferences` 옵션을 설정해 이미지만 sync에서 예외 설정을 해둡니다.
---
=> fix(infra): allow modifying image by argocd-image-updater

apps/k8s/client-api/overlays/stage/kustomization.yaml
스테이지 Client API에서 누락된 Minio 접근을 위한 정보를 추가합니다.
---
=> fix(infra): add aws-credentials.yaml to stage client api

apps/backend/apps/admin/src/admin.module.ts, apps/backend/libs/cache/src/cache-config.service.ts
Admin API 컨테이너 시작 시 캐시 연결 test 실패가 확률적으로 실패합니다.
아마 BullMQ와 기존 캐시 저장소가 사용하는 Redis의 DB가 겹쳐서 발생하는 문제로 예상됩니다.
- BullMQ와 기존 캐시 저장소가 사용하는 Redis DB를 분리합니다.
---
=> fix(be): separate cache db

apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/(overall)/@tabs/assessment/_components/Columns.tsx, apps/frontend/app/admin/course/[courseId]/assignment/[assignmentId]/(overall)/@tabs/assessment/_components/ParticipantTable.tsx, apps/frontend/graphql/assignment/mutations.ts
Final Score와 Auto Graded Score를 전환할 수 있는 Combobox를 만들고, Auto Graded Score일 때 'Apply to Final Score' 버튼을 보이게 해 자동 채점 점수를 최종 점수에 반영하는 API를 연동하였습니다.
일단 두 개의 뷰로 나눈 이유는, Auto Graded Score 테이블과 비슷한 형식이 Submission 탭의 Students에도 있지만 잘 쓰이지 않고, Submissons에 있기 적절하지 않다고 생각에 추후 제거하고 Assessment에서만 자동 채점 점수를 관리하는 게 맞다고 생각했습니다. 또한 나중에 더 확장해서 특정 열(problem)을 클릭해서 해당 문제들을 전부 자동채점 처리, 특정 행(student)를 클릭해서 해당 학생의 제출들을 전부 자동채점 처리, 특정 칸(submission)을 클릭해서 해당 제출만 자동채점 처리 등의 구현이 가능할 것이라고 생각했기 때문입니다.
closes TAS-2062
---
=> feat(fe): add auto finalize button

apps/k8s/admin-api/overlays/stage/cors-middleware.yaml, apps/k8s/client-api/overlays/stage/cors-middleware.yaml
기존 CORS의 'allow-origin-list'에서 wildcard가 동작하지 않아 preview에서 CORS 에러가 발생합니다.
Regex를 대신 적용해 CORS 규칙을 올바르게 적용합니다.
---
=> fix(infra): preview domains are not caught in cors middleware

apps/frontend/components/auth/SignIn.tsx
저 눈동자 버튼이 submit 버튼으로 인식되어 엔터를 누르면 패스워드가 보이던 버그를 수정합니다.
---
Closes TAS-2093
=> chore(fe): prevent isPasswordVisible activation when pressing enter on signIn modal

apps/frontend/app/(client)/(code-editor)/_components/TestcasePanel/useRunner.ts
Next.js 서버에서 아래와 같은 에러가 종종 발생합니다. 코드 에디터 페이지에서 refresh할 때 발생하는 것으로 보아, 해당 페이지 내 SSR 이슈로 보였습니다.
```
▲ Next.js 15.4.6
- Local:        http://frontend-6c5689984f-gsrbq:5525
- Network:      http://frontend-6c5689984f-gsrbq:5525
✓ Starting...
✓ Ready in 464ms
ReferenceError: self is not defined
at 28372 (.next/server/chunks/3915.js:1:5723)
at c (.next/server/webpack-runtime.js:1:143)
at 32848 (.next/server/chunks/1177.js:3:12717)
at Function.c (.next/server/webpack-runtime.js:1:143)
⨯ unhandledRejection:  ReferenceError: self is not defined
at 28372 (.next/server/chunks/3915.js:1:5723)
at c (.next/server/webpack-runtime.js:1:143)
at 32848 (.next/server/chunks/1177.js:3:12717)
at Function.c (.next/server/webpack-runtime.js:1:143)
```
확인 결과 xterm을 직접 import하면 브라우저 기능에 접근하여 서버 측에서 에러가 발생하였습니다. …
=> fix(fe): do not import xterm directly for ssr error

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/qna/[qnaId]/page.tsx
로그아웃했을 때 Q&A detail page에 못 들어가는 에러를 수정했습니다.
---
closes TAS-2106
=> fix(fe): enable to access detail page even when logout

apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/qna/_components/QnACategoryFilter.tsx, apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/qna/_components/QnADataTable.tsx, apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/qna/_components/QnAMainTable.tsx, apps/frontend/app/(client)/(main)/contest/[contestId]/@tabs/qna/page.tsx
1. 대회 운영진에게도 upcoming 대회에서는 qna category filter 옵션으로 General만 표시됩니다.
2. 파란 동그라미 표시
기존: Admin, Manager, Reviewer는 isResolved=false,  Participant는 isRead=false
수정: Admin, Manager는 isResolved=false,  Reviewer, Participant는 isRead=false
=> fix(fe): revise qna main page

apps/frontend/app/(client)/(code-editor)/_components/EditorHeader/EditorHeader.tsx
언어 바꾸면 기존에 썼던 코드가 소리소문 없이 사라지는게 아무리 생각해도 좀 불안해서 모달을 넣었습니다...
언어바꾸는 드롭다운과 리셋모달 확인해주세요!
warning으로 변경.
closes.
---
=> feat(fe): add Confirm Modal when Changing Language

apps/k8s/monitoring/grafana/values.yaml, apps/k8s/monitoring/loki/values.yaml, apps/k8s/monitoring/otel-collector/otel-collector.yaml
`monitoring-minio`에 구성된 minio 유저 시크릿을 helm chart의 `values.yaml`에 주입하는 방법을 모르겠습니다.
추후 중앙화된 저장소 관리를 위해 `monitoring-minio`의 minio로 이전해야 합니다.
이를 통해 Loki의 기본 설정인 multi-tenancy 모드를 해제합니다.
따라서 이와 연결된 서비스(OTel Collector, Grafana)의 요청 헤더에 `X-Scope-OrgId`를 제거합니다.
다시 `monitoring-minio`의 minio에 연결하려면 아래 링크를 참조하시면 도움이 됩니다.
- https://artifacthub.io/packages/helm/grafana/loki?modal=values&path=loki.storage
- https://github.com/grafana/loki/issues/12249
- https://community.grafana.com/t/storing-s3-accesskeyid-and-secretaccesskey-securely/92133/8
- https://grafana.com/docs/loki/latest/setup/install/helm/reference/
아마 이 PR만 merge 되면 위처럼 로그 확인이 가능할 겁니다.
---
=> fix(infra): use loki chart minio instead of custom minio

apps/k8s/argocd/applications/frontend-preview.yaml
Argo CD `frontend-preview`에서 cluster-issuer를 letsencrypt 대신 letsencrypt-dns01로 replace하는 과정에서,
annotation 안에 있는 `.`과 `/`가 올바르게 escape되지 않았습니다.
`.`은 escape할 필요가 없고, `/`은 `~1`로 대신 적어야합니다.
https://github.com/kubernetes-sigs/kustomize/issues/1256#issuecomment-535007229
frontend-preview resource를 모두 frontend-preview namespace에만 생성하고, 새로운 namespace(frontend-preview-{{.number}})를 생성하지 않도록 합니다.
---
=> fix(infra): replace cluster-issuer in frontend-preview correctly

apps/infra/production/dns/cloud-beaver.tf, apps/k8s/argocd/applications/cloud-beaver-stage.yaml, apps/k8s/cloud-beaver/deployment.yaml, apps/k8s/cloud-beaver/ingress.yaml, apps/k8s/cloud-beaver/namespace.yaml, apps/k8s/cloud-beaver/pvc.yaml, apps/k8s/cloud-beaver/service.yaml
Stage 환경 Postgres에 접속하기 위한 웹 DB IDE를 설정합니다.
CloudBeaver를 사용했고, https://beaver.stage.codedang.com/ 에서 접속할 수 있습니다.
설정 변경은 admin 로그인으로 가능하고, Notion secret 페이지에 계정 정보 적어뒀습니다.
---
=> feat(infra): add cloud beaver to access stage db

apps/frontend/app/globals.css
확인해보니 shadcn Button과 button 모두 직접 지정하지 않는 이상 포인터로 변하지 않길래 global.css를 수정했습니다!
인라인으로 직접 지정하는 것이 더 우선순위가 높기 때문에  global.css를 수정하는 것이 옳다고 생각해 변경합니다.
closes TAS-2121
---
=> fix(fe): restore button cursor;pointer

apps/frontend/app/(client)/(main)/course/[courseId]/_components/AssignmentAccordion.tsx, apps/frontend/app/(client)/(main)/course/[courseId]/_components/ExerciseAccordion.tsx
일부 제출내역이 관련없는 문제의 제출내역이라고 아코디언에 렌더링 되는 문제가 있었습니다.
원인은 'submission[index].submission.submissionTime,' 
이렇게 submissoin의 배열의 인덱스를 맹목적으로 사용하고 있어서 생긴 문제인 것 같습니다.
ubmission배열에서 problemId가 일치하는 제출내역을 찾아서 매칭시키는 방법으로 해결했습니다.
---
=> fix(fe): match each submission with according problem based on problemId

apps/backend/apps/admin/src/problem/services/problem.service.ts
getProblem에서 Admin의 경우만 권한 Bypass를 하고 있어 SuperAdmin을 추가합니다.
---
closes TAS-2176
=> fix(be): add SuperAdmin bypass to getProblem

apps/frontend/libs/instagram.ts
`SecretsManagerClient`를 사용하기 위해서는 `region` 설정이 필요합니다.
누락된 `region` 값을 상수인 `ap-northeast-2`로 설정합니다.
이번 경우처럼 토큰을 가져오는 상황에서는 어떤 에러가 발생할 지 모르기에 에러 처리도 추가했습니다.
- 사실상 현재로서는 다른 리전에 배포할 일이 없는 서비스이기에 `region` 값은 상수로 두었습니다.
- #3204 에 의존적입니다. 이 PR 병합이 선행되어야만 Argocd 프리뷰 확인 가능합니다.
---
=> fix(infra): update AWS region with enhanced error handling
